### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-angular#1]
Create and publish some initial release with the current Carbon (cloud style) look and feel.

TODO:

- [x] forms
  - [x] labels
  - [x] text fields
  - [x] checkboxes
  - [x] toggles
  - [x] select
  - [x] button
  - [x] input
- [x] dropdown
- [x] combobox
- [x] modal
- [ ] dialog
  - [x] overflow menu
  - [x] tooltip
  - [ ] definition tooltip
- [ ] calendar
  - [ ] base calendar
  - [ ] date picker
- [x] banners
  - [x] notification
  - [x] toast
- [ ] icon
- [x] table
- [x] tabs
- [x] buttons

**Comment by blazejpawlak** [comment]
Hey @cal-smith, we've been working on something at IBM for quite some time. Can you reach out at Slack? I'd like to show you guys some stuff and discuss potential cooperation here.

**Comment by cal-smith** [comment]
With v2.0 out I'm going to close this issue since we have the foundation for the rest of these set. Further discussion can happen in component specific issues 🎉
