### ISSUE TITLE
Issue ComboBox scroll updated items

### ISSUE THREAD

**Issue by SauloRomo** [IBM/carbon-components-angular#1001]
## Detailed description

ibm-combo-box that fills  the property items with a call from an api  that is triggerd with a keyup event but i got some trouble with the items property when is updated,  i spect the  <ibm-dropdown-list> update with the new items that i call  that actually does  but at the end of the call the dropdown  closes instead of stay open and let the user know those new items are available to select in other words anytime i modify the property items from comboBox the dropdown-list close also  im using the scroll event in the <ibm-dropdown-list> that call the api  when the user go at the end of the list then i set the result to  items property  and also the dropdown  closes instead of stay open and let the user know those new items are available to select

> Is this issue related to a specific component?

ibm-combo-box  and  ibm-dropdown-list

> What did you expect to happen? What happened instead? What would you like to see changed?

the combo should stay open when the list of items are updated instead of that it close

> What browser are you working in?

Google Chrome

> What version of the Carbon Design System are you using?

3.27.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

this product is a internal aplication for ibm excutives , is really important to be fixed because the realse date for this part of the project is at the end of january 2020

## Steps to reproduce the issue

1. Step one
   add an event for search elements from the items that bring the api  and also add the scroll event on  
   ibm-dropdown-list 
2. Step two
    compile and go to the interface when you scrolling a the end you need to call the api an see the last 
    element then call the api for more items and you will see the api calls and the combo closes 

## Additional information

![Jan-09-2020 15-05-41](https://user-images.githubusercontent.com/25408064/72290386-a7c15d00-3612-11ea-915b-659ffa8afcc9.gif)

**Comment by cal-smith** [comment]
@Pablodotnet said he'd take an initial look at this! Big thanks 💯

**Comment by Donisius** [comment]
@SauloRomo I'm trying to recreate this issue by simply updating the items property with new items when I scroll on the dropdown list but I can't seem to get it to close the way it's closing in your example. Is it possible to provide a minimal reproduction on code sandbox or stackblitz or something similar?

**Comment by Donisius** [comment]
Already fixed through #883
