### ISSUE TITLE
Missing binding to size in Modal component

### ISSUE THREAD

**Issue by DKIMN** [IBM/carbon-components-angular#1002]
## Detailed description

> Describe in detail the issue you're having.

The Modal component is missing binding to the size property.
https://www.carbondesignsystem.com/components/modal/style#sizes

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is a bug.
> Is this issue related to a specific component?

The modal component.
> What did you expect to happen? What happened instead? What would you like to see changed?

Setting the size should reflect change on modal size.
> What version of the Carbon Design System are you using?

Version 3.32.1.

**Comment by cal-smith** [comment]
These specs are brand new (not a bug) - parent issue for modal updates can be found here: #994
