### ISSUE TITLE
To get toolbar search(ibm-table-toolbar-search) component closed, without clicking the clear button

### ISSUE THREAD

**Issue by tulasigudibanda** [IBM/carbon-components-angular#1003]
I am using ibm-table-toolbar-search component in my data table. 
(Ref : https://github.com/IBM/carbon-components-angular/blob/e6c1566758b66779d323f9fb8fb142ac74e8039d/src/search/search.component.ts)
Feature Requirement : I should be able to  automatically close the toolbar search by reading the queryParams. In other words, I should be able to drive some input which will in turn call the clearSearch()  function in the component, without actually clicking on the clear button.

Scenario : 
When I give some search text in the search box, url gets updated with that text as queryParam. 
When I click browser back button, queryParams will be removed from the url. 
At this point,  I want to get the search box cleared and closed without me clicking on the clear button.

**Comment by cal-smith** [comment]
To be clear, we won't handle any automatic queryParam reading - we can't possibly know what functionality would be expected in all cases. What we can do is fix the component so that clearing the `value` correctly clears the search 👍

**Comment by Donisius** [comment]
You will probably need to double bind the value in order to achieve clearing the search through setting `value` to empty. See https://codesandbox.io/s/issue1003-wf6o9 for an example

**Comment by zvonimirfras** [comment]
Looks like double-binding the value as shown in Doni's example in files `src/app/app.component.html` and `src/app/app.component.ts` should get you as far as a component library can, as Cal mentioned. It's also been a year, so closing.
