### ISSUE TITLE
Tabs chacheActive change after checked error

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-angular#1006]
Likely either due to the `*ngIf` on the `ibm-tab` or the setting in the `ibm-tabs`/`ibm-tab-headers`

We should also make sure `ibm-tab-group` supports `cacheActive` (and maybe rename `cacheActive` so it makes more sense)

**Comment by cal-smith** [comment]
To be done this quarter (a team in Watson Health has a release date this Q and is affected)

**Comment by Donisius** [comment]
It seems that `cacheActive` works as intended without throwing an after checked error on my end, even when dynamically setting the property. Were you able to recreate this error?

**Comment by cal-smith** [comment]
Double check outside of the storybook ... I believe it's related to the `afterContentInit` in `tabs.component`/`tab-headers.component` ... I didn't independently recreate it, but it seems likely that the error is coming from somewhere within the component

**Comment by Donisius** [comment]
Doesn't seem to throw the error: https://codesandbox.io/s/issue1006-54xon

**Comment by ninja511** [comment]
closing pending additional information: can't reproduce
