### ISSUE TITLE
Error import("dist/src/i18n/i18n.service").

### ISSUE THREAD

**Issue by Tokscull** [IBM/carbon-components-angular#1008]
Upgrading  to 3.35 does not work.
![image](https://user-images.githubusercontent.com/46087056/72734871-bb893800-3bab-11ea-9481-cfa194bed414.png)
![Untitled](https://user-images.githubusercontent.com/46087056/72734957-ed9a9a00-3bab-11ea-86fe-f7c96d2b5680.png)

_Originally posted by @Tokscull in https://github.com/IBM/carbon-components-angular/issues/992#issuecomment-576303747_

**Comment by cal-smith** [comment]
This was closed by #1007
