### ISSUE TITLE
DatePicker component’s pattern property conflicts with Angular’s pattern validator

### ISSUE THREAD

**Issue by yinglejia** [IBM/carbon-components-angular#1010]
## Detailed description

It seems the `DatePicker` component’s `pattern` property conflicts with Angular’s `pattern` validator. https://angular.io/api/forms/PatternValidator

If we write code like below:

```
<ibm-date-picker
  [pattern]="..."
  [dateFormat]="..."
  formControlName="..."
>
```

This will activate Angular’s pattern validator. Since DatePicker’s value (which is an array with Date object(s)) doesn’t match the regex pattern, it will fail the Angular’s pattern validator.

It seems easier fix is to use a new property like `datePattern` or `inputPattern` to avoid this conflict.

**Comment by HYACCCINT** [comment]
Could it be because of the "pattern" property of javascript input, which the ibm-date-picker-input is based on?

**Comment by cal-smith** [comment]
That and the Angular forms module defines a directive `[pattern]` ... so really we need to deprecate the existing input, and swap over to a new one
