### ISSUE TITLE
Set the language globally for datepicker module

### ISSUE THREAD

**Issue by cyrusfurtado** [IBM/carbon-components-angular#1011]
## Detailed description

> Currently the language for the Datepicker needs to be at component level with an `Input` property.

> Carbon Components Angular version used is `3.35.3`

> This is a feature request.

> Issue related to IBM Datepicker `ibm-date-picker` component.

> Datepicker language could be set at Module import level

> Current project being worked on is `IBM food trust`

### Change request
```
// within datepickers module definition
export class DatePickerModule {
	/**
	 * Set the language for flatpickr globally where the module is imported
	 * as mentioned here https://github.com/flatpickr/flatpickr/tree/master/src/l10n
	 */
	static setLocale(lang: string): ModuleWithProviders {
		flatpickr.localize(l10n[lang] || l10n.default);
		return {
			ngModule: DatePickerModule
		};
	}
...
...
...
}

// then in the imports section of angular app
@NgModule({
imports: [
				DatePickerModule.setLocale("fr"),
				FormsModule,
				...
                                ...
			],
})

```

**Comment by cal-smith** [comment]
I believe this has been resolved via the `i18n` service's `setLocal` method 👍
