### ISSUE TITLE
using StickyHeader attribute Getting ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: 0'. Current value: 'ngIf: 10'.

### ISSUE THREAD

**Issue by naveenkumarkg** [IBM/carbon-components-angular#1016]
## Detailed description

> Sticker Header is working with basic table but with table having expansion panel it throwing the error and disturbing the UI table

> Is this issue related to a specific component?
Yes This issue is with <ibm-table>

> What did you expect to happen? What happened instead? What would you like to see changed?

Wanted stickyheader for all kinds of tables with out affecting the CSS design
> What browser are you working in?
Chrome, mozilla,IE

> What version of the Carbon Design System are you using?
        "carbon-components": "^10.9.2",
        "carbon-components-angular": "^3.36.0",

## Steps to reproduce the issue

  <ibm-table [striped]="true" **class="display_block"** **[stickyHeader]="true"** [model]="model" [showSelectionColumn]="false" (sort)="simpleSort($event)">
            </ibm-table>

Adding stickyHeader getting the error, 
<img width="951" alt="sticky" src="https://user-images.githubusercontent.com/7873731/73048781-4154fe00-3ea0-11ea-95d8-27abe146e61d.PNG">

* Screenshots or code
* Notes

**Comment by Pablodotnet** [comment]
@Donisius I'm having some issues with table too, may be related with this (I'm not using sticky header)

<img width="1256" alt="Screen Shot 2020-01-27 at 10 24 28 AM" src="https://user-images.githubusercontent.com/10190000/73193051-9b97ce00-40ef-11ea-9000-871b68dc2216.png">

**Comment by Donisius** [comment]
@naveenkumarkg @Pablodotnet Thanks for bringing up the issue! It seems the issue everywhere but our storybook

**Comment by naveenkumarkg** [comment]
Thank you this issue is resolved partially , but with Expansion panel the styles are affecting , The styling issue is still exists . I am finding the fix too . Or What is the best way to use stickyHeader along with Expnasion ?

**Comment by cal-smith** [comment]
> Thank you this issue is resolved partially , but with Expansion panel the styles are affecting , The styling issue is still exists . I am finding the fix too . Or What is the best way to use stickyHeader along with Expnasion ?

That sounds like a different issue ... Could you open another issue for that? If you could include some screenshots and a minimal reproduction that would be awesome 💯
