### ISSUE TITLE
ProgressIndicator mobile UI

### ISSUE THREAD

**Issue by Tokscull** [IBM/carbon-components-angular#1022]
Progress Indicator have default minimal width and on a phones with small width (iPhone 5,SE) he does not scale to screen size of mobile phone. 

![BlueBlueCar](https://user-images.githubusercontent.com/46087056/73340270-7cce3e80-428b-11ea-87cb-a3f1ba3f4ff7.png)

If I remove min-width and change width in '.bx--progress-step' class and change width in '.bx--progress-line' class this solves the problem. But i haven't possibility to do it from my code, only from element inspector in browser.

**Comment by cal-smith** [comment]
This seems like a styling bug ... could you open an issue here https://github.com/carbon-design-system/carbon and reference this issue? Thanks!

**Comment by Tokscull** [comment]
Okay, I did it. New issue: https://github.com/carbon-design-system/carbon/issues/5212
