### ISSUE TITLE
Modal always dismisses itself when clicking outside of it

### ISSUE THREAD

**Issue by lruffing** [IBM/carbon-components-angular#1027]
Modal always dismisses itself when clicking outside of it

## Detailed description

> Describe in detail the issue you're having.
I am creating an alert modal using ModalService.show(...) and when this modal is displayed, it will be dismissed when the user clicks on any area outside of it.
> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug
> Is this issue related to a specific component?
Modal
> What did you expect to happen? What happened instead? What would you like to see changed?
Clicking outside this modal should not dismiss the modal.(at least it should be optional to dismiss it)
> What version of the Carbon Design System are you using?
3.30.0
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Application Delivery Intelligence
Ships early March 2020.
## Steps to reproduce the issue
1) The issue can me seen using the story book in Modal-Transactional at https://angular.carbondesignsystem.com/?path=/story/components-modal--transactional
2) Click the "Open Modal" button
3) Once the modal is displayed, click somewhere outside the modal and the modal disappears.

## Additional information
I think the bullet "give an escape hatch for applications that don't want that (maybe overriding some method?)" of this previous issue comment may not have been addressed:
https://github.com/IBM/carbon-components-angular/issues/505#issuecomment-484240090

**Comment by Donisius** [comment]
Remove `(overlaySelected)="closeModal()"` from `ibm-modal` to prevent it from closing when clicking the area outside.

**Comment by lruffing** [comment]
@Donisius I believe the issue https://github.com/IBM/carbon-components-angular/issues/505 was created to explicitly add that behavior (close modal when clicking the area outside.) Although I don't really agree with that behavior for all modals, if you back it out you won't you likely get complaints (at least from the person who opened issue 505)?

**Comment by lruffing** [comment]
sorry, I did not mean to close this issue

**Comment by cal-smith** [comment]
Yeah ... my current line of thinking is that we should pass an object to the `AlertModal` close handler that specifies (among other things) _where_ the close event is coming from

**Comment by HYACCCINT** [comment]
Both an input indicating how a click outside the modal should be handled, and somehow differentiating close event from a button/clicking outside?
