### ISSUE TITLE
Issue with Angular Testability since 3.32.0

### ISSUE THREAD

**Issue by calesce** [IBM/carbon-components-angular#1029]
## Detailed description

> Describe in detail the issue you're having.

We are using Selenium for testing our Angular application. The test scripts need to wait for Angular to finish loading, so they use `window.getAllAngularTestabilities()[0]` (see [Testability](https://angular.io/api/core/Testability)) which has a property of `_ngZone.hasPendingMacrotasks`, which is expected to be `false` when the page and components have loaded.

We had issues with this in the past with `setTimeout`, `requestAnimationFrame`, where we need to use [NGZone's `runOutsideAngular()`](https://angular.io/api/core/NgZone#runOutsideAngular), otherwise the `hasPendingMacrotasks` will always be `true`.

It appears [this commit](https://github.com/IBM/carbon-components-angular/commit/88e5747e8cb0924e8b4b2e748e4b1ef16c297ff8), released with 3.32.0, may have caused some issues for us because now several pages cause the `hasPendingMacrotasks` property to always be true. It can happen both on page load or when the test script opens an overflow menu.

I believe it's an issue for any component that uses [`ElementService`](https://github.com/IBM/carbon-components-angular/blob/master/src/utils/element.service.ts), which uses `AnimationFrameServiceSingleton`, which uses `requestAnimationFrame`. I think the simple solution would be to wrap all `rAF` calls in a `this.ngZone.runOutsideAngular()` block but would like to see what you all think.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to see changed?

See above

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

3.37.3 (latest)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

An IBM Watson Health product

## Steps to reproduce the issue

Not reproducible in Codesandbox or similar because window object appears to be isolated from the Angular app so doesn't have the `getAllAngularTestabilities()` method.

1. Step one
Look at results of `window.getAllAngularTestabilities()[0]._ngZone`
2. Step two
Add one of the Carbon datepicker or overflow menu to page and interact with it.
3. Step three
Look at results of ``window.getAllAngularTestabilities()[0]._ngZone` again and see the `hasPendingMacrotasks` property.

## Additional information

* Screenshots or code

![image](https://user-images.githubusercontent.com/5377524/73566221-f3547300-4428-11ea-92ce-13139ba29b62.png)

* Notes

**Comment by calesce** [comment]
I updated [this line](https://github.com/IBM/carbon-components-angular/blob/master/src/utils/animation-frame.service.ts#L14) and line 23 to be wrapped in a `runOutsideAngular` call like this:
```js
this.ngZone.runOutsideAngular(() => {
    this.animationFrameId = requestAnimationFrame(this.doTick.bind(this));
});
```

It seems to have resolved the problem we're seeing with Testability, but I'm not sure about the performance implications because it seems like a hot path.

**Comment by cal-smith** [comment]
Oh interesting 🤔 I think your fix would likely have a net perf improvement if my understanding of `runOutsideAngular` and the microtask states is correct ... Totally slipped my mind that Angular would hook into `requestAnimationFrame` as an update provider ...
