### ISSUE TITLE
Data Table: Animation is removed from skeleton view of the table 

### ISSUE THREAD

**Issue by Donisius** [IBM/carbon-components-angular#1036]
> Describe in detail the issue you're having.

The loading animation is removed from the skeleton table. The only way for the loading animation to get applied is if a span exists within the table header/body elements.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug.

> Is this issue related to a specific component?

Table.

> What did you expect to happen? What happened instead? What would you like to see changed?

Loading animation should appear in skeleton table.

> What browser are you working in?

Chrome, Firefox

> What version of the Carbon Design System are you using?

10.9.2

**Comment by HYACCCINT** [comment]
Is there a  link to the design of what it should look like?

**Comment by Donisius** [comment]
@HYACCCINT https://react.carbondesignsystem.com/?path=/story/datatableskeleton--default has an example

**Comment by cal-smith** [comment]
Closed by #1059
