### ISSUE TITLE
<ibm-toast>   showClose has to be true by default 

### ISSUE THREAD

**Issue by tulasigudibanda** [IBM/carbon-components-angular#1039]
The carbon toast component should have showClose set to true to render the close icon by default.
<ibm-toast *ngIf="showToastNotification" (close)="closeToastNotification()" [notificationObj]="notificationObj">
 </ibm-toast>

Right now , we need to set it as part of notificationObj to make it work:
this.notificationObj = {
        type: 'warning',
        title: '',
        subtitle: '',
        caption: ``,
        lowContrast: false,
        showClose: true
      }

**Comment by HYACCCINT** [comment]
@tulasigudibanda Hello, we were not able to reproduce this issue, would it be possible for you to send a showcase of code that is causing the bug?

**Comment by ninja511** [comment]
closing pending additional information: can't reproduce
