### ISSUE TITLE
HeaderAction component should make display of close icon optional when active

### ISSUE THREAD

**Issue by fionamurphy** [IBM/carbon-components-angular#1044]
## Detailed description

The latest change to the HeaderAction component means the close icon is always displayed when the action is active - is it possible to make this behaviour optional maybe? Perhaps with an additional optional Input property to show the close icon when active that defaults to true? 

https://github.com/IBM/carbon-components-angular/blob/85c307d833e40d40a54db9212204e55917f6891e/src/ui-shell/header/header-action.component.ts#L23

We have a design requirement to display the same icon whether active or inactive and are extending the component and overriding the component template for now to achieve this.

fyi @Donisius

**Comment by cal-smith** [comment]
Likely covered by #1031

**Comment by Donisius** [comment]
Closed by #1031
