### ISSUE TITLE
Component Input 'multiple' behaves inconsistently for File uploader when Drop enabled. 

### ISSUE THREAD

**Issue by mragujar** [IBM/carbon-components-angular#1045]
`mulitple` Input of File Uploader component behaving inconsistently when `drop` is set to `true`.

## Detailed description
> Describe in detail the issue you're having.

In the file uploader component when `drop` is set to `true`, and input `multiple` is set to false, User can still drop multiple files to the uploader.

> Is this a feature request (new component, new icon), a bug, or a general issue?

A bug

> Is this issue related to a specific component?

File Uploader

> What did you expect to happen? What happened instead? What would you like to see changed?

If Input `multiple` is set to `false`, User should be able to drop only one file

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

 "carbon-components": "^10.9.2",
 "carbon-components-angular": "^3.38.0",

## Steps to reproduce the issue
This can be observed at https://angular.carbondesignsystem.com/?path=/story/components-file-uploader--drag-and-drop by removing check from `Supports multiple files` box.

* Screenshots or code
![captured](https://user-images.githubusercontent.com/58841505/73937099-4dae7180-490a-11ea-9cad-8d984ea8593d.gif)

**Comment by HYACCCINT** [comment]
@cal-smith Wondering if the uploader should not accept any files when dropping multiple files, or simply accepting the first one?

**Comment by cal-smith** [comment]
Difficult to say for sure ... I'd double check with the react implementation, but I would lean towards only accepting the first

**Comment by HYACCCINT** [comment]
Kk, looks like it only accepts the first one
