### ISSUE TITLE
[Progress indicator] Highlighting the tabs

### ISSUE THREAD

**Issue by Tokscull** [IBM/carbon-components-angular#1057]
## What packages are you using?

- [x] `carbon-components: "^10.9.3"`
- [x] `carbon-components-angular: "^3.39.1"`

## Detailed description
If I select a tab in the 'second step' to get additional information it will get highlighted. But if I now select the next one, still the first one stays highlighted. Please highlight only the tab for which the popup is displayed.

![progrInd](https://user-images.githubusercontent.com/46087056/74337368-36133500-4db1-11ea-8176-86861a122c19.gif)

I checked [react design carbon system](https://react.carbondesignsystem.com/?path=/story/progressindicator--default) and [carbon design system](https://www.carbondesignsystem.com/components/progress-indicator/code) and not saw same problem. So, I think this problem specific only to the [angular design system](https://angular.carbondesignsystem.com/?path=/story/components-progress-indicator--basic).

**Comment by Donisius** [comment]
Will be fixed by #1048
