### ISSUE TITLE
Angular 9 doesnt compile with carbon-Angular

### ISSUE THREAD

**Issue by Atrastea** [IBM/carbon-components-angular#1060]
Angular 9 does not compile with carbon-components-angular

## Detailed description

Im trying to use carbon-components-angular with Angular 9. It works if i set in tsconfig.json
```
  "angularCompilerOptions": {
    "enableIvy": false
  }
```

 But id like to run it with Ivy, as soon as i try to compile with Ivy, every Module i have included throws an error. Its always the same 2 Erros

```
ERROR in Failed to compile entry-point carbon-components-angular -->
@ContentChildren predicate cannot be interpreted
tabQuery: [{ type: ContentChildren, args: [Tab,] }],
Value at position 0 in the NgModule.declarations of TabsModule is not a reference: [object Object]
```

Has anyone an idea what im doing wrong? Or does carbon just not work with ivy yet? (edited) 

## Steps to reproduce the issue

Just run ng serve on any Angular 9 application.

**Comment by cal-smith** [comment]
This is known, we'll be adding support this quarter, see here for our release plan https://github.com/IBM/carbon-components-angular/issues/896
