### ISSUE TITLE
Buttons Component -  Buttons with icon, breaking the UI in safari browser.

### ISSUE THREAD

**Issue by amirkhan064** [IBM/carbon-components-angular#1063]
I have found an issue in carbon buttons component "buttons with icons". It's breaking the UI in the safari browser.
I am using:-
"carbon-components": "10.9.3",
"carbon-components-angular": "3.38.0",

**Comment by Donisius** [comment]
A workaround you can use is:
```
			<button class="bx--btn bx--btn--primary" tabindex="0" type="button">
				With icon<svg focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" aria-hidden="true" class="bx--btn__icon">
				<path d="M16,2C8.4,2,2,8.4,2,16s6.4,14,14,14s14-6.4,14-14S23.6,2,16,2z M22,17h-5v5h-2v-5h-5v-2h5v-5h2v5h5V17z"></path><path d="M22 17L17 17 17 22 15 22 15 17 10 17 10 15 15 15 15 10 17 10 17 15 22 15z" data-icon-path="inner-path" opacity="0"></path>
				</svg>
			</button>
```

Where the child content and icon are both side by side. I'm not 100% sure why this works but maybe in safari having the content and icon in separate lines are treating the two as separate inline components.

**Comment by amirkhan064** [comment]
Even we knew the workaround. However, it would be better if we get the fix at the carbon level.

**Comment by cal-smith** [comment]
There's nothing we can do if safari is treating the svg and the text as two seperate inline elements - that's purely browser bug territory.

For icons be sure to use the directive form (`<svg ibmIconIconName></svg>`) as well 👍
