### ISSUE TITLE
Overflow menu not working inside <ibm-table-container> after carbon 3.32.0

### ISSUE THREAD

**Issue by sparikh1594** [IBM/carbon-components-angular#1064]
## Detailed description
> Describe in detail the issue you're having.
Overflow menu has stopped working inside <ibm-table-container> after updating to carbon 3.32.0

It does open now but closes the overflow right away

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
<ibm-table>

> What did you expect to happen? What happened instead? What would you like to see changed?
Would like to see overflow menu open and stay open until another action is clicked

> What browser are you working in?
Chrome. Works fine in Firefox

> What version of the Carbon Design System are you using?
3.39.6

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
ADI - This is a stop ship issue for us. We have our code freeze on Feb 21 2020

## Steps to reproduce the issue

https://codesandbox.io/s/carbon-components-angular-jipo3

## Additional information

* Screenshots or code
* Notes

**Comment by r4d** [comment]
seeing the same issue in 3.32.0 but not in 3.28.0

**Comment by sparikh1594** [comment]
I would like raise the severity for this issue as it's breaking a big part of the code. And we have to test the build by tomorrow. Is there any way the team can prioritize the issue

**Comment by sparikh1594** [comment]
Thank you all for the quick response!
