### ISSUE TITLE
Tabs containing expandable tiles cause expression changed errors when toggled

### ISSUE THREAD

**Issue by Donisius** [IBM/carbon-components-angular#1066]
When tabs contain expandable tiles it causes an `ExpressionChangedAfterItHasBeenCheckedError` when toggling between tabs.

**Comment by dabeng** [comment]
I came across the same issue. Please refer to demo - https://stackblitz.com/edit/carbon-components-angular-demo -> tile

**Comment by Donisius** [comment]
@dabeng I tried replicating the issue on code sandbox (since stackblitz isn't opening for me for some reason) but it seems like with the latest version of `carbon-components-angular` it does not show the error. I know that there was an issue a while back that fixed the adjusting of heights causing the expression changed error. You can checkout my demo - https://codesandbox.io/s/expandable-tiles-in-tabs-2rrfb

**Comment by dabeng** [comment]
@Donisius It woks. Thanks a lot.

**Comment by dabeng** [comment]
Hi @Donisius I got the same with latest version 3.43.0
<img width="764" alt="Screen Shot 2020-03-05 at 1 45 45 PM" src="https://user-images.githubusercontent.com/5689075/75951752-c4c62e00-5ee7-11ea-885a-ea78898a92e0.png">
