### ISSUE TITLE
Please export datepicker-input.module 

### ISSUE THREAD

**Issue by eddielca** [IBM/carbon-components-angular#1067]
## Detailed description

```BUILD ERROR
: Unexpected value 'DatePickerInputModule in /Users/eddieli/apps/buc-common/node_modules/carbon-components-angular/index.d.ts' imported by the module 'BucComponentsModule in /Users/eddieli/apps/buc-common/projects/common/src/lib/modules/buc-components/buc-components.module.ts'. Please add a @NgModule annotation.
: Can't export value DatePickerInputModule in /Users/eddieli/apps/buc-common/node_modules/carbon-components-angular/index.d.ts from BucComponentsModule in /Users/eddieli/apps/buc-common/projects/common/src/lib/modules/buc-components/buc-components.module.ts as it was neither declared nor imported!

Error: : Unexpected value 'DatePickerInputModule in /Users/eddieli/apps/buc-common/node_modules/carbon-components-angular/index.d.ts' imported by the module 'BucComponentsModule in /Users/eddieli/apps/buc-common/projects/common/src/lib/modules/buc-components/buc-components.module.ts'. Please add a @NgModule annotation.
: Can't export value DatePickerInputModule in /Users/eddieli/apps/buc-common/node_modules/carbon-components-angular/index.d.ts from BucComponentsModule in /Users/eddieli/apps/buc-common/projects/common/src/lib/modules/buc-components/buc-components.module.ts as it was neither declared nor imported!
```

we are currently packaging our wrapper component library which wraps around carbon angular components. So that we only need to upgrade this single library for all our iframe applications instead of going into each iframe repo.

we need the date picker input module to be exported for us to package a wrapper component module. Currently this is blocking us from build a valid npm package

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by cal-smith** [comment]
closed by #1082
