### ISSUE TITLE
I want a nested progress indicator

### ISSUE THREAD

**Issue by dabeng** [IBM/carbon-components-angular#1080]
I want a nested progress indicator. How can I achieve this with current carbon-components-angular ?
![fc89d0b7-7b75-4052-bcb4-82b772f3d27d](https://user-images.githubusercontent.com/5689075/75304524-6ad9be80-587e-11ea-8e12-eacf979c9df6.png)

**Comment by cal-smith** [comment]
There's no designs for this at the moment ... you should raise this as a design enhancement in https://github.com/carbon-design-system/carbon 

There may also be another pattern that would suit your needs better, so it's definitely worth exploring alternative designs
