### ISSUE TITLE
Progress indicator doesn't provide click event listener

### ISSUE THREAD

**Issue by Licen-it** [IBM/carbon-components-angular#1097]
## Detailed description

Checking the React version of this component, it expose a callback `onChange` that return the index of the step. This functionality is missing in the Angular version.

P.S.:
I'll contribute on this issue

**Comment by cal-smith** [comment]
We should definitely expose a `selected` or `change` event ... It may also make sense for it to support `NgModel` 🤔 ... We should probably emit the entire `Step` that's selected, as well as the index
