### ISSUE TITLE
Try to upgrade to Angular 9

### ISSUE THREAD

**Issue by bitforcesrl** [IBM/carbon-components-angular#1099]
## Try to upgrade to Angular 9
Carbon design is compatible with Angular 9?

## Problems
After updating angular/cli to Angular 9, I have these errors for each module: 

This likely means that the library (carbon-components-angular) which declares **StructuredListModule (SelectModule, TableModule .. )** has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

package.json
 "carbon-components": "^10.10.1",
 "carbon-components-angular": "^3.43.0",

**Comment by cal-smith** [comment]
This is known, we'll be adding support this quarter, see here for our release plan #896

We have a PR open here #1096 that you can follow as well
