### ISSUE TITLE
Overflow menu not opening if menu button is below the fold of scroll parent

### ISSUE THREAD

**Issue by calesce** [IBM/carbon-components-angular#1101]
## Detailed description

> Describe in detail the issue you're having.

See description, we hit the issue in our Carbon table but can be reproduced in the Storybook example

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Overflow menu

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

Chrome, FF

> What version of the Carbon Design System are you using?

Seen in 3.39.6 and latest on Storybook (should be 3.43.0)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Watson Health - Study Advance

## Steps to reproduce the issue
1. Go to the overflow menu [Storybook example](https://angular.carbondesignsystem.com/?path=/story/components-overflow-menu--basic).
2. Shrink the application height of the application so that the "Top Placement" overflow menu is below the fold, like this:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5377524/75825007-22cd0700-5d6a-11ea-9322-f59661c548cd.png">
3. Attempt to open the "Top Placement" menu and the menu will not open, and the scroll position may jump to the top.

## Additional information

* Happens with both top and bottom placement options
* I couldn't reproduce with this Code Sandbox example (might not have the right combination of styles and parent elements): https://codesandbox.io/s/carbon-components-angular-gjsxc but I see it in our app and in the storybook.

**Comment by cal-smith** [comment]
Pretty sure I reproduced locally:
![image](https://user-images.githubusercontent.com/1744185/75825845-32514d80-5d74-11ea-87b0-c6a488d6592a.png)

So in this example I've clicked on the overflow menu, and it's gotten the active state, but it's not opening. Not totally sure what the fix is here, but it definitly should open in this case ... we may need to add some padding to the visibility calculation.

To be clear, the desired behaviour here is that it _shouldn't_ open when it's fully out of the viewport, but it _should_ open when it's reasonably visible in the viewport?

**Comment by calesce** [comment]
Agreed that it should open when it's reasonably visible. I'll also note that even if it's initially below the fold then scrolled above the fold and fully visible it will still fail to open. It almost seems like the scroll event isn't causing the visibility calculation to re-run.

Also, it could be a good solution to have a `placement="auto"` option that looks at the fold to see whether to position it "top" or "bottom".

Thanks for the quick response!

**Comment by calesce** [comment]
Hi @cal-smith, wondering if you know when you all will get to this one. We have a code freeze date of March 19th for our next release so we'll need to use a workaround if it looks like it'll be after the 17th or so.

In our case the overflow menu is in a data table so we can probably use pagination in favor of scrolling as a workaround.

**Comment by cal-smith** [comment]
I'll take a look at it this week!
