### ISSUE TITLE
Data table: Checkbox for all broken when used with skeleton

### ISSUE THREAD

**Issue by trytosend** [IBM/carbon-components-angular#1103]
## Detailed description

> Describe in detail the issue you're having.
BUG REPORT:
When changing model of the table, main checkbox misbehaves. On (selectAll) and (deselectAll) always triggers (selectAll).
Code example: https://stackblitz.com/edit/angular-7wrzxr 

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Data table

> What did you expect to happen? What happened instead? What would you like to see changed?
Expected function (deselectAll) to unmark all checkboxes

> What browser are you working in?
Chrome & Firefox

> What version of the Carbon Design System are you using?
"carbon-components": "^10.9.3",
"carbon-components-angular": "^3.40.3",

## Steps to reproduce the issue

Example code here: https://stackblitz.com/edit/angular-7wrzxr

1. try to use checkbox for all

## Additional information

![skeleton_checkbox_bug](https://user-images.githubusercontent.com/26918024/75851817-e8577e80-5dea-11ea-8f26-20e67b376f30.gif)

**Comment by Donisius** [comment]
Instead of switching the models you should just do `this.model = Table.skeletonModel(5, 5);` and then set `this.model` to a new `TableModel` when you have the data, or in the case of your example in the setTimeout

**Comment by trytosend** [comment]
Hello Donisius, that is exactly how I was using it before, but same error occurs when you switch 2 times between real model and skeletonModel. Example where I faced it was when I was using select, which was switching table data. Each time I selected something, it made call on BE and displayed skeleton. But when I displayed second set of real data it always bugged and stayed bugged.
