### ISSUE TITLE
Fix DAP issues for Content Switcher

### ISSUE THREAD

**Issue by youda97** [IBM/carbon-components-angular#111]
Level | Description
-- | --
V | All content must reside within a WAI-ARIA landmark or labelled region role. | Details
V | Widget with role of tablist must have no more than one tabbable element.

**Comment by cal-smith** [comment]
1. association or preview issue
2. we'll have to check carbon-components and carbon-components-react, but I'm not sure that arrow keys only is right for this (which is what this implys)
