### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by Akshat55** [IBM/carbon-components-angular#1134]
## Detailed description

> Describe in detail the issue you're having.
Tried to build the project, but build failed (ng build --prod).

> Is this issue related to a specific component?
Combobox

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected my project to build instead my project did not build 😟

> What version of the Carbon Design System are you using?
Latest - 3.46.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
SUP - Releasing on March 31 - Can't build docker image

## Steps to reproduce the issue
ng build --prod || building in general

## Additional information

* Screenshots or code
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/38994122/76921676-04f0bd80-68a5-11ea-89b1-a492d98b5a09.png">

**Comment by zvonimirfras** [comment]
Fixed in #1132 
Reopen if still a problem after it
