### ISSUE TITLE
Fix DAP issues for Modal

### ISSUE THREAD

**Issue by youda97** [IBM/carbon-components-angular#114]
Level | Description
-- | --
V | The WAI-ARIA role(s) and/or attribute(s) aria-modal are not valid for the element div. See rule help for guidance. | Details
V | The WAI-ARIA role(s) and/or attribute(s) banner are not valid for the element header. See rule help for guidance. | Details
V | The WAI-ARIA role(s) and/or attribute(s) contentinfo are not valid for the element footer. See rule help for guidance. | Details
V | All content must reside within a WAI-ARIA landmark or labelled region role.

**Comment by aradhikaIbm** [comment]
I'm trying to take a look at these issues as an effort for IWR accessibility compliance.

**Comment by aradhikaIbm** [comment]
Actually there are 3 issues related to modal: 


Level | Description | Fix
-- | --
V | The WAI-ARIA role(s) and/or attribute(s) aria-modal are not valid for the element div. See rule help for guidance. | set the role to dialog
-- | --
V | The WAI-ARIA role(s) and/or attribute(s) banner are not valid for the element header. See rule help for guidance. | Per investigation header does not need the role. Seems per the html5 element the default role does not need to be specified.
V | The WAI-ARIA role(s) and/or attribute(s) contentinfo are not valid for the element footer. See rule help for guidance.  | Per investigation footer does not need the role. Seems per the html5 element the default role does not need to be specified.
