### ISSUE TITLE
Time picker select's arrow displays incorrectly on IE11

### ISSUE THREAD

**Issue by jdcai** [IBM/carbon-components-angular#1143]
## Detailed description

> Describe in detail the issue you're having.

Issue details can be found at https://github.com/carbon-design-system/carbon/issues/5651

There is a pull request https://github.com/carbon-design-system/carbon/pull/5672 that will fix the issue for vanilla and react since the class "bx--select_arrow" is on the SVG but for angular it will make it display incorrectly in all browsers since the class will be on the container instead of the SVG.
![image](https://user-images.githubusercontent.com/4312305/77320490-0aa43400-6ce7-11ea-9725-1c15e2b90fa1.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Time picker select

> What did you expect to happen? What happened instead? What would you like to see changed?

Arrow should display correctly on IE11. Maybe if the arrow icon uses carbon icons angular's SVG directive instead of the component. This way we can put the class `class="bx--select__arrow"` on the SVG and it should display correctly.

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

carbon-components: 10.10.2
carbon-components-angular: 3.46.6

**Comment by jdcai** [comment]
@cal-smith @Donisius The icon got changed back to a component instead of a directive and is causing this issue again. Https://github.com/IBM/carbon-components-angular/blob/master/src/timepicker-select/timepicker-select.component.ts

**Comment by cal-smith** [comment]
😱 totally our bad ... I'll do up a PR to sort that out ... are you seeing that with v4? or v3?

**Comment by jdcai** [comment]
I'm seeing it with v4.1.6. For v3 i've just been on v3.49.5 where it's working.

**Comment by cal-smith** [comment]
This seems to have been fixed again at some point 👍
