### ISSUE TITLE
Table component vertical scroll issue

### ISSUE THREAD

**Issue by nitishjain07** [IBM/carbon-components-angular#1148]
Table component - Expandable table (https://angular.carbondesignsystem.com/?path=/story/components-table--with-expansion)

To replicate - Expand any table row. Now scroll up and down.

Issue - Once user tries to scroll through page, vertical scrollbar shows inside table because of which user is not able to scroll through page.

This issue got induced in carbon version - 3.45.1. As earlier, this wasn't there.

Kindly look into this. Thanks in advance!

**Comment by nitishjain07** [comment]
According to my findings issue is because of styling property **display: block** to table container with class - **bx--data-table-container**. If I overwrite this property with **display: inline** it fixes the issue.

I saw below code in latest version which adds this property to table container:
[_nghost-oml-c28] {
    display: block;
    position: relative;
}

**Comment by Donisius** [comment]
Should be fixed by https://github.com/IBM/carbon-components-angular/pull/1145
