### ISSUE TITLE
Table component - setTimeout and message handler violation issues

### ISSUE THREAD

**Issue by abhisheksinghrana** [IBM/carbon-components-angular#1151]
There are lot of setTimeout and message handler issues are coming while scrolling table component because of that page gets hanged or sometime start responding slowly.

<img width="880" alt="violation issue" src="https://user-images.githubusercontent.com/29912424/77610024-90261f00-6f47-11ea-99e8-d8ef75b800c7.png">

@cal-smith @zvonimirfras

**Comment by cal-smith** [comment]
Hey @abhisheksinghrana sorry this has taken so long, we've been pretty swamped with some of the v4/v11 work ... I did some preliminary testing, and it does seem like as the rows increase some of the interactions do slow down quite significantly. That being said, in order for it to slow down to a noticeable degree I had to add quite a few rows - have you explored using pagination as a way to reduce the number of rows visible on screen?

**Comment by asudoh** [comment]
Weighing in and @cal-smith has a good point. Another suggestion I have for the issue author is following below steps:

1. Go to Performance tab
2. Hit the Record (icon) button
3. Run the use case that shows the console log in question
4. Click on the Stop button
5. Hit the Save profile (icon) button and select the download location
6. Post the downloaded file here

![performance-tab-1](https://user-images.githubusercontent.com/1259051/82101142-a29e2700-9746-11ea-813b-d18c23cb87a9.gif)

In this way, the team can have much clearer insight of what the offending code is, without having to spending time to guess how to re-create the performance problem. Hope this helps!

BTW agreed with @cal-smith that pagination is a "must" for ensuring performance. Without it, the page can have excessive amount of DOM nodes that Carbon Angular library would have no control over for the performance.

**Comment by ninja511** [comment]
Any updates on this?

**Comment by ninja511** [comment]
closing for now - reopen if needed
