### ISSUE TITLE
Overflow Menu - Showing cannot set property 'tabIndex' of undefined

### ISSUE THREAD

**Issue by abhisheksinghrana** [IBM/carbon-components-angular#1152]
Whenever we open overflow menu it always give error "Cannot set property 'tabIndex' of undefined" in console.

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/29912424/77610516-ed6ea000-6f48-11ea-89cf-386aa4c6762b.png">

@cal-smith @zvonimirfras

**Comment by Donisius** [comment]
I can't seem to reproduce the issue, what version of `carbon-components-angular` are you using?

**Comment by abhisheksinghrana** [comment]
@Donisius, We are using latest version.
We are using ibmOverflowMenu directive and passing custom template.
We are not using overflow menu options as they are not required.
Snippet is attached below.

`<div class="filter-btn bx--toolbar-action" *ngIf="showFilter && filterComponent" [ibmOverflowMenu]="filterPanel" [flip]="true" [placement]="'bottom' [offset]="filterDetails?.offset">`
        `<ibm-icon-settings-adjust16>
        </ibm-icon-settings-adjust16>`
`</div>`

`<ng-template #filterPanel><div (click)="stopPropagation($event)">`
    `<woo-table-filter-placeholder [data]="filterDetails" (applyFilters)="applyFilters($event)">
    </woo-table-filter-placeholder>`
  `</div>`
`</ng-template>`
