### ISSUE TITLE
ibm-label cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by martijnmelchers** [IBM/carbon-components-angular#1158]
# Detailed description

### Describe in detail the issue you're having.
When using the `ibm-label` component throws an error (not fatal, page still loads) when you use it in Angular 9

### Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

Is this issue related to a specific component?

ibm-label

### What did you expect to happen? What happened instead? What would you like to see changed?

Not throw an error, instead it threw the following error:
```
login.component.html:12 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at Label.push../node_modules/carbon-components-angular/input/label.component.js.Label.ngAfterContentInit (label.component.js:73)
    at callProviderLifecycles (core.js:33680)
    at callElementProvidersLifecycles (core.js:33652)
    at callLifecycleHooksChildrenFirst (core.js:33634)
    at checkAndUpdateView (core.js:45977)
    at callViewAction (core.js:46338)
    at execComponentViewsAction (core.js:46266)
    at checkAndUpdateView (core.js:45979)
    at callViewAction (core.js:46338)
    at execEmbeddedViewsAction (core.js:46295)
```
### What browser are you working in?
Chrome version 80

### What version of the Carbon Design System are you using?
3.47.1

## Steps to reproduce the issue
Use angular 9, create a page and just add the following:
```html
<ibm-label
            helperText="The email you used during sign-up"
            [invalid]="true"
            invalidText="Please enter a valid email">
            Email
            <input ibmText formControlName="email" name="email">
          </ibm-label>
```

**Comment by martijnmelchers** [comment]
This is still not resolved in v4.
Is there a reason why we're getting this error?...

**Comment by martijnmelchers** [comment]
@cal-smith Any updates on this, this makes the project seem very messy?

**Comment by cal-smith** [comment]
Hey 👋 super sorry this fell through the cracks! There's been some post-release issues with `@carbon/icons-angular` that has been taking up most of my time. Totally my bad!

We'll definitely investigate this, but if you wanted to contribute a fix or propose a solution that would be amazing! We rely pretty heavily on community contributions 🙂

Sorry again if this gave a bad impression! We definitely don't want to lose track of anything.

**Comment by Donisius** [comment]
Seems like this only happens when I use version 4.1.0 or earlier, it looks like a guard was introduced in #1205. So just upgrade to version 4.1.1 or later and you shouldn't come across this error. https://codesandbox.io/s/carbon-components-angular-7bt0h?file=/src/app/app.component.html
