### ISSUE TITLE
Modal overflow indicator is permanently enabled

### ISSUE THREAD

**Issue by jmcguire23** [IBM/carbon-components-angular#1172]
It appears a new element has been recently added to the modal component which shows a gradient fade effect to the bottom of the modal content. This should be conditional, and allow the developer to make a choice of when and where they would enable this. 

https://github.com/IBM/carbon-components-angular/blob/94a3c9f1e18686b3652d218a96b389f850fd2ac5/src/modal/modal.component.ts#L101

If you see the React implementation, they have wrapped this particular element in a conditional rendering block - 
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Modal/Modal.js#L399

I would make the suggestion to of appending a `*ngIf` to this element and a new input that sets a boolean value that controls the visibility of this element.

**Comment by blaise2s** [comment]
What's the status of this fix? We wanted to update our version of carbon but now I'm hesitant and wanting to see progress here before updating.
