### ISSUE TITLE
Input textbox disable not working with formcontrolname

### ISSUE THREAD

**Issue by anusha801** [IBM/carbon-components-angular#1177]
I am trying to implement disabling of textbox. Below is the piece of code that I tried. Disabling works fine when I dont add formcontrolname,but when I add formcontrolname disabled doesnt work.below code doesnt work because of formcontrolname.
**html**
```
<div [formGroup]="sampleForm">
<ibm-label
	[helperText]="helperText">
			{{'Identifier'}}
			<input
				ibmText
			        formControlName="identifier"
				[disabled]="disabled"
				[placeholder]="'something'"
				[autocomplete]="'off'">
		</ibm-label>
		</div>
```

**component**

```
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
 
  disabled = true;
  sampleForm: FormGroup;
  constructor(private fb: FormBuilder) {
  }
  ngOnInit() {
    this.createSearch();
   
  }
  createSearch() {
    this.sampleForm = this.fb.group({
      identifier: ['']
    });
  }
}

```

**module.ts** 

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {InputModule, StructuredListModule} from 'carbon-components-angular';
import { AppComponent } from './app.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    InputModule,
    StructuredListModule,
    FormsModule,
    ReactiveFormsModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }


```

**Comment by Donisius** [comment]
If you are using a FormGroup you won't be able to disable HTML along with a FormControl. You can disable it within the form control like this:
```
@Component({
	selector: 'app-reactive-forms',
	template: `
		<form [formGroup]="formGroup">
			<ibm-label>
				<input
					ibmText
					formControlName="input"
					[disabled]="disabled"
					placeholder="Placeholder text">
			</ibm-label>
		</form>
	`
})
class ReactiveFormsStory implements OnInit {
	formGroup: FormGroup;

	@Input() disabled = true;

	constructor(protected formBuilder: FormBuilder) {}

	ngOnInit() {
		this.formGroup = this.formBuilder.group({
			input: new FormControl({ value: '', disabled: this.disabled })
		});
	}
}
```

**Comment by cal-smith** [comment]
> If you are using a FormGroup you won't be able to disable HTML along with a FormControl. You can disable it within the form control like this:
> 
> ```
> @Component({
> 	selector: 'app-reactive-forms',
> 	template: `
> 		<form [formGroup]="formGroup">
> 			<ibm-label>
> 				<input
> 					ibmText
> 					formControlName="input"
> 					[disabled]="disabled"
> 					placeholder="Placeholder text">
> 			</ibm-label>
> 		</form>
> 	`
> })
> class ReactiveFormsStory implements OnInit {
> 	formGroup: FormGroup;
> 
> 	@Input() disabled = true;
> 
> 	constructor(protected formBuilder: FormBuilder) {}
> 
> 	ngOnInit() {
> 		this.formGroup = this.formBuilder.group({
> 			input: new FormControl({ value: '', disabled: this.disabled })
> 		});
> 	}
> }
> ```

I believe it should be possible to call `.disable` to disable the control, without needing the extra binding you have there ... I _think_ this is just a missing feature on our side (i.e. we haven't 100% implemented the form control API)

**Comment by cal-smith** [comment]
Huh 🤷‍♂️ okay, unsure where the issue could be then, since that should always work
