### ISSUE TITLE
Overflow menu position is incorrect

### ISSUE THREAD

**Issue by chengjun0124** [IBM/carbon-components-angular#120]
Hi guys
I saw [PR76](https://github.com/IBM/carbon-components-angular/pull/76). It should fix the position issue. But I still got this issue after I upgrade to 1.8.1

Overflow menu works fine in https://angular.carbondesignsystem.com/. But it doesn't appear at the correct position in my local project. I checked the html structures in https://angular.carbondesignsystem.com/ and my local project, they are different.

Html structure from https://angular.carbondesignsystem.com/
```
<ibm-overflow-menu>
    <div placement="bottom"></div>
</ibm-overflow-menu>
<ibm-dialog-placeholder>
    <div></div>
    <ibm-overflow-menu-pane>
        <ul class="bx--overflow-menu-options undefined" style="top: 38px; left: -20px;">
            <ibm-overflow-menu-option>
                <button>xxx</button>
            </ibm-overflow-menu-option>
        </ul>
    </ibm-overflow-menu-pane>
</ibm-dialog-placeholder>
```

Html structure from my project
```
<ibm-overflow-menu>
    <div ng-reflect-ibm-overflow-menu="[object Object]"></div>
    <ibm-overflow-menu-pane>
        <div class=" undefined" style="top: 675px; left: -873px;">
            <ul class="bx--overflow-menu-options">
                <ibm-overflow-menu-option>
                    <button ng-reflect-klass="bx--overflow-menu-options__btn" ng-reflect-ng-class="[object Object]">xxx</button>
                </ibm-overflow-menu-option>
            </ul>
        </div>
    </ibm-overflow-menu-pane>
</ibm-overflow-menu>
<ibm-dialog-placeholder>
    <div></div>
</ibm-dialog-placeholder>
```
Here is the code I used in my project
```
<ibm-overflow-menu>
      <ibm-overflow-menu-option>Option 2</ibm-overflow-menu-option>
    </ibm-overflow-menu>
<ibm-dialog-placeholder></ibm-dialog-placeholder>
```

**Comment by cal-smith** [comment]
I would make sure you're pulling the latest version of `carbon-components-angular` - make sure you remove package-lock.json and clear node_modules. It seems to me like it's still pulling an outdated version.

Let me know if that fixes it 👍 if not a sample project/codesandbox would be super helpful!

**Comment by chengjun0124** [comment]
Hi Callum
Yes, I deleted package-lock.json and node_modules, I am using `carbon-components 9.23.0` and `carbon-components-angular 1.8.1`.

Will try create a sample later.

**Comment by chengjun0124** [comment]
Hi Callum
https://codesandbox.io/s/oq658zrx65 

`@import "~carbon-components/scss/globals/scss/styles.scss";`
This code didn't work correctly, I have not debugged it in time, so I commented it in styles.scss. 

What I care is why html structure of overflow menu is different with https://angular.carbondesignsystem.com/, does this make menu in wrong position?

Please use browser dev tool to see the html structure after you click menu.

![1](https://user-images.githubusercontent.com/16715803/46126510-2c426d80-c260-11e8-874a-0c19249db045.jpg)

**Comment by zvonimirfras** [comment]
It looks like it doesn't really "appendToBody".

**Comment by zvonimirfras** [comment]
It also looks like the PR has the proper format to trigger publishing but commits don't. We'll need to add an empty commit to give it a push. @cal-smith, wanna do that?

Side-note, it would be really great if semantic-release could use the PR name format instead of commit message format. A lot of reasons...

**Comment by cal-smith** [comment]
If you set the pr commit title to be valid for semantic release i believe it works. The github pr title isn't passed to git so semantic release has no idea what it should be.

We can test this out with some upcoming PRs though

**Comment by cal-smith** [comment]
Confusingly I think `1.8.2` should have all the updates

**Comment by zvonimirfras** [comment]
Does that mean we can close this?

**Comment by scarraway** [comment]
Btw- seems to work for me in `1.8.3`

**Comment by zvonimirfras** [comment]
Ok, closing for now, reopen if issue reappears.
