### ISSUE TITLE
Sidenav with Model for large devices

### ISSUE THREAD

**Issue by sumerabegum** [IBM/carbon-components-angular#1200]
I am implementing header with sidenav in my application using UIShell - header, For creating dynamic menu ( sidenav with model ) I have used the below code snippet, the navigationItems input works for small devices and does not work for the large device.

<ibm-sidenav *ngIf="isMenuVisible&&active" [navigationItems]="navigationItems" [expanded]="active">

**Comment by cal-smith** [comment]
The `navigationItems` input is just for items from the header that should appear in the sidnav when the screen is small :+1: For all other items you should include them between the `ibm-sidenav` tags 👍
