### ISSUE TITLE
how to control placement of Overflow menu

### ISSUE THREAD

**Issue by chengjun0124** [IBM/carbon-components-angular#121]
Hi

I tried `autoPosition` and `placement` of directive `ibmOverflowMenu' to control the menu positon. Seems they don't work.

**Comment by cal-smith** [comment]
`autoPosition` is deprecated ... it should probably be removed ... I think `placement` in `ibmOverflowMenu` needs to be enhanced to support the `top` placement, then you can do `placement="top"` (for just top placement) or `placement="bottom,top`" (for auto positioning)

**Comment by chengjun0124** [comment]
hi Callum
could you please also enhance placement=left? thank you.

**Comment by chengjun0124** [comment]
Hi Callum
Thank you.

You will also enhance left and right, right?

**Comment by cal-smith** [comment]
the overflow menu only supports left and right placement, so an input has been added to flip it left or right!
