### ISSUE TITLE
Daterange Picker - Closes overflow menu on clicking over dates.

### ISSUE THREAD

**Issue by abhisheksinghrana** [IBM/carbon-components-angular#1227]
We are using overflow menu as filter panel.
On that filter panel, we are using daterange picker and we added event.stopPropagation() on entire panel so, it will not close on clicking inside the panel.

## Issue description
When we click on daterange picker for selecting date, 70-80% time it closes the filter panel instead of opening datepicker even we have stopPropagation on panel.

## Library versions
Angular - 8.2.14,
"carbon-components": "10.10.3",
"carbon-components-angular": "3.49.7"

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/29912424/80136985-28073f00-85c0-11ea-851f-4d29c78056e2.png">

@Donisius

**Comment by Donisius** [comment]
Doing it like below seems to work, the stop propagation prevents the pane from closing when its' content is clicked:
```
		        <div
				class="filter-btn bx--toolbar-action"
				[ibmOverflowMenu]="filterPanel"
				placement='bottom'>
				Clickeroni
			</div>

			<ng-template #filterPanel>
			<div (click)="$event.stopPropagation()">
				<ibm-date-picker
					[label]="label"
					[placeholder]="placeholder"
					[language]="language"
					[theme]="theme"
					[value]="value"
					[disabled]="disabled"
					[invalid]="invalid"
					[invalidText]="invalidText"
					[dateFormat]="dateFormat"
					(valueChange)="valueChange($event)">
				</ibm-date-picker>
				<button>test</button>
			</div>
			</ng-template>
			<ibm-placeholder></ibm-placeholder>
```
A possible reason it isn't working for you could be because the datepickers you have are not actually inside of the pane area and you are clicking outside.

**Comment by ninja511** [comment]
closing pending additional information.
