### ISSUE TITLE
Update ModalService and sample to not use deprecated classes/methods

### ISSUE THREAD

**Issue by teresamonahan** [IBM/carbon-components-angular#123]
## Detailed description

The ModalService currently uses ReflectiveInjector which was deprecated in V5: See https://angular.io/api/core/ReflectiveInjector.
https://angular.io/api/core/Injector#create should be used instead.

Also the sample modal component passes values through to the dialog using `this.injector.get("modalText")`. However injector.get is deprecated since V4 in favour of https://angular.io/api/core/Injector#get which uses Type<T> or InjectionToken<T> rather than any.

These issues show up as lint warnings in my project but it doesn't look like the deprecation rule or type checking is enabled for linting in the carbon-components-angular repo.

> Is this issue related to a specific component? Yes, the Modal

> What would you like to see changed? Use of more up to date APIs 

> What browser are you working in? Latest

> What version of the Carbon Design System are you using? Latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? Assess

FYI there may be a better approach but it's possible to inject simple data types using the `@Inject` parameter decorator instead of using injector.get

i.e. SampleModalComponent would change from 

```
class SampleModalComponent {
	modalText: string;
	constructor(private injector: Injector) {
		this.modalText = this.injector.get("modalText");
	}
}
```

to this:
```
class SampleModalComponent {
	modalText: string;
	constructor(@Inject('modalText') text:string) {
		this.modalText = text;
	}
}
```

**Comment by teresamonahan** [comment]
FYI @cal-smith

**Comment by cal-smith** [comment]
Thanks!
