### ISSUE TITLE
Question: How to implement Pagination without using a TableModel?

### ISSUE THREAD

**Issue by ksurendra** [IBM/carbon-components-angular#1230]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue? Question

> Is this issue related to a specific component? Yes, Pagination

> What version of the Carbon Design System are you using? 
   "carbon-components": "^10.6.2",
   "carbon-components-angular": "^3.17.3",

## Additional information

We have an array of objects (Paper). Also using a Search filter.

Our code in .html:
```
<ibm-search
    placeholder="Search title"
    (clear)="clearSearch()"
    [(ngModel)]="listFilter"
    >Search</ibm-search>

<ibm-pagination
    [model]="filteredPapers"
    (selectPage)="selectPage($event)">
</ibm-pagination>
...
...
<div ibmRow *ngFor="let paper of filteredPapers">
...
.. display articles here {{ filteredPapers. }}..
...
</div>

in .ts
// Pagination
selectPage(page) {
	console.log('..selectPage', page);
	// implementation..
}
```

How can we implement this? Or would appreciate if we can refer to any blogs/articles.

Most examples we are finding are based on TableModel but we do not have a table:
```
in .html:
<ibm-pagination [model]="model" (selectPage)="selectPage($event)"></ibm-pagination>

in .ts:
import { TableModel, TableHeaderItem, TableItem } from 'carbon-components-angular';
..
model = new TableModel();
```

**Comment by cal-smith** [comment]
You'll want to take a look at the `PaginationModel` :+1: It's a pretty simple class, but it should be all you need to use the pagination

**Comment by ksurendra** [comment]
Thanks @cal-smith 

Was able to make some progress: (works only when page loads. Any click on bar not loading content.. trying to solve it).

```
<ibm-pagination
	[model]="model"
	(selectPage)="selectPage($event)">
</ibm-pagination>
```

component typescript:
```
import { PaginationModel } from 'carbon-components-angular';
..
@Input() model = new PaginationModel();
@Input() skeleton = false;
@Input() disabled = false;
@Input() pageInputDisabled = false;
@Input() pagesUnknown = false;

@Input() get totalDataLength() {
	return this.model.totalDataLength;
}
set totalDataLength(value) {
	this.model.totalDataLength = value;
}
       ...
       ...
// Pagination
selectPage(page) {
	console.log('Loading page', page, 'from pagination model');
	this.model.currentPage = page;
	this.model.totalDataLength = this.filteredPapers.length;

	// manage
	const offset = this.model.pageLength * (page - 1);
	const pageRawData = this.filteredPapers.slice(offset, offset + this.model.pageLength);
	this.filteredPapers = this.prepareData(pageRawData);
	this.model.currentPage = page;
}

prepareData(data) {
	const newData = [];

	for (const datum of data) {
		newData.push(datum);
	}
	return newData;
}
```

**Comment by ksurendra** [comment]
Was able to solve this. Solution at 
https://stackoverflow.com/questions/61412753/how-to-implement-pagination-in-angular-carbon-design-system-without-using-a-tabl/61433354#61433354
