### ISSUE TITLE
weekday format inconsistencies in DatePicker calendar

### ISSUE THREAD

**Issue by neoccccc** [IBM/carbon-components-angular#1231]
## Detailed description

> Describe in detail the issue you're having.

there are some inconsistencies between angular version of calendar and the official documentation. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Date Picker

> What browser are you working in?

Chrome

> version

3.28.0

## Additional information

* Screenshots or code
angular:
![image](https://user-images.githubusercontent.com/4793962/80258497-60a32900-8651-11ea-83a8-4102fa5db6be.png)

official docs:
![image](https://user-images.githubusercontent.com/4793962/80258477-53863a00-8651-11ea-883f-034a435dc6be.png)

**Comment by asudoh** [comment]
Weighing in; I know it's hacky, but we historically mangle those day-in-the-week strings: https://github.com/carbon-design-system/carbon/blob/v10.11.0/packages/components/src/components/date-picker/date-picker.js#L32-L39

**Comment by neoccccc** [comment]
> Weighing in; I know it's hacky, but we historically mangle those day-in-the-week strings: https://github.com/carbon-design-system/carbon/blob/v10.11.0/packages/components/src/components/date-picker/date-picker.js#L32-L39

Thank you for the reply! However I am a bit confused as I am new to this. How do I access Flatpickr through DataPicker object?

**Comment by asudoh** [comment]
Uh, I tried to provide a hint wrt how this library code can address the problem, not necessarily in application code.
