### ISSUE TITLE
Error placing a list inside a non-HTML element

### ISSUE THREAD

**Issue by BitForger** [IBM/carbon-components-angular#1236]
Line affected:
https://github.com/IBM/carbon-components-angular/blob/389ef8f6b1acd8029d34b35852a62021719a7fe6/src/list/list.directive.ts#L29

### Example Code:
```html
<ibm-accordion>
	<ibm-accordion-item>
		<ul ibmList>
			<li ibmListItem>test</li>
		</ul>
	</ibm-accordion-item>
</ibm-accordion>
```

When placing a list using `ibmList` inside an element that is a component or other angular supplied element (eg. `ng-container`) you receive an error:
```
ERROR TypeError: Cannot read property 'tagName' of null
    at List.get nested [as nested] (carbon-components-angular.js:15054)
    at List.get ordered [as ordered] (carbon-components-angular.js:15036)
    at List_HostBindings (carbon-components-angular.js:15059)
    at setHostBindingsByExecutingExpandoInstructions (core.js:11571)
```

## Debugging
I set a conditional breakpoint on the line affected according to the error message
![image](https://user-images.githubusercontent.com/7409480/80392501-3fbf1b80-887d-11ea-87f3-c43445a355b4.png)

I reloaded the page and waited for the breakpoint to activate. `this.elementRef.nativeElement` looks like:
![image](https://user-images.githubusercontent.com/7409480/80393004-e2779a00-887d-11ea-960d-dfc71e10c2ed.png)

## Workarounds
The workaround is to use to wrap the list in a native HTML element.
```html
<ibm-accordion>
	<ibm-accordion-item>
		<div class="list-wrapper">
			<ul ibmList>
				<li ibmListItem>test</li>
			</ul>
		</div>
	</ibm-accordion-item>
</ibm-accordion>
```

## Discussion
Is this how you intend for lists to work? If the above workaround is actually desired usage then feel free to close this.

However, if this isn't desired behavior I can certainly prepare a PR for this to resolve the issue.

**Comment by cal-smith** [comment]
Lists should definitely work as content to an Angular component :+1: It would be awesome if you could make a PR to sort this out!
