### ISSUE TITLE
Small square appears in date picker on mobile size

### ISSUE THREAD

**Issue by Donisius** [IBM/carbon-components-angular#1243]
A small square appears in the date picker input on mobile size that when clicked generates an input element.

![image](https://user-images.githubusercontent.com/45505172/80809887-9fc10500-8b90-11ea-92a9-6397e8a96b67.png)

**Comment by ChenCheress** [comment]
hi @Donisius, could you please help to fix it asap, because this has caused a production issue, thank you very very much!

**Comment by Donisius** [comment]
@ChenCheress I've had issues reproducing the problem can you provide the code used to create the date picker component, and the version of `carbon-components` and `carbon-components-angular` you are using? thanks

**Comment by ChenCheress** [comment]
@Donisius 
The code is in below:
```
<ibm-date-picker
                [label]="'label'"
                [placeholder]="'placeholder'"
                [language]="'en'"
                [theme]="'dark'"
                [value]="interviewDate"
                [disabled]="false"
                [invalid]="false"
                [invalidText]="'invalidText'"
                [dateFormat]="'m/d/Y'"
                (valueChange)="valueChange($event)">
            </ibm-date-picker>
```
----------------------------------------------
and the version we use are: 
    "carbon-components": "10.4.1",
    "carbon-components-angular": "3.21.0",
-------------------------------------------------
Notes: this error happens only for mobile mode, when you open console in Chrome, and select mobile or pad device, it will continue to cause errors like this and the datepicker doesn't work:
https://ibm.enterprise.slack.com/files/WEJHM77HS/F012LNTFJDC/image.png

**Comment by Donisius** [comment]
@ChenCheress So the issue did come up for me on version 3.21.0, however upgrading to version 3.49.7, the issue seems to have already been fixed.

The template I used was:
```
	<ibm-date-picker [flatpickrOptions]="{ disableMobile: true }">
	</ibm-date-picker>
```

and the result after clicking on mobile size:
<img width="412" alt="Screen Shot 2020-05-06 at 11 37 08 AM" src="https://user-images.githubusercontent.com/45505172/81197459-48ef6d00-8f8e-11ea-953f-9bcc8157f5b8.png">

I am closing this seems it seems to already have been fixed but please feel free to reopen if the issue still exists.
