### ISSUE TITLE
Tab index doesn't seem to be working on structured list row (v3)

### ISSUE THREAD

**Issue by jdcai** [IBM/carbon-components-angular#1256]
## Detailed description

The list row element doesn't have a tabindex when the structured list selection is set to true. You aren't able to tab to it.

In the code it looks like when selection is set to true on the structured list it will set selection to true on the list row too
https://github.com/IBM/carbon-components-angular/blob/ee4efffde616a2c6165131b18ff6fd19ca6a95c6/src/structured-list/structured-list.component.ts#L154

And when selection is set to true on list row it should set tabindex but it doesn't seem to work
https://github.com/IBM/carbon-components-angular/blob/ee4efffde616a2c6165131b18ff6fd19ca6a95c6/src/structured-list/list-row.component.ts#L80

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug
> Is this issue related to a specific component?

Structured list and list row
> What did you expect to happen? What happened instead? What would you like to see changed?

The list rows should be tabable and when pressing enter or space it should trigger the selection. 
Not sure if the pressing enter or space to trigger selection is already there or not since tabbing isn't working but I would like to be able to do that.

> What browser are you working in?

Chrome
> What version of the Carbon Design System are you using?

3.46.5, issue is also happening on current storybook
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM AD
## Steps to reproduce the issue

https://angular.carbondesignsystem.com/?path=/story/components-structured-list--with-selection

If you press tab you are not able to tab to a row and if you inspect the element there isn't a tab index attribute on it

**Comment by jdcai** [comment]
@Donisius could the fix also be put in the v3?

**Comment by Donisius** [comment]
> @Donisius could the fix also be put in the v3?

@jdcai sure!

**Comment by cal-smith** [comment]
Re-opening to track for V3

**Comment by cal-smith** [comment]
Done!
