### ISSUE TITLE
[Request] Allow importing of `cycleTabs` utility of `tab.service` in V4

### ISSUE THREAD

**Issue by sjbeatle** [IBM/carbon-components-angular#1266]
## Allow importing of `cycleTabs` function of `tab.service` in V4
Perhaps other services and utilities, as well. Some of them are very helpful and remove the need to create utilities "in-house".

## Detailed description
Previously, we could deep import utilities such as `cycleTabs` by doing the following:
```typescript
import { cycleTabs } from 'carbon-components-angular/common/tab.service';
```
Since updating to v4, I now get the following build error:
>ERROR in ./src/app/subscriptions/filter-panel/filter-panel.component.ts
>Module not found: Error: Can’t resolve ‘carbon-components-angular/common/tab.service’ in ‘/[PATH]/packages/ui/src/app/subscriptions/filter-panel’

---

### What version of the Carbon Design System are you using?
v4 (w/Angular 8)
@cal-smith

**Comment by cal-smith** [comment]
I believe this is possible now 👍 I just checked the exports in `common` and it appears to be exported ... I'm going to close this now, definitely re-open if it's still an issue!
