### ISSUE TITLE
Add List component

### ISSUE THREAD

**Issue by bculrey** [IBM/carbon-components-angular#127]
HTML and style: http://carbondesignsystem.com/components/list/code
Usage: http://carbondesignsystem.com/components/list/usage
Styling: http://carbondesignsystem.com/components/list/style

**Comment by esuau** [comment]
There is already a `ListGroup` component. What do you think about starting from this basis?

**Comment by cal-smith** [comment]
`ListGroup` was closer to the `StructuredList` ... it's kinda gone now anyway, since carbon doesn't have a good equivalent
