### ISSUE TITLE
Table toolbar can get shifted vertically

### ISSUE THREAD

**Issue by daveweaverweather** [IBM/carbon-components-angular#1271]
## Detailed description

Under certain circumstances the table toolbar get get shifted up vertically such that only the bottom half/third of it is visible.

I've seen the issue on Chrome and Firefox. I've not tested other browsers.

Using 
    "carbon-components": "^10.11.2",
    "carbon-components-angular": "^4.1.5",

## Steps to reproduce the issue

The issue happens on the angular storybook page as well as my app.

To reproduce:

1. go to: https://angular.carbondesignsystem.com/?path=/story/components-table--with-toolbar
2. select the checkbox in the table header
3. press shift-tab, in the hope of changing the focus to the previous element
4. Notice the toolbar disappears! 
5. de-select the checkbox in the table header
6. Notice the toolbar re-appears, but this time it's offset vertically such that only the bottom half can be seen.

## Additional information

Screenshots:

1.  The table before:
![image](https://user-images.githubusercontent.com/27726764/82228496-198f1780-9921-11ea-9d3e-c2a9983d8b3e.png)

2. select the checkbox:
![image](https://user-images.githubusercontent.com/27726764/82228580-31669b80-9921-11ea-92ca-4a5d4cedff6a.png)

3. press shift-tab:
![image](https://user-images.githubusercontent.com/27726764/82228611-40e5e480-9921-11ea-926c-1dfe7f5c0562.png)

4. deselect the checkbox:
![image](https://user-images.githubusercontent.com/27726764/82228736-6d016580-9921-11ea-957f-9cdc4632be0d.png)

**Comment by yinglejia** [comment]
@daveweaverweather are you still seeing the problem with latest version? This should have been fixed by https://github.com/IBM/carbon-components-angular/pull/1241.

**Comment by daveweaverweather** [comment]
@yinglejia  I've just updated to carbon-components-angular 4.4.0 and I'm still seeing the same problem.

**Comment by yinglejia** [comment]
> @yinglejia I've just updated to carbon-components-angular 4.4.0 and I'm still seeing the same problem.

Please note in the current implementation, you'll need to make sure `tabindex` of your toolbar buttons are set to `-1/0` according to the selection state. Take a look at the example code in `table.stories.ts` in https://github.com/IBM/carbon-components-angular/pull/1241.

**Comment by zvonimirfras** [comment]
@daveweaverweather is this still an issue after applying @yinglejia suggestion with tab index?

**Comment by zvonimirfras** [comment]
I've looked into it and it looks like sometimes, in addition to @yinglejia suggestion you also need to do that on every selectable item in content which might be non-trivial for some components. `ngIf`ing the toolbar content seems to have the same effect and changes in #1715 show how to do that.
