### ISSUE TITLE
Inline Loading: Add `error` state

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#1278]
## Detailed description

> Describe in detail the issue you're having.

The Carbon version of the Inline Loading has an error state which is missing from the Angular library:
https://www.carbondesignsystem.com/components/inline-loading/usage
![image](https://user-images.githubusercontent.com/1253469/82380641-cc7d7500-99f6-11ea-989f-985ded83205d.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

ibm-inline-loading

> What did you expect to happen? What happened instead? What would you like to see changed?

The Angular component would allow specifying this new error state. Ideally, there would be a `state: InlineLoadingState` to help setting the component's style. The current way with `isActive` and `success` requires to have 2 flags controlling the state and is not very intuitive. 

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

3.46.5

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Application Discovery for IBM Z

**Comment by stanislavgeorgiev** [comment]
@cal-smith @zvonimirfras I'm trying to push a PR for this issue but I'm getting errors in the `pre-push` hook. I did clone the repo in a branch new folder and ran `npm i` just before adding my code. I did try `npm i -g tslint` as well but no luck. 

```
Could not find implementations for the following rules specified in the configuration:
    use-input-property-decorator
    use-output-property-decorator
    use-host-property-decorator
    no-attribute-parameter-decorator
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
        
Warning: The 'no-use-before-declare' rule requires type information.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! carbon-components-angular@0.0.0 lint: `tslint src/**/*.ts && stylelint src/**/*.scss --config .stylelintrc.yml`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the carbon-components-angular@0.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sgeorgiev@ca.ibm.com/.npm/_logs/2020-05-19T22_46_27_468Z-debug.log
error: failed to push some refs to 'https://github.com/stanislavgeorgiev/carbon-components-angular.git'
```

**Comment by stanislavgeorgiev** [comment]
Do I need to put a PR to merge this into v4 or it would be done automatically at a certain moment?

**Comment by cal-smith** [comment]
If you can open a PR to add it to v4 that would be awesome! ... otherwise I'll add this to our backlog
