### ISSUE TITLE
Modal not displayed with Angular 9.1

### ISSUE THREAD

**Issue by bitforcesrl** [IBM/carbon-components-angular#1282]
# Detailed description
I have updated to angular 9.1 and no modal is displayed.
But when I try to open a modal the code inside ngOnInit is reached, like console.log("TEST"), and is printed in the console.
<img width="1747" alt="Schermata 2020-05-20 alle 12 50 27" src="https://user-images.githubusercontent.com/46250701/82438974-2be09100-9a9a-11ea-82a9-23a75104ead9.png">

## Step to reproduce the issue

package.json
"carbon-components": "^10.12.0",
"carbon-components-angular": "^4.2.5",

app.component.html
```html
<router-outlet></router-outlet>
<ibm-placeholder></ibm-placeholder>
```

test-modal.component.html
```javascript
export class TestModalComponent extends BaseModal implements OnInit {
  constructor(protected injector: Injector) {
    super();
  }
  ngOnInit(): void {
    console.log('TEST');
  }
  closeModal() {}
}
```

my-component.component.ts
```javascript
onDeleteCollection() {
    this.modalService.create({ component: TestModalComponent, inputs: {} });
}
```

**Comment by cal-smith** [comment]
Hey 👋 Make sure to check out the v3 to v4 upgrade guide: https://github.com/IBM/carbon-components-angular/wiki/v3-to-v4-upgrade-guide

In this case I think you'll need to add [`[open]="open"` to the `ibm-modal` in your template](https://github.com/IBM/carbon-components-angular/wiki/v3-to-v4-upgrade-guide#open-input-in-modal)
