### ISSUE TITLE
Breadcrumb Component doesn't support dynamic update of Breadcrumb Items

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#130]
## Detailed description
Change `breadcrumb.stories.ts` to the following code:
```
import { storiesOf, moduleMetadata } from "@storybook/angular";
import { withNotes } from "@storybook/addon-notes";
import { action } from "@storybook/addon-actions";
import { withKnobs, boolean, number } from "@storybook/addon-knobs/angular";

import { BreadcrumbModule, DialogModule } from "../";
import { range } from "../common/utils";

const MAXIMUM_ITEM_COUNT = 50;

storiesOf("Breadcrumb", module)
	.addDecorator(
		moduleMetadata({
			imports: [BreadcrumbModule, DialogModule]
		})
	)
	.addDecorator(withKnobs)
	.add("Basic", () => ({
		template: `
		<ibm-breadcrumb [noTrailingSlash]="noTrailingSlash" [overflowThreshold]="overflowThreshold">
			<ibm-breadcrumb-item
			  *ngFor="let index of range(itemCount)"
				href="{{href(index)}}">
				Breadcrumb {{index}}
			</ibm-breadcrumb-item>
		</ibm-breadcrumb>`,
		props: {
			noTrailingSlash: boolean("noTrailingSlash", true),
			overflowThreshold: number("overflowThreshold", 4),
			itemCount: number("itemCount", 4),
			range: (stop: number, start = 0, step = 1) => {
				console.log("range: " + stop);
				let itemCount = Number(stop);
				if (isNaN(itemCount) || itemCount < 0) {
					itemCount = 0;
				}
				if (itemCount > MAXIMUM_ITEM_COUNT) {
					itemCount = MAXIMUM_ITEM_COUNT;
				}
				return range(itemCount, start, step);
			},
			href: (index: number) => {
				const uid = ("" + Math.random()).substr(2, 6);
				const href = "#_" + index + "_" + uid;
				console.log("href: " + href);
				return href;
			}
		}
	}));

```
The breadcrumb component doesn't display the correct items with the item count knob is changed
![breadcrumb-items](https://user-images.githubusercontent.com/3009737/46099320-60655200-c1be-11e8-82aa-6e7ad79762f2.gif)

**Comment by cal-smith** [comment]
I spend some time playing with this recently, and it's definitely a tricky problem ... from what I can tell the template is only getting instantiated once per component, and when doing dynamic updates the templates don't get consumed in the right order - but only when trying to split out the overflow items from the rest ... If I just use the list directly everything works fine.

**Comment by markewallace** [comment]
@zvonimirfras I can switch to using a model to support dynamic items

**Comment by cal-smith** [comment]
@markewallace 

I managed to get this style working:

```
<ibm-breadcrumb [noTrailingSlash]="noTrailingSlash">
    <ibm-breadcrumb-item *ngFor="let item of range(breadcrumbCount)" [href]="'item' + item">
        <ng-template>Breadcrumb {{item}}</ng-template>
    </ibm-breadcrumb-item>
</ibm-breadcrumb>
```

The key was in the `ng-template` ... I've got a couple more ideas to try out but that's at least functional ...

**Comment by cal-smith** [comment]
Okay ... so I got 

```
<ibm-breadcrumb [noTrailingSlash]="noTrailingSlash">
			<ibm-breadcrumb-item *ngFor="let item of range(breadcrumbCount)" [href]="'item' + item">
				Breadcrumb {{item}}
			</ibm-breadcrumb-item>
		</ibm-breadcrumb>
```

working by swapping out all the templates and ng-content for `innerHTML` and `outerHTML` calls 😂 for this case I don't see an inherit issue with that, since it's basically the same as using a model (but a little more flexible)

**Comment by cal-smith** [comment]
And the overflow menu breaks _sometimes_ when doing that.

At this point I've sunk a good couple days into this, and it seems to be a timing issue with ng-content, ng-template, and passing values between multiple levels ... so not something we can easily fix (hopefully something that's fixed with the new Ivy renderer, but we're not there yet)

So yeah, if you want to switch to a model @markewallace I'd definitely go that way ... collectively we've spent far too much time on this, and it's not worth being stubborn over a usecase that's impossible to implement correctly.

**Comment by cal-smith** [comment]
This seems to work with the model, and as far as I can tell everyone is good with that ... closing!
