### ISSUE TITLE
modal: ExpressionChangedAfterItHasBeenCheckedError when not setting hasScrollingContent

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#1303]
## Detailed description

I'm using version 3.49.7 of carbon-components-angular, I had this issue twice that when something change on the modal that change the size of something internally (I think) and hasScrollingContent input is not setted, it throws the following error: 
`Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: false'. Current value: 'ngIf: true'.`

**Comment by zvonimirfras** [comment]
Since Doni can't reproduce it and no additional information is provided in over half a year, assuming this is resolved or not needed any more. Feel free to reopen.
