### ISSUE TITLE
 Allow to pass context to customTrigger in ibm-overflow-menu

### ISSUE THREAD

**Issue by chakSharma** [IBM/carbon-components-angular#1305]
## Detailed description
Im using Carbon-ng 4.4.  I need to change the content dynamically for customTrigger for ibm-overflow-menu based selected row in the table. There is currently no way to pass context to customTrigger for ibm-overflow-menu.

**Comment by cal-smith** [comment]
What kind of context would be useful? Since `customTrigger` is a template ref you should already have access to the component state where it's declared.

**Comment by zvonimirfras** [comment]
Seeing that this is left unanswered for over half a year and Cal's solution should be enough to solve the problem. Feel free to reopen with additional information.
