### ISSUE TITLE
Create Data Table using angular 

### ISSUE THREAD

**Issue by akshay27395** [IBM/carbon-components-angular#1307]
Hi,
I am new  in angular and I used Carbon design template for creating data table. I used code available on github.com but I got following error.

Error =>
**ERROR in src/app/table/table.component.ts:184:3 - error NG8002: Can't bind to 'sortable' since it isn't a known property of 'table'.

184     [sortable]="sortable"
        ~~~~~~~~~~~~~~~~~~~~~
src/app/table/table.component.ts:185:3 - error NG8002: Can't bind to 'noBorder' since it isn't a known property of 'table'.

185     [noBorder]="noBorder"
        ~~~~~~~~~~~~~~~~~~~~~

src/app/table/table.component.ts:214:4 - error NG8002: Can't bind to 'checkboxRowLabel' since it isn't a known property of 'tbody'.

214             [checkboxRowLabel]="getCheckboxRowLabel()"
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/table/table.component.ts:215:4 - error NG8002: Can't bind to 'enableSingleSelect' since it isn't a known property of 'tbody'.

215             [enableSingleSelect]="enableSingleSelect"
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**

**Comment by cal-smith** [comment]
Hey @akshay27395 👋 We're going to need some more detail in order to understand the issue:

- which version of `carbon-components-angular`
- which version of Angular
- what does your template look like?
- what does your component module look like? Are the imports correct?

Thanks!

**Comment by akshay27395** [comment]
Hi @cal-smith ,

Thanks for reply. I got solution to my issue. 
Faced problem because I have not import table module.

Thanks
