### ISSUE TITLE
DatePicker: Year not respecting selected theme

### ISSUE THREAD

**Issue by virkt25** [IBM/carbon-components-angular#1311]
## Detailed description

> Describe in detail the issue you're having.

- The Year value (2020) besides the month is showing as black while in a dark theme

> Is this a feature request (new component, new icon), a bug, or a general issue?

- Bug

> Is this issue related to a specific component?

- Date Picker

> What did you expect to happen? What happened instead? What would you like to see changed?

- The year should be the same color as the month

> What browser are you working in?

- Chrome

> What version of the Carbon Design System are you using?

- Latest / See Reproduction

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

- CS360 + Others.

## Steps to reproduce the issue

- https://github.com/virkt25/carbon-ng-demo
![image](https://user-images.githubusercontent.com/3311536/83923888-2e591100-a751-11ea-9ea1-3e6f451d8452.png)

**Comment by Donisius** [comment]
Closing because it seems to have been resolved in https://github.com/carbon-design-system/carbon/pull/6248
