### ISSUE TITLE
Large vendor.js file

### ISSUE THREAD

**Issue by anudeepreddy** [IBM/carbon-components-angular#1320]
I have added carbon-components-angular to my project and added the header component. I am amazed to see that the vendor.js file size shoots up to 40+MB. Can you please help me figure out the issue.

You can have a look at this screenshot

![Screenshot (124)](https://user-images.githubusercontent.com/6022231/84148572-d5ed8080-aa7c-11ea-938d-934d0e67808e.png)

**Comment by AmgadHassanNabil** [comment]
Hi anudeepreddy, I  faced this issue also but when i built the app with prod parameter. The vendor.js ent as low as 1mb

**Comment by darlanalves** [comment]
+1 here.
I created [this reproduction repo](https://github.com/darlanalves/carbon-components-slow-tests) with just one component from Carbon

@anudeepreddy as mentioned above, if you build with --prod it will reduce back to ~1mb.

BUT that is not the case for tests. There's no --prod setup for karma, so is even worse. The vendor.js file will have over 100Mb and kill any hopes for productivity.

## App without Carbon Angular
<img width="1138" alt="Screenshot 2020-06-16 at 12 28 26" src="https://user-images.githubusercontent.com/745095/84771087-15662080-afd9-11ea-8697-cc969ecd7113.png">

## Same app with Carbon Angular
<img width="1459" alt="Screenshot 2020-06-16 at 12 53 18" src="https://user-images.githubusercontent.com/745095/84771124-257e0000-afd9-11ea-8e1d-bfdbda641822.png">

**Comment by darlanalves** [comment]
One interesting thing: Carbon with Angular 8 generates ~ 50MB of vendor.js code.
Same app with Angular 9 bumped to over 100Mb.

## Angular 8 + Carbon Angular:

<img width="1137" alt="Screenshot 2020-06-16 at 12 34 37" src="https://user-images.githubusercontent.com/745095/84771291-70981300-afd9-11ea-9245-83ef439f9e8a.png">

**Comment by FrancescoBorzi** [comment]
@cal-smith can you please have a look at this? this is currently blocking us as it makes all our builds fail in our unit tests:

> as mentioned above, if you build with --prod it will reduce back to ~1mb.
>BUT that is not the case for tests. There's no --prod setup for karma, so is even worse. The vendor.js file will have over 100Mb and kill any hopes for productivity.

so our unit tests are timing out because of this issue :(

**Comment by cal-smith** [comment]
Hey 👋 Sorry, I was out on vacation last week! This is definitely on my radar, and I've been working on splitting out the component entry points ... I hope to have a PR up for that work soon!

Thanks for all the detail! It's super helpful 💯

**Comment by Aracturat** [comment]
@cal-smith I updated carbon-components-angular to the latest version, but the problem is still here. I ran webpack-bundle-analyzer, it look like problem in @carbon/icons-angular package. 
![image](https://user-images.githubusercontent.com/1833101/89733560-6d248380-da80-11ea-8592-9ce9adafaf58.png)

**Comment by cal-smith** [comment]
We're a little stuck at the moment given that we have to support Angular 9, which means that the components have to deal with 9s sub-optimal `ngcc` process, which means we can't fully switch to per-icon packages _yet_. With Angular 10 I _think_ the program based finder should be smarter with what it compiles, which should let us make better use of the per-icon packages in `@carbon/icons-angular@11.1.4`.

If you can use the per-component imports in the latest version of v4 it should help a bit, but the ultimate solution will be once we can totally switch everything over to per-icon imports.

**Comment by lepidotteri** [comment]
> 
> 
> We're a little stuck at the moment given that we have to support Angular 9, which means that the components have to deal with 9s sub-optimal `ngcc` process, which means we can't fully switch to per-icon packages _yet_. With Angular 10 I _think_ the program based finder should be smarter with what it compiles, which should let us make better use of the per-icon packages in `@carbon/icons-angular@11.1.4`.
> 
> If you can use the per-component imports in the latest version of v4 it should help a bit, but the ultimate solution will be once we can totally switch everything over to per-icon imports.


Angular ^10 here, this makes the library completely useless, the problem is still there; with or without the Carbon Charts, vendor.js bundle is consistently over 50MB:

![immagine](https://user-images.githubusercontent.com/45174270/107266808-528a9180-6a46-11eb-96f2-71dd5ceea0bf.png)
