### ISSUE TITLE
Nested Accordian does not expand/collapse

### ISSUE THREAD

**Issue by chakSharma** [IBM/carbon-components-angular#1354]
## Detailed description
When Accordion is nested inside another Accordion , the expand/collapse behavior of the nested Accordion does not work properly (i.e. unable to expand and collapse nested Accordion by clicking on it's header)

Understood from @Donisius that nesting Accordion inside and Accordion is not currently supported but since there is no Tree component till now, need ability to nest Accordion inside an Accordion to implement tree structure.

Carbon-ng version: 4.4

**Comment by cal-smith** [comment]
This is something you'll want to bring up with your design team with Carbon. It's fundamentally unsupported from a styling perspective (child accordions inherit parent accordions open style).

Unfortunately this is something you'll need to build out yourself if you require it immediately.
