### ISSUE TITLE
Tabs switch to a dropdown at set width, 

### ISSUE THREAD

**Issue by pickle-weasle** [IBM/carbon-components-angular#1361]
Hi There, I was asked to make a ticket by @Donisius on the carbon angular channel after coming across this.

## Detailed description

> Describe in detail the issue you're having.

When using the tabs, when you resize the window by reducing its width, at a certain point, the tabs will turn into a dropdown. The point at which this happens is not clear and can cause issues if you've too many tabs. In fact the issue is observable on the angular carbon storybook tabs page:
https://angular.carbondesignsystem.com/?path=/story/components-tabs--basic
if you reduce the width of the window, the fourth tab will disappear from view before it changes to a dropdown.
> Is this a feature request (new component, new icon), a bug, or a general issue?

general issue/ bug?
> Is this issue related to a specific component?

yes, tabs
> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the point at which the tabs turned to dropdowns to be relative to the total width of the tabs, as soon as one of the tabs starts going out of view, change it to a dropdown.
According to @Donisius "ibm-tab switches from tabs to dropdown through the carbon styles, looking through, it looks like at 42rem it switches over. It looks like it also happens in the vue and react implementations as well."

## Steps to reproduce the issue

1. Navigate to https://angular.carbondesignsystem.com/?path=/story/components-tabs--basic
2. Resize the window, reducing the width, you will see the fourth tab disappear before the tabs change to a dropdown

## Additional information

* Screenshots
![image](https://user-images.githubusercontent.com/13419930/85393404-d8ec7480-b544-11ea-8997-4dcf3287e5e6.png)

![image](https://user-images.githubusercontent.com/13419930/85393423-e0138280-b544-11ea-80f9-8b193bae7b1a.png)

**Comment by cal-smith** [comment]
This is by design. This is controlled by a media query, you may be able to override it by checking the tabs scss and changing when it switches styles. 

Alternatively open an issue on the Carbon repo, since this is entirely a styling issue - we don't control when the tabs switch to the dropdown form at all.

**Comment by pickle-weasle** [comment]
Hi @cal-smith I was going to open an issue on the Carbon repo as this seems like something that would make sense, all tabs being accessible at different (reasonable) screen widths. 
When I was searching through for previous tickets I came across this one:
   https://github.com/carbon-design-system/carbon/issues/6917
it shows scrolling arrows when some of the tabs are not in view. This is something that you can see when you reduce the window width on the React Storybooks:
   https://react.carbondesignsystem.com/?path=/story/tabs--default
Do you know are there plans to also have these arrows in the Angular version?
Should i open an enhancement request in this repo for it?

**Comment by cal-smith** [comment]
> Should i open an enhancement request in this repo for it?
Sure! I'm not sure when I'll get around to it, otherwise it would make a good contribution 👍 We'll want to support both tab forms, so the scrollable tabs should be opt-in via a `scrollable` input

**Comment by pickle-weasle** [comment]
Hey there, this seems to resolve the issue, however I get the following warning :
npm WARN carbon-components-angular@4.20.0 requires a peer of @carbon/icons-angular@^11.0.0 but none is installed. You must install peer dependencies yourself
Things are failing in the pipeline, seems to not be building along the way at some point and I'm trying to find RC.
Currently have:
 "carbon-components": "~10.21.0",
    "carbon-components-angular": "^4.20.0",
    "@carbon/icons-angular": "12.0.0",`

Should i have an older carbon-components-angular build for icons12?

**Comment by cal-smith** [comment]
Please open a new issue for that.
