### ISSUE TITLE
Uncaught exception when using OverflowMenu

### ISSUE THREAD

**Issue by dsuwirya** [IBM/carbon-components-angular#137]
I'm getting this uncaught exception when trying to use the OverflowMenu from dialog.module. I'm on Angular 5.x and carbon-components-angular 1.8.1.

![image](https://user-images.githubusercontent.com/5710527/46253243-22756180-c43c-11e8-86e5-2139b888e21e.png)

![image](https://user-images.githubusercontent.com/5710527/46253256-4d5fb580-c43c-11e8-91d1-a34ada3f7dae.png)

and after commenting out temporarily that particular line, it's still complaining about the 'options':

![image](https://user-images.githubusercontent.com/5710527/46258547-57ac9e80-c492-11e8-8ed9-a947ec4f3c21.png)

when used as per documentation:

![image](https://user-images.githubusercontent.com/5710527/46258556-7c087b00-c492-11e8-9287-32f8e9755fbc.png)

**Comment by zvonimirfras** [comment]
Documentation needs an update...

Storybook gives a usage example:

```html
<ibm-overflow-menu>
	<ibm-overflow-menu-option>Option 1</ibm-overflow-menu-option>
	<ibm-overflow-menu-option>Option 2</ibm-overflow-menu-option>
</ibm-overflow-menu>
```

**Comment by dsuwirya** [comment]
First exception as shown above is still there. In addition, after I commented out that line (temporarily), now I'm getting this exception:
![image](https://user-images.githubusercontent.com/5710527/46424995-3ea92500-c700-11e8-8724-025f98d86036.png)

After commenting out this line, it got rendered ( i.e. the three vertical dots ).

**Comment by cal-smith** [comment]
We require a peer of rxjs@6 ... `fromEvent` and friends don't exist in rxjs@5.X.X.

An update should fix this, let us know if it doesn't :+1:

**Comment by cal-smith** [comment]
Also we require a peer of angular@6 ... I suggest you check your dependencies against our peerDependancies and update accordingly

**Comment by dsuwirya** [comment]
In the context of an established product, unfortunately upgrading to angular-6, or even just to rxjs-6 is not as simple and may not be even possible as there're just too many implications. Is there anyway to make this library to be backward compatible with angular-5, rxjs-5? It's just a pity, if because of few items like this we end up can't use / adopt this library. Thanks!

**Comment by zvonimirfras** [comment]
That's, unfortunately, not something we can dedicate resources to, right now. Those implications go both ways.

You could look into somehow polyfilling missing parts, like fromEvent.

**Comment by dsuwirya** [comment]
for reference, this is now possible by using: "rxjs": "~5.6.0-forward-compat.5",
