### ISSUE TITLE
Accordion item doesn't expand on `expanded="true"`

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#139]
## Detailed description

> Describe in detail the issue you're having.

I'm setting the `<accordion-item expanded="true">` directly in my component template and the item doesn't expand. I can see the `aria-expanded` is changing to `true` but the `bx--accordion__item--active` class doesn't get added to the item. Then when I click on the item, nothing happens, I have to click a second time before the item expands.

**Comment by zvonimirfras** [comment]
From what I can see it's the `arria-expanded` on the button inside the item that needs to be set.

**Comment by zvonimirfras** [comment]
Looks like `bx--accordion__item--active` doesn't get set on the host.

It's because `@HostBinding("class") itemClass = "bx--accordion__item";` overrides the class.
That needs to be `@HostBinding("class.bx--accordion__item") itemClass = true;` Line 38 in `accordion-item.component.ts`

**Comment by stanislavgeorgiev** [comment]
Yeap, exactly.

**Comment by stanislavgeorgiev** [comment]
Oups, I'm just seeing that @youda97 is already assigned to fix that defect. Heads up, there's a pull request with the fix!
