### ISSUE TITLE
overflow-menu: overflow menu does not close when openning modal from it

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#1413]
## Detailed description

We are using versions: carbon-components: 10.10.3 and carbon-components-angular: 3.49.7
If we open a modal from an option on the overflow menu, it remains open. I'll try to make a recreation of this issue on stackblitz.

**Comment by zvonimirfras** [comment]
Is this still an issue? Were you able to make a minimal recreation of it?

**Comment by zvonimirfras** [comment]
No longer an issue.
