### ISSUE TITLE
ComboBox: If the user search for the wrong string it shows the error but, but dropdown remains open, it should be closed.

### ISSUE THREAD

**Issue by amirkhan064** [IBM/carbon-components-angular#1428]
## ComboBox: If the user searches for the wrong string it shows the error but, but dropdown remains open, it should be closed. Because to see the message user has to click outside to close it.

> Because the error message is hidden. user needs to click outside to see the message, better we close the dropdown in case of error or wrong search string.

![image](https://user-images.githubusercontent.com/20635981/88619616-9d9c1300-d0b9-11ea-9e54-30e4e095a2c6.png)

**Comment by Donisius** [comment]
It seems to behave this way on the react side https://react.carbondesignsystem.com/?path=/story/multiselect--filterable, since we follow their specs and you need a change in behaviour I would open an issue on https://github.com/carbon-design-system/carbon/issues/new/choose

**Comment by Donisius** [comment]
It remains open in https://react.carbondesignsystem.com/?path=/story/combobox--default with the error message, if it's a wrong search string and it closes it becomes a filterable dropdown and it's no longer a combobox. I would open an issue on https://github.com/carbon-design-system/carbon/issues/new/choose about the position of the error message when the combobox is open

**Comment by ninja511** [comment]
closing - pls reopen if needed.
