### ISSUE TITLE
[combobox]: displayValue for combobox

### ISSUE THREAD

**Issue by vitaliyzolotoy** [IBM/carbon-components-angular#1429]
It would be useful is combobox component will have such option [displayValue] as dropdown has

**Comment by Donisius** [comment]
@vitaliyzolotoy  you should be able to just use the `listTpl` input on the `ibm-dropdown-list` and have custom list items that way. Not sure if we can use display value on the combobox since combobox uses an input

**Comment by zvonimirfras** [comment]
Looks like Doni's suggestion should do the trick and seems like the correct solution. Feel free to reopen with more information if that's not the case.
