### ISSUE TITLE
ComboBox - while typing in search-box it's also clearing the complete input sometime.

### ISSUE THREAD

**Issue by amirkhan064** [IBM/carbon-components-angular#1435]
## Detailed description

> I am having an issue with carbon Combobox, As you can see in the attached video. If I am adding any text after the selected text it's clearing the field after adding some text and call the selected method automatically.

> General issue

>ComboBox 

> It shouldn't clear the input while the user is typing and also should not trigger the select method. The user is just typing doesn't;t make any sense to trigger select method here.

> I am using :
"carbon-components": "10.10.3",
"carbon-components-angular": "3.53.5",

[combobox-issue.mov.zip](https://github.com/IBM/carbon-components-angular/files/5013936/combobox-issue.mov.zip)

**Comment by Donisius** [comment]
Hello, the version of carbon-components presented on https://angular.carbondesignsystem.com/?path=/story/components-combobox--with-ngmodel isn't the latest. This doesn't seem to be happening on the latest of both version 3 and 4

**Comment by zvonimirfras** [comment]
Per Doni's comment, seems to be fixed in latest. Feel free to reopen with additional info if needed.
