### ISSUE TITLE
Table expanded data with columns

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#1441]
## Detailed description

This is a feature request because I have a design that needs to have the expanded data separated with columns to be setted respecting the table headers, with the next screenshot it will be more understandable.
Currently if you set the expanded data with the template way, it sets the template to a td with colspan 2 I think, so it is limited to that td.

<img width="1135" alt="Screen Shot 2020-08-06 at 10 13 38 AM" src="https://user-images.githubusercontent.com/10190000/89549115-85b94300-d7cd-11ea-9b0b-0b9c7eb1a53a.png">

**Comment by tacho090** [comment]
@Pablodotnet how do you expect your table to look after the feature request is submitted? Could you upload a mock or example image of how you visualize it please?

**Comment by Pablodotnet** [comment]
@tacho090 you can see it on the screenshot posted over there...

**Comment by Pablodotnet** [comment]
Any update on this @cal-smith ? 👍

**Comment by cal-smith** [comment]
Nothing specific ... The best way to handle this seems to be allowing nested table models, or at the very least nested rows ... We don't really have a `TableRow` type so that does make this a bit more complicated

**Comment by zvonimirfras** [comment]
@Pablodotnet Have you tried adding `tr`s and `td`s with the correct data (and classes(?)) in your expanded template?

**Comment by cal-smith** [comment]
I _think_ the issue here is that we already have a `td` and adding `tr`/`td`s within that causes issues. Ideally I would think that we would support nested rows on the model level and just render it appropriately.
