### ISSUE TITLE
Tooltip and Dialog directive missing alignment property 

### ISSUE THREAD

**Issue by Pranav143** [IBM/carbon-components-angular#1458]
## Detailed description

When implementing a tooltip using carbon-components-angular, there isn't an alignment property to align the tooltip towards the 'start' 'centre' or 'end'. This means that if a tooltip in a default bottom/top/right/left position overflows past a boundary, it gets cut off. And there is no align option implemented in the tooltip directive or dialog directive to handle this.

This issue is related to tooltips within carbon-components-angular.

This is an enhancement issue.

carbon-components-angular: 3.53.7

 ```
<ng-template #tooltipHeaderTpl>
  <span>
    {{ data element to put tooltip on }}
    <span
      trigger="click"
      placement="bottom"
      [ibmTooltip]="tooltipTpl"
      // align = "start"  --This feature is missing
    >
    </span>
  </span>
  <ng-template #tooltipTpl>
    <p>Some text for the tooltip</p>
  </ng-template>
</ng-template>
```

Notice in the screenshot below, placing the tooltip at the bottom of the data table cell results in it overflowing and getting cut off.

<img width="328" alt="Screen Shot 2020-08-06 at 11 48 52 AM" src="https://user-images.githubusercontent.com/51279514/90036346-c4d90f80-dc77-11ea-80f8-2deab2f82894.png">

Ideally, the tooltip component should accept a default prop to align its tooltip to the start / centre / or end of the tooltip label. And, the caret should always point to the centre of the tooltip label. To achieve something such as below:

<img width="440" alt="Screen Shot 2020-08-06 at 11 56 28 AM" src="https://user-images.githubusercontent.com/51279514/90036895-63fe0700-dc78-11ea-867f-3afbcd29d923.png">

**Comment by Donisius** [comment]
As per our discussion on slack, the carbon design system does not support tooltip alignment for complex tooltips so we cannot apply this feature on the directive. You can use alignment on the tooltip definition or the tooltip icon components.
