### ISSUE TITLE
[AAT] - Multiple navigation landmarks must have unique labels specified with aria-label or aria-labelledby

### ISSUE THREAD

**Issue by UjjwalUpadhyay123-bit** [IBM/carbon-components-angular#1462]
## Detailed description
Need to add aria-label or aria-labelledby to nav element of ibm-tab component. This is because the Accessibility testing tool is throwing the issue.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
ibm-tabs

> What did you expect to happen? What happened instead? What would you like to see changed?
Expected to see no accessibility issue. Got the above AAT issue.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using? 10.11.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Go to  https://ecamstage14.multicloud-ibm.com/lite/insights/ridashboard
2. Use DAP to scan
Expected: Multiple navigation landmarks must have unique labels specified with aria-label or aria-labelledby

## Additional information

* Screenshots or code
![AAT - nav issue](https://user-images.githubusercontent.com/11502476/90647941-8a163f00-e256-11ea-853b-c15e26c21f24.png)

* Notes

**Comment by cal-smith** [comment]
Use either the [`ariaLabel`](https://angular.carbondesignsystem.com/documentation/components/Tabs.html#ariaLabel) or [`ariaLabelledBy`](https://angular.carbondesignsystem.com/documentation/components/Tabs.html#ariaLabelledby) Inputs

**Comment by UjjwalUpadhyay123-bit** [comment]
@cal-smith - The ariaLabel and ariaLabelledBy tags are not working for ibm-tab. Please check into this.
