### ISSUE TITLE
Radio button not updated when using reactive forms

### ISSUE THREAD

**Issue by huineng** [IBM/carbon-components-angular#1464]
"carbon-components-angular": "^4.12.1",

When creating a form with reactive forms the radio button does not get checked when loading that form

The write function of the ControlValueAccessor works as designed but there's no action to refresh the component to reflect this state

the solution is to update the write function with a refresh of the radios

https://github.com/IBM/carbon-components-angular/blob/a593b9b17e9d525989d746fc6fb087009c8a8b15/src/radio/radio-group.component.ts#L254

changing to 

```
RadioGroup.prototype.writeValue = function (value) {
        this.value = value;
        var _this = this;
        setTimeout(function () {
            _this.updateSelectedRadioFromValue();
            _this.checkSelectedRadio();
        });
    };
```

let me know if i need to make a pull request for this 

thanks

**Comment by huineng** [comment]
Radio button needs to be implemented like checkbox was implemented https://github.com/IBM/carbon-components-angular/blob/master/src/checkbox/checkbox.component.ts  with proper changeDetection: ChangeDetectionStrategy.OnPush

Today i cannot use the radio module because lack of this refresh strategy

i wanted to help you by making a pull request but i cannot and the clone cannot be installed. thanks

**Comment by cal-smith** [comment]
I responded to your other issue with the installation issues, so hopefully we can get that sorted! Otherwise, thanks for opening the issue 👍

**Comment by huineng** [comment]
Can this be prioritised? Today radio module cannot be used in reactive forms , and as i'm migrating from another angular form library i have to stick their radio buttons  until gets solved.

thanks

**Comment by cal-smith** [comment]
Sure, I'll take a look at this
