### ISSUE TITLE
[AAT] - Multiple navigation landmarks must have unique labels specified with aria-label or aria-labelledby

### ISSUE THREAD

**Issue by UjjwalUpadhyay123-bit** [IBM/carbon-components-angular#1468]
Need to add aria-label or aria-labelledby to nav element of ibm-tab component. This is because the Accessibility testing tool is throwing the issue.

Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

Is this issue related to a specific component?
ibm-tabs

What did you expect to happen? What happened instead? What would you like to see changed?
Expected to see no accessibility issue. Got the above AAT issue.

What browser are you working in?
Chrome

What version of the Carbon Design System are you using? 10.11.1

Steps to reproduce the issue
Go to ibm-tab component
Use DAP to scan
Expected: Multiple navigation landmarks must have unique labels specified with aria-label or aria-labelledby

Additional information

![SS-AAT](https://user-images.githubusercontent.com/11502476/91007086-b59f7d80-e5f8-11ea-8a62-1bb259ecf4af.png)

**Comment by UjjwalUpadhyay123-bit** [comment]
@cal-smith - Please look into this on priority.

**Comment by Donisius** [comment]
@UjjwalUpadhyay123-bit This only seems to come up if there are multiple tabs on the page and you don't set an `ariaLabel` on the `ibm-tabs`. Which DAP rule set are you using?

**Comment by cal-smith** [comment]
To cover all the bases @Donisius, is that true for the `ibm-tabs` and `ibm-tab-header-group`?

**Comment by Donisius** [comment]
@cal-smith The only way that issue came up on both `ibm-tabs` and `ibm-tab-header-group` is when there were more than one of them on a page but setting a unique `ariaLabel` prevented the issue from coming up 👍

**Comment by cal-smith** [comment]
Ah, so I guess our unique ID generator isn't working quite correctly then - they should have unique IDs by default

**Comment by cal-smith** [comment]
So there's no issue here then, since we don't supply a default aria label, because we can't know what label would make sense contextually. I'm going to close this then.
