### ISSUE TITLE
Package cannot be installed

### ISSUE THREAD

**Issue by huineng** [IBM/carbon-components-angular#1469]
I tried to install a clone of this but it failed. I guess some of your packages are too old

```
> node-sass@4.12.0 install /Users/Documents/workspace/lab/carbon-components-angular/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-83_binding.node":

HTTP error 404 Not Found
```

it doesn't exist  https://github.com/sass/node-sass/releases

**Comment by cal-smith** [comment]
We don't depend on `node-sass` 🙂 `v4.12.0` definitely exists on the releases page - https://github.com/sass/node-sass/releases/tag/v4.12.0, and locally everything install fine for me ... The binary downloaded is system dependent, so we need some more information:

- which version of node are you using? (I recommend 12)
- which version of MacOS are you using?

And of course, make sure you're using an up to date version of `npm` to install dependencies - we don't use `yarn` for our development.

**Comment by huineng** [comment]
node-sass 4.12.0 exists indeed, it's just the binary "darwin-x64-83_binding.node"  that is not there for this version of node_sass for the mac i'm using, there are a couple of git tickets around this

i  don't want to investigate too much into this  issue.. i'm converting my existing angular site to carbon and i'm using 
angular 10.x , typescript 3.9.7 on node 14.8.. it all works nice.

I just wanted to see if i could do any contribution if needed. So far it all works fine except the toggle typescript warning i'm getting and the onpush i'm missing for the radio..But i'm sure we'll get there

**Comment by cal-smith** [comment]
Okay, all else being equal I'm going to close this issue then 👍 Totally happy to reopen and work through this to get it functional for your setup.
