### ISSUE TITLE
Carbon Table Custom Column Renders as [object, Object] until paging 

### ISSUE THREAD

**Issue by kristinreddington** [IBM/carbon-components-angular#1470]
Custom columns made with a TemplateRef and rendered with an <ng-template> tag renders the entire data object passed to the custom column as [object, Object] until I page to a different page in the table. This happens only on the initial load, so if I refresh the page after paginating, it will render back to [object, Object].  

 The data I pass is an interface object of the data I need for each row in my carbon table. I pass the whole object, which contains all the data I need for different actions available in the table, and use a Template Reference and ng-template in order to render the specific data I need for that column. Please see below. 

// TS file 

getModelData(pmTable: NominatorTable[]) {
    const pageData: TableItem[][] = []; // reset
    for (let i = 0; i < pmTable.length; i++) {
      pageData.push(
        [**new TableItem({ data: pmTable[i], template: this.customItemTemplate})**,
        new TableItem({ data: pmTable[i].university }),
        new TableItem({ data: pmTable[i].facultyLastName  }),
        new TableItem({ data: pmTable[i].facultyFirstName }),
        new TableItem({ data: pmTable[i].facultyEmail }),
        new TableItem({ data: pmTable[i].status }),
        new TableItem({ data: pmTable[i], template: this.customTableItemTemplate }),
        new TableItem({ data: this.asLocalDateString(pmTable[i].submittedDate) }),
      ]
      );
    }
    return pageData;
  }

// HTML file
<ng-template #customItemTemplate let-data="data">
          {{**data.internalNominationId**}
 </ng-template>

[ezyzip.zip](https://github.com/IBM/carbon-components-angular/files/5118675/ezyzip.zip)

**Comment by yinglejia** [comment]
You may need to add `{ static: true }` like `@ViewChild('customItemTemplate', { static: true }) customItemTemplate: TemplateRef<any>`.

**Comment by LeonardoTeruel** [comment]
I am facing a similar problem, and if I try to add the `{static: true}` I see the message: 

Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.ts(2345)

Issue still persists.

**Comment by zvonimirfras** [comment]
@LeonardoTeruel this would happen if you're on angular <=7 and in some cases after the upgrade you might need to remove all node_modules and run a clean `npm install`.
Does that help?

**Comment by zvonimirfras** [comment]
@yinglejia solution should work for most and my previous comment should start from clean slate if that wasn't enough.

If you tried those two and still get the error, feel free to reopen with additional info.
