### ISSUE TITLE
Removing tag filter causes dialog to close unexpectedly

### ISSUE THREAD

**Issue by oetlinge** [IBM/carbon-components-angular#1485]
## Detailed description

> Describe in detail the issue you're having.

I've extended the dialog component and dialog directive to create a custom dialog that includes tag filters and a number of checkboxes for toggling those tag filters. When I check/uncheck a checkbox, a tag filter is added to / removed from the array of tags in the dialog. I also have a function that responds to the `close` output of the tag filter by removing that tag from the array. Removing tags by clicking the clear/delete button on the tag filter causes the dialog to close, whereas removing tags via the checkboxes does not.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

tag filter and possibly dialog

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the dialog to remain open instead of closing. Removing tags from the array should not trigger dialog closing.

> What browser are you working in?

N/A

> What version of the Carbon Design System are you using?

3.54.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Sterling UIHub. Need this resolved before end of September 2020.

## Steps to reproduce the issue

[Codesandbox](https://codesandbox.io/s/carbon-components-angular-forked-sri29)

1. Add dialog directive to a button or other element.
2. Add tag filters to the dialog's template via ngFor and provide an array as input.
3. Define a function to listen to the `close` output of the tag filter and remove the tag in response.
4. Click on the button to open the dialog.
5. Click the x on one of the tag filters.

**Comment by oetlinge** [comment]
Any estimate on when this will be available in v4? We upgraded to 4.12.3 recently.

**Comment by tacho090** [comment]
Is this issue still open even though it has already been solved in version 3.54.1?

**Comment by oetlinge** [comment]
It's been fixed in 3.54.1, but is still broken in v4.
