### ISSUE TITLE
Property 'change' in type 'Toggle' is not assignable to the same property in base type 'Checkbox'

### ISSUE THREAD

**Issue by iliyaeffati** [IBM/carbon-components-angular#1489]
When `strictFunctionTypes` is true I get the following error

<img width="1414" alt="Screenshot 2020-09-03 at 12 38 54" src="https://user-images.githubusercontent.com/7510949/92105045-83550380-ede2-11ea-88bc-af25306bf9d7.png">

Versions:
"carbon-components-angular": "4.14.0",
"@angular/cli": "10.1.0",
"@angular/compiler-cli": "10.1.0",
 "typescript": "3.9.5"

**Comment by huineng** [comment]
https://github.com/IBM/carbon-components-angular/issues/1343

**Comment by zvonimirfras** [comment]
This looks like a dup of #1343 which is closed in #1647 so this should be closed as well. Feel free to reopen with more info if needed.
