### ISSUE TITLE
Data table: Fail to focus on the Search button through keyboard TAB button 

### ISSUE THREAD

**Issue by Bsujeet** [IBM/carbon-components-angular#1493]
## Detailed description

>Describe in detail the issue you're having.

When using IBM datatable component cannot open table search using keyboard.
Failed to use tab key to focus on the  Search icon.
This is Accessibility testing issue 

> Is this a feature request (new component, new icon), a bug, or a general issue?

BUG

> Is this issue related to a specific component?

ibm-table-toolbar-search 

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected The search icon should be operated using a keyboard but instead cannot focus on search icon in <ibm-table-toolbar-search> in datatable component 

> What version of the Carbon Design System are you using?

"carbon-components-angular": "3.49.7"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

I am working in MCMP. This is expected to be fixed by OCTOBER.

## What browser are you working in?
Chrome

## Tools 
JAWS2019

## Steps to reproduce the issue

1. https://angular.carbondesignsystem.com/?path=/story/components-table--with-toolbar
2. Use TAB button to navigate to search icon.

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/25789698/92225736-4744a000-eec1-11ea-8b8e-3a29dd2490e2.png)

**Comment by tacho090** [comment]
Does #1528 solve this issue?

**Comment by Donisius** [comment]
@tacho090 Sorry for the delayed response, #1528 did close this and it doesn't seem to be a problem in version 4, so I'll close this but feel free to reopen if there are any issues.
