### ISSUE TITLE
Accessibility issues 

### ISSUE THREAD

**Issue by maheshkanchetti** [IBM/carbon-components-angular#1498]
Fixed the accessibility issues across the following components 
1. Toggle Component
2. Sidenav Component
3. Header action Component
4. Tab header group component

Toggle Component
 Added aria-label and name input properties for the toggle component	

Sidenav Component
Updated the role for list item as “ListRole” instead of “none”, Added Aria-label to nav

Header Action Component
Removed Aira-label as its not required.
Tab header group component
Added condition to prevent empty anchor tag

https://github.com/IBM/carbon-components-angular/pull/1495

**Comment by maheshkanchetti** [comment]
#1495

**Comment by zvonimirfras** [comment]
Looks like this issue lists things that are fixed in the linked PR. Feel free to reopen if still needed.
