### ISSUE TITLE
Allow restricting accordion items to only one expanded at a time

### ISSUE THREAD

**Issue by oetlinge** [IBM/carbon-components-angular#1503]
## Detailed description

> Describe in detail the issue you're having.

Would like to prevent having multiple accordion items within the same accordion expanded, so that only one can be expanded at a time.

> Is this a feature request (new component, new icon), a bug, or a general issue?

feature

> Is this issue related to a specific component?

accordion/accordion item

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected a configurable property to restrict how many accordion items can be expanded simultaneously, but none currently exists.

> What version of the Carbon Design System are you using?

3.54.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Sterling UIHub. Required for September 2020 deliverables.

**Comment by cal-smith** [comment]
Totally my bad on missing this ... we already support `expanded` as an `@Input` - https://angular.carbondesignsystem.com/3.49.7/documentation/components/AccordionItem.html#expanded You should be able to use that to control which accordion is open!

**Comment by zvonimirfras** [comment]
Looks like already doable with what Cal said. Feel free to reopen with more information if necessary.
