### ISSUE TITLE
DatePicker does not work with reactive forms (fix included)

### ISSUE THREAD

**Issue by huineng** [IBM/carbon-components-angular#1504]
v 4.15.0

Date Picker does not work with reactive forms 
This is because 

```
if (this.isFlatpickrLoaded() && this.flatpickrInstance.config) {
```

are both null at time of writevalue, so the value can never be set

https://github.com/IBM/carbon-components-angular/blob/master/src/datepicker/datepicker.component.ts#L313

Now the good news is that this is easy to fix just wrap it in a setTimeout like this (this allows the view to be completely initialized

```
writeValue(value: (Date | string)[]) {
    this.value = value;
	setTimeout(() => {
            if (this.isFlatpickrLoaded() && this.flatpickrInstance.config) {
                this.setDateValues(this.value);
            }
        }, 1)
  }
```

Thanks for having this fixed

**Comment by huineng** [comment]
the 1 is not needed

```
	writeValue(value: (Date | string)[]) {
		this.value = value;

		setTimeout(() => {
			if (this.isFlatpickrLoaded() && this.flatpickrInstance.config) {
				this.setDateValues(this.value);
			}
		});
	}
```

**Comment by cal-smith** [comment]
Thanks for hunting down the fix! I should have a PR up shortly 👍
