### ISSUE TITLE
Drop down does not work with reactive forms (needs changedetector or onpush)

### ISSUE THREAD

**Issue by huineng** [IBM/carbon-components-angular#1518]
v 4.15.0

I'm using reactive forms and when initialising my form the writevalue is written correctly

Nevertheless, "Every subsequent update" of the reactive form does not refresh the value on screen
That is i debugged until propagateSelected and values are assigned correctly but the view is not refreshed

This is because i use reactive forms with onpush strategy so i propose that there's some change mechanism in place in drop down that refreshes the view like change detector markForCheck()

from a user experience

user selects a value from a dropdown 
![image](https://user-images.githubusercontent.com/3482445/92936642-545d1400-f418-11ea-8b5e-92556664c294.png)

user hits reset ..nothing changes **( i''m using angular this.form.reset({})**

user just touches any of the other controls and the form is reset

![image](https://user-images.githubusercontent.com/3482445/92936765-82425880-f418-11ea-822e-12029ed3250e.png)

thanks

**Comment by huineng** [comment]
just for info #1536 does not solved the above, the above is related to this.form.reset({}

**Comment by Donisius** [comment]
I made a simple code sandbox with a dropdown within a reactive form using the onpush strategy, I can't seem to break it but I must be missing something @huineng, if you want to take a quick look https://codesandbox.io/s/dropdown-reactive-forms-1bq7e?file=/src/app/app.component.html

**Comment by cal-smith** [comment]
I too am having issues reproducing this issue. I'm using Angular 11 and the latest version of carbon-components-angular. A minimal ng cli app that exhibits the issue would help with debugging.

**Comment by huineng** [comment]
yes, after installing latest version it works 

thanks
