### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#1519]
## Detailed description

> Describe in detail the issue you're having.

Provide Angular 10 support

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

4.11.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM AD

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by cal-smith** [comment]
Definitly long overdue ... I don't think there's any specific fires I need to put out this week, so I'll take some time to work on this.

**Comment by stanislavgeorgiev** [comment]
Thanks Cal! :-)

**Comment by yinglejia** [comment]
@cal-smith we are working on a new Angular project, so it will be great to see Angular 10 support soon!
