### ISSUE TITLE
Combobox opening under modal

### ISSUE THREAD

**Issue by huineng** [IBM/carbon-components-angular#1530]
It's getting quite messy , spent whole day and still not working

I have tried to implement the combobox with 2 alternatives .. 

1. using the itemValueKey.. but here i hit the problem as you also have on your demo webpage
https://angular.carbondesignsystem.com/?path=/story/components-combobox--with-reactive-forms

![image](https://user-images.githubusercontent.com/3482445/93539091-c6a08d80-f91d-11ea-94b6-d4eb549c8d49.png)

now clear that item or select any other value 
in case you clear that item, whatever you select is not shown on screen

![image](https://user-images.githubusercontent.com/3482445/93539154-eb950080-f91d-11ea-9846-8bb74f0f72ca.png)

or if you don't clear, the value always stays the same 
![image](https://user-images.githubusercontent.com/3482445/93539186-0798a200-f91e-11ea-94b7-da8cfcaa9742.png)

see the "selected"

Please help me out urgently , i'm promoting this library but with every update , i think new problems are created

2. without itemValueKey

i'm not even sure where to start, maybe related with your upgrade to angular 10 (which i was using when you were not yet on ng10 ) and your previous version WAS working , so it might be your upgrade to angular 10

So i had to change to using "temValueKey" that at least didn't give me any error ( just the bug above)

this is the bug i got

```
  "TypeError: Cannot assign to read only property 'selected' of object '[object Object]'",
     "    at DropdownList.push.8a99f462d6cebb67ffa6.DropdownList.doClick )",
     "    at Object.eval [as handleEvent] (ng:///DropdownModule/DropdownList.ngfactory.js:66:23)",
     "    at handleEvent ",
     "    at callWithDebugContext"
```

thanks

**Comment by huineng** [comment]
same for ngmodel https://angular.carbondesignsystem.com/?path=/story/components-combobox--with-ngmodel

**Comment by huineng** [comment]
and this doesn't look nice

https://angular.carbondesignsystem.com/?path=/story/components-combobox--in-modal

![image](https://user-images.githubusercontent.com/3482445/93596479-5f1f2800-f987-11ea-9080-e22d24596c1a.png)

**Comment by tacho090** [comment]
@huineng was the issue solved by #1539?

**Comment by huineng** [comment]
yes only this remains https://angular.carbondesignsystem.com/?path=/story/components-combobox--in-modal

**Comment by cal-smith** [comment]
I'm not sure what's going on with the `z-index` there 😱 As a work around you should be able to target `.bx--list-box--expanded` and give it a high enough `z-index` ... We may want to consider explicitly adding it to the styles to sort out these edge cases 🤔

**Comment by huineng** [comment]
For me you can close it, i don't have that problem with my apps, i just thought it might be an issue in the library

**Comment by cal-smith** [comment]
Gotcha 👍 I'll leave it for the moment, since it seems like something that can be fixed generally

**Comment by zvonimirfras** [comment]
Should be fixed with https://github.com/carbon-design-system/carbon/pull/8107
