### ISSUE TITLE
combobox : check on value

### ISSUE THREAD

**Issue by huineng** [IBM/carbon-components-angular#1533]
in formcontrol it can happen that a value has not yet been assigned and that the formcontrol value remains undefined

https://github.com/IBM/carbon-components-angular/blob/27e3216576c871a99e06fdbcc25bc6a93a94ca27/src/combobox/combobox.component.ts#L531

this can lead to a bug on the combox 

```
 "TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))",
```

possible solution 
```
if (this.itemValueKey) {
  // clone the specified item and update its state
  const newValue = Object.assign({}, this.view.getListItems().find(item => item[this.itemValueKey] === value ? value || ""));
  newValue.selected = true;
this.view.propagateSelected([newValue]);
} else {
  this.view.propagateSelected([value ? value || ""]);
}
```

**Comment by JoelLau** [comment]
hi @cal-smith, can I take this up as part of hacktoberfest

**Comment by cal-smith** [comment]
I can't seem to assign you at the moment @JoelLau, but thanks for taking this on!
