### ISSUE TITLE
No documentation available 

### ISSUE THREAD

**Issue by AlexandraAnghel** [IBM/carbon-components-angular#1534]
For the last few days there has been no documentation for angular-carbon

**Comment by zvonimirfras** [comment]
Both https://angular.carbondesignsystem.com and https://angular.carbondesignsystem.com/documentation/index.html seem to be working. What are you referring to?

**Comment by cal-smith** [comment]
The links are broken in the storybook. For now use the links that @zvonimirfras supplied.
