### ISSUE TITLE
ibm-select value doenst update when ngmodel value changes

### ISSUE THREAD

**Issue by cljsmid** [IBM/carbon-components-angular#1536]
## Detailed description

When using the ibm-select component to filter, trying to reset the filter with another component by changing the value of the bound variable. This does not update the selectbox. 

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug 

> Is this issue related to a specific component?
ibm-select

> What did you expect to happen? What happened instead? What would you like to see changed?
Value should reflect the value in the ngModel 

> What browser are you working in?
Newest chrome and firefox. 

> What version of the Carbon Design System are you using?
  "carbon-components": "10.20.0",
  "carbon-components-angular": "4.17.0"

## Steps to reproduce the issue

template:
```
<ibm-select [(ngModel)]="filterVal" (ngModelChange)="filter()" >
 <option value="one" >one</option>
 <option value="two" >two</option>
</ibm-select>
<button type="button" (click)="filterVal = 'one'" >Reset</button>
```
component:
```
filterval = 'one'
```

Reproduce:
Clicking the reset button, should reset the visual of the component, but doesn't.

**Comment by huineng** [comment]
i think related https://github.com/IBM/carbon-components-angular/issues/1518

**Comment by cljsmid** [comment]
Yeah it's the same issue, only with a different component.
