### ISSUE TITLE
ComboBox - Dropdown list box gets closed automatically on selection of checkbox

### ISSUE THREAD

**Issue by tulasigudibanda** [IBM/carbon-components-angular#1553]
With combo-box, when  I select a checkbox, dropdown list box gets closed automatically which doesn't allow me to do multi-selection of the items.

Expectation :  I should be able to select more than one checkbox item until I close it explicitly.

 Version : "carbon-components-angular": "^4.18.5",

**Comment by Donisius** [comment]
@tulasigudibanda is this still an issue with the latest version? It works as expected on the current version used on the demo site https://angular.carbondesignsystem.com/?path=/story/components-combobox--multi-select

**Comment by zvonimirfras** [comment]
Looks like this is already fixed. Feel free to reopen with reproduction steps if needed.
