### ISSUE TITLE
Feature request: Pivot tables

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#1563]
## PIVOT TABLES

This tables are different of a normal table, they are used on a more complex way, handling the structure of what is shown with drag and drop, I'll post some examples of them.

https://github.com/nicolaskruchten/pivottable
https://github.com/flexmonster/pivot-angular
https://www.syncfusion.com/kb/11109/how-to-get-started-easily-with-syncfusion-angular-8-pivot-table

**Comment by cal-smith** [comment]
This is a super interesting idea! I'd definitely open an issue over on https://github.com/carbon-design-system/carbon, since we really need some proper design consensus and styles before we take something like this on!

**Comment by Pablodotnet** [comment]
I'll open the issue over there

**Comment by cal-smith** [comment]
Tracking: https://github.com/carbon-design-system/carbon/issues/6987

**Comment by zvonimirfras** [comment]
Looks like this won't make it into the design so it won't make it into Angular version either, per @aagonzales [comment](https://github.com/carbon-design-system/carbon/issues/6987#issuecomment-738895835) in the tracking issue.
