### ISSUE TITLE
[(ngModel)] not working in ibm-table-toolbar-search even though while inspect, ng-reflect-model="000UJB" has correct value

### ISSUE THREAD

**Issue by krishnashree-roy** [IBM/carbon-components-angular#1564]
I need to display the previous searched value in the ibm-table-toolbar-search when I come back to the page. So I used below code. But it is not binding the value in ibm-table-toolbar-search where as the normal input field binding is working fine.

<ibm-table-toolbar-search  [skeleton]="skeleton" [placeholder]="placeholder" [tableSearch]="true"
    [(ngModel)]="searchedValue" ngDefaultControl name="searchVal" (valueChange)="searchValueChange($event)" (clear)="clear()">
</ibm-table-toolbar-search> 

[(ngModel)] not working in ibm-table-toolbar-search even though when I did inspect, ng-reflect-model="000UJB" has correct value as highlighted in the screenshot.
![issue](https://user-images.githubusercontent.com/52851838/95454401-06d9b580-098a-11eb-944b-f7136d37dd6c.png)

**Comment by krishnashree-roy** [comment]
Any Update on this issue?

**Comment by zvonimirfras** [comment]
Seems to be setting the value just fine in the storybook. When you say "not working", what does that mean?

**Comment by zvonimirfras** [comment]
Since no reply, assuming it's ok. Feel free to reopen with the requested info otherwise.
