### ISSUE TITLE
feat: Ability to hide the calendar icon in the datepicker input field component 

### ISSUE THREAD

**Issue by Rogier-blip** [IBM/carbon-components-angular#1568]
## Description
The ability to hide the calendar icon in the datepicker input field component 

## Detailed description

When using the date picker input field component I want to use the component as a `Simple date input` type. In the carbon documentation, can be [seen](https://www.carbondesignsystem.com/components/date-picker/usage/) that the Simple date input does not have the calendar icon on the right side of the input field.

![Screenshot 2020-10-14 at 09 23 46](https://user-images.githubusercontent.com/28896196/95956707-f8165700-0dfe-11eb-87e1-261e354180a9.png) 

With the current API's I am not able to remove the calendar icon from the component. 

_Is this a feature request (new component, new icon), a bug, or a general issue?_
Feature request

_Is this issue related to a specific component?_
DatePickerInputComponent

_What did you expect to happen? What happened instead? What would you like to see changed?_
Ability to remove the calendar icon from the date picker input field

_What version of the Carbon Design System are you using?_
carbon-component: 10.21.0
carbon-components-angular: 4.19.1

**Comment by cal-smith** [comment]
Huh, not sure when that changed on us ... I'm fairly confident that it used to have an icon. Either way, I'm thinking we'll probably want to just remove it entirely for the simple input case
