### ISSUE TITLE
Fail to implement Apollo client

### ISSUE THREAD

**Issue by lvneves2010** [IBM/carbon-components-angular#1573]
I am trying to get the 

badge for Carbon Angular , but when I start the step 3 and install the Angula Apollo the application crashes. I have made both corrections anticipated by the team but the problem is still there, There is still something wrong with this code.
<img width="1201" alt="Screen Shot 2020-10-21 at 09 50 14" src="https://user-images.githubusercontent.com/37113334/96721686-dda22780-1382-11eb-8bb5-b518c9b231de.png">

**Comment by cal-smith** [comment]
Please open this in the repo for the tutorial.
