### ISSUE TITLE
Progress indicator: Steps are undefined

### ISSUE THREAD

**Issue by Rogier-blip** [IBM/carbon-components-angular#1576]
## Title 
When using the progress indicator component, there is a chance that you will get a `this.steps is undefined` exception.

### Problem
When using the progress indicator in the following way:

```
<ibm-progress-indicator 
                        [current]="current"
                        [steps]="steps"
>
</ibm-progress-indicator>
```

The progress indicator throws an exception saying `this.steps is undefined`.

But when you order the inputs like this:

```
<ibm-progress-indicator 
                        [steps]="steps"
                        [current]="current"
>
</ibm-progress-indicator>
```

The exception isn't thrown.

### Reason
I believe the reason for this is that the input `current` has a setter that references the `steps` variable. If the inputs are not ordered correctly an exception is thrown. 

### Solution
I believe a good solution would be to move the setter code to the ngOnChanges lifecycle hook and check there if all the inputs are available before running the code.

> What version of the Carbon Design System are you using?

carbon-components: "10.21.0",
carbon-components-angular: "4.19.1",

**Comment by Rogier-blip** [comment]
I could make a PR for this. Just let me know if this is something you want to fix :)

**Comment by cal-smith** [comment]
Hey @Rogier-blip! Sorry for the late response, it would be amazing if you could make a PR for this!

**Comment by Rogier-blip** [comment]
I have been unable to reproduce this issue in the library. In both, the unit tests and in Storybook the issue does not occur.

It only occurs with these Angular versions in the project that I have been working on.

```
"dependencies": {
    "@angular/animations": "10.1.6",
    "@angular/cdk": "10.2.5",
    "@angular/common": "10.1.6",
    "@angular/compiler": "10.1.6",
    "@angular/core": "10.1.6",
    "@angular/forms": "10.1.6",
    "@angular/material": "10.2.5",
    "@angular/platform-browser": "10.1.6",
    "@angular/platform-browser-dynamic": "10.1.6",
    "@angular/router": "10.1.6"
    ...
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1001.7",
    "@angular/cli": "10.1.7",
    "@angular/compiler-cli": "10.1.6",
    "@angular/language-service": "10.1.6",
    ...
  }
```

It seems that in Angular 10.2.x there is a change that fixes this issue.

Nevertheless, I do think the pattern that is used is problematic.

```
set current(current: number) {
  if (current === undefined || current < 0) {
    for (let i = 0; i < this.steps.length; i++) {
      ...
   }
  ...
}
```
In the setter, it is assumed that `this.steps` is defined. Which can't be known for sure. It really depends on when this piece of code is executed. Is it executed before the steps input is available or not?

Even though the issue does not occur right now I still propose to move the code being executed in the setter to the ngOnInit, where we are sure that all inputs are available, and handle subsequent updates of `current` in the ngOnChanges. 

@cal-smith Could you give your opinion about this?

**Comment by cal-smith** [comment]
> It only occurs with these Angular versions in the project that I have been working on.

Ah, yeah we're keeping the project on Angular 7 for now, so it's totally possible this is a version specific issue. Still worth fixing of course.

> Even though the issue does not occur right now I still propose to move the code being executed in the setter to the ngOnInit, where we are sure that all inputs are available, and handle subsequent updates of current in the ngOnChanges.

Seems like a reasonable change to me! We've been using the getter/setter pattern with _reasonable_ success, but it's definitely caused a few headaches as well. I think in this case it might be a bit more future proof if we go with the traditional ngOnInit + ngOnChanges combo.
