### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by mrtariqsaeed** [IBM/carbon-components-angular#1588]
## Detailed description

When I add the Carbon css import in styles.scss `@import "~carbon-components/scss/globals/scss/styles";`
and run `ng serve` I get this error `JavaScript heap out of memory`

Here is my dependencies:

"dependencies": {
    "@angular/animations": "~10.2.0",
    "@angular/common": "~10.2.0",
    "@angular/compiler": "~10.2.0",
    "@angular/core": "~10.2.0",
    "@angular/forms": "~10.2.0",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "~10.2.0",
    "@angular/platform-browser-dynamic": "~10.2.0",
    "@angular/router": "~10.2.0",
    "@carbon/icons-angular": "^11.2.1",
    "carbon-components": "^10.23.2",
    "carbon-components-angular": "^4.23.1",
    "jwt-decode": "^3.0.0",
    "minimist": "^1.2.5",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.0",
    "@angular/cli": "~10.2.0",
    "@angular/compiler-cli": "~10.2.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }

> Is this a feature request (new component, new icon), a bug, or a general issue?
A bug

> Is this issue related to a specific component?
No

> What version of the Carbon Design System are you using?
`"carbon-components": "^10.23.2",`
`"carbon-components-angular": "^4.23.1"`

## Steps to reproduce the issue

1. Create a new angular project using angular 10
2. use npm to install `"carbon-components": "^10.23.2"` and `"carbon-components-angular": "^4.23.1"`
3. In the styles.scss add this line `@import "~carbon-components/scss/globals/scss/styles";`
4. run ng serve

**Comment by cal-smith** [comment]
There's not a lot we can do about this, since it's dependent on sass behaviour and the implementation of `carbon-components`. I believe you can opt into a newer sass compiler if you explicitly install `sass`, and updating your node version may also help. Failing that You can try running the CLI directly with `--max-old-space-size` set.

You may also want to open an issue on the `carbon-components` side and see if they have any other suggestions.

Closing since we can't do anything about it.

**Comment by mrtariqsaeed** [comment]
@cal-smith hey man, I am a little bit disappointed, I didn't get an answer to that same question on the `carbon-ng` slack channel, and here your closing the issue cuz there's nothing you can do about it. I know that the `--max-old-space-size` thing can fix it, but why it doesn't work out of the box. I should be able to install Carbon with angular and use it right away. The angular carbon documentation doesn't have any recommendations regarding which dependency versions and which angular version I should use with the latest Carbon version, why I need to figure that out myself.

**Comment by cal-smith** [comment]
There is one person dealing with the entirety of this project and associated slack questions: me. I hear your frustration, and I wish there was more I could do to help.

I am tremendously sorry I didn't get to your slack question, however consider my response here equivalent.

I will always welcome contributions, and **constructive** suggestions - simply opening an issue to complain about a problem you can solve simply isn't constructive. Had this been an issue with actionable improvements to the documentation perhaps with a plan to achieve them, I would have let it stand. If you wish to open an issue along those lines it would be more than welcome!

**Every form of contribution is more important than you think**. Code improvements are helpful, but documentation contributions and incredible. Don't ever think you have nothing to contribute.

Again, I hear you, and I wish there was more that could be done. Understand that closing issues such as this isn't a personal attack.

**Comment by mrtariqsaeed** [comment]
Really appreciate your kind words, and you're right I should probably try contributing to the documentation instead of complaining about it :D. Thanks again Cal, and I will see if there is something I can help with.
