### ISSUE TITLE
Overflow menu positioning in IE 11

### ISSUE THREAD

**Issue by chengjun0124** [IBM/carbon-components-angular#159]
Hi 

I am using overflow menu, it cannot work correctly in IE11, and when I run storybook(https://angular.carbondesignsystem.com) in IE11, I see a blank page. Does carbon-components-angular support IE?

**Comment by zvonimirfras** [comment]
Storybook currently requires polyfills to support it. They are not present so storybooks don't render.

Components should, though.

What's not working correctly regarding overflow menu?

**Comment by jdcai** [comment]
I'm also having an issue with overflow menu on IE11. 
I'm using the overflow menu as part of a table like the "table with overflow menu" in storybook.
When I open the overflow menu it appears on the bottom left of the screen instead of under the overflow menu

**Comment by zvonimirfras** [comment]
Is that just on IE11?

**Comment by jdcai** [comment]
Yes, in firefox and chrome it works normally

**Comment by zvonimirfras** [comment]
@cal-smith This looks like some IE11 specific positioning weirdness. Do you mind taking a look at it?
