### ISSUE TITLE
WAI-ARIA attribute is not valid for "searchbox" role 

### ISSUE THREAD

**Issue by GSSCDylan** [IBM/carbon-components-angular#1598]
##  Detailed description

> Describe in detail the issue you're having.

- **ibm-combo-box with (search) attribute will generate an input as following:**

`<input type="text" role="searchbox"  aria-haspopup="true  aria-aria-labelledby="dropdown-0">`

**- But WAI-ARIA attributes is not valid for the searchbox role**

> Is this a feature request (new component, new icon), a bug, or a general issue?

- **bug**

> Is this issue related to a specific component?

- **ibm-combo-box**

> What browser are you working in?

- **Firefox**

> What version of the Carbon Design System are you using?

`"carbon-components": "10.20.0",
    "carbon-components-angular": "4.17.0"`

## Steps to reproduce the issue

1.     Use browser to open an webpage that contains ibm-combo-box with (search) attribute
2.     Run IBM Equal Access Accessibility Checker

## Additional information

* Screenshots or code
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/73825731/98346705-4f4fc600-2051-11eb-9e99-751835699a7d.png">
<img width="874" alt="image" src="https://user-images.githubusercontent.com/73825731/98346742-5bd41e80-2051-11eb-9dac-920fe4420018.png">

* Notes

**Comment by GSSCDylan** [comment]
Hi @cal-smith , please also help to fix this issue ASAP, it's also impact our AD AVT compliance. @stanislavgeorgiev  FYI

**Comment by cal-smith** [comment]
Closed by #1615
