### ISSUE TITLE
Date picker input

### ISSUE THREAD

**Issue by iliyaeffati** [IBM/carbon-components-angular#1599]
Date picker convert a random and incorrect  input to a valid date. 

![Screenshot 2020-11-06 at 11 35 11](https://user-images.githubusercontent.com/7510949/98358566-32060200-2027-11eb-9dff-51efe4f24f55.png)

**Comment by cal-smith** [comment]
We can't know what format your application, or your users if it's locality specific, require dates in ... Formatting the dates and generating errors for incorrect input is left up to the application.

Are there specific issues with the inputs/outputs available for value handling?
