### ISSUE TITLE
Progress indicator: optionalText is a required field

### ISSUE THREAD

**Issue by Rogier-blip** [IBM/carbon-components-angular#1604]
## Detailed description

> Describe in detail the issue you're having.

After updating to 4.26.1 optional text became a required field in the Step interface from the progress indicator component

> Is this issue related to a specific component?

Progress indicator

> What did you expect to happen? What happened instead? What would you like to see changed?

Have optionalText as an optional field.

> What version of the Carbon Design System are you using?

"carbon-components": "10.23.2",
"carbon-components-angular": "4.26.1",

**Comment by stanislavgeorgiev** [comment]
Thanks for the quick merge and release @cal-smith and @zvonimirfras!
