### ISSUE TITLE
Need to translate 'CANCEL' button(text) on ibm-tool-bar in carbon-10

### ISSUE THREAD

**Issue by aaratichavan** [IBM/carbon-components-angular#1621]
After selecting one or multiple rows (checkbox), toolbar will display above table with 'Items selected' & 'Cancel' button.
**Expected** - 'Items selected' & 'Cancel' button text should to translate in other language.

**Actual** - Only 'Items selected' text get translated in other language & 'Cancel' text remains in English .

**Comment by zvonimirfras** [comment]
Upon inspecting `ibm-table-toolbar` (assuming that's the one you're talking about since ibm-tool-bar doesn't exist and all other toolbars don't have a cancel button), it appears that the component is following the same process for cancel as for all other translatable text.

How are you setting the translation?

**Comment by aaratichavan** [comment]
> This my code

```
.html
<ibm-table-toolbar [model]="dataTableModel" [batchText]="toolbarTranslations"  #toolbar></ibm-table-toolbar> 
.ts
toolbarTranslations = this.translation.translate('CARBON_10.TOOLBAR');
.json file
 "TOOLBAR": {
      "ITEM_SELECTED": "{{ count }} item selected",
      "ITEMS_SELECTED": "{{ count }} items selected",
      "CANCEL": "Cancel",
      "SINGLE": "1 item selected",
      "MULTIPLE": "{{count}} items selected"
    }
```
Everything get translated except Cancel. I have attached screenshots for reference

**Comment by zvonimirfras** [comment]
Looks like you only set translations for `batchText`. You should also set the translation for `cancelText` (and `ariaLabel` probably as well).

That should solve your problem. Feel free to reopen if needed.
