### ISSUE TITLE
Select option value null becomes 'null' 

### ISSUE THREAD

**Issue by cljsmid** [IBM/carbon-components-angular#1627]
> Describe in detail the issue you're having.

Using ibm-select with an option with a null value doenst work as expected. The null value gets transformed into a string 'null'. The value should stay null. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Ibm select 

> What browser are you working in?

Chromes latest 

> What version of the Carbon Design System are you using?

   "carbon-components": "10.24.0"
   "carbon-components-angular": "4.26.2"

`
<ibm-select
  [(ngModel)]="myFilter"
  (ngModelChange)="filter()"
  name="myFilter"
  ibmCol
  [columnNumbers]="{ lg: 3, md: 3 }">
    <option [value]="null">No filter</option>
    <option *ngFor="let type of filterTypes" value="{{ type.key }}">{{ type.value }}</option>
</ibm-select>
`

Using the above code, the filter() method will be called with value 'null' instead of null

**Comment by zvonimirfras** [comment]
As far as I can tell, it's the native select element that does the conversion from value to string and we can't tell the difference between a `null` value and a `"null"` string. It's what native change event gives us.

What's your intention here?

If it's to have a default option with no value, that's [usually achieved with an empty string](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) (`""`) for value. (Coincidentally, empty string is a falsey value in JS).

**Comment by zvonimirfras** [comment]
Since there's no reply and enough time has passed, assuming the reply resolved the issue. Feel free to reopen with requested info otherwise.
