### ISSUE TITLE
Add a light style to the Carbon components that support it

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#163]
## Detailed description

> Describe in detail the issue you're having.

Provide an option to choose between the default style and the light style for the components that are supporting it in Carbon:

- [ ] Dropdown
- [x] Input
- [ ] Select
- [x] Textarea

That new setting should have the same name for all components. For example, `style: "" | "light" = "";` or `light = false`.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Yes

> Is this issue related to a specific component?

Select

**Comment by zvonimirfras** [comment]
To whoever picks this up, we decided that `@Input` for controlling this should be named `theme`.

**Comment by stanislavgeorgiev** [comment]
https://github.com/IBM/carbon-components-angular/pull/215 is fixing the Input and Textarea
