### ISSUE TITLE
combobox component input field has a wrong role

### ISSUE THREAD

**Issue by grenobnik** [IBM/carbon-components-angular#1637]
this bug is due to an error in the component template, the role attribute appears two times:
```
role="combobox"
...
role="searchbox"
```
replacing the correct value `combobox` by `searchbox`

**Comment by cal-smith** [comment]
I believe this has been fixed. Each element with a `role` only has one `role` ... there appears to be some other a11y issues with combobox, but I think those are covered by other issues. I'll close this for now, feel free to reopen if it's till an issue.
