### ISSUE TITLE
ibm-toggle set value=undefined 

### ISSUE THREAD

**Issue by shroffsmiti** [IBM/carbon-components-angular#1648]
Ibm-toggle component is setting the value to undefined at 
https://github.com/IBM/carbon-components-angular/blob/master/src/toggle/toggle.component.ts#L65

and this is violation for AAT. 
Checkbox input and others with the name "undefined" are not grouped together
Violation
Related sets of radio buttons or checkboxes should be programmatically grouped

**Comment by zvonimirfras** [comment]
`ibm-toggle` is setting the value of the input to what ever the user set the `value` attribute to. The same way checkbox does. Perhaps we could default it to `false`.

**Comment by zvonimirfras** [comment]
@shroffsmiti after rereading the issue you brought up, it doesn't seem to be due to `value` attribute, but due to missing `name`.

`name` input is something a developer should set for each group. It would look something like

```typescript
<ibm-toggle name="your-name"></ibm-toggle>
```

When you add the name, do you still get the same violation?

**Comment by shroffsmiti** [comment]
@zvonimirfras thanks for this info, when we add name it does not throw any violation. 
Plz close this issue.

**Comment by zvonimirfras** [comment]
Thank you for verifying 🙂
