### ISSUE TITLE
Lots of icons will disappear in Windows High Contrast Black mode/ White mode  (Accessiblity issue) 

### ISSUE THREAD

**Issue by GSSCDylan** [IBM/carbon-components-angular#1651]
## Detailed description

> Describe in detail the issue you're having.
Lots of icons will disappear in Windows High Contrast Black mode or Windows High Contrast White mode
> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug
> Is this issue related to a specific component?
No
> What browser are you working in?
FireFox
> What version of the Carbon Design System are you using?
"4.27.7"
## Steps to reproduce the issue
In Windows OS,  change the theme to Windows High Contrast Black mode or Windows High Contrast White mode
Launch a Web APP that using Carbon-Angular

## Additional information

* Screenshots or code
High Contrast White mode issues:
![White-Configure-Environments2](https://user-images.githubusercontent.com/73825731/101486288-6149bf00-3997-11eb-983f-b520cace94f2.png)
![White-Dashboard-Service3](https://user-images.githubusercontent.com/73825731/101486301-660e7300-3997-11eb-808e-dd5bc33e7cf7.png)
![White-Dashboard-Servers3](https://user-images.githubusercontent.com/73825731/101486317-6dce1780-3997-11eb-9d55-105166f52584.png)
High Contrast Black mode issues:
![Black-Audit-Users](https://user-images.githubusercontent.com/73825731/101486512-bb4a8480-3997-11eb-9ca1-39e5ad124cd6.png)
![Black-Monitor2](https://user-images.githubusercontent.com/73825731/101486519-bd144800-3997-11eb-8fab-60411080e0f6.png)
![Black-Analyze service-Users](https://user-images.githubusercontent.com/73825731/101486522-be457500-3997-11eb-8b35-c1a248e26c5e.png)
![Black-Configure-Environments2](https://user-images.githubusercontent.com/73825731/101486524-bede0b80-3997-11eb-927f-3152a5db5dbd.png)
![Black-Dashborad1](https://user-images.githubusercontent.com/73825731/101486525-bf76a200-3997-11eb-863f-d3216b746125.png)

* Notes

**Comment by GSSCDylan** [comment]
@cal-smith , could you please help to investigate this issue?

**Comment by stanislavgeorgiev** [comment]
It looks like there's a new CCS Media queries that are supposed to be dealing with high contrast: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors

I did try it in FF 83 but it doesn't seem to be working

**Comment by stanislavgeorgiev** [comment]
A search query for related issues in Carbon, there's quite a few unfortunately:
https://github.com/carbon-design-system/carbon/issues?q=is%3Aissue+is%3Aopen+high+contrast

**Comment by cal-smith** [comment]
This is something that would need to be resolved at the `carbon-components` level ... We don't control the styling of the icons at all.
