### ISSUE TITLE
Combobox is getting focused after 1st loading of page

### ISSUE THREAD

**Issue by badheshweta21** [IBM/carbon-components-angular#1667]
## Detailed description

>I just loaded page and combobox is focused

> This issue is with combobox basic component.

https://angular.carbondesignsystem.com/?path=/story/components-combobox--basic

> carbon components version : ^4.27.1

## Steps to reproduce the issue

On 1st load of page combobox is focused

## Additional information

![image](https://user-images.githubusercontent.com/19573886/102243333-0e38b480-3f21-11eb-8912-90c749b207db.png)

**Comment by DusanMilko** [comment]
@cal-smith 
Example of 2: If you update one of the items to be selected with a setTimeout then the combobox gets focus. If its updated programmatically like this we shouldn’t focus.

Example of 3: In combobox If you go to “Basic” and type in a filter search such as “aaaa” you see all results, but you should see none. If you go to “Multi-select” and do same “aaaa” search you get no results. Should be consistent
