### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by Licen-it** [IBM/carbon-components-angular#1669]
## Detailed description

> Describe in detail the issue you're having.

I'm getting this console error while on mobile screen: `Unable to preventDefault inside passive event listener invocation` triggered in `onTouchStart` from `dialog.directive.ts`
The effect of this error is that my overflow menu opens and closes straight away.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

any component using `dialog.directive.ts`

> What browser are you working in?

any

> What version of the Carbon Design System are you using?

latest

## Steps to reproduce the issue

you can catch it even in storybook, just go there in any component using a dialog (eg. table with toolbar, overflow menu etc) and reduce the browser size to mobile size.

**Comment by zvonimirfras** [comment]
I can't replicate the console error but I can the behavior. What happens is touch and click both get registered and toggle the dialog. Touch toggles it open, click toggles it close.
