### ISSUE TITLE
title in table item in table component showing [object object]

### ISSUE THREAD

**Issue by aishwaryamyana** [IBM/carbon-components-angular#1674]
Steps to reproduce 

Pass the object to table as nested objects like below 
[new TableItem(data: {data: "Name 1"}), new TableItem(data: {data: "qwer"})]
PFA for this showing title as [object object]
<img width="1468" alt="Screen Shot 2020-12-21 at 12 53 32 PM" src="https://user-images.githubusercontent.com/53562295/102750931-d0a6b200-438c-11eb-8349-5b83931b379b.png">

Title will work fine if the data is simple object like below
[new TableItem({data: "Name 1"}), new TableItem({data: "qwer"})
PFA for working scenario and thats why not able to reproduce in story book

<img width="1455" alt="Screen Shot 2020-12-21 at 12 54 16 PM" src="https://user-images.githubusercontent.com/53562295/102750965-dbf9dd80-438c-11eb-8182-7134ec504cf3.png">

**Comment by aishwaryamyana** [comment]
<img width="1591" alt="Screen Shot 2020-12-21 at 1 08 45 PM" src="https://user-images.githubusercontent.com/53562295/102751413-b4574500-438d-11eb-9400-a12f1d0187ac.png">

This is how it looks on UI

**Comment by Donisius** [comment]
@aishwaryamyana hi, if you are sending in nested objects to the tableItems you can do something like: `[new TableItem(data: {data: "Name 1"}, title: "Name 1"), new TableItem(data: {data: "qwer"}, title: "qwer")]`

**Comment by Donisius** [comment]
This solution worked locally on version `4.35.0` of `carbon-components-angular`. I'm will close this for now but feel free to reopen if the issue persists.

**Comment by aishwaryamyana** [comment]
@Donisius 
If I add title in the object , it works properly in nested object in previous version of carbon-components-angular.
And in new version 4.35.0 , I dont need to add **title** explicitly . am I Correct?

**Comment by Donisius** [comment]
@aishwaryamyana Sorry for the delayed response. You would still need to add the **title** explicitly in the latest version. I don't know if it makes sense to assume the **title** from a given nested object. If you believe it should be assumed (or auto-detected) we can look into it if it makes sense if you open up an issue!
