### ISSUE TITLE
ibm-select: when invalid, restricts click area for the dropdown

### ISSUE THREAD

**Issue by oprabhudesai** [IBM/carbon-components-angular#1680]
## Detailed description

> Describe in detail the issue you're having.
ibm-select component when invalid does not show error icon in the component. also the clickable area is limited

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
yes. ibm-select

> What did you expect to happen? What happened instead? What would you like to see changed?
error icon expected in the component. Also it should allow to click in the whole component to open the options
> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
"carbon-components": "^10.24.0",
 "carbon-components-angular": "^4.27.6",

## Additional information

* Screenshots or code
* 
![image](https://user-images.githubusercontent.com/17044953/102987138-e9070000-4537-11eb-9db5-3890a02d1e9b.png)

* Notes

**Comment by zvonimirfras** [comment]
This is fixed in https://github.com/IBM/carbon-components-angular/pull/1675 v4.31.9

**Comment by oprabhudesai** [comment]
> This is fixed in #1675 v4.31.9

Thanks for the update!
