### ISSUE TITLE
ibm-combobox: Has default tabindex set to 0

### ISSUE THREAD

**Issue by oprabhudesai** [IBM/carbon-components-angular#1689]
## Detailed description

> Describe in detail the issue you're having.
ibm-combobox component has default tabindex of 0 set to it which causes the focus set to it by default on page load. For forms where this component used in middle/end of the form does not look good.
> Is this a feature request (new component, new icon), a bug, or a general issue?
general issue
> Is this issue related to a specific component?
ibm-combobox
> What did you expect to happen? What happened instead? What would you like to see changed?
tabindex should be -1 so the focus is not set to it default and it is also tabbable in sequence
> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
"carbon-components": "^10.24.0",
"carbon-components-angular": "^4.34.0",

## Additional information

* Screenshots
![image](https://user-images.githubusercontent.com/17044953/103805050-09c36f80-5079-11eb-89b8-6d600e52ee4d.png)

**Comment by cal-smith** [comment]
That's not what `tabindex="0"` does. From MDN - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

>`tabindex="0"` means that the element should be focusable in sequential keyboard navigation, after any positive tabindex values and its order is defined by the document's source order.

`tabindex="-1"` as you suggest, would remove the combobox from the tab order entirely - not what we want.

More to the point, if the focus is defaulting to the combobox in your app that suggests to me an issue with your app - the storybook doesn't exhibit that behaviour.

Please open another issue with a clear reproduction (ideally a new ng CLI app pushed to github)

**Comment by oprabhudesai** [comment]
> That's not what `tabindex="0"` does. From MDN - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
> 
> > `tabindex="0"` means that the element should be focusable in sequential keyboard navigation, after any positive tabindex values and its order is defined by the document's source order.
> 
> `tabindex="-1"` as you suggest, would remove the combobox from the tab order entirely - not what we want.
> 
> More to the point, if the focus is defaulting to the combobox in your app that suggests to me an issue with your app - the storybook doesn't exhibit that behaviour.
> 
> Please open another issue with a clear reproduction (ideally a new ng CLI app pushed to github)

Thanks for the details.
