### ISSUE TITLE
Expansion table stripped="true" changes the strip rows background colour when row is expanded

### ISSUE THREAD

**Issue by nsharma1989** [IBM/carbon-components-angular#1696]
## Title line template: [Title]: Brief description
When using table with expansion and stripped is true. The alternate stripped background breaks after expanding the row

## Detailed description
> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Table with expansion

> What did you expect to happen? What happened instead? What would you like to see changed?
Striped rows background should not change for not expanded rows

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
latest

## Steps to reproduce the issue

go to storybook 
https://angular.carbondesignsystem.com/?path=/story/components-table--with-expansion
Select stripped from Knob
Expand a row
the below 2 rows will change the background colour

## Additional information
before:

![Screen Shot 2021-01-11 at 12 02 53 PM](https://user-images.githubusercontent.com/18398195/104216097-9ff3ee80-5407-11eb-8229-2cb3a3693876.png)

After:
![Screen Shot 2021-01-11 at 12 03 07 PM](https://user-images.githubusercontent.com/18398195/104216142-abdfb080-5407-11eb-973d-0d148d29b86c.png)

**Comment by cal-smith** [comment]
Does this happen when every row is expandable? Or just a few? It also seems like our current implementation is causing a few issues with this as well (adding/removing the row vs showing/hiding with styles) ... there's definitely a few bugs here to fix.

**Comment by nsharma1989** [comment]
I see it happening on expanding 1st row only.

**Comment by cal-smith** [comment]
Hey there 👋 this was touched on in this PR https://github.com/IBM/carbon-components-angular/pull/1843/files but there's not a lot more we can do - mixing expandable rows with non-expandable rows _and_ striping will always lead to some strangeness in row striping given how Carbon applies the stripes. If you need mixed expandable/normal rows I would suggest disabling striped rows.
