### ISSUE TITLE
[Table pagination dropdown arrow]: Dropdown not appearing when you click the arrow

### ISSUE THREAD

**Issue by CJMeek** [IBM/carbon-components-angular#1709]
## Detailed description

I added a pagination model to my table (separately as I needed to add my own functionality to the pagination bar) and when you click on the dropdown arrow to select a page number nothing appears. However, when you click the number then the dropdown appears. I'm not sure if this is a bug or just intended but it is a little confusing. I currently work in Firefox, and working with the latest version of carbon-components and carbon-components-angular.

## Steps to reproduce the issue

1. Added pagination component to page
2. Gave the pagination component a model with sizes and page numbers etc
3. Set current page to 1 and set total data length to size of data coming in from the api

## Additional information

* Screenshots or code
<img width="1377" alt="Screenshot 2021-01-21 at 10 40 00" src="https://user-images.githubusercontent.com/44683056/105339977-33ca7500-5bd5-11eb-9f2d-9bf09d8d927d.png">

<img width="152" alt="Screenshot 2021-01-21 at 10 40 34" src="https://user-images.githubusercontent.com/44683056/105339986-375dfc00-5bd5-11eb-8eab-01be585b7aca.png">

**Comment by zvonimirfras** [comment]
Seems to be working fine in the [story](https://angular.carbondesignsystem.com/?path=/story/components-table--with-pagination). Here's the [code](https://github.com/IBM/carbon-components-angular/blob/master/src/table/stories/app-pagination-table.component.ts) for that story.

From your comment, it's not clear if you're using the same (TableModel) for the table _and_ the pagination, but you should, they are designed for that.

It also, from the image, looks like only the number portion is selected (the blue rectangle) while in the story it always also selects the chevron (so it's inside the rectangle).

Can you create a minimal reproduction app?

**Comment by zvonimirfras** [comment]
After chatting about it, it looks like an app level issue.
