### ISSUE TITLE
Table Row Accessibility

### ISSUE THREAD

**Issue by aradhikaIbm** [IBM/carbon-components-angular#172]
## Detailed description

> Describe in detail the issue you're having.
After getting input back from the accessibility team, a full grid implementation is not needed. But they did suggest for ease of use to able to navigate the table using the up and down arrows (ie following a row level focus). As part of row level navigation, could the End and Home be added. Home would take you to the first row and End would take you to the last row. 

Per the feedback: 
It may be possible to enable per line navigation without getting into a full grid design, in such a case (i.e., up/down arrows move focus by line, tabbing moves across row between cell content that takes focus).

Hopefully there are no design impacts for row level navigation. I believe the table already highlights the row if focus is on the row.

> Is this a feature request (new component, new icon), a bug, or a general issue?
enhancement

> Is this issue related to a specific component?
Tables

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Watson Recruitment, Accessibility deadline of Dec 10, 2018.

**Comment by zvonimirfras** [comment]
Which a11y spec describes this behavior?

**Comment by aradhikaIbm** [comment]
I believe they recommended only doing a portion of the grid navigation. They said having cell by cell is not needed but recommended row. If we need more guidance, I'm sure we could work with the accessibility team. I've shared the feedback they gave us on the tables. 

Per the feedback stated below, I would interpret that giving a row the focus as you go up and down using arrows. The left and right arrow are not needed since we are not implementing cell by  cell. 
Per the feedback: (Accessibility team feedback)
It may be possible to enable per line navigation without getting into a full grid design, in such a case (i.e., up/down arrows move focus by line, tabbing moves across row between cell content that takes focu

This is the link for grids. 
https://www.w3.org/TR/wai-aria-practices/#keyboard-interaction-for-data-grids

**Comment by ninja511** [comment]
Documenting email exchange on this (October 16)

Josh: 
For Tables, I believe we were delegating navigation to the screen readers themselves. It's my understanding that each one has their own set of commands to help with table navigation. For example:
 
- JAWS: https://www.freedomscientific.com/Training/Surfs-Up/Table_Reading_Commands.htm
- NVDA: https://webaim.org/resources/shortcuts/nvda#tables
- VoiceOver: https://www.apple.com/voiceover/info/guide/_1133.html
 
Are there additional requirements in place here that we should try and add to the spec for tables?
 
Dean: 
thx Josh ... Zvonimir feels the same way.
 
Alicia, given this feedback from both Carbon (React & Angular) dev teams perhaps you'd like to investigate adding this functionality in your application code ?

**Comment by ninja511** [comment]
Closing  - as per above comment. Please reopen if needed.
