### ISSUE TITLE
Overflow menu alignment is not proper

### ISSUE THREAD

**Issue by aaratichavan** [IBM/carbon-components-angular#1720]
When page limit is 10 in table then overflow menu alignment works properly but when page limit is more than 10 then overflow menu display on another row.

**Expected**: After clicking on 12th row and scroll-down then again select 16th row overflow menu, then overflow menu should display on 16th row only.

**Actual**: After clicking on 12th row and scroll-down then again select 16th row overflow menu, then overflow menu is  displaying on 12th row only.

![image](https://user-images.githubusercontent.com/69956330/106225818-e751eb80-620b-11eb-8ea6-337c6919b85c.png)

**Comment by zvonimirfras** [comment]
Thanks for bringing this to our attention, @aaratichavan.

Does this still happen at the latest version of carbon-components and carbon-components-angular (currently 10.27.0 and 4.39.0)?

If yes, it doesn't happen when following your steps and changing data length in [our example](https://angular.carbondesignsystem.com/?path=/story/components-table--with-overflow-menu) so please provide minimal code example that would enable us to replicate this.

**Comment by aaratichavan** [comment]
@zvonimirfras Verified with latest version of carbon-components and carbon-components-angular, i can still reproduce this issue
can you please verify with more than 10-20 records in table. It is only reproducing when there are more than 10 records in table.

**Comment by zvonimirfras** [comment]
Yes, I did try that. Please provide a minimal reproduction that we can use to replicate what you're seeing.

We can only do something about it once we can replicate it 🙂

**Comment by vseverestek** [comment]
I had gone through a similar issue. I found that I was using multiple ibm-placeholder which caused the problem. I kept a single ibm-placholder to fix the problem.

**Comment by zvonimirfras** [comment]
@aaratichavan, try what @vseverestek suggested if it's applicable.

If it's still a problem, feel free to reopen and provide a minimal reproduction that we can use to debug the issue.
