### ISSUE TITLE
Angular Version Update!

### ISSUE THREAD

**Issue by seriouz** [IBM/carbon-components-angular#1725]
Hi guys, thanks for your effort! My question is why there is no visible work on a Carbon version with an up-to-date Angular? The currently used Angular 8 is no longer under support and even Angular 9 reaches end of life on august this year. There are some major performance improvements on Angular 9+ (especially compile time).
https://angular.io/guide/releases#support-policy-and-schedule

**Comment by lepidotteri** [comment]
> 
> 
> Hi guys, thanks for your effort! My question is why there is no visible work on a Carbon version with an up-to-date Angular? The currently used Angular 8 is no longer under support and even Angular 9 reaches end of life on august this year. There are some major performance improvements on Angular 9+ (especially compile time).
> https://angular.io/guide/releases#support-policy-and-schedule

I wouldn't have my hopes up, the Angular team for Carbon Components is ridiculous. AOT vendor.js bundles are still in the tens of MBs size

**Comment by cal-smith** [comment]
> My question is why there is no visible work on a Carbon version with an up-to-date Angular? 

Hey @seriouz, thanks for the question. I'd be curious what's preventing you from adopting newer versions of Angular? We do support the latest version (11), and you can take advantage of all the benefits you list in your app. We do develop on an older version, but we do that to provide the greatest level of version compatibility - there should be no effect on your application.

**Comment by cal-smith** [comment]
> I wouldn't have my hopes up, the Angular team for Carbon Components is ridiculous.

Hi @lepidotteri I would like to make sure you have read and understood our [code of conduct](https://github.com/IBM/carbon-components-angular/blob/master/.github/CODE_OF_CONDUCT.md). If you have an issue with the components please don't hesitate to raise an issue and we'll work with you to resolve it, however attacking the core team will not be tolerated - we are humans too.

Now given your following comment:

> AOT vendor.js bundles are still in the tens of MBs size

This absolutely should not be the case. Please make sure you're on a recent version of Angular (10/11) and the latest version of `carbon-components-angular`, you can drop the `@carbon/icons-angular` dependency and replace it with `IconModule` and `@carbon/icons`. If you still have issues with bundle sizes make sure you're taking advantage of per-component modules (ex. `import { ButtonModule } from "carbon-components-angular/button";`) and lazy-loading.

If you have further specific issues with bundle sizes please open an issue with as much detail as you can (a minimal reproduction would be ideal).

**Comment by seriouz** [comment]
> 
> 
> > My question is why there is no visible work on a Carbon version with an up-to-date Angular?
> 
> Hey @seriouz, thanks for the question. I'd be curious what's preventing you from adopting newer versions of Angular? We do support the latest version (11), and you can take advantage of all the benefits you list in your app. We do develop on an older version, but we do that to provide the greatest level of version compatibility - there should be no effect on your application.

Sorry i haven't seen it anywhere that gave me a hint that the newer Angular version are supported. Did i miss it, or is it nowhere recorded?

**Comment by cal-smith** [comment]
> > > My question is why there is no visible work on a Carbon version with an up-to-date Angular?
> > 
> > 
> > Hey @seriouz, thanks for the question. I'd be curious what's preventing you from adopting newer versions of Angular? We do support the latest version (11), and you can take advantage of all the benefits you list in your app. We do develop on an older version, but we do that to provide the greatest level of version compatibility - there should be no effect on your application.
> 
> Sorry i haven't seen it anywhere that gave me a hint that the newer Angular version are supported. Did i miss it, or is it nowhere documented?

We declare our version support via `peerDependencies` here: https://github.com/IBM/carbon-components-angular/blob/master/package.json#L62-L64

Definitly open to suggestions as to how we can make our version support more obvious 👍

**Comment by cal-smith** [comment]
I'm going to assume this issue has been resolved.

**Comment by seriouz** [comment]
@cal-smith Thank you!
