### ISSUE TITLE
Large shipped vendor.js bundle persisting in Angular ^10

### ISSUE THREAD

**Issue by lepidotteri** [IBM/carbon-components-angular#1726]
> 
> 
> We're a little stuck at the moment given that we have to support Angular 9, which means that the components have to deal with 9s sub-optimal `ngcc` process, which means we can't fully switch to per-icon packages _yet_. With Angular 10 I _think_ the program based finder should be smarter with what it compiles, which should let us make better use of the per-icon packages in `@carbon/icons-angular@11.1.4`.
> 
> If you can use the per-component imports in the latest version of v4 it should help a bit, but the ultimate solution will be once we can totally switch everything over to per-icon imports.

Angular ^10 here, this makes the library completely useless, the problem is still there; with or without the Carbon Charts, vendor.js bundle is consistently over 50MB:

![107266808-528a9180-6a46-11eb-96f2-71dd5ceea0bf](https://user-images.githubusercontent.com/45174270/107267787-a47fe700-6a47-11eb-929f-1510bfdef951.png)

_Originally posted by @lepidotteri in https://github.com/IBM/carbon-components-angular/issues/1320#issuecomment-775361002_

**Comment by cal-smith** [comment]
Just noticed this, I'll bring my comment over from #1320:

You can drop the `@carbon/icons-angular` dependency and replace it with `IconModule` and `@carbon/icons`. If you still have issues with bundle sizes make sure you're taking advantage of per-component modules (ex. `import { ButtonModule } from "carbon-components-angular/button";`) and lazy-loading.

50mb is excessive though, even with `@carbon/icons-angular` I've never seen a production app with a bundle that large, definitely share some info from `source-map-explorer`/`webpack-bundle-analyzer` (howto: https://stackoverflow.com/questions/46567781/angular-cli-output-how-to-analyze-bundle-files)

**Comment by cal-smith** [comment]
Given that there has been no further information provided in the 15 days this has been open I'm going to assume it has been resolved.
