### ISSUE TITLE
Carbon table component issue with the header checkbox

### ISSUE THREAD

**Issue by Hiromiakita** [IBM/carbon-components-angular#1728]
## Detailed description

> Describe in detail the issue you’re having.
Carbon table component issue with the header checkbox. After  selecting one checkbox on the table, clicking on the header checkbox will mark as if it was selecting every item on the table without actually doing it.
> Is this a feature request (new component, new icon), a bug, or a general issue?
General Issue
> Is this issue related to a specific component?
Table Component (https://angular.carbondesignsystem.com/?path=/story/components-table--basic)
> What did you expect to happen? What happened instead? What would you like to see changed?
Two possible outcomes, the checkbox on the header would remain empty or it would select every Item on the table.
> What browser are you working in?
Version Chrome 88.0.4324.146 (Official Build) (x86_64)
> What version of the Carbon Design System are you using?
4.40
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
HRBD IQ

## Steps to reproduce the issue

1. Go to https://angular.carbondesignsystem.com/?path=/story/components-table--basic
2. On the table template select one checkbox (not header)
3. On the table template select header checkbox

## Additional information

* Screenshots or code

https://user-images.githubusercontent.com/36249782/107539010-2b3cdd00-6b8a-11eb-8af6-ef7ccbd21d64.mov

**Comment by zvonimirfras** [comment]
Clicking the header checkmark correctly deselects everything in the table.
It should also deselect the header checkmark, which it doesn't at the moment.
