### ISSUE TITLE
Combo-box issue not getting all the entries 

### ISSUE THREAD

**Issue by mattsai** [IBM/carbon-components-angular#1733]
I have 2 combo-boxes of dates.
List_date_a and List_date_b, date_a cannot pass date_b so What I do Just returned the old value and re-build the list (map function), I console log the content of the list and it shows me all the items, but only shows one.
![image](https://user-images.githubusercontent.com/63029294/108134535-f940e480-707b-11eb-80ae-7e236512e24c.png)
![image](https://user-images.githubusercontent.com/63029294/108134822-808e5800-707c-11eb-9e7c-2b881e67b75d.png)

Also with one item, I have only one item and if it's just one item I want to select by default it selects it but doesn't show it 
![image](https://user-images.githubusercontent.com/63029294/108134733-5ccb1200-707c-11eb-9178-feedb1af8835.png)

**Comment by zvonimirfras** [comment]
The issue here seems to be that filtering (typing into the box) removes entries from the visible list. That might have been the old behavior. Reference implementation now just jumps to the first matching reference.

**Comment by mattsai** [comment]
I see, so there's a way to solve it?
I mean I have this method
```
if (!valueIO) {
      this.startDateValue = this.oldValueDateStart; // returning his old value
      this.dateStart = this.rebuiltArray(this.dateStart,this.startDateValue); //rebuilt array (an array, the value to be selected =true)
      this.activeDS='error'; //error inline loading -> not valid
    } else {
      this.activeDS='hidden';
      this.oldValueDateStart = this.startDateValue; // updating old value
      this.startDateValue = value;
      this.dateUpdate = this.startDateValue + "-" + this.endDateValue;
      this.flagDateRange = true; // method date range will be executed
    }
```
also just change to ngModel combobox... and yes, returns all the entries but doesn't change 
in th eline
 this.startDateValue = this.oldValueDateStart; // returning his old value 
if I console log their value is the old previous value, but in the combobox show the selected date

**Comment by zvonimirfras** [comment]
If you take a look at the [current demo](https://angular.carbondesignsystem.com/?path=/story/components-combobox--basic), you'll notice that if you don't explicitly set the text of the combobox, clicking the chevron shows all the values. Explicitly setting the text starts filtering.

My comment was to provide a bit of info for whoever works on this because filtering seems to have changed in the reference implementation.

Current 'workaround' for you would be: don't explicitly set the text in combobox search field. That's something user can do if they wish but you don't really need to programmatically.

**Comment by fionamurphy** [comment]
I have also ran into this issue when updating the items for a combobox whose items are dependant on the value of another combobox. This is using reactive forms.  Any workaround for  this? 🙏 

Reproducable by modifying the [Combobox reactive forms demo](https://angular.carbondesignsystem.com/?path=/story/components-combobox--with-reactive-forms) to the below:

`@Component({
	selector: "app-reactive-combobox",
	template: `
		<form [formGroup]="sampleForm" (ngSubmit)="onSubmit(sampleForm)">
			<ibm-combo-box
				formControlName="combobox"
				[size]="size"
				[label]="label"
				[helperText]="helperText"
				itemValueKey="content"
				[theme]="theme"
				[items]="items">
				<ibm-dropdown-list></ibm-dropdown-list>
			</ibm-combo-box>
			selected: {{ sampleForm.get("combobox").value | json }}
			<ibm-combo-box
				style="margin-top: 40px"
				formControlName="multibox"
				[label]="label"
				[size]="size"
				itemValueKey="content"
				[helperText]="helperText"
				type="multi"
				[items]="items">
				<ibm-dropdown-list></ibm-dropdown-list>
			</ibm-combo-box>
			selected: {{ sampleForm.get("multibox").value | json }}
		</form>
	`
})
class ReactiveFormsCombobox implements OnInit {
	public sampleForm: FormGroup;
	items = [
		{
			content: "one"
		},
		{
			content: "two"
		},
		{
			content: "three"
		},
		{
			content: "four"
		}
	];
	@Input() label = "";
	@Input() helperText = "";
	@Input() size = "md";
	@Input() theme = "dark";

	constructor(private fb: FormBuilder) {}

	ngOnInit() {
		this.sampleForm = this.fb.group({
			combobox: new FormControl,
			multibox: new FormControl
		});

		this.sampleForm.get("combobox").setValue("four");
		this.sampleForm.get("multibox").setValue(["four", "two"]);
		setTimeout(() =>
			this.items = [
			{
				content: "one"
			},
			{
				content: "two"
			},
			{
				content: "three"
			},
			{
				content: "four"
			},
			{
				content: "five"
			}
		], 100)
	}
}`

<img width="492" alt="Screenshot 2021-06-17 at 21 57 31" src="https://user-images.githubusercontent.com/46631345/122471343-126c8a00-cfb7-11eb-9c42-55e145218a33.png">
