### ISSUE TITLE
Pagination current page dropdown misaligned

### ISSUE THREAD

**Issue by yobvicky** [IBM/carbon-components-angular#1734]
## Detailed description

> Current page dropdown carat svg appears outside the drop down

> Is this a feature request (new component, new icon), a bug, or a general issue? - Bug

> Is this issue related to a specific component? - Pagination

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using? - 4.40.0

## Steps to reproduce the issue
1. https://angular.carbondesignsystem.com/?path=/story/components-pagination--basic
2. Hover over the current page dropdown
3. Click on the carat drop down icon

Actual result - It has no action. It works only when clicking the number

![image](https://user-images.githubusercontent.com/18388533/108210320-64a8b600-7151-11eb-8684-077e5c52d6a3.png)

**Comment by Michael-Baylis** [comment]
We are seing this in the Galasa project as well,  same on Firefox, Chrome and Safari.
