### ISSUE TITLE
Tabs styles not applied

### ISSUE THREAD

**Issue by yobvicky** [IBM/carbon-components-angular#1763]
Tabs component is not working in the latest version. Styles are not applied and looks broken

## Detailed description

> Is this a feature request (new component, new icon), a bug, or a general issue? - Bug

> Is this issue related to a specific component? Yes

> What version of the Carbon Design System are you using?
"@carbon/icons-angular": "^11.2.1",
    "carbon-components": "^10.30.0",
    "carbon-components-angular": "^4.44.0"

## Steps to reproduce the issue

sample code
`<ibm-tabs>
  <ibm-tab heading="one">Tab Content 1</ibm-tab>
  <ibm-tab heading="two">Tab Content 2</ibm-tab>
  <ibm-tab heading="three">Tab Content 3</ibm-tab>
  <ibm-tab heading="four" disabled="true">Tab Content 4</ibm-tab>
</ibm-tabs> `
## Additional information

* Screenshots or code
*
![image](https://user-images.githubusercontent.com/18388533/111667350-9f7a3880-883a-11eb-9e56-3816a2eb928d.png)

* Notes

**Comment by zvonimirfras** [comment]
It looks fine in [the demo](https://angular.carbondesignsystem.com/?path=/story/components-tabs--basic).

I just tested latest (4.44.0) carbon-components-angular with latest (10.30.0) carbon-components and it looks as expected.

Guessing from your screenshot, it looks like you might have not imported the styles in your app.

Given all that, I'll close the issue.

If you can replicate it [using code sandbox](https://codesandbox.io/s/carbon-components-angular-0129r494ql) or some other way that would allows us to poke around, please reopen this issue.
