### ISSUE TITLE
ibm-select doesn't follow ngModel

### ISSUE THREAD

**Issue by kuroyuki** [IBM/carbon-components-angular#1776]
## Detailed description

> Describe in detail the issue you're having.

Using ngModel to initialise selected option for ibm-select doesn't update the component.
I see the issue has been reported previously and marked as resolved 
for example, https://github.com/IBM/carbon-components-angular/issues/1536

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
ibm-select

> What did you expect to happen? What happened instead? What would you like to see changed?
change selected option programatically

> What browser are you working in?
latest Chrome/Safari

> What version of the Carbon Design System are you using?
 "carbon-components": "^10.31.0",
    "carbon-components-angular": "^4.46.0",

## Steps to reproduce the issue
```
<div style="width: 165px;">
  <ibm-select [(ngModel)]="selected">
    <option value="option1">Option 1</option>
    <option value="option2">Option 2</option>
    <option value="option3">Option 3</option>
  </ibm-select>
  <br />
  <span>Selected: {{ selected }}</span>
</div>
```

Sandbox https://codesandbox.io/s/carbon-components-angular-forked-0y7q2?file=/src/app/app.component.html:0-275
<img width="205" alt="image" src="https://user-images.githubusercontent.com/1229090/113155410-a98c3600-9241-11eb-9d4f-59f21fc93ef3.png">

**Comment by maksym-plotnikov** [comment]
There's also issue with reactive forms with last versions of Angular Carbon - form control value doesn't mapped to select and also we had strange error inside `updateValidityTree` angular forms method but currently it's kind of random bug. 
When we'll have all steps to reproduce - we will open an issue.

**Comment by maksym-plotnikov** [comment]
Same with Reactive forms :) We already have a ticket for that!

**Comment by maksym-plotnikov** [comment]
https://github.com/IBM/carbon-components-angular/issues/1798

**Comment by Donisius** [comment]
@kuroyuki  @maksym-plotnikov  sorry for the delay and thank you for creating the sandbox, it seems like `@ViewChild`  was not getting the right reference for the select element only in a prod build. I'll open a PR soon to fix this.

**Comment by maksym-plotnikov** [comment]
@Donisius much appreciated for a quick turnaround!
