### ISSUE TITLE
HTML 'title=""' attribute does not work with Carbon's TableHeaderItem

### ISSUE THREAD

**Issue by jhoose** [IBM/carbon-components-angular#1780]
## Detailed description

I am an IBMer, I encourage you to contact me via IBM slack @jhoose (I do **_not_** check my personal GitHub often).

Our application has a very large table with country initials has column headers, due to space restrictions and the amount of data on the table we want to leave the table columns headers as country initials to save space. That said, to help the users that might not know country initials we wanted to add the countries full name to the table's header title attribute, for example, Carbon table header would be "AE" then the user hovers over the table header column "AE" and the country full name appears as "United Arab Emirates", just like HTML's built-in title attribute: `<th title="United Arab Emirates">AE</th>`. I was looking in the Carbon documentation and found some information that you can just do `new TableHeaderItem({data: "AE", title: "United Arab Emirates", style: { some CSS styling if needed} }),` but that did not work. I could see on the dev tools that the rendered html tag did indeed have title="United Arab Emirates" but when table header "AE" was moused over only "AE" showed up in the browsers default tooltip when it should've been "United Arab Emirates". I tried other variations to no avail. I was hoping **_not_** to use a Carbon tooltip component or some dynamic javascript since our code is already complex and the angular component.ts file is already very large, and I did **_not_** find any documentation on how to add a carbon tooltip directly to a carbon new TableHeaderItem.

Please see this IBM slack thread for more details:
https://ibm-cio.slack.com/archives/CBZC0LM2N/p1616693051136500

What browser are you working in?
Google Chrome
Version 89.0.4389.90 (Official Build) (x86_64)

What version of the Carbon Design System are you using?
I recently moved our carbon-angular application from Carbon 3 to Carbon 4 although this issue happens in **_both_** Carbon versions.

Here is the package.json versions before upgrade:
"dependencies": { "dependencies": { "@angular-devkit/build-angular": "~0.10.7", "@angular/animations": "^7.2.16", "@angular/common": "^7.2.16", "@angular/compiler": "^7.2.16", "@angular/core": "^7.2.16", "@angular/forms": "^7.2.16", "@angular/http": "^7.2.16", "@angular/platform-browser": "^7.2.16", "@angular/platform-browser-dynamic": "^7.2.16", "@angular/router": "^7.2.16", "@carbon/icons-angular": "^10.8.2", "@carbon/themes": "^10.11.2", "bootstrap": "^3.3.7", "carbon-components": "10.11.2", "carbon-components-angular": "^3.49.7",

Here is the package.json versions after upgrade:
"dependencies": { "@angular-devkit/build-angular": "~0.901.15", "@angular/animations": "^9.1.13", "@angular/common": "^9.1.13", "@angular/compiler": "^9.1.13", "@angular/core": "^9.1.13", "@angular/forms": "^9.1.13", "@angular/platform-browser": "^9.1.13", "@angular/platform-browser-dynamic": "^9.1.13", "@angular/platform-server": "^9.1.13", "@angular/router": "^9.1.13", "@carbon/icons-angular": "^11.2.1", "@carbon/themes": "^10.11.2", "bootstrap": "^3.3.7", "carbon-components": "^10.30.0", "carbon-components-angular": "^4.40.0",

**Comment by zvonimirfras** [comment]
Ah, so, yes... `TableHeaderItem` doesn't have the `title`. `TableItem` does. We should add that and make sure it's used in the template like the one in `TableItem` is.
