### ISSUE TITLE
Accessibility keyboard tabbing within <ibm-table>

### ISSUE THREAD

**Issue by sumanapp** [IBM/carbon-components-angular#1810]
While, using the tab keystroke to navigate my application, when an ibm-table component is tabbed over the keyboard navigation control does not drill down into the table's rows. The control reaches the table header and then switches to the table footer avoiding the rows.

Is there a way to navigate through the table rows ( such that a specific row can then be selected by a (keyup.enter) event).

Thanks

**Comment by ninja511** [comment]
see suggestions here: https://github.com/IBM/carbon-components-angular/discussions/1831
