### ISSUE TITLE
How to give a component a different theme.

### ISSUE THREAD

**Issue by veighnsche** [IBM/carbon-components-angular#1869]
I hope that I have made myself understandable.

My current theme

```
@import '~carbon-components/scss/globals/scss/theme';

// Use the gray 10 theme
$carbon--theme: $carbon--theme--g10;
@include carbon--theme();
```

But now I want to use `<ibm-tabs>` in theme g100.

Is this in any way possible?

**Comment by omar-zahid** [comment]
Its possible.
In your tabs stylesheet, add the following:

``` scss
.dark-tabs{
@include carbon--theme($carbon--theme--g100) {
    @include tabs;
   }
}
```

**Comment by veighnsche** [comment]
Thank you @omar-zahid!

Only, I'm greeted with an error: "SassError: Undefined mixin." on @include tabs;

Which mixin must I import?

**Comment by omar-zahid** [comment]
@veighnsche 
``` scss
@import '~carbon-components/scss/components/tabs/tabs';
```

**Comment by Donisius** [comment]
Thanks for addressing this @omar-zahid!
