### ISSUE TITLE
Legends in Carbon Chart 

### ISSUE THREAD

**Issue by akshay27395** [IBM/carbon-components-angular#1870]
Hi,
 I m new to Carbon Design System and using "@carbon/charts-angular": "^0.41.76" in my project to display charts in a page.
I m finding difficulty in removing ellipses in the legend and some addition component of expand and import is shown which is not required in my code .
So can anyone help me with this to solve as early as possible . Its on priority for mi.
Thanks in advance and an earliest help will be appreciable from IBM Carbon Team

Code of the line graph :
`   <ibm-line-chart [data]="liquidityTrendGraph" [options]="options1"></ibm-line-chart>`

<img width="715" alt="Screenshot 2021-07-22 at 1 31 07 PM" src="https://user-images.githubusercontent.com/35006691/126607920-8d4c7244-9bf8-47df-b7fa-0ee82916c804.png">

**Comment by Donisius** [comment]
Hi @akshay27395, this seems to be a question for `carbon-charts`. You can open an issue [here](https://github.com/carbon-design-system/carbon-charts/issues/new).
