### ISSUE TITLE
Paginaton Nav component doesn't fire page select output on Chromium based browsers

### ISSUE THREAD

**Issue by omar-zahid** [IBM/carbon-components-angular#1871]
## Detailed description

> Selecting a page from the dropdown does not fire and output

## Steps to reproduce the issue

https://angular.carbondesignsystem.com/?path=/story/components-paginationnav--basic

1. Load the app in Chromium based browsers such as Google Chrome
2. Select the ... dropdown and click on the page number
3. Monitor the console for logs. No event gets fired in Chrome
## Additional information

![image](https://user-images.githubusercontent.com/57479337/126891349-a83d576a-e582-4b25-a39a-cb6f85514a42.png)

**Comment by omar-zahid** [comment]
@zvonimirfras Can you help take a look at this issue.

**Comment by sksiyer** [comment]
Hi 👋🏼 , I'd like to take a shot at this issue

**Comment by zvonimirfras** [comment]
> Hi 👋🏼 , I'd like to take a shot at this issue

Good luck and have fun!

**Comment by cduran** [comment]
Hi forgot to search for issue first but I reported this same bug here #1923.  And I did a fix for it #1924
