### ISSUE TITLE
The pristine status of ibm-dropdown sets to false by default.

### ISSUE THREAD

**Issue by dinpatna** [IBM/carbon-components-angular#1882]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue? 
> bug

> Is this issue related to a specific component?
> ibm-dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?
> When a ibm-dropdown is created by ngIf the default value of form control pristine is set to false. It is expected to be true. The default pristine value when user hasn't touched the dropdown should always be true.

> What browser are you working in?
> Firefox, Chrome and Safari.

> What version of the Carbon Design System are you using?
> "carbon-components": "^10.41.0",
> "carbon-components-angular": "^4.54.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
> This is a part of IBM App Services Portal. This is a critical issue which is blocking the Carbon Upgrade and the release date is August 16th.

## Steps to reproduce the issue
> Here is the link to the sample codesandbox code trying to reproduce the issue.

[Codesandbox](<https://codesandbox.io/s/carbon-components-angular-forked-dwkte?file=/src/app/app.component.ts>)

[Codesandbox URL](<https://dwkte.csb.app/>)

1. Open the url https://dwkte.csb.app/
2. Open the browser console for checking console logs
3. By default we will be in Page with Android Platform as selected. It has one input field (Text Input Field 2). The pristine value is printed as true which is correct. 
4. Now click on iOS platform button, now it adds 2 new fields out of which one is dropdown. 
5. Check the console logs where the form value is printed. We can see that the pristine value for dropdown is set to false, whereas the pristine value of text fields is true. (Attached Screenshot for reference)
6. Expected that the pristine of dropdowns should be true as well. 

## Additional information

* Screenshots 
<img width="1338" alt="Screenshot 2021-08-11 at 6 19 03 PM" src="https://user-images.githubusercontent.com/9131033/129031535-05e76b08-3dfb-4a97-bce0-a0b66a397ef3.png">

**Comment by cal-smith** [comment]
This was super helpful! Thanks @dinpatna!
