### ISSUE TITLE
SVG of the ibm-file-uploader missing the tabindex attribute 

### ISSUE THREAD

**Issue by GSSCDylan** [IBM/carbon-components-angular#1897]
## Detailed description

> SVG of the ibm-file-uploader missing the tabindex attribute 

> Is this a feature request (new component, new icon), a bug, or a general issue?  
issue

> Is this issue related to a specific component?  
 ibm-file-uploader

> What did you expect to happen? What happened instead? What would you like to see changed?
  The svg of the uploader should have a tabindex attribute,such as tabindex="0". then the close icon can get focus via keyboard
> What browser are you working in?
FireFox
> What version of the Carbon Design System are you using?
    "carbon-components": "10.31.0",
    "carbon-components-angular": "4.54.2",

## Additional information

* Screenshots or code

<img width="942" alt="missing tabindex " src="https://user-images.githubusercontent.com/73825731/131486324-276dacc3-8d8a-49fd-b686-d8f860dba99a.png">

If I manually add the tabindex from developer tools of Firefox, it will work  well
<img width="985" alt="add tabindex " src="https://user-images.githubusercontent.com/73825731/131486444-7e8db3ab-c0ab-430a-a620-cea851fe550c.png">

* Notes

**Comment by GSSCDylan** [comment]
@Santalov @cal-smith

**Comment by ninja511** [comment]
FYI @cal-smith has left IBM

**Comment by zvonimirfras** [comment]
@GSSCDylan sounds like you already have a fix for this. Do you mind contributing it? 🙂

**Comment by GSSCDylan** [comment]
Hi @zvonimirfras ,I've submit a PR https://github.com/IBM/carbon-components-angular/pull/1901 for the fix.
