### ISSUE TITLE
dropdown style broken

### ISSUE THREAD

**Issue by grenobnik** [IBM/carbon-components-angular#1900]
Chevron-down icon is over sized in <ibm-dropdown> component in recent versions, see the official [storybook](https://angular.carbondesignsystem.com/?path=/story/components-dropdown--basic) and compare with [ibm-combo-box](https://angular.carbondesignsystem.com/?path=/story/components-combobox--basic)

![dropdown-ko](https://user-images.githubusercontent.com/6929951/132018406-0826a209-ff41-4490-b858-5e5ade0debec.png)

The generic style specification is [here](https://www.carbondesignsystem.com/components/dropdown/code)

![dropdown-ok](https://user-images.githubusercontent.com/6929951/132018690-348c88fd-980b-4fb8-81e6-cb468fd82f31.png)

The problem seems to be coming from  `class="bx--list-box__menu-icon"` that is applied inside `<svg>`, while it should outside.

![dropdown-broken-style](https://user-images.githubusercontent.com/6929951/132018460-0cb8bef3-c194-4c78-9417-301fb8a44cb5.png)

As it is done in  `<ibm-combo-box>` component.

![combobox](https://user-images.githubusercontent.com/6929951/132018496-20f552a1-bc29-4ac5-af67-54881a07f062.png)

**Comment by zvonimirfras** [comment]
Hi @grenobnik! Looks like you already have a good grasp of the problem and how to fix it.

Wanna contribute it?
