### ISSUE TITLE
Update documentation demo links

### ISSUE THREAD

**Issue by zvonimirfras** [IBM/carbon-components-angular#1902]
Our documentation comments have "See demo" links that link to stories page.

Stories now have "Components" and "Patterns" sections, which changed the `path` part of the URL.

Update the `path` part and test the links.

e.g.

```
[See demo](../../?path=/story/table--basic)
```

should be

```
[See demo](../../?path=/story/components-table--basic)
```

**Comment by adinhtdsibm** [comment]
@zvonimirfras Can you assign me this issue? I will update the link.

**Comment by thanh-lam** [comment]
I'm interested in contributing as well. Maybe there'll be more than one issue to go around? A list of suggesting steps for starters would be helpful. For example:
* Check out the code (example command...)
* Make the changes or fixes and test them
* Check in the code or commit
* ...
Thanks!

**Comment by zvonimirfras** [comment]
That's awesome, @thanh-lam! 

There are plenty of [other issues](https://github.com/IBM/carbon-components-angular/issues) waiting. 😃

**Comment by adinhtdsibm** [comment]
@zvonimirfras Created PR #1906 for this issue. Please validate.
