### ISSUE TITLE
Modal's closeModal that calls ModalService.prototype.destory gives error in IE11

### ISSUE THREAD

**Issue by jdcai** [IBM/carbon-components-angular#191]
## Detailed description

> Describe in detail the issue you're having.

On IE11 when I try to close a modal it will call closeModal() which calls ModalService.prototype.destory
and I get an error "Object doesn't support property or method 'focus'"
on line `this.placeholder.componentRefs[index]["previouslyFocusedElement"].focus();  // return focus`

![image](https://user-images.githubusercontent.com/4312305/47243117-150a2200-d3bf-11e8-8c21-dd8aa8f70330.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Modal Service/Component

> What browser are you working in?

IE 11

## Steps to reproduce the issue

Open modal in IE 11
Click on X to close the modal
IE11 debugger will give  "Object doesn't support property or method 'focus'" error

**Comment by cal-smith** [comment]
this may be fixed by #203 ... we may also have to just add a check for `.focus`. I'll do some more testing locally 👍

**Comment by cal-smith** [comment]
Yep I can't seem to repro this in the storybook with the changes from #203 (plus a polyfill for `Element.matches`) ... How are you triggering the modal?

We may have to wait for 2.0 to be released before we can adequately test this though 😕

**Comment by jdcai** [comment]
I updated my carbon components angular and i'm not seeing the error anymore.
So maybe it did get fixed in #203

**Comment by cal-smith** [comment]
Hm, #203 isn't merged yet ... it's possible something else fixed it though! Good news either way, I'll close this now then 👍
