### ISSUE TITLE
Sort arrows are centered instead of next to header text in IE11

### ISSUE THREAD

**Issue by jdcai** [IBM/carbon-components-angular#192]
## Detailed description

> Describe in detail the issue you're having.

Sort arrows are centered in the header instead of being next to the header text
![image](https://user-images.githubusercontent.com/4312305/47243526-4f27f380-d3c0-11e8-87c8-24a5224d8b4b.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Table component

> What did you expect to happen? What happened instead? What would you like to see changed?

The sort arrow should be next to the header text instead of in the middle of the header column

> What browser are you working in?

IE 11

**Comment by zvonimirfras** [comment]
This looks like a css issue. Some css issues can't be fixed for older browsers in cases when browser don't support certain features.

Do you get the same result on vanilla and react?

If yes, please open an issue in carbon-components library.

**Comment by jdcai** [comment]
Yeah, if I open carbon design's data table page I also see the sort arrows being centered.
I'll open an issue with them.
