### ISSUE TITLE
DAP Potential Violation on Table component

### ISSUE THREAD

**Issue by johnharan** [IBM/carbon-components-angular#193]
> Describe in detail the issue you're having.
There is a DAP 'Potential violation' showing for the Table component.

> What browser are you working in?
Chrome Version 70.0.3538.67
> What version of the Carbon Design System are you using?
9.32.1
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Watson Recruitment

## Additional information

* Screenshots or code
![tablepv](https://user-images.githubusercontent.com/8806230/47295822-8557b400-d608-11e8-9ac6-b564c3e641eb.png)

**Comment by zvonimirfras** [comment]
Not a violation.

**Comment by johnharan** [comment]
@zvonimirfras Hi, for accessibility testing our team is annotating our DAP scan reports to include info on why any violation/potential-violation may be ignored - to assist with this, can you expand on why this is classed as 'not a violation'?
