### ISSUE TITLE
File Uploader calls filesChange twice

### ISSUE THREAD

**Issue by mattia85** [IBM/carbon-components-angular#1939]
Hello,
I'm using the file uploader inside an ibm modal, this is the file uploader configuration:
```
<ibm-file-uploader [accept]="acceptedFileExtensions"
    [multiple]="false"
    [(files)]="files"
    drop="true"
    dropText="Drag and drop files here or upload"
    (filesChange)="onDropped($event)">
</ibm-file-uploader>
```
The problem is that the **onDropped** method is called twice when selecting a second file (multiple=false).

Those are the steps to reproduce the issue:
1. select a file a confirm
2. without removing the first files, select a second file and confirm
3. the **filesChange** cb is called twice 

Try this on https://codesandbox.io/s/carbon-components-angular-forked-gvovo

It seems that the issue starts calling clear method
https://github.com/IBM/carbon-components-angular/blob/c29d2a6126ac8d7f171bd6c4c87333327dfd871d/src/file-uploader/file-uploader.component.ts#L216

Let me know if you need more details.

Mattia

**Comment by mattia85** [comment]
Is there an update?

**Comment by Donisius** [comment]
@mattia85 Sorry for the delay! Taking a look at this right now, thanks for providing an example!
