### ISSUE TITLE
[Feature Request] Can editing in the data table be supported?

### ISSUE THREAD

**Issue by haozhelee** [IBM/carbon-components-angular#1940]
Can there be input or drop-down boxes in the cell? I have not seen any relevant examples.

Like this
![image](https://user-images.githubusercontent.com/26142398/145513778-219b8bdc-2791-4c87-bf7d-9c3186e0ee10.png)

### Detailed description.
carbon-components: 10.48.0
carbon-components-angular: 4.55.5

**Comment by Akshat55** [comment]
This is something you can implement using templates. Have a look at the following example which uses a template to create column with links:

https://github.com/IBM/carbon-components-angular/blob/master/src/table/stories/app-pagination-table.component.ts

You would use a similar approach, but you would add form elements to it.
