### ISSUE TITLE
Combobox is making reactive form dirty

### ISSUE THREAD

**Issue by Licen-it** [IBM/carbon-components-angular#1943]
## Detailed description

> Describe in detail the issue you're having.

When combobox is used in a reactive form and the form set the initial value, the component is marking the form dirty

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Combobox

> What did you expect to happen? What happened instead? What would you like to see changed?

When the reactive form set the value the combobox shouldn't emit a value changed event which is what is causing the issue

> What browser are you working in?

any

> What version of the Carbon Design System are you using?

latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

n/a

## Steps to reproduce the issue

1. Add combobox in a reactive form
2. set a value to the form control associated with the combobox
3. form is now dirty

**Comment by srikanthbhamidipalli** [comment]
@Licen-it  it is happening with dropdown as well.

**Comment by Licen-it** [comment]
> @Licen-it this is happening with dropdown as well.

I don't know what version you are referring to, but dropdown isn't causing this issue in latest version

**Comment by srikanthbhamidipalli** [comment]
correct, it's not happening in latest version.
Thanks @Licen-it
