### ISSUE TITLE
Support Angular 13

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#1947]
## Detailed description

> Describe in detail the issue you're having.

Enable support for Angular 13 - we've already migrated to use Angular 13 in our application and so far haven't seen any issues.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by zvonimirfras** [comment]
Closed by #1948 🥳

**Comment by stanislavgeorgiev** [comment]
Awesome! Thank you @Donisius and @zvonimirfras 

https://github.com/IBM/carbon-components-angular/pull/1948/files#diff-afc80420296b2cd15c79b96f9cb5d50c2580b2e50b84433971f81e75fe9367e7R28

There's an `ng12` folder name that sneaked in
