### ISSUE TITLE
Radio: Radio not behaving correctly

### ISSUE THREAD

**Issue by cduran** [IBM/carbon-components-angular#1986]
## Detailed description

Radio should behave as standard radios behave. If we select one it should stay selected even if click on it again.
[Components | Radio](<https://angular.carbondesignsystem.com/?path=/story/components-radio--basic>) 

1. Just click on one that's already selected or select a new one and click on it, see the selection disappear 

Video showing the issue 

https://user-images.githubusercontent.com/164527/153419398-b19a15a8-bca8-4abd-a7a6-a40dea51868d.mov

**Comment by Licen-it** [comment]
I spotted the same issue and I have a solution almost ready. Will create soon a PR linking this issue.
