### ISSUE TITLE
role="menuitem" should be in <li> element for ibm-header

### ISSUE THREAD

**Issue by GSSCDylan** [IBM/carbon-components-angular#2002]
> Is this issue related to a specific component?
**header**
> What browser are you working in?
 **Firefox 92.0.1 (64-bit)**
> What version of the Carbon Design System are you using?
**"carbon-components": "10.31.0",
"carbon-components-angular": "4.46.0"**

## Steps to reproduce the issue

1.     Open a panel that contains ibm-header component
2.     Run Accessibility Assessment

## Additional information

* Screenshots or code
<img width="1706" alt="menu1" src="https://user-images.githubusercontent.com/73825731/153794946-62fb1437-807e-4351-aee2-9a040a13601e.png">
<img width="1294" alt="menu2" src="https://user-images.githubusercontent.com/73825731/153794960-665f2b35-0aa6-41c3-a25e-4c806d9f8dee.png">

* Notes

**Comment by Akshat55** [comment]
Closing issue, since issue has been addressed.
