### ISSUE TITLE
Tabs: Select tab on click on the entire tab, not just the text

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#201]
## Detailed description

> Describe in detail the issue you're having.

Currently you have to click on the text stroke of each tab to activate them which very often leads to clicking on a tab doesn't activate it. It's not even just the text box, you have to click on place where there's a letter beneath or the click won't register. 

I think the entire tab header should be clickable including the padding.

**Comment by cal-smith** [comment]
Agreed, this should be as easy as moving the `(click)` binding higher up in the `ibm-tab-headers` list
