### ISSUE TITLE
Overflow Menu: Hover state doesn't take the full width of the item

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#205]
## Detailed description

> Describe in detail the issue you're having.

Overflow menu items with shorter text have shorter hover background:
![image](https://user-images.githubusercontent.com/1253469/47472036-0d8db300-d7db-11e8-8710-d92d4bf36d35.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Overflow Menu

> What did you expect to happen? What happened instead? What would you like to see changed?

Elements with shorter text to show like this:
![image](https://user-images.githubusercontent.com/1253469/47471997-e9ca6d00-d7da-11e8-9772-a2d959c5dc91.png)

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

9.23.0

**Comment by zvonimirfras** [comment]
Looking at the [storybook](https://angular.carbondesignsystem.com/?selectedKind=Overflow%20Menu), it appears fine... How do you reproduce it ([there](https://angular.carbondesignsystem.com/?selectedKind=Overflow%20Menu))?

**Comment by cal-smith** [comment]
Is this still an issue? If so is there a minimal reproduction we could look at?

**Comment by stanislavgeorgiev** [comment]
Closing this issue since I finally found a style on our side that's redefining something on the overflow menu. Sorry for bugging you on this

**Comment by cal-smith** [comment]
No worries! glad you got it sorted out
