### ISSUE TITLE
`appendToBody` should default to `true`

### ISSUE THREAD

**Issue by zvonimirfras** [IBM/carbon-components-angular#211]
... for 2.0

maybe even change name to something else since it's technically appending to placeholder (preferably). Maybe even inverse the logic and have an `appendAfterElement` which we'd then default to `false`.

**Comment by cal-smith** [comment]
Maybe `appendInline`? or `showInline`? Either way agreed ... I think we should swap the defaults around and add a setter to `appendToBody` that notes it as deprecated.

**Comment by zvonimirfras** [comment]
Do you want to make this part of the "one placeholder to rule them all" PR? It's kinda sorta related.

**Comment by zvonimirfras** [comment]
It's done. Available from 2.0
