### ISSUE TITLE
Bug in documentation : The link to W3 develop seems to be no longer good in the documentation.

### ISSUE THREAD

**Issue by timothyalcaide** [IBM/carbon-components-angular#2113]
## Detailed description

The link to W3 develop seems to be no longer good in the documentation.

What is the correct link ?

## Steps to reproduce the issue

1. Go to https://github.com/IBM/carbon-components-angular#contributing
2. Click to W3 develop link (https://w3.ibm.com/developer/docs/open-source/contributing/)

**Comment by Akshat55** [comment]
Closing issue since W3 develop link is working again, you will have to connect to the VPN to access it.
