### ISSUE TITLE
The <ibm-checkbox> component doesn't need to have aria attributes

### ISSUE THREAD

**Issue by zmariaalice** [IBM/carbon-components-angular#2156]
## Detailed description

> Describe in detail the issue you're having.

I’m using the IBM Accessibility Checker tool, and in the table component the tool reported that the input tag could not have an aria-checked attribute

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

`<ibm-checkbox>`

> What did you expect to happen? What happened instead? What would you like to see changed?

Remove the aria attributes from <ibm-checkbox>

> What browser are you working in?

   Google Chrome

> What version of the Carbon Design System are you using?

"carbon-components": "^10.53.0",
"carbon-components-angular": "^4.57.8"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

end of June

## Steps to reproduce the issue
Run the IBM Accessibility Checker tool on component

## Additional information

* Screenshots or code

<img width="808" alt="Screen Shot 2022-06-08 at 14 46 58" src="https://user-images.githubusercontent.com/40126035/173835691-1399dcdc-21f9-47e0-b784-e883384ddc5a.png">
<img width="1123" alt="Screen Shot 2022-06-08 at 14 47 30" src="https://user-images.githubusercontent.com/40126035/173835771-12fd07c7-0cfa-4e85-8495-353c976cb4b1.png">

* Notes
[https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked)

**Comment by maicongodinho** [comment]
On it.
