### ISSUE TITLE
Importing styles greatly increases the size of the bundle

### ISSUE THREAD

**Issue by dkhrunov** [IBM/carbon-components-angular#2159]
## Detailed description
After adding `@import "~carbon-components/scss/globals/scss/styles";` to my styles, the size of the final bundle increased significantly. This is fine?

Size of the bundle with import styles:
![image](https://user-images.githubusercontent.com/25565058/174897590-31e28156-fbf6-441b-8439-d626450a8513.png)

Size of the bundle without this styles:
![image](https://user-images.githubusercontent.com/25565058/174897357-bc93af45-3114-4e4a-88ca-f795f7c935a8.png)

**Comment by Akshat55** [comment]
This is expected, you're importing all of the styles even the ones that are not used. You can import styles for specific components that you are using, but that will require maintenance and may cause issues with some components. Carbon V11 fixes this I believe, but support for V11 hasn't been added yet.

**Comment by dkhrunov** [comment]
Thank you @Akshat55 !
