### ISSUE TITLE
Pagination Table wrapper

### ISSUE THREAD

**Issue by danny-ibm** [IBM/carbon-components-angular#216]
Hey Carbon team, 

I am currently on a client project implementing a design for a client.

![image](https://user-images.githubusercontent.com/42442504/47658217-f9460f00-db68-11e8-91a6-d5dc43809a83.png)

I've had no success getting the `pagination` wrapper working. The docs for this aren't too clear but I found some good comments within the specific module.ts files + stories.ts files for table. 

I've been able to generate just the table but how do you add a dataLink between a row on the table for a custom link? Bear with me as I am new to ts + angular...

**Comment by zvonimirfras** [comment]
https://angular.carbondesignsystem.com/documentation/components/Table.html#customization explains how to use custom templates in tables.

[This](https://blog.angular-university.io/angular-ng-template-ng-container-ngtemplateoutlet/) and [this](https://angular.io/guide/structural-directives) will tell you more about templates from angular perspective.

You would normally add pagination component after the table component (it's not a wrapper) and give it the same model you're feeding the table. Then tie into the `selectPage` emitter.

More info here: https://angular.carbondesignsystem.com/documentation/components/Pagination.html


What would you change to make the docs clearer to you?

**Comment by danny-ibm** [comment]
thanks for the quick response! Wow I didn't see this doc link.. Sorry im so used to seeing this storyboard for React Components... you click on a component you can see some knobs but no clear docs such as here: https://angular.carbondesignsystem.com/documentation/components/Pagination.html

Thanks so much i'll try this out now! Kudos to the team for taking on this feat while dealing with the Duo stuff!

**Comment by zvonimirfras** [comment]
Sure thing, thanks Danny! :)
