### ISSUE TITLE
Combobox focus does not act as expected when using tab keys

### ISSUE THREAD

**Issue by gcate** [IBM/carbon-components-angular#2160]
## Detailed description

The focus behavior for combobox (when using tab keys) does not act as expected.
**Problems:**
1. Single select combobox seems to get focus twice:  Once with a visible focus (blue outline) and then a hidden focus (no outline).
2. Multi select combobox seems to get focus twice:  Once with only a flashing cursor (no blue outline) and then a hidden focus (no outline).

I expect combobox focus to behave the same as it does for droplists.
(I am not sure I am describing this well but try the codesandbox link below and you will see the problem.)

## Steps to reproduce the issue

**[Codesandbox](https://codesandbox.io/s/angular-combobox-focus-issue-rrvt6y?file=/src/main.ts)**

1. Start with focus on Text input field, then click tab key.  
2. The Combobox with single select will have focus (blue outline).  Click tab key again, nothing seems to be selected.  
5. Click tab again and the next field (Text input) will have blue focus outline.
6. Click tab again, the Combo with multi-select has a flashing cursor but no blue outline.  
7. Click tab key again, nothing seems to be selected.
8. Click tab again and the next field (Text input) will have blue focus outline.

For comparison, tab through the droplist fields in same sandbox.   I expect comboboxes to have same behavior as the droplist fields.

## Additional information
Video of the problem here:
https://user-images.githubusercontent.com/4819973/174922715-9cd455cc-72ee-418f-81fa-1192d3537df3.mp4

**Comment by makandre** [comment]
> The Combobox with single select will have focus (blue outline). Click tab key again, nothing seems to be selected.

I think the down arrow got the focus but has no blue outline; I just opened https://github.com/IBM/carbon-components-angular/issues/2153 about this recently.

**Comment by gcate** [comment]
@makandre  I don't understand why down arrow should get focus.  Shouldn't combobox act just like dropdown as far as focus when there is nothing selected?

**Comment by makandre** [comment]
@gcate Not saying it should or should not, it was just an observation that it's receiving the focus but has no blue outline. This was flagged by accessibility test of our product.
