### ISSUE TITLE
Error: Module not found: Error: Can't resolve ...

### ISSUE THREAD

**Issue by zosmf-Mira** [IBM/carbon-components-angular#2173]
## Detailed description

> Describe in detail the issue you're having.
./src/app/dynamic-components/add-service/add-service.component.ts:14:0-99 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/loading/loading.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/dynamic-components/add-service'

./src/app/dynamic-components/add-service/add-service.component.ts:16:0-101 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/combobox/combobox.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/dynamic-components/add-service'

./src/app/dynamic-components/edit-table-rows/edit-table-rows.component.ts:10:0-99 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/input/text-area.directive' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/dynamic-components/edit-table-rows'

./src/app/zmf-diagnostics/diagnostics-list/diagnostics-list.component.ts:15:0-93 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/tabs/tabs.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/diagnostics-list'

./src/app/zmf-diagnostics/diagnostics-list/diagnostics-list.component.ts:16:0-92 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/tabs/tab.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/diagnostics-list'

./src/app/zmf-diagnostics/diagnostics-list/diagnostics-list.component.ts:20:0-108 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/placeholder/placeholder.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/diagnostics-list'

./src/app/zmf-diagnostics/export-list/export-list.component.ts:19:0-102 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/checkbox/checkbox.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/export-list'

./src/app/zmf-diagnostics/export-list/export-list.component.ts:21:0-106 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/table-container.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/export-list'

./src/app/zmf-diagnostics/export-list/export-list.component.ts:22:0-96 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/input/label.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/export-list'

./src/app/zmf-diagnostics/export-list/export-list.component.ts:24:0-96 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/input/input.directive' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/export-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:24:0-106 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/table-container.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:25:0-110 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/header/table-header.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:26:0-116 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/header/table-header-title.directive' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:27:0-122 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/header/table-header-description.directive' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:28:0-112 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/toolbar/table-toolbar.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:29:0-120 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/toolbar/table-toolbar-actions.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:30:0-98 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/button/button.directive' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:32:0-120 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/toolbar/table-toolbar-content.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:33:0-96 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/table.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/loglevel-list/loglevel-list.component.ts:35:0-108 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/placeholder/placeholder.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/loglevel-list'

./src/app/zmf-diagnostics/spacemng-list/spacemng-list.component.ts:10:0-95 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/input/label.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/spacemng-list'

./src/app/zmf-diagnostics/spacemng-list/spacemng-list.component.ts:12:0-95 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/input/input.directive' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/spacemng-list'

./src/app/zmf-diagnostics/spacemng-list/spacemng-list.component.ts:13:0-105 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/table-container.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/spacemng-list'

./src/app/zmf-diagnostics/spacemng-list/spacemng-list.component.ts:14:0-109 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/header/table-header.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/spacemng-list'

./src/app/zmf-diagnostics/spacemng-list/spacemng-list.component.ts:15:0-121 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/header/table-header-description.directive' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/spacemng-list'

./src/app/zmf-diagnostics/spacemng-list/spacemng-list.component.ts:16:0-96 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/table/table.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/spacemng-list'

./src/app/zmf-diagnostics/spacemng-list/spacemng-list.component.ts:17:0-102 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/checkbox/checkbox.component' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/spacemng-list'

./src/app/zmf-diagnostics/spacemng-list/spacemng-list.component.ts:18:0-98 - Error: Module not found: Error: Can't resolve '../../../../node_modules/carbon-components-angular/button/button.directive' in '/Users/yuanyuan/Documents/Angular/zmfui_diagnosis/src/app/zmf-diagnostics/spacemng-list'

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
carbon-components-angular

> What did you expect to happen? What happened instead? What would you like to see changed?
could work correctely

> What browser are you working in?
firefox

> What version of the Carbon Design System are you using?
    "carbon-components": "^10.6.1",
    "carbon-components-angular": "^4.56.3",
    "carbon-icons": "7.0.7",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
z/OSMF 3.1 GA

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by Akshat55** [comment]
That error message doesn't tell me much - have you imported the modules that aren't found in your NgModule imports?

e.g.
```
// Module imports

@NgModule({
	declarations: [],
	exports: [],
	imports: [
             // ... Missing modules go here
	]
})
export class YourModule { }
```

**Comment by zosmf-Mira** [comment]
Yes, they were there. I checked again, the import path should be "node_module/.." instead of "../../node_module/...". 
"../../node_module/"could be recognized by old angular version, but angular version 13 could not.  
Thanks for your reply anyway.
