### ISSUE TITLE
Improve tooltip performance

### ISSUE THREAD

**Issue by sparikh1594** [IBM/carbon-components-angular#224]
## Detailed description

> Describe in detail the issue you're having.

Tooltip in a table column with 50+ rows was causing performance issue. Tooltip was taking close to 5+ seconds to render.

From further investigation 
```document.body.firstElementChild.addEventListener("click", () => null, true);``` in `Dialog Directive` was causing the issue. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

Performance / Scalability issue. 

> Is this issue related to a specific component?

Dialog 

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

"carbon-components": "9.23.0",
"carbon-components-angular": "1.9.2",

**Comment by zvonimirfras** [comment]
This should be solved by creating a singleton event listener in that place. Probably via new service.

**Comment by asudoh** [comment]
Weighing in - While improving performance of tooltip is a good move, it may be worth noting that Carbon UX recommends pagination for tables with many rows.
