### ISSUE TITLE
Bug: Reactive Form Checkbox, Disable state

### ISSUE THREAD

**Issue by r2-codes** [IBM/carbon-components-angular#2247]
## Detailed description

 I had to use the checkbox component, with reactive forms. As we know Angular suggests for disabling the control with reactive form best case is to use from the FormControl({ value: false, disabled: false }), and not with disable property on the input. I was working with tabs so I tried to do some toggle based of the condition, to disable the checkbox or to enable it so, I tried with the reactive form function enable() or disable(). The toggle worked but when I return back to the tab where I had the checkbox it has some errors from the disable state that the checkbox component had. But I tried on separate component, and assigned the disable to true, faced the same error.

> Is this issue related to a specific component?
   Checkbox Component - < ibm-checkbox >< / ibm-checkbox >

> What did you expect to happen? What happened instead? What would you like to see changed?
   I expect when I return to the tab the checkbox need to be disabled but also to work properly not to crash.

> What version of the Carbon Design System are you using?
   
![image](https://user-images.githubusercontent.com/32378328/189918284-c7dc57d1-fc06-4ea8-94e3-8150f217d5a3.png)

## Steps to reproduce the issue

1. Create a FormGroup with an test input-name
2. Use the carbon checkbox

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/32378328/189918977-a28babf4-74ec-471a-9f32-ce89f7b87ce6.png)
![image](https://user-images.githubusercontent.com/32378328/189919037-1e17e549-51f2-48ca-b0f2-e870bc6272fa.png)
![image](https://user-images.githubusercontent.com/32378328/189919132-7b8083ac-19b5-4eea-8e0a-8dadb01efeee.png)
![image](https://user-images.githubusercontent.com/32378328/189919217-5931411b-7c69-4e05-a804-ce978a7853fd.png)
![image](https://user-images.githubusercontent.com/32378328/189919278-2a66a841-823a-41eb-a0b8-f808f5accbb4.png)

**Comment by Akshat55** [comment]
Closing since similar to #2228

**Comment by Akshat55** [comment]
Please follow status in issue #2228 :)
