### ISSUE TITLE
[Pagination] Page selector using ITEMS_PER_PAGE translation key

### ISSUE THREAD

**Issue by yuriybelike** [IBM/carbon-components-angular#2264]
## Detailed description

> Is this issue related to a specific component?

Pagination

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected for the page selector `<select>` label to be something like "Page" or "Current page". Instead it has the "Items per page" label.

![image](https://user-images.githubusercontent.com/60257988/191783052-10a30906-3f7b-418c-adad-7214730b287e.png)

> What browser are you working in?

Chrome 105

> What version of the Carbon Design System are you using?

Latest

## Additional information

As far as I can see this line https://github.com/IBM/carbon-components-angular/blob/9f232e50063a9ce431a3b96d64086859cb72f74f/src/pagination/pagination.component.ts#L115 could be changed to use `pageText.subject` instead of `itemsPerPageText.subject`.

**Comment by exequiel09** [comment]
Can I take this on?
