### ISSUE TITLE
Display a title tooltip on mouse-hover/tab of the sort icon in Table component

### ISSUE THREAD

**Issue by johnharan** [IBM/carbon-components-angular#245]
In chrome v70, if the user hovers over a sort icon in the Table component, the title e.g. "Sort rows by this header in ascending order" will show in a tooltip.

![sort_title_tooltip](https://user-images.githubusercontent.com/8806230/48129895-c98eb980-e282-11e8-8ebe-788573f57096.png)

The title does not show in firefox 63, safari v12, IE 11.

For enhanced accessibility, the tootip should show on mouse hover or on keyboard tab.

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is a feature/enhancement request.

> Is this issue related to a specific component?

Table Component

> What version of the Carbon Design System are you using?

"carbon-components": "9.32.1",
"carbon-components-angular": "1.9.1"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IWR

## Steps to reproduce the issue

[https://angular.carbondesignsystem.com/?knob-size=md&knob-showSelectionColumn=true&knob-striped=true&knob-sortable=true&selectedKind=Table&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel](url)

1. hover over the sort icon in the table component in chrome and note that the tooltip will display the title contained in the sort svg. 
2. Repeat step 1 on firefox/IE/safari and note that no tooltip displays

**Comment by zvonimirfras** [comment]
Same behavior is observable on vanilla and react flavors too and issue this issue should opened in carbon-components.

Tooltip you see on chrome is achieved with the `alt` property on an svg.

**Comment by johnharan** [comment]
added to carbon-components https://github.com/IBM/carbon-components/issues/1411

**Comment by carmacleod** [comment]
@zvonimirfras 
> Tooltip you see on chrome is achieved with the alt property on an svg.

Just sayin'...  :)
- `alt` is not a valid attribute for svg
- the tooltip is actually coming from the `<title>` child of the svg, but not all browsers do this

https://www.w3.org/TR/SVG/struct.html#TitleElement
> User agents may use markup within ‘title’ to influence the visual presentation of titles (such as tooltips), but are not required to do so.
