### ISSUE TITLE
Add UI Shell Component

### ISSUE THREAD

**Issue by dimipankratz** [IBM/carbon-components-angular#247]
## Detailed description

> Describe in detail the issue you're having.

The new [UI Shell](http://www.carbondesignsystem.com/experimental/ui-shell/code) component is still experimental but would probably make sense to have it in plan as an Angular implementation. We have a specific scenario for such component and it'd help us a lot to have an Angular implementation of it.

> Is this a feature request (new component, new icon), a bug, or a general issue?

It is a feature request.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

The new Watson Talent administration experience would use this component for multiple apps.

**Comment by cal-smith** [comment]
So we had some internal discussion, and while we do want to support something like this, we realized it requires some additional design work before we can include it here. We'll use this issue to keep everyone in the loop 👍

**Comment by cal-smith** [comment]
We're doing this!
