### ISSUE TITLE
Add Data Visualization Components

### ISSUE THREAD

**Issue by dimipankratz** [IBM/carbon-components-angular#248]
## Detailed description

It would make sense to have the [Data Visualization](http://www.carbondesignsystem.com/data-visualization/overview/general) components at least wrapped with Angular. There is a [React add-on](https://github.com/carbon-design-system/carbon-addons-data-viz-react) project for the charts and I'd expect something similar for Angular. The Angular-based charts components could live in their own repository or be a part of this repo. It would be also great, if you could put more thought into accessibility than just providing some [recommendations](http://www.carbondesignsystem.com/data-visualization/overview/general#accessibility). A better accessiblity handling with Angular components would be a great added value.

> Is this a feature request (new component, new icon), a bug, or a general issue?

It is a feature request.

**Comment by cal-smith** [comment]
Hi! I'd suggest taking a look at [Carbon Charts](https://github.com/IBM/carbon-charts/) ... they should cover whatever you need ([including angular wrappers](https://github.com/IBM/carbon-charts/tree/master/packages/angular))👍 

I'll also note that data viz isn't something we want to handle in this repo, so I'm going to close this. Let us know if you have any questions!

**Comment by dimipankratz** [comment]
Makes sense & thank you for the pointers!
