### ISSUE TITLE
Overflow menu does not work in IE

### ISSUE THREAD

**Issue by sparikh1594** [IBM/carbon-components-angular#273]
## Detailed description

> Describe in detail the issue you're having.

Overflow menu options are not clickable in IE (except the first option).
Also, IE give an error for focus `Object doesn't support property or method 'focus' 

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
overflow menu

> What did you expect to happen? What happened instead? What would you like to see changed?
When clicking any option the action should be triggered

> What browser are you working in?
IE 11

> What version of the Carbon Design System are you using?
2.0.7

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
ADI

## Additional information

* Screenshots or code
![image 4](https://user-images.githubusercontent.com/43587264/48507596-3238e180-e801-11e8-8211-60004a4c6fcb.png)

Also, there the style is breaking in all three browsers (IE, Firefox, Chrome). Where clicking outside the option doesn't close the menu

**Comment by johnharan** [comment]
@cal-smith Hi, as of 2.0.8 I'm no longer seeing the first item in the overflow-menu get focus when the menu is opened. Also able to make two overflow-menu buttons show at the same time in the Table.

**Comment by sparikh1594** [comment]
I am also seeing the same behavior
