### ISSUE TITLE
Dropdown selected is triggered when component is rendered

### ISSUE THREAD

**Issue by imandyie** [IBM/carbon-components-angular#276]
## Detailed description

> Describe in detail the issue you're having.

Just upgraded recently to the latest version and noticed that Dropdown calls `selected` method when component is rendered. This is causing the API being called twice. This didn't happen before. Is this what is supposed to happen?

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?

The `selected` method should only be triggered when an option is selected.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

**Comment by instakarlo** [comment]
Hi, we are still experiencing this on `"carbon-components-angular": "^2.47.2",`
