### ISSUE TITLE
Table: Should not have inline hard coded column widths

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#277]
## Detailed description

> Describe in detail the issue you're having.

I'm using the `TableHeaderItem.className` property to set my column style including the `width` property which gets overwritten. The table is automatically attaching an inline `width` attribute to each column and the only way to overwrite it is by using `!important` in my class which I wish I don't have to use.

If you need to keep the `width` attribute then at least do it through a class that can be easily overwritten by the consumer application.

![image](https://user-images.githubusercontent.com/1253469/48566929-fc136480-e8c9-11e8-839a-12e5e67a68f7.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Table

> What version of the Carbon Design System are you using?

2.0.7

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

ADI

**Comment by esuau** [comment]
Table component uses `ngStyle`. The width of the column inherits from the header item. You can actually set the width by doing :

```typescript
new TableHeaderItem({
    data: "...",
    style: { "width": "50px" },
    ...
})
```

**Comment by stanislavgeorgiev** [comment]
Thanks for the reply @esuau but inline styling is not in line with our development guidelines and we don't see it as a good practice.

**Comment by zvonimirfras** [comment]
You can set `TableHeaderItem` style as a workaround.

**Comment by stanislavgeorgiev** [comment]
I could but it goes to the same point about maintainability.

**Comment by cal-smith** [comment]
So originally this API was put in place due to a requirement to have resizable (draggable) columns ... there's no good way to do drag-to-resize without inline styles.

That said, Carbon (currently) doesn't have a requirement for resizable columns ... I think a preferable default would be no inherit styling (unless specified in `TableHeaderItem`) and `TableHeaderItem` should gain a `class` config option ... that way you don't need to poke the carbon class hierarchy directly.

**Comment by stanislavgeorgiev** [comment]
I agree that if I had resizeable columns then inline width is the way to go. My table is neither resizeable nor has draggable columns though :) 
`TableHeaderItem` already has a `class` property :)

**Comment by cal-smith** [comment]
Ooops, there it is! `className` ... goes to show how familiar I am with the Table source ... okay, so then this is just a bug 👍

**Comment by stanislavgeorgiev** [comment]
Thanks for fixing it @cal-smith!
