### ISSUE TITLE
Expandable row don't match table width

### ISSUE THREAD

**Issue by PawelKaim** [IBM/carbon-components-angular#280]
## Detailed description

`Colspan` value in Table expandable row is calculated base on `[attr.colspan]="model.data.length + 2"` [link](https://github.com/IBM/carbon-components-angular/blob/070d1d39eb8d63663a6e3abc7f4eafa95676ae0b/src/table/table.component.ts#L336) which is causing expandable container to not match width of Table if there is `<5` items in `model.data`

<img width="1658" alt="screenshot 2018-11-15 at 09 22 10" src="https://user-images.githubusercontent.com/45090913/48604244-22400f80-e971-11e8-9abe-a7c827808ce0.png">

## Steps to reproduce the issue

1. Create carbon table with 2 expandable rows
2. Expand expandable row
3. Check if width of expandable row match table width 

## Additional information

Example with 4 items in `model.data`

<img width="1916" alt="screenshot 2018-11-15 at 09 28 36" src="https://user-images.githubusercontent.com/45090913/48604559-1d2f9000-e972-11e8-91b4-ab113178f19e.png">

Example with 5 items in `model.data` 

<img width="1740" alt="screenshot 2018-11-15 at 09 35 01" src="https://user-images.githubusercontent.com/45090913/48604576-2c164280-e972-11e8-87ee-71e5340874e4.png">

**Comment by esuau** [comment]
Related to #275

**Comment by weinfurt** [comment]
+1

I was just about to report the same issue.
I guess that instead of `model.data.length`, it should be something like `model.data[0].length` which refers to number of columns in table data. Thanks.
