### ISSUE TITLE
Carbon Components has errors with Angular 7

### ISSUE THREAD

**Issue by hvlawren** [IBM/carbon-components-angular#283]
## Detailed description

> Describe in detail the issue you're having.

After upgrading to Angular 7, a build fails due to compile errors in Carbon Components

> Is this a feature request (new component, new icon), a bug, or a general issue?

Issue: Fix compilation when using Angular 7

> Is this issue related to a specific component?

No

> What version of the Carbon Design System are you using?

Latest

## Steps to reproduce the issue

Include Angular Carbon in an application
Upgrade application to Angular 7

```
ERROR in (1,1): : Directive Select, Property 'blur' is protected and only accessible within class 'Select' and its subclasses.
node_modules/carbon-components-angular/table/table.component.d.ts.Table.html(90,8): : Property 'columnDraggedHoverIndex' is protected and only accessible within class 'Table' and its subclasses.
node_modules/carbon-components-angular/table/table.component.d.ts.Table.html(90,8): : Property 'columnDraggedPosition' is protected and only accessible within class 'Table' and its subclasses.
node_modules/carbon-components-angular/table/table.component.d.ts.Table.html(108,8): : Property 'columnDraggedHoverIndex' is protected and only accessible within class 'Table' and its subclasses.
node_modules/carbon-components-angular/table/table.component.d.ts.Table.html(108,8): : Property 'columnDraggedPosition' is protected and only accessible within class 'Table' and its subclasses.
node_modules/carbon-components-angular/table/table.component.d.ts.Table.html(87,7): : Property 'isColumnDragging' is protected and only accessible within class 'Table' and its subclasses.
node_modules/carbon-components-angular/tabs/tab-headers.component.d.ts.TabHeaders.html(31,6): : Property 'tabref' does not exist on type 'TabHeaders'.
node_modules/carbon-components-angular/tabs/tab-headers.component.d.ts.TabHeaders.html(36,7): : Property 'tabref' does not exist on type 'TabHeaders'.
```

Note that Angular 7 adds considerable value through upgrades to the CDK, which add support for virtual scrolling and for focus traps.

**Comment by cal-smith** [comment]
Did some testing today, can confirm that JIT and AOT work fantastically for most components ... I'll be setting up a comprehensive test environment so we can actually get the ball rolling on this.

Honestly this is pretty incredible, in the early days of Angular (v2/v3) it was still a pretty big deal jumping a major version.
