### ISSUE TITLE
Overflow menu jumps on rendering in all browsers

### ISSUE THREAD

**Issue by sparikh1594** [IBM/carbon-components-angular#284]
## Detailed description

> Describe in detail the issue you're having.

On all browser, with the latest 2.0.7 release, I see that clicking on the overflow menu causes for the page to jump up and down and lose its position on the page. 

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Overflow menu

> What did you expect to happen? What happened instead? What would you like to see changed?
For the overflow menu to position properly and focus properly

> What browser are you working in?
Chrome, firefox, IE

> What version of the Carbon Design System are you using?
2.0.7

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
ADI

## Additional Info

Here was a slack conversation from carbon-ng channel for other details.
https://ibm-systems-z.slack.com/archives/CBZC0LM2N/p1541805021153200

## Additional information

* Screenshots or code
* Notes

**Comment by johnharan** [comment]
Also since a recent update, we are noticing the overflow menu is displaying 1 row lower on our carbon Table with overflow menu.

**Comment by johnharan** [comment]
I've added https://github.com/IBM/carbon-components-angular/issues/285 to cover some more issues i've noticed were recently introduced for the overflow menu, these issues look to be related.

**Comment by cal-smith** [comment]
I've got a fix for this incoming ... we were setting the focus _before_ the component was positioned, which was jumping the page down
