### ISSUE TITLE
Deprecation warning is wrong

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#288]
In this file: https://github.com/IBM/carbon-components-angular/blob/master/src/modal/modal-placeholder.component.ts

The code references the wrong selector
```
console.warn("`ibm-dialog-placeholder` has been deprecated in favour of `ibm-placeholder`");
```

**Comment by cal-smith** [comment]
Ooops, that's what I get for copy pasta deprecation notices.
