### ISSUE TITLE
Move CI over to travis-ci.org

### ISSUE THREAD

**Issue by theiliad** [IBM/carbon-components-angular#29]
Currently we're using travis-ci.com (which is used for enterprise and paid solutions).

Open-source projects should be on travis-ci.org.

**Steps:**
1. Activate repo on travis-ci.org
2. Move env. vars. over
3. Update git branch settings

**Be sure to also update this as well:**
![image](https://user-images.githubusercontent.com/14989804/44925525-a4c71480-ad1c-11e8-86b6-698cdf0d4e4e.png)

**Comment by cal-smith** [comment]
Travis is moving everything to travis-ci.com: https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

So we're perfect where we are :+1:
