### ISSUE TITLE
Modal: cannot use <input> element in content of modal dialog

### ISSUE THREAD

**Issue by weinfurt** [IBM/carbon-components-angular#305]
## Detailed description
I would like to create a 'Log in' modal dialog which would be rendered whenever 401 response is received. For that, I would like to use `<input>` element in the modal content to get user's id and password. Something like this:

![image](https://user-images.githubusercontent.com/10806904/49516987-4c635e00-f89b-11e8-837f-669d5a4bdc70.png)

But the resulting dialog does not contain the input elements. Only the 'safe' elements like `<p>` and labels are present.

![screenshot_2018-12-05_14-52-05](https://user-images.githubusercontent.com/10806904/49517850-7158d080-f89d-11e8-974a-af9839a5af4a.png)

You can notice the warning in the console window:
WARNING: sanitizing HTML stripped some content (see [http://g.co/ng/security#xss](http://g.co/ng/security#xss)).

If I read the Angular article correctly, it means that Angular marks the <input> element as dangerous and removes it during code sanitization from the modal content. The string value of modalContent is bound to `innerHTML` property of `<p>` element in [alert-modal.component.ts](https://github.com/IBM/carbon-components-angular/blob/fad3545ad1ccf009d9cc880b4a8282e3ba2f6a05/src/modal/alert-modal.component.ts#L57) 

I tried to mark the content as safe with `sanitizer.bypassSecurityTrustHtml()` but it does not have any effect on the result.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Modal component

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect that any HTML passed into modal content is rendered without issues.

> What browser are you working in?

Chromium, Chrome, Firefox (latest versions)

> What version of the Carbon Design System are you using?

Latest available

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

z/OSMF

**Comment by zvonimirfras** [comment]
`show` obviously has some limitations, but it's also just a convenience function around `create`, which takes full components that extend `BaseModal`, where you can put whatever you can build with angular.

See [`ModalStory`](https://github.com/IBM/carbon-components-angular/blob/master/src/modal/modal.stories.ts#L33) as an example.

Feel free to reopen the issue if this doesn't solve your problem.

**Comment by weinfurt** [comment]
Thank you @zvonimirfras for the hint! The `create()` function works well for me.
