### ISSUE TITLE
Table: Specify columns in the template

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#308]
## Detailed description

> Describe in detail the issue you're having.

The specific issue we're running at right now is that if the language of browser changes and load new language strings then all components would show the new strings except the table headers. That's because they were programmatically set in the component and don't use translation pipes.

Reloading the whole browser tab solves the issue of course.

I think would make a lot of sense to allow the headers to be defined as another set of components in the template as that would increase readability and allow for dynamic string updates. For example:
```
<ibm-table>
   <ibm-table-headers>
      <ibm-table-header [title]="name | translate"></ibm-table-header>
   </ibm-table-headers>
</ibm-table>
```

**Comment by cal-smith** [comment]
This would be a great enhancement!

I know with `ngx-translate` it's possible to request the translations programmatically (`TranslationService.get`) ... as a interim/alternative fix would it be possible to do something like that and update the model accordingly? I'm not sure what translation/i18n library you're using, so I'm not sure if that's a feasible suggestion.

**Comment by stanislavgeorgiev** [comment]
We're using `ngx-translate` and then we create header like this:
```
  ngOnInit() {
    this.businessTermModel.header = [
      new TableHeaderItem({ data: this.translate.instant("definition"), sortable: false }),
      new TableHeaderItem({ data: this.translate.instant("status") }),
    ];
  }
```

The interim solution for now would be to hook each table to the `languageChanged` event and recreate the header. That seems like a lot of additional code that's unnecessary and we get for free if we use a template declaration (which also feels more natural I think)

**Comment by zvonimirfras** [comment]
This _should_ be resolved with the table refactor as there's an `ibmTableHeaderTitle` directive where you can do something similar to what's requested. If this is still an issue, feel free to reopen.

**Comment by stanislavgeorgiev** [comment]
Yeap, you already have this
