### ISSUE TITLE
Outline for tooltips

### ISSUE THREAD

**Issue by theiliad** [IBM/carbon-components-angular#31]
The outlines show up for both tooltip examples. What is the reasoning there?

![image](https://user-images.githubusercontent.com/14989804/44936675-ae17a780-ad43-11e8-9458-f2c0c2d5c11b.png)

![image](https://user-images.githubusercontent.com/14989804/44936643-8d4f5200-ad43-11e8-8ff2-72a89ad83c05.png)

**Comment by cal-smith** [comment]
I believe that comes in from carbon-components 
... I think that's an a11y thing.

**Comment by asudoh** [comment]
Some background wrt Carbon code; Carbon has a mechanism to put focus on floating menu (e.g. tooltip) when it gets open, however, we don’t make the tooltip focusable given we have an alternate way to make the tooltip content accessible: https://github.com/IBM/carbon-components-react/pull/518

**Comment by cal-smith** [comment]
Ah cool ... we should totally look into adding `aria-owns` then
