### ISSUE TITLE
Create better Github issue labels

### ISSUE THREAD

**Issue by theiliad** [IBM/carbon-components-angular#32]
Just as a reference, this is what I've started with in charts:
![image](https://user-images.githubusercontent.com/14989804/44936738-eae39e80-ad43-11e8-9541-de3b1610eb6d.png)

**Comment by zvonimirfras** [comment]
We haven't updated labels in a while so I assume we're good with what we have at the moment.

We can, of course, change labels as need arises, but discussion seems to be over for now.
