### ISSUE TITLE
Standardize size Inputs

### ISSUE THREAD

**Issue by youda97** [IBM/carbon-components-angular#328]
Different components are using different input values. (ie. md, lg, normal)

**Comment by zvonimirfras** [comment]
I think I remember seeing some changes in code regarding this. @cal-smith is this addressed?

**Comment by cal-smith** [comment]
It's definitely been tidied up a bit ... I think in general we're just adopting the carbon size values for better design system consistency vs trying to make them consistent just for us.

Either way, we can close this.
