### ISSUE TITLE
Progress indicator module (with experimental feature on) is not rendering correctly

### ISSUE THREAD

**Issue by kaustubh57** [IBM/carbon-components-angular#332]
Trying to use progress indicator module (with experimental feature on)… it’s not rendering correctly for me. @cal-smith asked to create an issue for this on slack.
Possible cause: "the HTML slightly changed for that component for experimental"

## Detailed description
- This is a bug or general issue.
- Using "ProgressIndicatorModule" on the page
- It should render progress indicator as shown in demo pages but apparently it's not!
- Checked on Chrome and Firefox
- Versions of carbon components:
   "carbon-components": "^9.62.6",
   "carbon-components-angular": "^2.9.0",
   "carbon-icons": "^7.0.7"
- As of now, there is NO release date for UI we are building for WCA (mobile).

## Steps to reproduce the issue
1. Imported "ProgressIndicatorModule" in app module
2. Using `<ibm-progress-indicator [steps]="steps"></ibm-progress-indicator>` to view the progress indicator.
3. It's not rendering correctly.

![image](https://user-images.githubusercontent.com/1927067/50786646-fc483480-1268-11e9-86ff-ee97874fe79e.png)

**Comment by cal-smith** [comment]
Looks like the SVGs have changed, but the class names and structure is the same ... Not sure what the best way forward is, but we'll definitely need some way of switching between the old and new icons.

Maybe a service?

**Comment by cal-smith** [comment]
This should be resolved with #358
