### ISSUE TITLE
Table: Add folder type rows allowing to expand extra table rows

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#335]
## Detailed description

> Describe in detail the issue you're having.

My project needs to have folder type rows serving like groups for other table rows. The key difference from the currently supported by Carbon expand row function is that those child rows would have the same columns as the parent row and could be further expanded. Here's a typical structure

```
 Folder 1                     |   metric   |    metric   |   text
       Sub-folder 1.1         |   metric   |    metric   |   text
             Item 1.1.1       |   metric   |    metric   |   text
             Item 1.1.2       |   metric   |    metric   |   text
       Item 1.1               |   metric   |    metric   |   text
       Item 1.2               |   metric   |    metric   |   text
```

I can work on this and contribute the code back to the repo if that's something of interest to you.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

Table

**Comment by cal-smith** [comment]
So from what I can tell, this isn't supported by carbon-components as is ... I'd suggest opening a [feature request here](https://github.com/IBM/carbon-components/issues/new/choose), to see if it's something we want to support on a system level.

While that's in progress, you'll want to implement this as an addon ([addon example](https://github.com/carbon-design-system/carbon-addons-cloud))... both so you have something you can consume _now_ and so we (meaning the whole carbon team) have a reference implementation to evaluate.

**Comment by zvonimirfras** [comment]
It's been 2 years, do we still want to keep track of this?
Considering that there was a solution and there seems to be no progress on design, I'll assume no. Feel free to reopen if we actually do :)

**Comment by stanislavgeorgiev** [comment]
Sure, np
