### ISSUE TITLE
Carbon styling not applied to Table component in v1.5.0

### ISSUE THREAD

**Issue by polanders** [IBM/carbon-components-angular#35]
## Steps to reproduce the issue
A the table component to a page, when rendering it has no styling.

![image](https://user-images.githubusercontent.com/23030962/45034888-93e60e00-b050-11e8-8e2c-cab860ee1fea.png)

**Comment by zvonimirfras** [comment]
That PR sets `bx--data-table-v2--tall` class for size `lg`.

What you're explaining would happen for everything before that PR, not after. 😕 
It works fine in the [storybook](https://angular.carbondesignsystem.com/?knob-size=lg&knob-showSelectionColumn=true&knob-striped=true&selectedKind=Table&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).

**Comment by polanders** [comment]
What I mean is this PR is not in the current v1.5.0 release, I'm asking for a release that includes it.

**Comment by polanders** [comment]
👍 🥇 thank you, very much appreciated
