### ISSUE TITLE
Drag&drop between components

### ISSUE THREAD

**Issue by zvonimirfras** [IBM/carbon-components-angular#366]
What would we have to do to enable developers to develop apps that allow users to drag and drop items between components?

What are the possible use cases?

How can we structure data to support that?

What additional APIs would components need?

How best to filter what's drag-able and drop-able?

Which components would you expect to support it?

How to insure compatibility in future components? How to make things generic enough?

**Comment by stanislavgeorgiev** [comment]
In our case we want to have a Table that allows 2 ways of rows reordering - an accessible way with up/down buttons and UX friendly drag-and-drop. We imagine that Table would have another property `@Input() rowsDraggable = false;` similar to `@Input() columnsDraggable = false;` and would work in a similar way.

![image](https://user-images.githubusercontent.com/1253469/51499805-ab245e80-1d99-11e9-8179-3abe029d642f.png)

**Comment by cal-smith** [comment]
This issue is pretty broad, and there's other design considerations involved ... drag and drop within a table is technically possible with the v3 table and some directives from the Angular CDK ... I'm going to close this for now, but we can definitely re-examine parts of this
