### ISSUE TITLE
Table: Enable single select of rows not working

### ISSUE THREAD

**Issue by immanenipavankumar** [IBM/carbon-components-angular#375]
## Detailed description

> Describe in detail the issue you're having.

Using `ibm-table`, we should be able to enable single selection of rows in the table using this parameter `enableSingleSelect`. 

Here is the code that I am using to set up the table..

```
            <ibm-table *ngIf="businessTerms?.length !== 0"
                       id="business-terms-check-list"
                       [model]="businessTermModel"
                       [striped]="false"
                       [size]="size"
                       [showSelectionColumn]="!readonly"
                       [enableSingleSelect]="true"
                       (selectRow)="rowSelectionChanged()"
                       (deselectRow)="rowSelectionChanged()"
                       class="headless">
            </ibm-table>
```
even though when I set this parameter to `true`, I am able to select multiple rows..

![image](https://user-images.githubusercontent.com/45642194/51732665-cf02d100-2033-11e9-8629-0c3168ff5c4b.png)

We are not modifying the model at all in `rowSelectionChanged`.

After further investigation, it was found that if `showSelectionColumn` is true it doesn’t work …
So we need to set `showSelectionColumn` to false, and live without the checkboxes. 

This seems like a basic function that seems to be broken and our team would like to get a fix for this issue as soon as possible.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Table

**Comment by cal-smith** [comment]
seems like CCR is adding support for radio buttons: https://github.com/IBM/carbon-components-react/pull/1824

Based on that, perhaps `enableSingleSelect` should swap the checkboxes for radios ... thoughts @zvonimirfras?

**Comment by zvonimirfras** [comment]
Single select was historically tied to hiding the checkbox column and it didn't have any effect if used while checkbox column was shown.
With radio button support becoming a thing in design, we can make it a thing in code too.
