### ISSUE TITLE
Tabs used as navigation shouldn't include a tabindex

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-angular#389]
~There's a tabidndex on the generated content panel, there shouldn't be one there (instead the content should correctly apply tabindexes)~

**Comment by youda97** [comment]
According to the [w3 example](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html) the next tab sequence should be the tabpanel element

**Comment by cal-smith** [comment]
Hm, so to support tabs as navigation we'll want to add some kind of toggle to disable the tabindex on the tabpanel
