### ISSUE TITLE
"i18n Tooling" link in the README.md doesn't work

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#39]
## Steps to reproduce the issue

1. Go to https://github.com/IBM/carbon-components-angular#resources
2. Click on the "I18n Tooling" link
3. You'll see a "Page not found"

**Comment by zvonimirfras** [comment]
Dear Angular...

It looks like they moved that to https://angular.io/guide/i18n

Great catch, Stanislav! Thank you! 😃

**Comment by stanislavgeorgiev** [comment]
Happy to help :-)

Thanks,
Stan.
