### ISSUE TITLE
Overflow menu bug on the page with scroll

### ISSUE THREAD

**Issue by TatyanaKahanovich** [IBM/carbon-components-angular#399]
## Detailed description

> Describe in detail the issue you're having.

We have a lot of tables in our application. There are overflow menu in each table row. If we scroll page overflow menu appears much lower than we expected. If we don't scroll page or set scroll at the top - Overflow menu appears in the right place.

> Is this a feature request (new component, new icon), a bug, or a general issue?

a bug

> Is this issue related to a specific component?

OverflowMenu

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect overflow menu appears near three vertical dots. Instead it appears much lower.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components-angular:  2.29.0

## Steps to reproduce the issue

https://codesandbox.io/s/y369zqxol1

**Comment by cal-smith** [comment]
Thanks for that codesandbox 🙌 I think I know what's going on here ...
