### ISSUE TITLE
Can you deploy the storybook somewhere

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#4]
## Detailed description
Can you deploy the project storybook somewhere after every build so we can see the latest version code running? One option is to use GutHub pages using this tool: https://github.com/storybooks/storybook-deployer

**Comment by zvonimirfras** [comment]
Yes, storybook will be deployed soon. Cal is working on it.

**Comment by cal-smith** [comment]
We're waiting on some npm/github credentials to get everything fully working, but in the meantime I've manually published the current storybook to https://ibm.github.io/carbon-components-angular and the current documentation to https://ibm.github.io/carbon-components-angular/documentation/

**Comment by markewallace** [comment]
That's great, thanks @cal-smith

**Comment by cal-smith** [comment]
closed with #12 ... everything's now deploying as it should!
