### ISSUE TITLE
Dropdown menu is positioned incorrectly

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#405]
## Detailed description
Edit the dropdown basic story template as follows:
```
<div style="width: 300px">
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
	<ibm-dropdown
		[theme]="theme"
		placeholder="Select"
		[disabled]="disabled"
		(selected)="selected($event)"
		(onClose)="onClose($event)">
		<ibm-dropdown-list [items]="items"></ibm-dropdown-list>
	</ibm-dropdown>
	<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
</div>
```
If you scroll the page and open the dropdown the menu is positioned incorrectly as shown here:
![dropdown_position](https://user-images.githubusercontent.com/3009737/52747988-2bc32d00-2fdd-11e9-96a9-f7ebd93b1d47.gif)

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue? Bug

> Is this issue related to a specific component? Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed? Dropdown menu always positioned underneath the control even after scrolling

> What browser are you working in? Chrome

> What version of the Carbon Design System are you using? Issue reproducible using the project storybook

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? Assess

**Comment by cal-smith** [comment]
And fixed! #406 😎
