### ISSUE TITLE
Dropdown allows item to be deselected but this doesn't work for our usecase

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#408]
## Detailed description

We are using the Dropdown component to allow users to select sorting options for a table.
The Dropdown allows an item to be deselected if it the currently selected item and the user selects it again.
This doesn’t make sense for our use case so what we want to do is either disallow this or when we receive the event programmatically select the item. Is either option possible?

> Is this a feature request (new component, new icon), a bug, or a general issue? Feature request

> Is this issue related to a specific component? Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in? Chrome

**Comment by cal-smith** [comment]
#402 is related to this ... The carbon specs don't allow for items to be deselected if they're currently selected, so we should definitely change this to follow the spec 👍
