### ISSUE TITLE
Combobox doesn't open when twistie is clicked

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#410]
This can be reproduced here

https://angular.carbondesignsystem.com/?selectedKind=Combobox&selectedStory=Basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

1. Click in center of combo and the dropdown appears
2. Issue: Click the twistie and the dropdown fails to appear

**Comment by cal-smith** [comment]
First glance it seems like we just have to change where we're listening for events
