### ISSUE TITLE
TableModel.set data() should check the input and gracefully handle exceptions

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#42]
## Detailed description

> Describe in detail the issue you're having.

I'm seeing `ERROR TypeError: Cannot read property 'length' of undefined at TableModel.set [as data] (table-model.class.js:82)` in the console when I execute the following code:
  ```
ngOnInit() {
    this.myModel = new TableModel();
    this.myModel.data = [];
    this.myModel.header = [
      new TableHeaderItem({ data: 'My column name' }),
    ];
  }
```

I traced down the problem and it looks like the data is not checked for `null`, `undefined` or `[]` values and it fails with an Exception.

> What did you expect to happen? What happened instead? What would you like to see changed?

I think it should gracefully convert any falsy input as to no data is provided.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

```
    "carbon-components": "9.8.5",
    "carbon-components-angular": "^1.6.0", 
```

**Comment by zvonimirfras** [comment]
For `null` and `undefined` it could make sense to initialize data to empty table `[[]]`.

For `[]` I'd argue that it can introduce problems, but adding a better error message might be useful.

**Comment by stanislavgeorgiev** [comment]
For me `null` and `undefined` are the same as never calling `model.data = xxxx` and the component would use its defaults in that case.

I understand `[]` as empty data (no data) as that is literally passing an empty object with no rows. Passing `[[]]` looks weird and it really means "one row with no data in it" type of a scenario which is essentially the same as no data.
