### ISSUE TITLE
Implement Overflow menu

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#43]
> Is this a feature request (new component, new icon), a bug, or a general issue?

The Carbon Overflow menu is an integral part of my project. Would it be possible to implement it?
http://www.carbondesignsystem.com/components/overflow-menu/usage

**Comment by cal-smith** [comment]
For sure ... Looks like it'll definitely be part of the `dialog` family of components, so most of the base framework is already there for that.
