### ISSUE TITLE
ibm-table: Sticky headers not working in version 9

### ISSUE THREAD

**Issue by vivpat18** [IBM/carbon-components-angular#435]
ibm-table: is not scrollable also stickyheader property not working.

**Comment by vivpat18** [comment]
In Table lazy loading no table overflow functionality observed.
![image](https://user-images.githubusercontent.com/48437896/54121263-0846a300-4420-11e9-861e-01c37dafeb50.png)

**Comment by vivpat18** [comment]
Also,If we want to scroll table body headers are also getting scrolled; sticky header is not working.
 
![image](https://user-images.githubusercontent.com/48437896/54121414-5fe50e80-4420-11e9-83a9-55b9baf9dee8.png)

**Comment by cal-smith** [comment]
Sticky headers aren't supported in the v9 carbon-components css
