### ISSUE TITLE
Pagination: Shows up/down arrows in Chrome

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#448]
## Detailed description

> Describe in detail the issue you're having.

This screenshot comes from the storybook page:

![image](https://user-images.githubusercontent.com/1253469/54705950-3d37b180-4b14-11e9-87b9-401c1e5016b5.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Pagination

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

**Comment by cal-smith** [comment]
If you add `-webkit-appearance: none;` to the double arrows go away?

If this is an issue locally you may need to add [autoprefixer](https://github.com/postcss/autoprefixer) (or something equivalent) to fix it.

I've tried adding it to our storybook in the past but it wasn't picking up the config, I'll give it another shot though 👍

**Comment by stanislavgeorgiev** [comment]
Locally I have another version that started doing something else. I saw the above on the official storybook site though

**Comment by cal-smith** [comment]
Figured this out ... may be included before v3

**Comment by stanislavgeorgiev** [comment]
@cal-smith I'm not sure why was this issue closed when I can still see the storybook is still showing the issue

**Comment by cal-smith** [comment]
Yep, probably closed it a little eagerly, see this PR for more: https://github.com/IBM/carbon-components-angular/pull/478
