### ISSUE TITLE
DatePicker position within modal Dialog

### ISSUE THREAD

**Issue by dastoc** [IBM/carbon-components-angular#449]
## Detailed description

I found a bug for this component. As you can see below, when I use it on Modal Component the position is changed.
![image](https://user-images.githubusercontent.com/4670731/54707831-c0f79b00-4b20-11e9-8c9a-14e3942049aa.png)
Following some code lines that may be cause the bug:
![image](https://user-images.githubusercontent.com/4670731/54707995-20ee4180-4b21-11e9-98c8-ecf144bf8917.png)
Please, let me know if the bug description was clear for you.
Thanks in advance and excuse me if I did not write according to the established standards.

**Comment by cal-smith** [comment]
repro sandbox: https://codesandbox.io/embed/kk7p827w27

**Comment by cal-smith** [comment]
There seems to be a few bugs at play here:
- it doesn't always pick up the correct styles (I'd say most of the time it doesn't)
- it positions correctly on resize, but the initial position is always wrong (this may be due it part to the trigger element being an svg)
