### ISSUE TITLE
Digital Analytics in demo sites?

### ISSUE THREAD

**Issue by theiliad** [IBM/carbon-components-angular#45]
We've discussed this before internally.

With carbon products though I think we're able to use Google Analytics in the demos?

I can setup the accounts...

**Comment by cal-smith** [comment]
We have a Digital Analytics tenant already ... I'm not sure how difficult that would be to add, but that's another route we can explore (may as well dog food our own products right :wink:)

**Comment by theiliad** [comment]
@cal-smith Update: we're getting DA keys soon.

I'll add in this issue, then we can update

**Comment by cal-smith** [comment]
I have a feeling this isn't getting completed (for a few reasons ...)
