### ISSUE TITLE
Getting ExpressionChangedAfterItHasBeenCheckedError when using content switcher

### ISSUE THREAD

**Issue by jdcai** [IBM/carbon-components-angular#450]
## Detailed description

I updated my carbon components angular and I started getting an error on the content switcher.

The error I get when a page is opened with a content switcher is
`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'bx--content-switcher--selected: false'. Current value: 'bx--content-switcher--selected: true'`

and if I click on one of the content switcher buttons and then click on a button seperate from the content switcher, the content switcher button I selected becomes unselected, not sure if this is a seperate bug or if its caused by the error.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Content-switcher

> What did you expect to happen? What happened instead? What would you like to see changed?

The error should not show up and when selecting a option in the content switcher and then clicking a separte button it should not unselect the option.

> What browser are you working in?

Google chrome

> What version of the Carbon Design System are you using?

2.40.3

## Steps to reproduce the issue

https://codesandbox.io/s/r0pl0l6x9m

Open the console to see the ExpressionChangedAfterItHasBeenCheckedError when it is loaded.

1. First section will be selected by default.
2. Click on second section. Now it is selected.
3. Click on the Hi! button. Now none of the options in the content switcher is selected.

## Additional information

https://github.com/IBM/carbon-components-angular/pull/430 might be useful since it fixes a similar error but for the overflow menu

**Comment by cal-smith** [comment]
Looks pretty similar to #430, though in this case I think our solution is to delay the initial `active` set by a tick ... we should also check for existing active options and skip setting the first option if possible
