### ISSUE TITLE
make ui shell hamburger optional

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-angular#452]
right now it's required, and it should be optional.

**Comment by jdoyle65** [comment]
@cal-smith Playing around with this, is there a variable name you'd prefer for the option? Something like

- menu
- hasMenu
- hamburger
- showHamburger

etc.

**Comment by cal-smith** [comment]
At the moment I'm leaning towards `menu: boolean` or a `ibm-hamburger` component with a `<ng-content select="ibm-hamburger"></ng-content>` in the header

**Comment by cal-smith** [comment]
Here are some screens ... 

initial state:
![image](https://user-images.githubusercontent.com/1744185/55564377-c4188c80-56c5-11e9-900d-c0509cea4b7f.png)

right nav (`ibm-right-panel`?) open:
![image](https://user-images.githubusercontent.com/1744185/55564359-bb27bb00-56c5-11e9-889d-17c2c239ebc4.png)

hamburger menu (`ibm-navigation`?) open (note the menu opens _over_ the existing left nav):
![image](https://user-images.githubusercontent.com/1744185/55564338-afd48f80-56c5-11e9-92a4-8422cb192683.png)

these are coming from the latest carbon-components ... so there's a fair number of changes we'll have to make

**Comment by jdoyle65** [comment]
Interesting, it looks like the idea is for the right-hand panel to be opened arbitrarily, and the content being contextual to whatever opened it?

**Comment by cal-smith** [comment]
Yep, that seems to be the intention ... the example they have right now is a product search, but it seems like it could be anything.

**Comment by cal-smith** [comment]
For the purposes of this issue we can focus on `ibm-navigation`/`ibm-hamburger`

**Comment by jdoyle65** [comment]
Sounds like a plan. Perhaps for the context of this issue I'll set it up to expect an `ibm-hamburger` component to be projected through, and the other enhancements will come later?

**Comment by cal-smith** [comment]
Yep that sounds good 👍
