### ISSUE TITLE
Output type of Combobox selected is incorrect

### ISSUE THREAD

**Issue by hvlawren** [IBM/carbon-components-angular#46]
> Describe in detail the issue you're having.

Listed Output type of Combobox selected is ListItem

Actual Output type of Combobox selected is {item: ListItem}

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Combobox

> What version of the Carbon Design System are you using?

Latest

## Steps to reproduce the issue

https://github.com/IBM/carbon-components-angular/blob/master/src/dropdown/list/dropdown-list.component.ts 

Line 445 shows the DropdownList emitting an Object of type {item: ListBox}. 

https://github.com/IBM/carbon-components-angular/blob/master/src/combobox/combobox.component.ts

Line 268 shows the ComboBox emitting this object as a ListBox.

**Comment by cal-smith** [comment]
Nice catch! I wish TypeScript would enforce discrepancies like this better.

**Comment by hvlawren** [comment]
So the reason TypeScript doesn't catch this is that select event emitter is of type EventEmitter<Object>... As a result, the ComboBox has no way to know that the input isn't a ListItem... TypeScript definitely has more forgiving casting than more strongly typed systems.
