### ISSUE TITLE
Table: Ability to show a "No data" tile

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#48]
## Detailed description

> Describe in detail the issue you're having.

I have a Table component that may happen to have no data to show and I handle that no data case with the following code:
```
<ibm-table [model]="myModel"></ibm-table>
<div *ngIf="myData.length === 0" class="bx--tile">No data.</div>
```

![2018-09-07_10-15-59](https://user-images.githubusercontent.com/1253469/45224127-312a8780-b287-11e8-9b84-8032795299cc.png)

As you can see there's a gap between the table headers and the no data block because the table still creates an empty row with no cells which pushes the no data block lower. It would be nice to have an embedded mechanism to the no data situation, for example an input field `noDataMessage="No data"` (or `noDataTemplate`) which will be showed automatically when the model contains no data. It should look like a complete component and not cut at the header bottom like it is right now.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

Table

**Comment by zvonimirfras** [comment]
I'm thinking it could even work like:

```html
<ibm-table [model]="model">
	Content to show if there's no data.
</ibm-table>
```

so no additional input fields would be necessary.

**Comment by zvonimirfras** [comment]
Design guideline is to replace the table with your "no data" template.

Reasons behind this are related to accessibility. When the table is empty users have to tab through all the headers to find out there's no data.

Our designers will conduct some user testing to validate possible benefits behind this approach.

**Comment by stanislavgeorgiev** [comment]
That's a good point for the tabbing. The table should switch off at least the header sorting if there's no data.

**Comment by johnharan** [comment]
This feature would be ideal for my team's project. Our non-carbon data tables display a "no data" message in the first row, so now that we're converting to carbon we'd like to use the same approach.

**Comment by stanislavgeorgiev** [comment]
:1st_place_medal:
