### ISSUE TITLE
[proposal/discussion]: common layouts as components

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-angular#50]
Building on #47, it may be useful to provide common layouts via components and/or directives.

For example, a form could look like

```
<ibm-form
  (submit)="onSubmit($event)">
  <ibm-text>label text</ibm-text>
  <ibm-text>label text</ibm-text>
</ibm-form>
```

Where `ibm-form` automatically wires up the validation reporting and provides submit buttons/etc

Other examples would be a grid layout manager, an optimized list view, a content pager, or even a full dashboard generator based on components following a few standard interfaces.

I propose `layout.module` for this, we'll also need to find some samples of real world usage and pull out the common patterns and create some fairly well defined usage guidelines.

**Comment by theiliad** [comment]
Quick question, why `ibm-*`?

Seems non-necessary to include the company name in every directive/component, why not `carbon-*` or `c-*`?

**Comment by cal-smith** [comment]
Can we move that question to a separate issue?

**Comment by theiliad** [comment]
👍

**Comment by cal-smith** [comment]
That's one of the big selling points that I see ... if we design the API correctly, you could have a whole dashboard that (in theory) could adopt an entirely new design with a version update.

**Comment by cal-smith** [comment]
Closing for now ... Some of this work is being picked up internally, and some of it is being tackled at the design system level through the addons explorations
