### ISSUE TITLE
UI Shell Hamburger Menu: Needs Click Event + template addition

### ISSUE THREAD

**Issue by jefftmahoney** [IBM/carbon-components-angular#509]
## Detailed description

> Describe in detail the issue you're having.
Would be nice if the Hamburger component supported a `click()` event handler.  Also, would be nice if the template of the hamburger component toggled between what it has now and the big blue x, as portrayed here:
![Screen Shot 2019-04-22 at 10 47 46 AM](https://user-images.githubusercontent.com/2761266/56506344-2a861300-64ec-11e9-95d8-fb71a19daaa1.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?
Feature request

> Is this issue related to a specific component?
Hamburger menu component that's part of UIShell component.

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected there to be a click handler such that users could toggle between the default, three-bar hamburger menu icon that's present now and the blue x shown in the attached screenshot.

> What browser are you working in?
Chrome and Firefox.

> What version of the Carbon Design System are you using?
V10

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Watson for Protocol Development (Watson Health).  We would like to have this available for a 3rd-quarter release.

## Steps to reproduce the issue
You can see this behavior (or, rather, lack of behavior) in the storybook example (https://angular.carbondesignsystem.com/?path=/story/ui-shell--together).

## Additional information

* Screenshots or code
* Notes

**Comment by cal-smith** [comment]
Poking through [the demo](https://www.carbondesignsystem.com/experimental/ui-shell/code) and [the scss](https://github.com/IBM/carbon-components/blob/master/src/components/ui-shell/_header.scss#L34-L76) it seems like they have styles for that ... Let me know if you're interested in tackling this, I'll put it in our Q2 project either way :+1:
