### ISSUE TITLE
Decision on component/directive prefixes

### ISSUE THREAD

**Issue by theiliad** [IBM/carbon-components-angular#51]
So currently we're using the `ibm` prefix for our component & directive names.

I understand the reservations of using `carbon` or `cds` for now (internal discussion), but I think we should ideate more on this.

Feel free to present your ideas as well

**Comment by zvonimirfras** [comment]
Prefix will likely depend on the resolution of that internal discussion, and it might as well stay `ibm` so let's pick this up then.

It's good that we have this as a reminder, though.

**Comment by cal-smith** [comment]
Closing this since there's no strong argument to change it as of yet
