### ISSUE TITLE
bug(tooltip): tooltip caret always positioned at the top

### ISSUE THREAD

**Issue by youda97** [IBM/carbon-components-angular#512]
## Detailed description

> Describe in detail the issue you're having.

When changing the placement of the tooltip to left, right or top and caret it always positioned at the top and does not readjust.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?

caret should readjust instead of staying at the top of the tooltip. For example, if its placement is to the left and caret should be on the right of the tooltip.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.0.0

## Additional information

[storybook](https://angular.carbondesignsystem.com/?path=/story/tooltip--basic)

**Comment by cal-smith** [comment]
style reference: https://www.carbondesignsystem.com/components/tooltip/style

Seems like only top/bottom are supported

**Comment by dsuwirya** [comment]
'bottom' works fine, however when 'top' is used the caret position is not correct:

![image](https://user-images.githubusercontent.com/5710527/56746197-59e18d80-6741-11e9-8b47-53a0cbec4605.png)

**Comment by cal-smith** [comment]
I can't seem to reproduce the "blink" in the storybook ... a codesandbox that showcases the issue would be awesome :+1:

**Comment by abhisheksinghrana** [comment]
Hi team,
Seems like issue still persist.
https://codesandbox.io/s/carbon-angular-tooltip-w0gym
