### ISSUE TITLE
Search Component in toolbar mode closes even if there is a value

### ISSUE THREAD

**Issue by SaschaSchwarze0** [IBM/carbon-components-angular#535]
The Search component can be used in a toolbar mode (https://angular.carbondesignsystem.com/?path=/story/search--toolbar-search).

If the search is opened and a value is entered and one focuses somewhere else, the search closes.

Carbon describes something about the search in this mode here: https://www.carbondesignsystem.com/components/data-table/usage,  "Search returns results based on matches. It is used to locate and display a set of results. Search functionality within a table follows small search conventions. Search should be closed by default, and live below the table title."

There is no statement that it should be closed at all. I can understand an auto-close if there is no value, but if there is a value, then it does not make sense to close it.

**Comment by youda97** [comment]
This issue seems to be resolved. Feel free to open another issue if it is still not working as expected
