### ISSUE TITLE
Bug: Can't assign a function to X Button of Filter Tag Component

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#538]
## Detailed description
This is a bug on filter tag component, you can't assign an action/function to the close/cancel button when using the angular component, it should be possible.
What I would like it to be is to be like a prop or something called like buttonAction and assign a specific function to what it should do when clicking the X button in it.

## Steps to reproduce the issue

Implement a Filter Tag component on any view you want, click on the X button, it won't do anything and you can't assign the action directly in the component tag

**Comment by cal-smith** [comment]
You should be able to bind a `click` on the tag itself, at least as a short term solution ... we can totally add a specific `close` event for the close/cancel button though :+1:

**Comment by Pablodotnet** [comment]
I'll make a PR with this functionality this weekend 👍

**Comment by cal-smith** [comment]
Sounds good!
