### ISSUE TITLE
add ui shell component - no style

### ISSUE THREAD

**Issue by wddrosa** [IBM/carbon-components-angular#539]
Hi ,

I am testing the UI Shell component on my local.
Mine is angular project, so I am referring the storybook  here in https://angular.carbondesignsystem.com/?path=/story/ui-shell--header

After imported UIShellModule and just copy the Header template to my html.
And see how it looks is below:
![image](https://user-images.githubusercontent.com/33858531/57506899-c064cf00-732f-11e9-986d-cdddd94ce584.png)

That seems the style doesn't load successfully.
But I can not find css of "bx--header" in my carbon components in  "/node_modules/carbon-components/css/carbon-components.min.css".

Any ideas about this issue?

Thanks very much!

**Comment by cal-smith** [comment]
Since it's experimental you'll need to load the carbon components scss, and set up your `styles.scss` like so:

```scss
$feature-flags: (
	ui-shell: true
);

@import '~carbon-components/scss/globals/scss/styles';
```

Our [carbon angular starter repo](https://github.com/carbon-design-system/carbon-angular-starter) has the style imports configured, you'd just need to add the `feature-flags`

**Comment by wddrosa** [comment]
Sorry for  response late.

I cloned the carbon-angular-starter repo to my local and   added the code  `$feature-flags: (
	ui-shell: true
);   @import '~carbon-components/scss/globals/scss/styles';  `   to my styles.scss.
But the result  is that  the chrome can load the style, but not for Firefox.

Mine is Mac OS.Please help to have a look.
Thanks very much!

![image](https://user-images.githubusercontent.com/33858531/57610281-142b1e80-75a3-11e9-8c5f-36e9de19974e.png)

![image](https://user-images.githubusercontent.com/33858531/57610566-9fa4af80-75a3-11e9-8441-1d5f7147060a.png)
