### ISSUE TITLE
Data Table Pagination items per page select options are not configurable

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#546]
## Data table pagination items per page select options are not configurable: 
For data table pagination, we can select how many items to show on each page with model.pageLength, but if we select for example 5, the items per page select won't show with options like 5, 10, 15, 20, etc... and it doesn't show either until you click it and select 10.

## Detailed description
This is a feature request/bug may be, it is related to data table pagination, the problem is that if we define a model.pageLength for example to 5, the options on items per page should be 5, 10, 15, 20... BUT they are always with multiples of 10, it should change with multiples of what we define in pageLength.

## Steps to reproduce the issue
Add a data table with pagination, set model.pageLength to something different to 10 and items per page select won't show the select option, and if you open the select it will display only 10, 20, 30, 40, 50 options, it won't adapt to what you set in pageLength.

## Additional information

Data table with pageLength setted to 5: 

<img width="593" alt="Screen Shot 2019-05-14 at 9 40 59 AM" src="https://user-images.githubusercontent.com/10190000/57707005-7b40e580-762c-11e9-87ca-7ffd69674508.png">

Selected option dissapeared, and if you open the select the options always will be multiples of 10:

<img width="586" alt="Screen Shot 2019-05-14 at 9 41 17 AM" src="https://user-images.githubusercontent.com/10190000/57707168-c3f89e80-762c-11e9-87b9-e03b3d3c05f4.png">

**Comment by cal-smith** [comment]
We should probably just allow the user to specify an array of items per page ... so you can do `[5, 10, 15, 20]` or `[2, 4, 6, 8]` and just default it to `[10, 20, 30, 40, 50]`.

That way `pageLength` can be automatically set by the pagination

**Comment by Pablodotnet** [comment]
I was thinking more in using the pageLength to set the options automatically with a new option may be to set the limit of the option, for example I want pageLength in 5 and limit option to be 50, so make a cycle to set the options until reach the limit.

**Comment by cal-smith** [comment]
That's one approach, but what if the developer needs to do something like `[10, 50, 100]` ... `pageLength` tells us what the current length of one page is, but it's not very good at letting us define a set of lengths we can let the user choose from

**Comment by zvonimirfras** [comment]
Cal's approach allows all the use cases and devs can easily generate an array based on their desired pageLength.

**Comment by Pablodotnet** [comment]
Ok, I'll do it with Cal's approach 👍

**Comment by stanislavgeorgiev** [comment]
Any chance of merging the fix in the v2 stream?

**Comment by cal-smith** [comment]
For sure ... if you want to contribute the fix that would be awesome as well 👍 just be sure to pull from the `v9` branch

**Comment by stanislavgeorgiev** [comment]
I could try to do it but cannot do it this or next week...

**Comment by cal-smith** [comment]
No rush right now, so up to you! If it becomes more urgent we can take it over.

**Comment by Pablodotnet** [comment]
@cal-smith I can do the fix for v2 too if you want, just tell me which branch to use

**Comment by cal-smith** [comment]
@Pablodotnet sure! Base your changes off the v9 branch

**Comment by cal-smith** [comment]
I'll open a new issue for this 👍 - #550

**Comment by stanislavgeorgiev** [comment]
That would be great @Pablodotnet! Thanks!
