### ISSUE TITLE
(v2) Date Picker: Ignores `dateFormat` property value

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#554]
## Detailed description

> Describe in detail the issue you're having.

We're trying to localize the Date Picker's picked date through setting the `dateFormat` property. We tried `Y-m-d` (general) and `d.m.Y` (German) but both gets ignored and the value still shows as `m/d/Y` (US)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Date Picker

> What did you expect to happen? What happened instead? What would you like to see changed?

The component should ideally react to the browser language. At least it should respect the property setting.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v2@latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

**Comment by stanislavgeorgiev** [comment]
Would there be a review soon?

**Comment by cal-smith** [comment]
Just waiting on @zvonimirfras

**Comment by stanislavgeorgiev** [comment]
@zvonimirfras Can we have this back ported to v2 please?

**Comment by zvonimirfras** [comment]
@stanislavgeorgiev sure, I'll try to get to it. Do you, by any chance wish to open a PR with the code from https://github.com/IBM/carbon-components-angular/pull/537/files to [v9 branch](https://github.com/IBM/carbon-components-angular/tree/v9)?

**Comment by stanislavgeorgiev** [comment]
I tried @zvonimirfras but it's a bit over my head how to accept his PR into my v9-stan branch. I spent an hour just trying to figure out how to get the v9 code at all :D

**Comment by cal-smith** [comment]
😬 if I have some time I'll see about writing some docs around dealing with the v9 branch
