### ISSUE TITLE
Can't close toast notifications

### ISSUE THREAD

**Issue by erifsx** [IBM/carbon-components-angular#56]
> Describe in detail the issue you're having.

In https://github.com/IBM/carbon-components-angular/blob/master/src/banner/toast.component.ts
`bx--toast-notification__close-button` doesn't have a click listener like https://github.com/IBM/carbon-components-angular/blob/master/src/banner/banner.component.ts does.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Toast notifications

**Comment by zvonimirfras** [comment]
@cal-smith wanna take this one?

**Comment by cal-smith** [comment]
huh, oops, yeah I can take a look at this
