### ISSUE TITLE
Copy icon of <ibm-code-snippet> is not showing up in IE 11

### ISSUE THREAD

**Issue by dsuwirya** [IBM/carbon-components-angular#567]
Steps to reproduce:
- Open IE 11
- Go to : https://angular.carbondesignsystem.com/?path=/story/code-snippet--basic
- Missing copy icon as follow:

![image](https://user-images.githubusercontent.com/5710527/58274268-21d96480-7d58-11e9-9021-7c58e4a21708.png)

note. there might be similar issue in IE 11 with other components using SVG ? ref. https://github.com/carbon-design-system/carbon-elements/issues/519

**Comment by cal-smith** [comment]
fixed in `icons-angular` waiting for carbon patch release
