### ISSUE TITLE
Can't use <ibm-label> without <input> element

### ISSUE THREAD

**Issue by dsuwirya** [IBM/carbon-components-angular#568]
When using `<ibm-label>` without having `<input>` element, the following exceptions thrown:

![image](https://user-images.githubusercontent.com/5710527/58274747-24888980-7d59-11e9-92c4-a06eeffac6e6.png)

**Comment by cal-smith** [comment]
Yep, right now `ibm-label` only works on a limited subset of our form components. We have a few PRs open around standardizing our inputs, so hopefully we can expand it's use in the future!

**Comment by cal-smith** [comment]
So, with several of the changes we've made to our form controls it doesn't really make a whole lot of sense to use `ibm-label` with them - they already support all the same `Input`s. At the moment the path forward seems to be standardizing and abstracting those parts of the template/component class internally (of course all our internal components will be exported for general use :+1:)
