### ISSUE TITLE
Overflow Menu (v2): Thrown an `ExpressionChangedAfterItHasBeenCheckedError` when showing a modal

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#571]
## Detailed description

> Describe in detail the issue you're having.

I'm showing a modal dialog invoked from an overflow menu item. Everything works ok but I get this error in the console coming from `OverflowMenuOption.html:2`

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'tabIndex: 0'. Current value: 'tabIndex: -1'.
    at viewDebugError (VM27924 vendor.js:63213)
    at expressionChangedAfterItHasBeenCheckedError (VM27924 vendor.js:63201)
    at checkBindingNoChanges (VM27924 vendor.js:63303)
    at checkNoChangesNodeInline (VM27924 vendor.js:66174)
    at checkNoChangesNode (VM27924 vendor.js:66163)
    at debugCheckNoChangesNode (VM27924 vendor.js:66767)
    at debugCheckRenderNodeFn (VM27924 vendor.js:66721)
    at Object.eval [as updateRenderer] (VM27992 OverflowMenuOption.ngfactory.js:31)
    at Object.debugUpdateRenderer [as updateRenderer] (VM27924 vendor.js:66710)
    at checkNoChangesView (VM27924 vendor.js:66064)
```

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

`ibm-overflow-menu-option`, could be caused by `ibm-overflow-menu-pane: afterDialogViewInit()`

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

2.45.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

**Comment by youda97** [comment]
Can you provide an example with minimal code?

**Comment by KlavierCat** [comment]
The Assess UX Redesign team has seen the same problem and here is a gif reproducing this:

![OverflowMenuOption](https://user-images.githubusercontent.com/5871704/63096921-0e105980-bf67-11e9-963b-49ed888a59aa.gif)

Related code:
1. in https://github.ibm.com/talent-incubator/assess-ux-redesign/blob/master/src/app/pages/invitations/open-invitation/candidate-table/candidate-table.component.ts  , search for `resetAssessment`
2. in https://github.ibm.com/talent-incubator/assess-ux-redesign/blob/master/src/app/services/assessment-action.service.ts , search for `resetSession`.

**Comment by panpan-lin** [comment]
The Assess UX Redesign team has seen the same problem and here is a gif reproducing this:

![OverflowMenuOption](https://user-images.githubusercontent.com/5871704/63096921-0e105980-bf67-11e9-963b-49ed888a59aa.gif)

Related code:
1. in https://github.ibm.com/talent-incubator/assess-ux-redesign/blob/master/src/app/pages/invitations/open-invitation/candidate-table/candidate-table.component.ts  , search for `resetAssessment`
2. in https://github.ibm.com/talent-incubator/assess-ux-redesign/blob/master/src/app/services/assessment-action.service.ts , search for `resetSession`.

**Comment by cal-smith** [comment]
@panpan-lin are you still seeing this in `carbon-components-angular@2.49.2`?

**Comment by panpan-lin** [comment]
Our `package.json` shows the following versions:
```
    "@carbon/icons-angular": "10.3.2",
    "carbon-components": "10.3.2",
    "carbon-components-angular": "3.11.4", 
```

**Comment by cal-smith** [comment]
Ah, interesting, so it seems like it's an issue with v3 as well ... thanks! We'll check it out 🤔

**Comment by panpan-lin** [comment]
Just talking to our lead Mark and he thinks this PR of yours might have fixed it:
https://github.com/IBM/carbon-components-angular/pull/674

We'll see if we can upgrade our Carbon Angular version and see how that goes and let you know.

**Comment by panpan-lin** [comment]
Actually, just had another look at that PR seems to be included for the version 2.49.2, so now we are not quite sure if upgrading our v3 to a newer version will solve our problem.

**Comment by cal-smith** [comment]
Yeah, we need to pull and test the changes from that PR into `master` to get it released on v3 ... if you want to take a stab at that the contribution would be more than welcome :+1:

**Comment by panpan-lin** [comment]
Sure, I'll take a look.

**Comment by stanislavgeorgiev** [comment]
@zvonimirfras @cal-smith Thanks for fixing this!
Can you please port it to the v2 branch where it was filed?

**Comment by cal-smith** [comment]
This was originally fixed in v2 first 🙂 

If you're still running into this on the latest v2 release, let me know

**Comment by stanislavgeorgiev** [comment]
Which version would that be in @cal-smith ? I see only the 3.14.4

**Comment by panpan-lin** [comment]
@stanislavgeorgiev In [this PR](https://github.com/IBM/carbon-components-angular/pull/674) it says `2.49.2` ?

**Comment by stanislavgeorgiev** [comment]
ah ok, thanks @panpan-lin
