### ISSUE TITLE
Dropdown not working in IE11 in version v9, release version 2.47.4

### ISSUE THREAD

**Issue by vinitmohata** [IBM/carbon-components-angular#577]
## Detailed description
After upgrading from version 2.36.1 to 2.47.4, dropdown stops working, On click of dropdown , dropdown list is not showing for any type dropdown in IE11.

> Is this a feature request (new component, new icon), a bug, or a general issue? Issue

> Is this issue related to a specific component? dropdown component

> What did you expect to happen? What happened instead? What would you like to see changed? It should display dropdown list contents when click on dropdown.

> What browser are you working in? IE11

> What version of the Carbon Design System are you using? 2.47.4

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? 
In storybook it is reproducible
https://angular.carbondesignsystem.com/2.47.4/?path=/story/dropdown--multi-select

## Steps to reproduce the issue
1. Go to https://angular.carbondesignsystem.com/2.47.4/?path=/story/dropdown--multi-select in IE11
2. Select dropdown module
3. Select multi-select dropdown
4. Click on dropdown button
5. It will not show dropdown list contents

## Additional information

* Notes
Dropdown are working fine in version 2.36.1 in IE.

**Comment by vinitmohata** [comment]
@cal-smith : Can anyone work on this? As per my finding moving toggleMenu() function to <button> tag will fix it.

**Comment by cal-smith** [comment]
If you've identified a fix it would be great if you could also contribute it 👍 just pull from the `v9` branch on your upstream and apply the changes based on that. Otherwise we'll get to it soonish.

**Comment by cal-smith** [comment]
fixed by #611
