### ISSUE TITLE
Enhance <ibm-table> feature - add colspan and rowspan feature 

### ISSUE THREAD

**Issue by wcongkevin** [IBM/carbon-components-angular#580]
I want to implement colspan and rowspan feature for <ibm-table>  . 

As you can see in imagine .

![image](https://user-images.githubusercontent.com/13159235/58624992-11029300-8304-11e9-8aec-70a74c748d7d.png)

**Comment by zvonimirfras** [comment]
Use case in the image _should_ be implemented using a custom template for a table cell.

See [table documentation](https://angular.carbondesignsystem.com/documentation/components/Table.html) for more details.

**Comment by wcongkevin** [comment]
This is not only display image in <ibm-table> but also rowspan table cell . As you may see here .
![image](https://user-images.githubusercontent.com/13159235/58636992-18399900-8324-11e9-9145-9c52eaa5d986.png)

**Comment by zvonimirfras** [comment]
Thanks for pointing it out. I saw that, it's perfectly fine to have two lines in the same cell without merging cells. One way to achieve this is with a custom template, putting a `<br>` after the "Name".
It looks like you will have to use custom templates anyway, to get different font styles.

That would make your table look kind like:

```
----------------------------------
|       | ISG_Connector Name<br> |
| Image |                        |
|       | jdbc:mariadb://....... |
----------------------------------
|       | ISG_Connector Name<br> |
| Image |                        |
|       | jdbc:mariadb://....... |
----------------------------------
```

`-`s and `|`s represent cell boundaries

**Comment by wcongkevin** [comment]
Hi ,how to add image in this  customTableItemTemplate


![image](https://user-images.githubusercontent.com/13159235/59589129-d8dcbc00-911b-11e9-85bb-9c1ea88aed9b.png)

**Comment by wcongkevin** [comment]
Hi ,how to add image in this customTableItemTemplate
![image](https://user-images.githubusercontent.com/13159235/59589238-15101c80-911c-11e9-9bb9-06fb7d3aa10e.png)

**Comment by wcongkevin** [comment]
I haven't seen any image embed table in example

**Comment by zvonimirfras** [comment]
Hi Cong, there's no specific example for images because you would just use html `img` tag in the custom template (the thing you put the red border around in the screenshot).

So along the lines of `<img src="img-location.jpg">`...

**Comment by wcongkevin** [comment]
Hi Bro . How to remote checkbox in the first carbon table col ? 
![image](https://user-images.githubusercontent.com/13159235/59667265-02174e00-91e9-11e9-8124-5d93c08228bb.png)

**Comment by wcongkevin** [comment]
Hi zvonimirfras .
Here two question .

1,I already have set this property false . But checkbox is still displaying the first column of table . 
![image](https://user-images.githubusercontent.com/13159235/59996038-c1598200-968b-11e9-89b6-34d967384365.png)
2, No matter what put between cn.name & cn.url (e.g. <br> . /n ) .  Line is not changed to next . Please give some advice . Thanks . 
![image](https://user-images.githubusercontent.com/13159235/59996101-f06ff380-968b-11e9-992f-ece5c8dca423.png)

**Comment by wcongkevin** [comment]
HI zvonimirfras , Is there any carbon dialog example that I can refer to ?

**Comment by zvonimirfras** [comment]
This conversation turned into something unrelated to the issue, it's really old and the original question seems to have been answered.
