### ISSUE TITLE
[Slider]: "Expression has changed after it was checked"

### ISSUE THREAD

**Issue by virkt25** [IBM/carbon-components-angular#582]
## Detailed description

> Describe in detail the issue you're having.

Slider is working fine but seeing an error in the console coming from the slider. There was a value set for the slider (and it worked as expected).

![image](https://user-images.githubusercontent.com/3311536/58673447-6a28f180-8319-11e9-96aa-e170f4a88b8e.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

General Issue

> Is this issue related to a specific component?

Slider

> What did you expect to happen? What happened instead? What would you like to see changed?

Didn't expect to see an error message in the console coming from this component.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

3.7.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Internal Tool

## Steps to reproduce the issue

You can see the implementation here (internal link): https://github.ibm.com/client-success/cs360/blob/master/packages/ui/src/app/records/records.component.html#L36

## Additional information

* Screenshots or code
* Notes

**Comment by zvonimirfras** [comment]
Thanks for reporting this, TV!
These are annoying to see, annoying to fix and easy to miss.
