### ISSUE TITLE
[Slider] Knob starting at incorrect position

### ISSUE THREAD

**Issue by virkt25** [IBM/carbon-components-angular#584]
[Slider] Starting at the incorrect position

## Detailed description

> Describe in detail the issue you're having.

I have a Slider that has a range of 0 - 100. The initial value of the slider is set to 100 BUT that knob for the slider seems to be stuck at around 80% which the input box is showing the value as 100. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Slider

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected the know to be at 100 when the value is set to a 100.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

3.7.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

An internal tool.

## Steps to reproduce the issue

Internal Link. You can see the implementation here:

https://github.ibm.com/client-success/cs360/blob/master/packages/ui/src/app/records/records.component.html#L37-L47

and 

https://github.ibm.com/client-success/cs360/blob/master/packages/ui/src/app/records/records.component.ts#L13-L29

## Additional information

* Screenshots or code

Screenshot

![image](https://user-images.githubusercontent.com/3311536/58737059-1debb900-83ce-11e9-8548-70a986f4a6dd.png)

* Notes

**Comment by cal-smith** [comment]
Hi, @virkt25 ... your links appear to be dead, additionally I can't replicate the issue in our storybook environment. Updated links, and/or minimal reproduction would help debug this.

**Comment by virkt25** [comment]
The repo was renamed. Here are new links:

https://github.ibm.com/client-success/chi-explorer/blob/master/packages/ui/src/app/records/records.component.html#L37-L47

https://github.ibm.com/client-success/chi-explorer/blob/master/packages/ui/src/app/records/records.component.ts#L13-L29

**Comment by cal-smith** [comment]
Thanks, I'll take a look 🤔

**Comment by cal-smith** [comment]
I believe this was fixed with #639

**Comment by stanislavgeorgiev** [comment]
@cal-smith I can still this being an issue in the latest environment. I working on #916 and setting a `value` different than 0 in the story doesn't move the handle. Can you check?
