### ISSUE TITLE
NotificationService does not remove references to closed notifications

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#587]
## Detailed description

1. Open https://angular.carbondesignsystem.com/?path=/story/notification--dynamic
1. Open developer tools
1. Set a breakpoint at `NotificationService.showNotification`
1. Click the 'Show info notification button' and allow code to proceed past the breakpoint
1. Close the notification
1. Repeat previous two steps a few times
1. Click the 'Show info notification button' 
1. Inspect `NotificationService.notificationRefs` and you will notice that the references to all of the notifications are still there. 
1. Expect that they would be cleaned up when a notification is closed.

> Is this a feature request (new component, new icon), a bug, or a general issue? Bug

> Is this issue related to a specific component? NotificationService

> What did you expect to happen? What happened instead? What would you like to see changed? References to notifications are removed when they are closed

> What browser are you working in? Chrome

**Comment by cal-smith** [comment]
closed by #602
