### ISSUE TITLE
Changing date picker through keyboard does not work anymore

### ISSUE THREAD

**Issue by SaschaSchwarze0** [IBM/carbon-components-angular#600]
Use a date picker component and type manually. A valueChange event is not anymore emitted on blur.

This functionality was added just two months ago by @rudolpho1 through pull request https://github.com/IBM/carbon-components-angular/pull/453.

These days, the datepicker inputs (https://github.com/IBM/carbon-components-angular/blob/1ee414ceeecfe9da2005e2633f708691b16a2fb7/src/datepicker/datepicker.component.ts#L46 and https://github.com/IBM/carbon-components-angular/blob/1ee414ceeecfe9da2005e2633f708691b16a2fb7/src/datepicker/datepicker.component.ts#L61) in the date picker do not anymore listen to the valueChange event.

**Comment by cal-smith** [comment]
That would be weird regression ... Which version of carbon-angular is this on? There has been a number of updates to date picker, and I'm not sure which branch the linked code refers to.

**Comment by SaschaSchwarze0** [comment]
Hi @cal-smith this came in with the recent update to 3.10.0.

**Comment by cal-smith** [comment]
Strange ... I'll poke it a bit more and see what happened
