### ISSUE TITLE
Dropdown (v2): Swallows space keys after it's been opened

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#604]
## Detailed description

> Describe in detail the issue you're having.

I have a dropdown with an item template which adds a search box in the items list. The issue is that when I type something in the search box it gets through the `Dropdown.onKeyDown()` method first which swallows the spaces.

![image](https://user-images.githubusercontent.com/1253469/59381894-80c44500-8d2a-11e9-88bd-9b48b730cf18.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the component to handle spaces only when it needs to open the menu and leave them to propagate otherwise.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

2.45.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

**Comment by cal-smith** [comment]
Strange, the `Dropdown` component already only processes spaces if the dropdown is closed and, as far as I can tell, it never explicitly stops propagation (though it does `preventDefault`, but again, only when the dropdown is closed).

The base dropdown list does have some extra handling for spacebar keydowns on items, but I see that you're using a custom list so that likely doesn't apply.

**Comment by cal-smith** [comment]
If the search box is in the list, it also shouldn't hit the `Dropdown` keydown handler _first_, since it would have to bubble from the search input ... 

A minimal repro would really help debug this one.

**Comment by stanislavgeorgiev** [comment]
Actually I use the default `dropdown-list` with an item template. Here's a minimal version of what I'm doing and the issue is still there:
https://codesandbox.io/embed/carbon-components-angular-d5xuv

**Comment by cal-smith** [comment]
Oh weird ... I also just noticed the dropdown list does a strange double guard ... So this definitely needs some more investigation. I'll have to check what the a11y interaction patterns are, if we don't need to handle space for that we should be fine with just enter ... 

As for space triggering a scroll (the usual reason for a `preventDefault` on space) ...  if we let it bubble to the actual scrolling container we should be able to stop it there, without swallowing it.

Also, I wouldn't rule out extending `dropdown-list` and applying your customizations to that, depending on what interactions you need to support.

**Comment by stanislavgeorgiev** [comment]
@zvonimirfras what about the v2 branch?

**Comment by zvonimirfras** [comment]
@stanislavgeorgiev We don't automatically backport everything. @youda97 can do it if you need it. 👍

**Comment by stanislavgeorgiev** [comment]
Yes, I need it please. If something is filed against the v2 branch then I'd imagine that's where the fix should land in first as it's a support issue.

**Comment by zvonimirfras** [comment]
Yes, that would make sense...

@youda97 please backport this fix to v2 :)

**Comment by stanislavgeorgiev** [comment]
Thank you :)

**Comment by cal-smith** [comment]
done!
