### ISSUE TITLE
Breaking change on inputs in version 3.8.0 and above

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#607]
## Detailed description
On previous versions the inputs were using full width available, but since version 3.8.0 they got smaller by default.
Updated both carbon components and carbon angular components to it's latest versions and the issue persists.

## Steps to reproduce the issue

1. Add an input to any screen (using 3.5.0 version).
2. See how it use all the available width by default.
3. Update version to 3.8.0
4. See how the size of the input drastically changed.

## Additional information

Version 3.5.0:
<img width="806" alt="Screen Shot 2019-06-14 at 11 39 20 AM" src="https://user-images.githubusercontent.com/10190000/59524756-4bd70000-8e9a-11e9-9380-af21adf821bb.png">

Version 3.8.0:
<img width="851" alt="Screen Shot 2019-06-14 at 11 36 18 AM" src="https://user-images.githubusercontent.com/10190000/59524766-509bb400-8e9a-11e9-9249-8af04476442b.png">

**Comment by cal-smith** [comment]
The only way I can recreate this is by adding `flex` to the body element, so it doesn't seem to be something we've done explicitly, but rather some side effects of carbon's styling ... I _can_ reproduce the issue down to `carbon-components-angular` 3.0.3 which seems to indicate it's not something we've introduced recently.

**Comment by cal-smith** [comment]
I'm going to tentatively close this since it doesn't seem to be a breaking change on our end. If you can come up with a minimal reproduction ( this stackblitz is a decent starting point https://stackblitz.com/edit/carbon-angular-base?file=src%2Fapp%2Fapp.component.html ) we can look into this some more :+1:

**Comment by cal-smith** [comment]
From slack
> https://carbon-angular-base-dvkh6g.stackblitz.io
> 
> I have done a stackblitz
> to reproduce the issue with input sizes
> on the link you wrote on my issue (edited) 
> I don't know if I pass the link to you it will be like a new project so I'll share screenshots
> Using carbon-components version 10.1.0 and carbon components angular 3.5.0 it looks like this:
> ![image](https://user-images.githubusercontent.com/1744185/62961171-4169b180-bdca-11e9-889a-3d50f7558e2e.png)
> Updating carbon components angular to latest version 3.14.2 it looks like this now
> ![image](https://user-images.githubusercontent.com/1744185/62961179-4595cf00-bdca-11e9-8ea4-be1244aacbbe.png)
> After deleting ibmGrid and size classes
> ![image](https://user-images.githubusercontent.com/1744185/62961206-50e8fa80-bdca-11e9-9844-cf624f631293.png)
> ![image](https://user-images.githubusercontent.com/1744185/62961214-547c8180-bdca-11e9-90b5-7fdb6e1d58dd.png)

**Comment by cal-smith** [comment]
@Pablodotnet try updating to a newer version of `carbon-components` _and_ a newer version of `carbon-components-angular` ... I'm having trouble loading the stackblitz, but checking locally and looking through the carbon changelogs it seems that a `width: 100%` was added to the `bx--text-input__field-wrapper` - removing the `width: 100%` in the story perfectly replicates your issue.

**Comment by Pablodotnet** [comment]
The issue have been fixed with an update of carbon-components! Thanks!
