### ISSUE TITLE
Remove `@angular/http` from 'peerDependencies'

### ISSUE THREAD

**Issue by chchwil** [IBM/carbon-components-angular#609]
## Detailed description

> Describe in detail the issue you're having.

The `@angular/http` package/module was deprecated in favor of `@angular/common/http`.  So there is no version 8.0 release of `@angular/http`, but making it a peer dependency requires a valid version to be installed to use `carbon-components-angular`.  So any project that tries to upgrade to Angular 8 with `carbon-components-angular` will fail on `npm install'.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug or general issue.

> What did you expect to happen? What happened instead? What would you like to see changed?

`@angular/http` is not directly imported into any module within the `carbon-components-angular` project, so It should be removed from `peerDependencies`.

Side note: The same is true for `@angular/compiler` and `@angular/platform-browser-dynamic`.  They aren't imported into any module within `carbon-components-angular`.  But those do have version 8 releases, so they won't break `npm install`.

Side side note: `@angular/platform-browser` only seems to be used in unit tests.  It can probably also be removed from `peerDependencies`.

## Steps to reproduce the issue

Create a project that has `carbon-components-angular` and Angular v8 as dependencies.  Run `npm install`.

**Comment by cal-smith** [comment]
Great catch! We'll look at removing those, since I don't see anything that would cause a breakage.

If you want to contribute a fix for this, that would be awesome 🎉
