### ISSUE TITLE
How can I override the styles of table component ?

### ISSUE THREAD

**Issue by dabeng** [IBM/carbon-components-angular#614]
## Detailed description

> Describe in detail the issue you're having.

I want to customize the detailed styles of component table. Is there other solution except for "::ng-deep" ?

> Is this a feature request (new component, new icon), a bug, or a general issue?

It's a feature.

> Is this issue related to a specific component?

No

**Comment by cal-smith** [comment]
I _think_ I answered your question in slack ... so closing :+1:

**Comment by natashadecoste** [comment]
@dabeng 

The carbon-angular-components library offers many base styles that may be extended, overridden and embelished in your application but it depends on your goals. Please consider adding more information for your issue including what you currently have and what you would like to see/change about the table (or other) component.

Angular plans on deprecating` /deep/`, `::ng-deep` and `>>>` so it is not suggested that you use those (and it shouldn't be necessary)

**Comment by natashadecoste** [comment]
Some ways to create custom styles for table (and other) carbon components (by overriding the styles) are to:

- add custom stylesheets with rules targeting the carbon selectors & classes
- add custom classes to carbon components (see classNames within table module)
- add custom templates for table (ex. providing a custom template to TableItem)
