### ISSUE TITLE
Cannot build even.

### ISSUE THREAD

**Issue by Saliva520319** [IBM/carbon-components-angular#615]
environment  
macos 10.12.6
➜  ~ node -v
v12.4.0
➜  ~ npm -v
6.9.0
angular 8
carbon latest

I just follow the official guide do the flows

$ npx @angular/cli new my-project --style=scss
$ cd my-project
$ npm i --save carbon-components-angular carbon-components

then in src/styles.scss:
@import "~carbon-components/scss/globals/scss/styles.scss";

then  I run ng serve --port 3000 in local

![image](https://user-images.githubusercontent.com/11515867/59985274-22b92b00-9663-11e9-9c1e-830647cdc549.png)

what should I do, I cannot google anything to solve this.

hope someone would help me.

UPDATE:
I also try this , but doesn't work too.
![image](https://user-images.githubusercontent.com/11515867/59985308-598f4100-9663-11e9-89df-97066e07b0a2.png)

![image](https://user-images.githubusercontent.com/11515867/59985318-7592e280-9663-11e9-9dfd-22d746fb5033.png)

**Comment by natashadecoste** [comment]
check that you have node-sass (listed as devDependancy in package.json) installed.

`npm install node-sass`

**Comment by zvonimirfras** [comment]
@Saliva520319 [Carbon Angular Starter](https://github.com/carbon-design-system/carbon-angular-starter) has everything set up (with ng cli) for a carbon angular project.

It's a recommended way to start with carbon-angular-components. Try it out ;)

**Comment by cal-smith** [comment]
This is an issue with carbon-components. At the moment they're just supporting `node-sass`, we're pushing for them to support the newer `dart-sass` compiler (what angular switched to).

**Comment by Saliva520319** [comment]
> node-sass

Solve my problem! Thanks!

**Comment by Saliva520319** [comment]
> This is an issue with carbon-components. At the moment they're just supporting `node-sass`, we're pushing for them to support the newer `dart-sass` compiler (what angular switched to).

I'll try~

**Comment by Saliva520319** [comment]
> @Saliva520319 [Carbon Angular Starter](https://github.com/carbon-design-system/carbon-angular-starter) has everything set up (with ng cli) for a carbon angular project.
> 
> It's a recommended way to start with carbon-angular-components. Try it out ;)

I'll try~
