### ISSUE TITLE
Table: Support for horizontal and vertical scroll is missing

### ISSUE THREAD

**Issue by abhisheksinghrana** [IBM/carbon-components-angular#619]
Hi Team,

Support for horizontal and vertical scroll is missing in Table component.
I need these features as I have to implement infinite scrolling and have lot of columns in table  with nowrap content.

I am using 
Angular v6
"carbon-components": "^10.2.0",
"carbon-components-angular": "^3.7.0",

**Comment by cal-smith** [comment]
This is an issue with carbon-components, please reopen the issue here: https://github.com/carbon-design-system/carbon
