### ISSUE TITLE
invalid is true for  ibm-select component, but no invalid style

### ISSUE THREAD

**Issue by wuwdd** [IBM/carbon-components-angular#620]
I set the invalid to true, the invalid text display, but the invalid style for ibm-select doesn't display.

I saw the documentation and found that, the inside logic is   *ngIf="!skeleton && invalid"  to display the style of invalid input select.
So that when I only set the invalid is true, the style can not display.
But when I set the skeleton=false and invalid=true, the selection list can not display as below.

Please have a look !

Thanks very much!

**Comment by wuwdd** [comment]
Sorry I failed to add the screenshot

**Comment by magedhennawy** [comment]
I can't seem to replicate this, please post a code snippet to help us out a bit more!

**Comment by wuwdd** [comment]
Hi I use carbon-angular v10.
My angular code is as below:

 ***.component.html**
  ` <div class="input-wrapper">
        <ibm-select
        [invalid]="contractStatusValid"	       
        [label]="statusLable"	        
        [invalidText]="contractStatusValidTxt"	        
        (selected)="selectedStatus($event)"	       
        >	
        <option value="default" disabled selected hidden>Select</option>
					<option value="On-going">On-going</option>					
					<option value="On-Hold">On-Hold</option>					
          <option value="Waiting on Client">Waiting on Client</option>	          
          <option value="Escalated">Escalated</option>	          
          <option value="Terminated">Terminated</option>
        </ibm-select>	          
      </div>`

***.component.ts**
`contractStatusValid:boolean = true;
statusLable="Status";
contractStatusValidTxt: string = "Status is required!";`

The result is:
<img width="345" alt="Screen Shot 2019-06-27 at 7 10 16 PM" src="https://user-images.githubusercontent.com/33924918/60647787-173ede80-9e71-11e9-9213-4140980b2597.png">

The expect result is :
<img width="276" alt="Screen Shot 2019-07-04 at 3 34 44 PM" src="https://user-images.githubusercontent.com/33924918/60647878-50774e80-9e71-11e9-94e4-7c6b8c855336.png">

**Comment by magedhennawy** [comment]
Hey! @wuwdd 

I used the following code based on your component:

`<ibm-select [invalid]="invalid"
		[label]="label"
		[invalidText]="invalidText"
		(selected)="selectedStatus($event)"	>
			<option value="default" disabled selected hidden>Select</option>
			<option value="On-going">On-going</option>	<option value="On-Hold">On-Hold</option>
			<option value="Waiting on Client">Waiting on Client</option>
			<option value="Escalated">Escalated</option>
			<option value="Terminated">Terminated</option>
		</ibm-select>`

and 
`			invalid: boolean("Show form validation", true),
			invalidText: text("Form validation content", "Please select an option."),
			label: text("Label text", "Select Label")`

And all the above is working as expected.
I think it may have to do with the wrapper you have around the component.
If you are able to, could you please provide a reproduced version of your code, for example on https://codesandbox.io/ or something similar. 

Thanks!

**Comment by wuwdd** [comment]
Yes!I can saw this can working well on code sandbox, but not on my local.
I use angular 7.2.0  carbon-components 10.2.0 carbon-components-angular 3.1.0 to implement this.
I will try to create a new angular project on GitHub to reproduce this.
Thanks very much!

**Comment by magedhennawy** [comment]
No problem!
Best of luck with your projects!
