### ISSUE TITLE
Table (v2): Ability to set custom class for rows

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#626]
## Detailed description

> Describe in detail the issue you're having.

I need to add a custom class to an entire row to apply some additional conditional styling. The only way to do that now is if I hack the `rowsContext` property which works only if the row is not selected.

I already have the code working, it's basically adding another `rowsClass` property which mimics the way how `rowsContext` is working.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

Table

> What version of the Carbon Design System are you using?

2.48.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

**Comment by stanislavgeorgiev** [comment]
https://github.com/IBM/carbon-components-angular/pull/631#pullrequestreview-259140756

@cal-smith @zvonimirfras Would now be a good moment to port this over to `master`? I know you're doing some table refactoring right now.

**Comment by cal-smith** [comment]
Yep now is good :+1: we'll make sure to pull it in to the table refactor as well

**Comment by stanislavgeorgiev** [comment]
ok, I will try to submit it today then.
