### ISSUE TITLE
side-nav  collapsed behavior 

### ISSUE THREAD

**Issue by kuroyuki** [IBM/carbon-components-angular#629]
[Angular Side Navigation example](https://angular.carbondesignsystem.com/?path=/story/ui-shell--side-navigation) shows an example of not Fixed left side menu. 
After one of commits related to https://github.com/carbon-design-system/carbon/pull/2786 in Carbon Components the behaviour changed :
a height of side tab elements changes while collapsed/expanded. 

I did not find any examples or descriptions outside Angular Carbon and not sure if this is common behavior or Angular Carbon specific. 

Nevertheless it doesn't look naturally. 

I would expect to preserve the same height while hover on dynamic side panel as it was before. 

Some screenshots:
![image](https://user-images.githubusercontent.com/1229090/60707236-f085b400-9f13-11e9-98fb-2ba50aad1aed.png)

On Hover:
![image](https://user-images.githubusercontent.com/1229090/60707616-d4cedd80-9f14-11e9-8d1a-a6f7f1ef49cc.png)

**Comment by cal-smith** [comment]
The switcher seems to have disappeared from the latest sidenav designs, so I don't think that's valid anymore ... it seems like the different heights in the rail is being addressed by some of the linked issues/PRs here: https://github.com/carbon-design-system/carbon/issues/2972

**Comment by zvonimirfras** [comment]
Doesn't look relevant any more.
