### ISSUE TITLE
Row sizes are not customizable

### ISSUE THREAD

**Issue by dabeng** [IBM/carbon-components-angular#642]
## Detailed description

I'm trying to set the rows size of table to 'sm' but it is not working. I’m using  carbon-components v10.2.0 and carbon-components-angular v3.11.2

## Steps to reproduce the issue

Just set property "size" to "sm" and check the row height of data table

**Comment by zvonimirfras** [comment]
Changing knobs [here](https://angular.carbondesignsystem.com/?path=/story/table--basic) to different sizes seems to have the expected effect.

**Comment by cal-smith** [comment]
Closing since this does appear to work
