### ISSUE TITLE
Changing date picker through keyboard does not work anymore

### ISSUE THREAD

**Issue by SaschaSchwarze0** [IBM/carbon-components-angular#643]
#600 did not fix it.

DatePickerInput emits a valueChange event and nothing in DatePicker is listening to this ... this is still the case.

**Comment by cal-smith** [comment]
To be clear, the bug here is with the value not updating the tabbing/clicking outside of the field? Not live updating as the value changes? If I enter a value in the current storybook and press `Enter` the value does change, but there does seem to be a bug when tabbing/clicking away from the input.

**Comment by SaschaSchwarze0** [comment]
@cal-smith yes, the usual way of keyboard navigation in a form = tabbing through the fields and entering the value. Requiring to press Enter to apply a manually entered date value would imo be unexpected.

**Comment by cal-smith** [comment]
Okay cool 👍 with #632 merged this should be a pretty straightforward fix

**Comment by SaschaSchwarze0** [comment]
@cal-smith and while fixing this, can you consider to change https://github.com/IBM/carbon-components-angular/blob/7df42d9b5c16edd8bbeaf5e91acee870c1360963/src/datepicker/datepicker.component.ts#L188

to

`if (this.value && this.value.length > 0) {`

to allow binding a null value?

Thank you.

**Comment by cal-smith** [comment]
Funnily enough I hit an issue with `ngModel` and binding null as I was refactoring so I ended up with https://github.com/IBM/carbon-components-angular/blob/5c83fbc589645fd80a48ea79e3d3be0feec0954e/src/datepicker/datepicker.component.ts#L186-L195

Mostly just internal messing around ... this way we don't have to special case `null` everywhere

**Comment by SaschaSchwarze0** [comment]
Successfully verified. Ty @cal-smith
