### ISSUE TITLE
Skeleton is not working as expected when sort method is added in <ibm-table> in v9

### ISSUE THREAD

**Issue by vinitmohata** [IBM/carbon-components-angular#645]
## Detailed description

> I have enabled skeleton in table and added (sort) method in <ibm-table> tag and also having pagination enabled. 
when skeleton is true, table skeleton not looks proper, it shows skeleton for dropdown icon of sort and header text is moved below to it.
so If we remove sort from ibm-table tag it works proper.

> Is this a feature request (new component, new icon), a bug, or a general issue? bug

> Is this issue related to a specific component? v9

> What did you expect to happen? What happened instead? What would you like to see changed? it should show skeleton as shown when sort event is not added in <ibm-table> tag

> What browser are you working in? Chrome, Firefox, IE11

> What version of the Carbon Design System are you using? v9 (2.49.0)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? Trade Lanes Project

## Steps to reproduce the issue

1. Create page with <ibm-table> tag which includes skeleton and sort event and pagination enabled
2. Set skeleton true
3. set model data
4. You will see skeleton is of two line one for sort dropdown icon and one for headers

## Additional information

* Screenshots or code
Issue :- 
![ISSUE](https://user-images.githubusercontent.com/25260816/61119656-ef76f880-a4b8-11e9-825f-f222af9fb5c6.png)

Expected :- 
![expected](https://user-images.githubusercontent.com/25260816/61119655-ef76f880-a4b8-11e9-98f5-55dc193f9bca.png)

**Comment by youda97** [comment]
#646 closes this

**Comment by vinitmohata** [comment]
@youda97 : This changes are released in version v9?

**Comment by cal-smith** [comment]
Well, it's merged into v9 ... looks like it didn't actually run a release though 😕

**Comment by vinitmohata** [comment]
@cal-smith , @youda97 : It seems that if I set sortable false for one of the header, then that issue occurs again.
I have added sortable false for last header, image is given attached.
![image](https://user-images.githubusercontent.com/25260816/61696362-d42aa980-ad52-11e9-8311-32fa302e0ce4.png)

**Comment by cal-smith** [comment]
Hmm ... There's definitely a bug in the skeleton logic ... As a work around you may be able to use a empty model (we have `Table.skeletonModel(rowCount: number, columnCount: number)` that will build one for you) and just swap the models out when you want to go non-skeleton state.

**Comment by vinitmohata** [comment]
@cal-smith: Thanks for the information related to workaround.

**Comment by zvonimirfras** [comment]
Looks like it should be closed in #950. Feel free to reopen if still an issue.
