### ISSUE TITLE
Tab dropdown left open when I click out without selecting

### ISSUE THREAD

**Issue by aradhikaIbm** [IBM/carbon-components-angular#659]
## Detailed description

> Describe in detail the issue you're having.
So when using the tabs in small mode, I cannot leave the dropdown without selecting an option.  I can click away and the tab dropdown remains open. 

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Tabs in small mode

> What did you expect to happen? What happened instead? What would you like to see changed?
I would expect the dropdown to close if I focus off the dropdown regardless of making a selection. 

> What browser are you working in?
Chrome  Version 75.0.3770.100

> What version of the Carbon Design System are you using?

    "carbon-components": "10.3.2",
    "carbon-components-angular": "3.12.1",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IWR 

## Additional information
https://angular.carbondesignsystem.com/?path=/story/tabs--basic  - You can see the issue in the storybook itself. 

In the dropdown storybook, I noticed i can leave the dropdown without making a selection.
https://angular.carbondesignsystem.com/?path=/story/dropdown--basic

**Comment by aradhikaIbm** [comment]
I've updated my version to 3.13.2. I still don't see it working. I see that the storybook is working. Is there something i can check to make sure something is not cached ?

**Comment by cal-smith** [comment]
Make sure your `package-lock.json` isn't hanging on to an older version ... generally we end up deleting and re-generating it when we're bumping versions

**Comment by aradhikaIbm** [comment]
I've debugged this a bit more. Based upon the change I see :

	@HostListener("focusout", ["$event"])
	focusOut(event) {
		if (this.tabListVisible && **event.relatedTarget** === null) {
			this.tabListVisible = false;
		}
	}

Upon debugging, I noticed that "event.relatedTarget" is not null. I'm not sure why. Our page does have content around the tab. I'd willing to share my dev server link with someone if needed.

**Comment by aradhikaIbm** [comment]
I've debugged this a bit more. Based upon the change I see :

	@HostListener("focusout", ["$event"])
	focusOut(event) {
		if (this.tabListVisible && **event.relatedTarget** === null) {
			this.tabListVisible = false;
		}
	}

Upon debugging, I noticed that "event.relatedTarget" is not null. I'm not sure why. Our page does have content around the tab. I'd willing to share my dev server link with someone if needed.
