### ISSUE TITLE
Overflow menu is positioned incorrectly when added to a table column

### ISSUE THREAD

**Issue by markewallace** [IBM/carbon-components-angular#66]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue
- Take the sample from this PR https://github.com/IBM/carbon-components-angular/pull/67
- Run the storybook and open the `Table with overflow menu` story
- Click in last column to display the overflow menu
- Expect the overflow menu to display in last column but displays in the first column

## Additional information
![overflow_in_table](https://user-images.githubusercontent.com/3009737/45546018-ee7f2700-b813-11e8-88ed-4b3f0b6a5fab.gif)

**Comment by zvonimirfras** [comment]
The problem seems to be with overflow menu not being appended to body.

**Comment by zvonimirfras** [comment]
Upon inspection, it might be more than that.

With append to body, I get _(with highlighted action, same as in Mark's example, clicked)_:

![with append to body](https://user-images.githubusercontent.com/9692126/45556036-4e6fd080-b808-11e8-8325-0f6a65209a3c.png)

@cal-smith Do you mind taking a look at positioning for this? Might be missing some code in positioning service. Replacing overflow menu with tooltip works as expected.

**Comment by cal-smith** [comment]
I haven't looked at it yet, but it may be an issue with the `display` or `position` of the overflow menu container.

Since tooltip works I think it's something on the overflow-menu side - position.service should be able to position just about any arbitrary element.
