### ISSUE TITLE
Table header height issue of 'sm' size

### ISSUE THREAD

**Issue by nitishjain07** [IBM/carbon-components-angular#666]
Hi Team,

There is a CSS bug when using 'sm' size table with no selectionColumn. In this case height of first <th> element remains 3rem instead of 1.5rem.

You can replicate the issue at - https://angular.carbondesignsystem.com/?path=/story/table--with-overflow-menu. Go to knobs tab, select size='small' and uncheck showSelectionColumn property.

We are using this in our project. Can we please expect the fix soon.

Thanks in Advance!

We are using the below versions of carbon:
"carbon-components": "^10.4.1",
"carbon-components-angular": "^3.13.1"

**Comment by youda97** [comment]
Hmm this seems to be a styling issue. You should raise this in [carbon-design-system](https://github.com/carbon-design-system/carbon)

**Comment by nitishjain07** [comment]
I have raised the same in the carbon-design-systems - https://github.com/carbon-design-system/carbon/issues/3503. Thanks!

**Comment by zvonimirfras** [comment]
Looks like this will be fixed in carbon-components css and there seems to be no further work needed in angular for this.

Reopen if needed.
