### ISSUE TITLE
NullInjectorError: No provider for Modal  !!high priority

### ISSUE THREAD

**Issue by MiraYuan** [IBM/carbon-components-angular#675]
## Detailed description

> Describe in detail the issue you're having.
in my ts file, I add below code:
import { Modal } from 'carbon-components';
...
constructor(...,
    public Modal: Modal) { 
   
  }
...
> Is this a feature request (new component, new icon), a bug, or a general issue?
bug
> Is this issue related to a specific component?
No
> What did you expect to happen? What happened instead? What would you like to see changed?
No error happen and use it successfully.
> What browser are you working in?
filefox
> What version of the Carbon Design System are you using?
https://v9.carbondesignsystem.com/getting-started/developers/
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
zOSMF, a project of IBM for system z.
## Steps to reproduce the issue
1. follow steps from website "https://v9.carbondesignsystem.com/getting-started/developers/vanilla" to use javascript in my angular project.
2 I add below code in my ts file which need use it:
import { Modal } from 'carbon-components';
...
constructor(...,
    public Modal: Modal) { 
   
  }
... 
3. open my project, it will return "NullInjectorError: No provider for Modal" in browser console.

1. follow steps from website "https://v9.carbondesignsystem.com/getting-started/developers/vanilla" to use javascript in my angular project.
2 I add below code in my ts file which need use it:
import { Modal } from 'carbon-components';
...
constructor(...,
    public Modal: Modal) { 
   
  }
... 
3. open my project, it will return "NullInjectorError: No provider for Modal" in browser console.

## Additional information

* Screenshots or code
* Notes
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/48002643/61847653-0e748200-aede-11e9-97a6-2d4850956e80.png">

**Comment by cal-smith** [comment]
The `Modal` class from `carbon-components` isn't an angular service. Perhaps you meant to use `ModalService` from `carbon-components-angular`?

Either way, I see no bug here, high priority or otherwise.
