### ISSUE TITLE
!!! high priority !!!data-event "select-all" not take affection

### ISSUE THREAD

**Issue by MiraYuan** [IBM/carbon-components-angular#676]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?
https://v9.carbondesignsystem.com/components/data-table/code

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by cal-smith** [comment]
Please open an issue with more details.

I'm sorry the events aren't affectionate, but they're just code.
