### ISSUE TITLE
!!! high priority !!!Can't bind to 'model' since it isn't a known property of 'ibm-table'. 

### ISSUE THREAD

**Issue by MiraYuan** [IBM/carbon-components-angular#679]
## Detailed description

I've download carbon-components-angular by "$ npm i --save carbon-components-angular carbon-components", and add my style.css '@import "~carbon-components/scss/globals/scss/styles.scss";'

however, "import { storiesOf, moduleMetadata } from '@storybook/angular';" in my ts wills how no "@storybook/angular"

and when I use "<ibm-table [model]="model"></ibm-table>" in my HTML, it will show error 
Error: Template parse errors: Can't bind to 'model' since it isn't a known property of 'ibm-table'. 1. If 'ibm-table' is an Angular component and it has 'model' input, then verify that it is part of this module. 2. If 'ibm-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("  <ibm-table [ERROR ->][model]="model"></ibm-table>  "): ng:///AppModule/LoglevelListComponent.html@11:23 'ibm-table' is not a known element: 1. If 'ibm-table' is an Angular component, then verify that it is part of this module. 2. If 'ibm-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" 

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information
<img width="527" alt="image" src="https://user-images.githubusercontent.com/48002643/62017685-2a339d00-b1ea-11e9-8d10-602f9a450482.png">
<img width="967" alt="image" src="https://user-images.githubusercontent.com/48002643/62017715-446d7b00-b1ea-11e9-9658-9870b9956152.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/48002643/62017724-4f281000-b1ea-11e9-8cd4-82f149e58202.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/48002643/62017739-59e2a500-b1ea-11e9-8b0a-a2bc06e559a9.png">

* Screenshots or code
* Notes

**Comment by MiraYuan** [comment]
Please don't close this quickly, I need your help to start use carbon-components-angular in my ts project.

**Comment by MiraYuan** [comment]
Otherwise, I could use MatTable easily with 'import { MatTableModule } from '@angular/material';'. I'll very appreciate it if you could give me an example to use carbon tableModule successful.

**Comment by MiraYuan** [comment]
When I update to carbon-components-angular and carbon-components to 10, it works. This function only support carbon 10?

**Comment by youda97** [comment]
Firstly, you shouldn't be importing storybook. And for `ibm-table` to work you first need to import the module with `import { TableModule } from "carbon-components-angular";`

**Comment by MiraYuan** [comment]
Yes, I'd add it in my app.model.ts. what's more?

**Comment by MiraYuan** [comment]
Hi，the table is workable. I have another 2 questions:
1. Didn't carbon included edit table?
2. When use <ibm-tabs>, how to get elements created by HTML.(I'd tried both way that "document.getElementById("_messageBox")" and @ViewChild('_messageBox') messageBox: HTMLElement", and both them are null).

**Comment by MiraYuan** [comment]
Hi，the table is workable just with carbon10. I have another 2 questions:

    Didn't carbon included edit table?
    When use , how to get elements created by HTML.(I'd tried both way that "document.getElementById("_messageBox")" and @ViewChild('_messageBox') messageBox: HTMLElement", and both them are null).

**Comment by MiraYuan** [comment]
Hi，the table is workable just with carbon10. I have another 2 questions:

1. Didn't carbon included edit table?
2. When use , how to get elements created by HTML.(I'd tried both way that "document.getElementById("_messageBox")" and @ViewChild('_messageBox') messageBox: HTMLElement", and both them are null).

**Comment by youda97** [comment]
So what is your use case? What are you trying to accomplish?

**Comment by MiraYuan** [comment]
elements created in HTML with ”\<ibm-tabs\>\<ibm-tabs/\>“, I was trying to use it in my ts file. 
e.g.
”\<ibm-tabs\>\<input id="checkbox" type="checkBox"/\>\<div id="displayDiv" style="display:none"\>\<div/\>\<ibm-tabs\>\<ibm-tabs/\>“ ...
in my ts: if(document.getElementById("checkbox").getEttribute("checked")!=null){
    document.getElementById("displayDiv").style.display="";
}
In this case, both document.getElementById("checkbox") and document.getElementById("displayDiv") were null.

**Comment by MiraYuan** [comment]
elements created in HTML with ”\<ibm-tabs\>\</ibm-tabs\>“, I was trying to use it in my ts file. 
e.g.
”\<ibm-tabs\>\<input id="checkbox" type="checkBox"/\>\<div id="displayDiv" style="display:none"\>\<div/\>\<ibm-tabs\>\</ibm-tabs\>“ ...
in my ts: if(document.getElementById("checkbox").getEttribute("checked")!=null){
    document.getElementById("displayDiv").style.display="";
}
In this case, both document.getElementById("checkbox") and document.getElementById("displayDiv") were null.

**Comment by MiraYuan** [comment]
elements created in HTML with ”\<ibm-tabs\>\</ibm-tabs\>“, I was trying to use it in my ts file. 
e.g.
”\<ibm-tabs\>\<input id="checkbox" type="checkBox"/\>\<div id="displayDiv" style="display:none"\>\</div\>\<ibm-tabs\>\</ibm-tabs\>“ ...
in my ts: if(document.getElementById("checkbox").getEttribute("checked")!=null){
    document.getElementById("displayDiv").style.display="";
}
In this case, both document.getElementById("checkbox") and document.getElementById("displayDiv") were null.

**Comment by MiraYuan** [comment]
elements created in HTML with ”<ibm-tabs></ibm-tabs>“, I was trying to use it in my ts file.
e.g.
1. tab html:
\<ibm-tabs [followFocus]="followFocus" [isNavigation]="isNavigation"\>
            \<ibm-tab heading="{{ _messageService.getBundle('Tab_Collect_Titile') | translate}}"\>\<app-export-list\>\</app-export-list\>\</ibm-tab\>
            \<ibm-tab heading="{{ _messageService.getBundle('Tab_Loglevel_Title') | translate}}"\>\<app-loglevel-list\>\</app-loglevel-list\>\</ibm-tab\>
        \</ibm-tabs\>
2. app-export-list.html:
...
\<input id="checkbox" type="checkBox"/\>\<div id="displayDiv" style="display:none"\>\</div\>
 ...
3. app-export-list.ts: 
if(document.getElementById("checkbox").getEttribute("checked")!=null){
document.getElementById("displayDiv").style.display="";
}

In this case, both document.getElementById("checkbox") and document.getElementById("displayDiv") were null.

**Comment by MiraYuan** [comment]
Another case for edit table requirement:
this.model.data = [
      [
        new TableItem({ data: 'Name 1' }),
        new TableItem({
          data: { name: '<input value=\'Lessy\'/>', link: '#' },
          template: this.customTableItemTemplate,
        }),
      ],
...
]

Q: I want to create a input in gridcell to let customer could input data what they want.

**Comment by youda97** [comment]
This is not a carbon issue so there isn't much that I can help you with here

**Comment by youda97** [comment]
It does not look like you are using carbon-components-angular. You should be using the checkbox component from Carbon. Also, this does not look like a problem with carbon-components-angular. Maybe google it or reach out to your team for more help?

**Comment by youda97** [comment]
To use the table component you need to import the model and have the model defined in your typescript file
