### ISSUE TITLE
!high priority! When I use <ibm-tabs> to create two tabs, my ts file cannot find the element in tab page which created by HTML

### ISSUE THREAD

**Issue by MiraYuan** [IBM/carbon-components-angular#681]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information
In main html:
<ibm-tabs [followFocus]="followFocus" [isNavigation]="isNavigation">
            <ibm-tab heading="{{ _messageService.getBundle('Tab_Collect_Titile') | translate}}"><app-export-list></app-export-list></ibm-tab>
            <ibm-tab heading="{{ _messageService.getBundle('Tab_Loglevel_Title') | translate}}"><app-loglevel-list></app-loglevel-list></ibm-tab>
        </ibm-tabs>
in HTML of "app-export-list"
<table id="data_table" role="presentation" >
                <tr style="padding-left:10px;" >
                  <td>
                        <div class="bx--form-item bx--checkbox-wrapper">
                            <input type="checkbox" id="checkboxServer" name="checkboxServer" checked (change)="checkboxServerDiagChange()" class="bx--checkbox" >
                            <label  for="checkboxServer" class="bx--checkbox-label">{{ _messageService.getBundle('label_deFaultData') | translate }}</label>
                        </div>
                  </td>
...
in ts of "app-export-list", 
ngOnInit() {
    this.domCheckBoxServer = document.getElementById("checkboxServer");
...
}
it will show null....however, this code could work well if use "ngSwitch" for these two tabs.

* Screenshots or code
* Notes

**Comment by youda97** [comment]
Please look at our [storybook demo](https://angular.carbondesignsystem.com/?path=/story/welcome--to-carbon-angular) examples and [documentation](https://angular.carbondesignsystem.com/documentation/index.html) to help you get started with our components

**Comment by MiraYuan** [comment]
I’d read them...however, it not work well when I use it to my project....

**Comment by MiraYuan** [comment]
1. what I need import if I want to use "<ibm-icon-chevron-right16>"?
I'd import "Settings16Module,
    Delete16Module,
    Save16Module,
    Download16Module,".
2. Where could I found the ibm tag, such as <ibm-icon-chevron-right16>, reference which module?

**Comment by MiraYuan** [comment]
1. what I need import if I want to use "\<ibm-icon-chevron-right16\>"?
    I'd import "Settings16Module,
    Delete16Module,
    Save16Module,
    Download16Module,".
2 Where could I found the ibm tag, such as "\<ibm-icon-chevron-right16\>", reference which module?

**Comment by youda97** [comment]
You can find the icon library [here](https://www.carbondesignsystem.com/guidelines/iconography/library) and how to use icons-angular [here](https://github.com/carbon-design-system/carbon/tree/master/packages/icons-angular)
