### ISSUE TITLE
ToolTip Icon: Tooltip in IE is separated from pointer

### ISSUE THREAD

**Issue by aradhikaIbm** [IBM/carbon-components-angular#684]
## Detailed description

> Describe in detail the issue you're having.
Looking at the tooltip in IE, the tooltip is separated from the pointer (triangle). 

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug. In Chrome the the tooltip is attached to the pointer. 

> Is this issue related to a specific component?
tooltip icon 
https://angular.carbondesignsystem.com/?path=/story/tooltip-icon--basic

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
IE 11 

> What version of the Carbon Design System are you using?
v10.4 
carbon-angular -  3.13.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IWR

**Comment by cal-smith** [comment]
This is a bug in the carbon-components styles ... I'd suggest opening an issue there
