### ISSUE TITLE
Multiselect dropdown is not working when unselect the single selected dropdown item in version 2.49.0

### ISSUE THREAD

**Issue by vinitmohata** [IBM/carbon-components-angular#686]
## Detailed description

> Multiselect dropdown is not working when unselect the single selected dropdown item in version 2.49.0, once this conditions executed after that call to selected method stops working.

> Is this a feature request (new component, new icon), a bug, or a general issue? No

> Is this issue related to a specific component? Dropdown component

> What did you expect to happen? What happened instead? What would you like to see changed?
if user unselect the single selected value from dropdown it should call selected method with expected data.
> What browser are you working in?
Chrome, firefox, IE 11
> What version of the Carbon Design System are you using?
2.49.0
> What offering/product do you work on? Any pressing ship or release dates we should be aware of? TradeLanes (Having issue in production so need to be fix soon)

## Steps to reproduce the issue
Hi team, found new issue in multiselect dropdown in version 2.49.0.

Steps to reproduce:
1. Select one checkbox from dropdown and close dropdown
2. Open dropdown and unselect the selected one and close the dropdown.
3. Selected method will not call and user will see below error in console.
    TypeError: Cannot read property 'isUpdate' of null
    dropdown.component.ts:254,
4. After above error occured, calls to select method stops working.

## Additional information
* Notes : I have tested on version 2.47.4 and it's working fine there.

**Comment by vinitmohata** [comment]
@cal-smith : Any chances of getting this fixed soon?
This issue is in our production code.

**Comment by cal-smith** [comment]
Yep ... totally missed the production issue in the initial post

**Comment by cal-smith** [comment]
should be fixed with `carbon-components-angular@2.49.4`

**Comment by arslan-talib** [comment]
in multiselect dropdown, selected items not show in angular project, can anyone tell me the reason
and its working in separate task project but same code and step do in the project but selected items not shown
