### ISSUE TITLE
Tooltip displayed when no focus

### ISSUE THREAD

**Issue by aradhikaIbm** [IBM/carbon-components-angular#689]
## Detailed description

> Describe in detail the issue you're having.
Trying to understand the expected behavior of a tooltip when you focus away ? 
So when I click on the icon, I get the blue border and the tooltip popups. If I just move my mouse the tooltip stays up. It does not go away till I click somewhere else.

> Is this a feature request (new component, new icon), a bug, or a general issue?
general issue 

> Is this issue related to a specific component?
tooltips in general; We are using a tooltip icon where our tester found the issue. 

https://angular.carbondesignsystem.com/?path=/story/tooltip-icon--basic

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
Chrome, FF and IE

> What version of the Carbon Design System are you using?

    "carbon-components": "10.4.1",
    "carbon-components-angular": "3.13.2",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IWR

**Comment by cal-smith** [comment]
It's not clear to me what the issue is here, if any. It seems like you're describing browser specific behaviour. `tooltip-icon` is entirely CSS, so it's out of our control in any event.

**Comment by aradhikaIbm** [comment]
So I'm just trying to understand the expected behavior. So when using "ibm-tooltip-icon", a button is generated by the widget. If I can click on icon (ie the button) the tooltip does not go over when I move the mouse away. Is it expected for the icon to retain active/focus state upon onclick even if I've moved the mouse away ? Note the tooltip goes away if I click on anything else.

**Comment by cal-smith** [comment]
I can't replicate that behavior, so it sounds like something that is dependent on OS and browser behavior. The icon tooltip on the carbon site should behave the same, since it's all CSS driven. If this isn't the correct behavior and it needs to be fixed or for more clarity on this behavior, I would ask in #carbon-components or open an issue on the [carbon-design-system/carbon](https://github.com/carbon-design-system/carbon/issues/2911) repo.
