### ISSUE TITLE
There is an error when destroy a date-picker instance

### ISSUE THREAD

**Issue by ChenCheress** [IBM/carbon-components-angular#700]
## Detailed description
we have 2 tabs in a page, and one tab has a component which there is a datepicker in it, If we don't choose the tab contained date-picker, and navigate to another page, there is an error when destroy the date-picker
> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?
 component
> Is this issue related to a specific component?
ibm-date-picker
> What did you expect to happen? What happened instead? What would you like to see changed?
when navigate to another page and need to call ngDestroy
> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
3.14.2
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. we have 2 pages, 1st is homepage, 2nd is a tab page which have 2tabs, and Tab2 has a component, which contains a datepicker component.
2. visit homepage, then visit the tabpage which has tab1 as default,
3. Click back icon '<-' to return to homepage
4. The error appears

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/26919565/63008638-91717280-beb5-11e9-9810-1e9163349955.png)
![image](https://user-images.githubusercontent.com/26919565/63008724-c1207a80-beb5-11e9-9fbe-0153791cbcee.png)

* Notes
`this.flatpickrInstance` is an Array, when to run `this.flatpickrInstance.destroy();` we need to check the length of `this.flatpickrInstance`

**Comment by cal-smith** [comment]
Congrats on opening the 700th issue 🎉 

Also `this.flatpickrInstance` isn't an array, or at least it shouldn't be. checking `!this.flatpickrInstance && !this.flatpickrInstance.destroy` should be sufficient. If you'd like to open a PR with the fix that would be amazing.

**Comment by ChenCheress** [comment]
Thank you very much for your quickly support!

**Comment by ChenCheress** [comment]
@cal-smith Hi Cal, nice to speak to you, I just wonder when will this bugfix go release?

**Comment by cal-smith** [comment]
Hopefully soon ... I'm going to reopen this issue until the PR is merged - it'll automatically close the issue
