### ISSUE TITLE
ToolTip Icon: support additional placements (tooltip is cutoff) 

### ISSUE THREAD

**Issue by aradhikaIbm** [IBM/carbon-components-angular#703]
## Detailed description
> Describe in detail the issue you're having.

When using a the tooltip icon on a bar and if the bar is too small then the tooltip appears to cutoff. We have a line bar and the toolti[ spans the portion of a section of the bar. If the bar's width is too small then the tooltip scrolls off the screen and looks cut off.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug, maybe

> Is this issue related to a specific component?

tooltip icon

> What did you expect to happen? What happened instead? What would you like to see changed?

The tooltip box would have shown up more on the right if there was no space on the left. 

> What browser are you working in?

> What version of the Carbon Design System are you using?

v10.4.1
carbon-angular - 3.13.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IWR 

## Additional information

![image](https://user-images.githubusercontent.com/22798731/63115504-4e6ed800-bf65-11e9-808e-b004e7a7fa67.png)

vs when there is more space:

![image](https://user-images.githubusercontent.com/22798731/63115540-60507b00-bf65-11e9-9a0e-3608427ec6ec.png)

**Comment by zvonimirfras** [comment]
We currently support positioning top and bottom. Looks like styles since got support for also positioning left and right. Would implementing those solve your problem?

**Comment by erikavarga** [comment]
I'm not sure "left and right" would solve this issue. We want to keep the tooltip below the chart. Do you support the "start" position for bottom? This would solve our problem.
<img width="756" alt="Screen Shot 2019-08-19 at 1 59 48 PM" src="https://user-images.githubusercontent.com/54286076/63288028-b1c07900-c289-11e9-86e4-4a21651e63b3.png">

**Comment by cal-smith** [comment]
We don't support all the new positions at the moment (when did THAT happen!) we totally welcome a contribution that enables those though 👍
