### ISSUE TITLE
tooltip component: the tooltip covers the element in IE

### ISSUE THREAD

**Issue by ChenCheress** [IBM/carbon-components-angular#706]
## Detailed description
open carbon angular website in IE11, choose tooltip, then you find tooltip covers the element.
> Describe in detail the issue you're having.
https://angular.carbondesignsystem.com/?path=/story/tooltip-icon--basic
> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/26919565/63155490-38d0df80-c045-11e9-84e2-251dd1f779f6.png)

* Notes

**Comment by cal-smith** [comment]
That seems to be the icon tooltip ... can you confirm that it also breaks in the vanilla carbon-components? This seems like it may be a css issue

**Comment by ChenCheress** [comment]
> That seems to be the icon tooltip ... can you confirm that it also breaks in the vanilla carbon-components? This seems like it may be a css issue

![image](https://user-images.githubusercontent.com/26919565/63233819-e1a95580-c264-11e9-88bb-7bbb75e002b5.png)
Yes, it also breaks in the vanilla carbon-components, so do I need to open another issue for vanilla carbon-components

**Comment by asudoh** [comment]
Is this the same one as #3671?

**Comment by ChenCheress** [comment]
> Is this the same one as #3671?

Hi, I can't find #3671, could you give me a url about it, thank you!

**Comment by zvonimirfras** [comment]
> > Is this the same one as #3671?
> 
> Hi, I can't find #3671, could you give me a url about it, thank you!

Sure: https://github.com/carbon-design-system/carbon/issues/3671

**Comment by asudoh** [comment]
Thanks @zvonimirfras for correcting the link!

**Comment by emyarod** [comment]
https://github.com/carbon-design-system/carbon/pull/3739 should address the upstream issue

**Comment by cal-smith** [comment]
Awesome! Thanks for the quick resolution @emyarod

**Comment by cal-smith** [comment]
Upstream issue resolved! So, closing 🎉
