### ISSUE TITLE
IBM Header action icon colour

### ISSUE THREAD

**Issue by amitoj** [IBM/carbon-components-angular#715]
I know this forum is for bug requests, but I don't know where else to ask.
The document is not very clear on the usage of IBM Carbon themed icons in the Angular project.

```
  <ibm-header-global>
    <ibm-header-action aria-label="User">
      <ibm-icon-user20></ibm-icon-user20>
    </ibm-header-action>
  </ibm-header-global>
```

The above code adds a black user icon against a black background.

I'll appreciate if anyone can guide me towards the right icon type or CSS.

**Comment by cal-smith** [comment]
Check out https://github.com/carbon-design-system/carbon/tree/master/packages/icons-angular for more usage instructions for icons-angular.

You may find the directive form more useful - `<svg ibmIconUser20></svg>`

**Comment by amitoj** [comment]
Thanks, this is perfect
