### ISSUE TITLE
Issue with rendering the content text for tooltip-icon

### ISSUE THREAD

**Issue by pradeepkadiyala1980** [IBM/carbon-components-angular#723]
## Tooltip issue: 
 I am using tooltip icon and assigning the content. The tooltip display doesn't wrap the text and overflows the tooltip box. Any suggestions on how to overcome this. I am using carbon-components-angular latest version.

## Detailed description

> Describe in detail the issue you're having.
- We are using carbon component tooltip on content switcher buttons. 
- We have overridden the css of the contentswitcher component to display the overflow for each button. 
- The tooltip is displayed but the content inside the tooltip is not wrapping.
- I have tested this on carbon design system with knobs and found the same issue for tooltip icon component

![image (11)](https://user-images.githubusercontent.com/15691241/63790271-8f98ad80-c8be-11e9-92b0-6d5a681b6c92.png)

- The actual issue I see on our application is as below

![image (10) (10)](https://user-images.githubusercontent.com/15691241/63790328-a7703180-c8be-11e9-8038-b8c06cbacdb0.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?
This seems to be a bug

> Is this issue related to a specific component?
Tooltip-icon component

> What did you expect to happen? What happened instead? What would you like to see changed?
The content text of tooltip-icon should wrap inside the tootip box

> What browser are you working in?
Firefox, Chrome

> What version of the Carbon Design System are you using?
"carbon-components-angular": "3.15.1"
"carbon-components": "10.4.1",
"@carbon/icons-angular": "10.4.0",
"@carbon/themes": "10.5.0"

## Steps to reproduce the issue
This sandbox looks like react. I am having issue in angular.
You can reproduce in https://angular.carbondesignsystem.com/?path=/story/tooltip-icon--basic

Step 1: Goto Knobs tab
Step 2: Add the text `Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter Filter`

**Comment by Donisius** [comment]
It might be better to use the tooltip definition: https://angular.carbondesignsystem.com/?path=/story/tooltip-definition--basic as the content inside the tooltip will be wrapped in your application. However if you really wanted to use the tooltip icon you can overwrite the max-width styling.
