### ISSUE TITLE
Multi-select tiles do not initialize properly

### ISSUE THREAD

**Issue by pkreety** [IBM/carbon-components-angular#731]
Multi-select tiles with 'selected' flag just selects the last one
To reproduce it in the storybook: 
`<ibm-selection-tile *ngFor="let tile of [true, false, true, false]" value="tile1" [selected]="tile">Selectable Tile</ibm-selection-tile>`

@cal-smith

**Comment by cal-smith** [comment]
may be fixed by #724

**Comment by Donisius** [comment]
Everything works as expected.

**Comment by Donisius** [comment]
Everything works as expected!
