### ISSUE TITLE
header: header items disappear at 1056px view and lower 

### ISSUE THREAD

**Issue by youda97** [IBM/carbon-components-angular#732]
## Detailed description

> What did you expect to happen? What happened instead? What would you like to see changed?

The header items should be in the header at all times

> What browser are you working in?

Chrome

**Comment by cal-smith** [comment]
I believe this is part of the responsive styling ... the header items should collapse to a menu or something ...

**Comment by fionamurphy** [comment]
In the react example the header menu items collapse into the sidenav at 1056px view and lower:
http://react.carbondesignsystem.com/iframe.html?id=ui-shell--header-base-w-navigation-actions-and-sidenav&viewMode=story#
<img width="762" alt="Screenshot 2019-12-17 at 14 50 01" src="https://user-images.githubusercontent.com/46631345/71006341-1f1bd380-20dd-11ea-9277-075c4b9334c4.png">


They disappear in the angular example: https://angular.carbondesignsystem.com/?path=/story/components-ui-shell--together
<img width="708" alt="Screenshot 2019-12-17 at 14 50 45" src="https://user-images.githubusercontent.com/46631345/71006365-26db7800-20dd-11ea-9bf6-9a453170cf1d.png">

**Comment by cal-smith** [comment]
Thanks for the pointer ... I'm guessing there's some styles/containers that we're missing in the sidenav right now
