### ISSUE TITLE
File upload component - On the initial component load fileChanges event is getting fired 

### ISSUE THREAD

**Issue by amirkhan064** [IBM/carbon-components-angular#733]
## Detailed description
On the initial component load also fileChanges event is getting fired. Ideally, it should fire on file change. I found in carbon component source code that on ngOnInit() we are emitting this event.
example: In file (https://angular.carbondesignsystem.com/documentation/components/FileUploader.html#source)
ngOnInit() {
       // overrides the undefined files value set by the user
       if (!this.files) {
           this.files = new Set();
           this.filesChange.emit(this.files);
       }
   }

I am using the below carbon version:
"carbon-components": "^10.5.1",
"carbon-components-angular": "^3.14.4"

**Comment by zvonimirfras** [comment]
This will only happen if you don't supply initial files set to the component, so that's your workaround for now.

I see no reason why set couldn't be instantiated at definition, so I'm inclined to call this a bug.

@youda97 ? Any specific reason for this?
