### ISSUE TITLE
i18n cant find en.json v^3.15.1

### ISSUE THREAD

**Issue by henhen87** [IBM/carbon-components-angular#737]
I believe I may have found a bug. 
```
ERROR in ./node_modules/carbon-components-angular/__ivy_ngcc__/i18n/i18n.service.js

Module not found: Error: Can't resolve './en.json' in 'C:\Users\[me]\[Desktop]\IPAdvisor2.0\Front-End\AngularApp\node_modules\carbon-components-angular\__ivy_ngcc__\i18n'

```

I had to go to that location inside `node_modules` and add a copy of `en.json` inside `__ivy_ngcc__/i18n`, since the js file in there `i18n.service.js` is looking for it with 

```
var EN = require("./en.json");
```
but as mentioned `en.json` not in that directory. It is inside i18n directory in root of `angular-carbon-components`

**Comment by cal-smith** [comment]
We don't officially support the ivy compatibility compiler or ivy at the moment. Additionally, `@carbon/icons-angular` doesn't support ivy either.

We plan to upgrade our build system to fully support ivy in the future, but for the moment I recommend sticking with the old compiler.

**Comment by henhen87** [comment]
I am not sure if I used the `ivy compiler` specifically. The after installing package.json which has
```
"angular-carbon-components": "^3.15.1"
```
I do `ng serve` via `angular cli` and this error will show up. Is `ivy` related to the `i18n` directory? If so, that directory is created within the node_modules for angular-carbon-components.

**Comment by cal-smith** [comment]
`/__ivy_ngcc__/` folders are only created if your project is configured to use the ivy compiler. I'd double check your project configuration. [See here for the opt in instructions](https://angular.io/guide/ivy), the reverse should let you opt out.
