### ISSUE TITLE
ibm-tooltip-icon component hidden by select component

### ISSUE THREAD

**Issue by vvsby** [IBM/carbon-components-angular#743]
## Detailed description

> Describe in detail the issue you're having.

When I try to use **ibm-tooltip-icon** component as tooltip, I expect to see it under all other elements. But at this moment it has less priority than **ibm-select** component.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

ibm-tooltip-icon

> What did you expect to happen? What happened instead? What would you like to see changed?

Change z-index

> What browser are you working in?

Google Chrome
Version 76.0.3809.100 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

    "carbon-components": "^10.5.1",
    "carbon-components-angular": "^3.15.3",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
no
## Steps to reproduce the issue

1) Create simple table with 2 or more rows.
2) Add some ibm-select components for all rows and columns.
3) For one or more ibm-select add tooltip bigger than select element. 
```
 <ibm-tooltip-icon [content]="specificationRow.lessGreater" class="dropdown__middle">
      <div class="dropdown__middle">
         <ibm-select placeholder="Select" (selected)="tableChanged()" [id]="'lessGreater'+i"                                [(ngModel)]="specificationRow.lessGreater">
              <option   *ngFor="let factorValue of factorValues; index as factorValueIndex"     [value]="factorValue">
                                    {{factorValue}}
                </option>
            </ibm-select>
       </div>
 </ibm-tooltip-icon>
```
 4) Try to see tooltip text in first row (not last).

## Additional information

![image](https://user-images.githubusercontent.com/25610620/64697440-87896200-d4a9-11e9-9c94-665c22fe498b.png)

**Comment by cal-smith** [comment]
This seems to be an issue with the carbon styles ... I'd recommend opening an issue here: https://github.com/carbon-design-system/carbon/issues/new/choose

CC @asudoh/@emyarod (Not sure who's all working on Vanilla these days, so feel free to pass this on)

**Comment by zvonimirfras** [comment]
Since the related issue is closed in carbon, we can do very little else. If it's still relevant, provide the requested information in the linked issue and reopen it.
Due to the nature of it, when it's resolved on the styles side, it will likely reflect here as well.
