### ISSUE TITLE
UIShell - Header: Not able to set header banner's href

### ISSUE THREAD

**Issue by jdcai** [IBM/carbon-components-angular#747]
## Detailed description

> Describe in detail the issue you're having.

Currently when I click on the header banner it goes to # page and causes a page load.
I want to be able to set the href for the header banner. So that when I click on IBM [Platform] it will go to a page I want it to go to. 
![image](https://user-images.githubusercontent.com/4312305/64814800-2bd6db80-d572-11e9-9378-f526ae9728f1.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug/small change

> Is this issue related to a specific component?

UIShell header.component.ts

> What did you expect to happen? What happened instead? What would you like to see changed?

I want to have the option to set the href so that I can set what page it goes to.

> What browser are you working in?

Google Chrome

> What version of the Carbon Design System are you using?

2.49.4 but it also applies to v3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

## Steps to reproduce the issue

https://angular.carbondesignsystem.com/v2/?path=/story/ui-shell--header

Clicking on IBM[Platform] causes it to go to a different page

## Additional information

Please fix in v2 first before fixing in v3

**Comment by dsuwirya** [comment]
In Angular, what we usually want when the user click this is actually to trigger router.navigateByUrl() instead of going via <a href> to avoid page being reloaded. Can you please help to allow this scenario as well ?
