### ISSUE TITLE
UIShell - Header: I want to be able to have an icon with a menu in the header

### ISSUE THREAD

**Issue by jdcai** [IBM/carbon-components-angular#748]
## Detailed description

> Describe in detail the issue you're having.

Currently for header menu it forces you to use text and a down arrow. I want to use an icon instead.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request (change header-menu to allow this)

> Is this issue related to a specific component?

UI shell header-menu

> What did you expect to happen? What happened instead? What would you like to see changed?

I would like to be able to customize what element the header menu can be used with.

> What version of the Carbon Design System are you using?

2.49.4

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

## Steps to reproduce the issue

https://angular.carbondesignsystem.com/?path=/story/ui-shell--header

**Comment by cal-smith** [comment]
v3 accomplishes this with panels in the global actions:

![image](https://user-images.githubusercontent.com/1744185/66587512-8b67dd00-eb58-11e9-9e8d-dd8cdce65c62.png)

Would something like that satisfy your requirement @jdcai? There's no designs at the moment to support icon only header menus in Carbon, and we'd like to stick as close as possible to the published UI Shell specs ...

**Comment by cal-smith** [comment]
Since there hasn't been any input here, I'm going to close this for now ... let us know if you still want to work something out @jdcai and we can re-open 👍
