### ISSUE TITLE
Refactor calendar component (needs to add DatePicker too)

### ISSUE THREAD

**Issue by zvonimirfras** [IBM/carbon-components-angular#75]
Calendar component exists already but needs to be updated to use Carbon styles and needs to be combined with a date picker (that doesn't exist yet).

Doing one without the other won't be very useful so we group them in one issue.

HTML and styles: http://www.carbondesignsystem.com/components/date-picker/code
Usage: http://www.carbondesignsystem.com/components/date-picker/usage

**Comment by scarraway** [comment]
@zvonimirfras Do you know if anyone has started this one yet?

**Comment by zvonimirfras** [comment]
@scarraway, not at the moment, but I have someone in mind. Why do you ask?

**Comment by scarraway** [comment]
@zvonimirfras Just was curious when it might be implemented - We're migrating component libraries to this one, so we'll leave our existing datepicker in until it's ready.

**Comment by magedhennawy** [comment]
@scarraway hey Stephen, I'm working on this to have it ready for you asap :)
