### ISSUE TITLE
Filter's property of required is not work. 

### ISSUE THREAD

**Issue by ibmerzuo** [IBM/carbon-components-angular#751]
<img width="486" alt="图片" src="https://user-images.githubusercontent.com/55433267/65024295-20ffba80-d967-11e9-9a53-839c94a34bfe.png">
This Filter must be input something,Once I delete what I input,it's property of required is not work.

**Comment by zvonimirfras** [comment]
This issue seems to be missing reproduction steps etc. and hasn't had any activity in a long time. Feel free to reopen with additional info if still relevant.
