### ISSUE TITLE
Toast Notification Close Event Issue

### ISSUE THREAD

**Issue by nitishjain07** [IBM/carbon-components-angular#753]
Hi Team,

I have noticed that in Toast Notification we have a close method in the template, however, that event is missing in the component script. Kindly emit that event as done in 'Inline notification'.

Thanks in advance!

I am using below carbon versions:
"carbon-components": "^10.5.1",
"carbon-components-angular": "^3.14.4"

**Comment by cal-smith** [comment]
It already does :+1: just bind to `(close)` if you're using it in a template, or subscribe to `.close` on the instance returned from `NotificationService#showToast`
