### ISSUE TITLE
How to use <ibm-icon> ?

### ISSUE THREAD

**Issue by dsuwirya** [IBM/carbon-components-angular#77]
Hello,

Would it be possible to help giving a little guide on how I can use the <ibm-icon> ? 

Are all icons listed at http://www.carbondesignsystem.com/style/iconography/library supported ?

I'm only able to successfully use  `<ibm-static-icon>` so far, but it seems the icons are limited ?

Thanks.

**Comment by zvonimirfras** [comment]
In order to use `ibm-icons` you need to include proper icon sprites into your DOM. Right now icon service doesn't use the latest icon repository out of the box.

@cal-smith is currently working on resolving it and I'm sure he'll want to provide more details when he has them available :)

**Comment by cal-smith** [comment]
`ibm-static-icon` (primarily an internal use only component) and `ibm-icon` don't provide the correct icons at this point, and I'd argue they're going to be obsolete - we'll be shipping a really cool icon component at some point! so stay tuned for that!

In the interim I'd take a look at the developer section of http://www.carbondesignsystem.com/style/iconography/usage

**Comment by zvonimirfras** [comment]
Sounds like this can be closed for now.

**Comment by dsuwirya** [comment]
for reference, this is how to use carbon-icon in angular now: https://github.com/IBM/carbon-elements/tree/master/packages/icons-angular
