### ISSUE TITLE
UIShell - Header : make skipToContent optional

### ISSUE THREAD

**Issue by dsuwirya** [IBM/carbon-components-angular#772]
Hi,

Would it be possible to also make this skipToContent `<a href>` to become optional, using `*ngIf="skipTo"` ? This skipToContent is not always necessarily needed, implementable.

Thanks.

**Comment by cal-smith** [comment]
Should be fixed with https://github.com/IBM/carbon-components-angular/pull/782/files#diff-ff8cc0e530057da8e45857f8cfb249e4R29
