### ISSUE TITLE
UIShell - Header: Incorrect hamburger icon

### ISSUE THREAD

**Issue by dsuwirya** [IBM/carbon-components-angular#773]
Hi,

Our UX team is pointing that the hamburger icon that is used here is incorrect, it should be one with the 4 lines like this:

![image](https://user-images.githubusercontent.com/5710527/65605675-22d10b80-df6f-11e9-9dcf-592d477377d5.png)

Thanks.

**Comment by cal-smith** [comment]
This should be an easy change ... would you like to contribute the fix @dsuwirya?

**Comment by dsuwirya** [comment]
@cal-smith, I'd love to, but seems to be a lot of steps I need to do in order to contribute ? or is there any much easier/shorter step to be able to contribute ? thanks.

**Comment by dsuwirya** [comment]
@cal-smith, another question, is there any reason why you're not using icon from @carbon/icons-angular and using the svg directly here ?

**Comment by cal-smith** [comment]
> I'd love to, but seems to be a lot of steps I need to do in order to contribute ? 

The quickstart is only 4 or 5 short steps 🙂 I encourage you to give it a try! (no pressure though!) https://github.com/IBM/carbon-components-angular#quickstart 

> is there any reason why you're not using icon from @carbon/icons-angular and using the svg directly here ?

In short - no. The component was written before that icon was available, for the updated we'd definitely want to switch to the one provided by `@carbon/icons-angular`
