### ISSUE TITLE
Datepicker component caused infinite loop Error in IE 

### ISSUE THREAD

**Issue by ChenCheress** [IBM/carbon-components-angular#774]
## Detailed description

> 
Just put the following component in the code, and open IE 11, the error appears
<ibm-date-picker 
        [label]="('REQDETAIL.DATE' | translate) + '*'"
        [placeholder]="'placeholder'" 
        [theme]="'dark'"
        [value]="interviewDate" 
        [flatpickrOptions]="datepickerConfig"
        (valueChange)="valueChange($event)" >
</ibm-date-picker>
> Is this a feature request (new component, new icon), a bug, or a general issue?
 A bug for IE
> Is this issue related to a specific component?
Yes, datepicker component

> What browser are you working in?
IE 11
> What version of the Carbon Design System are you using?
 "carbon-components-angular": "^3.16.1"/"3.15.*"
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Yes we have to MTP in 7th, October

* Screenshots or code
![image](https://user-images.githubusercontent.com/26919565/65652362-136fc200-e044-11e9-9ddc-0053eabf443c.png)

* Notes

**Comment by Donisius** [comment]
A polyfill for element.closest needs to be installed in order to avoid the infinite loop.

**Comment by thesupernvk** [comment]
Hi,

We are on "carbon-components-angular": "^3.28.0" and still facing the issue on IE11.
Still getting the error "object does not support property or method 'closest'" and results in an infinite loop.

Can this issue be reopened?

Reg,
Navin

**Comment by Donisius** [comment]
> Hi,
> 
> We are on "carbon-components-angular": "^3.28.0" and still facing the issue on IE11.
> Still getting the error "object does not support property or method 'closest'" and results in an infinite loop.
> 
> Can this issue be reopened?
> 
> Reg,
> Navin

Since there is no support for closest in IE11, you need to add a polyfill to account for this, something like: https://www.npmjs.com/package/element-closest
