### ISSUE TITLE
basic overflow menu shows options with hyperlink

### ISSUE THREAD

**Issue by anusha801** [IBM/carbon-components-angular#775]
I am using basic overflow menu since I don't want the options to be displayed as hyperlink

```
<ibm-overflow-menu flip="true">
                    <ibm-overflow-menu-option  (click)="option1()">Option 1</ibm-overflow-menu-option>
                    </ibm-overflow-menu> 
```

![image](https://user-images.githubusercontent.com/22391813/65675803-652c4280-e06c-11e9-94dd-090468ea81ca.png)

**Comment by cal-smith** [comment]
I believe that's just the style for the v9 overflow menu options: https://v9.carbondesignsystem.com/components/overflow-menu/code

**Comment by anusha801** [comment]
But for the same piece of example in angular design story book,those styles
were not there..

**Comment by cal-smith** [comment]
looking at the v2 storybook it seems that they are: https://angular.carbondesignsystem.com/v2/?path=/story/overflow-menu--basic

The v3/Carbon 10 storybook has a different style, so that may be what you're seeing.

I'll close this since it all seems to be working as expected.
