### ISSUE TITLE
(v2) UI Shell: Add support for routed link on the brand link

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#779]
## Detailed description

> Describe in detail the issue you're having.

I want to link the brand text to a specific page in the application. At the moment the `skipTo` property doesn't seem to be working for me at all which is quite weird as looking at the code it looks like it should be working fine.

Application's homepage could easily be different than `/` and I see no way of changing that behavior at the moment.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

UI Shell

> What did you expect to happen? What happened instead? What would you like to see changed?

I'd like to set `[routerLink]` to the header in the same manner that `header-item` allows to.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

2.49.4

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/1253469/65720115-4b432d80-e075-11e9-9c84-105cdd5c6d14.png)

**Comment by cal-smith** [comment]
#801 should have fixed this, let me know if you're still having issues with this @stanislavgeorgiev
