### ISSUE TITLE
Storybook: Sort components alphabetically by name

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#78]
## Detailed description

> Describe in detail the issue you're having.

Components should be sorted alphabetically after the first one "Welcome"
https://angular.carbondesignsystem.com/
![image](https://user-images.githubusercontent.com/1253469/45646766-47f48980-ba92-11e8-8951-fd186711b0dc.png)

**Comment by cal-smith** [comment]
Yeah that would probably make a lot more sense ... should just be as simple as a `.sort` in the storybook config
