### ISSUE TITLE
[Firefox ESR compatibility]: Carbon-angular icon tooltips on an interactive button not able to be clicked or hovered over in Firefox 60.9.0esr (current ESR channel release)

### ISSUE THREAD

**Issue by brian-kulak** [IBM/carbon-components-angular#784]
## Detailed Description

In an IBM internal application, adding carbon-angular icon tooltips on interactive voting buttons has rendered the buttons unable to be clicked or hovered over in the current Firefox ESR release, Firefox 60.9.0esr (https://www.mozilla.org/en-US/firefox/60.9.0/releasenotes/).  They work fine in the current Firefox RR version and in other tested browsers (Chrome, edge, safari).

Screenshots provided below should provide a better picture of what's going on.  In summary, the functionality in question is "reddit-esque" allowing users to create posts and comment on posts, and allowing other users to upvote and downvote posts and comments.

When working properly, hovering over one of the voting buttons displays a circular highlight behind the button, and also a text tool tip (`Upvote` or `Downvote` as appropriate).  Clicking the button records an upvote or downvote by the user.

Since implementing Carbon tooltips here, it seems the upvote and downvote buttons are no longer clickable for users in Firefox 60.9.0esr, which is the current ESR version of Firefox and in wide use across IBM (representing >20% of our sessions in September MTD).  Hovering over the button still displays the text `Upvote` or `Downvote` tooltip, but the highlight is not displayed and, more problematically, clicking on the button does not work.  It appears the carbon tooltip is preventing detection of the button and thereby preventing the action from being performed.

_Version of the Carbon Design System we are using:_
carbon/icons-angular: 10.3.2
carbon-components: 10.5.0
carbon-components-angular: 3.14.3

_Offering/product we work on:_
Bluemine

_Pressing ship or release dates you should be aware of:_
This is already in our production system and impacting users, but we are going to back the carbon tooltips out in our next release (code freeze planned ~Oct 4, 2019) if it is not fixed sooner.
Based on our analysis, approx 22% of our users in September have visited Bluemine using Firefox ESR 60.9.0 (or earlier).  So it is a significant enough portion of the IBM population (anyone using Firefox who is on the ESR update channel) that it probably warrants addressing.  We have about 100k users from all parts of IBM so our usage is usually pretty good representation of the IBM population as a whole.

## Steps to reproduce the issue
Due to the confidential nature of Bluemine I would need to communicate this information privately and/or show you in a webex demo.  I've asked the developer to look into CodeSandbox for this.
UPDATE:  Kevin has put together a basic reproduction in codesandbox:
https://codesandbox.io/embed/carbon-components-angular-ho3b4?fontsize=14
Clicking on the Greet button in a compatible browser does an alert.  Clicking on the button in Firefox 60.9.0esr does not do the alert.

## Additional information
In the screenshots below, the red boxes were added by me after taking the screenshot to conceal potentially sensitive information.  Otherwise, the screenshots are unaltered.

**Expected Behavior: In Firefox 69.0.1, working properly -- hovering over the upvote button, button carbon tooltip and underlying circular highlight are displayed**
![image](https://user-images.githubusercontent.com/55890242/65787803-c1a06800-e127-11e9-801b-2f9c8d7c87ae.png)

**Expected Behavior:  In Firefox 69.0.1, working properly -- after clicking the upvote button, the vote is recorded with the vote score increasing by 1 (from 4 to 5 in this case)**
![image](https://user-images.githubusercontent.com/55890242/65787896-f90f1480-e127-11e9-8d19-92133c32018a.png)

**Bad Behavior: In Firefox 60.9.0esr, hovering over the upvote button displays the tool tip, but not the circular highlight**
![image](https://user-images.githubusercontent.com/55890242/65788358-e5b07900-e128-11e9-921d-fc6a56cdec1c.png)

**Bad Behavior:  In Firefox 60.9.0esr, clicking the upvote button does not record a vote.  Blue boxes appear around the button, and the tool tip "sticks" even when the mouse is moved away**
![image](https://user-images.githubusercontent.com/55890242/65788431-0ed10980-e129-11e9-9bfa-69d0917e7e69.png)

## Bluemine contacts
Developer:  Kevin Truong (kevin.truong@ibm.com)
PM:  Brian Kulak (brian.kulak@us.ibm.com)

**Comment by brian-kulak** [comment]
Update / added to main comment:  
Kevin has put together a basic reproduction in codesandbox:
https://codesandbox.io/embed/carbon-components-angular-ho3b4?fontsize=14
Clicking on the Greet button in a compatible browser does an alert.  Clicking on the button in Firefox 60.9.0esr does not do the alert.

**Comment by cal-smith** [comment]
So, debugging a bit, and this seems to be due to the buttons nesting ... The icon tooltip component already provides a button, so nesting another button within breaks the inner buttons `click` event ... you should be able to bind the `click` to the component itself and achieve the same result :+1:

**Comment by brian-kulak** [comment]
@cal-smith Kevin was able to fix this based on your feedback and suggestion -- thank you so much!

Also, I got in touch with Mozilla -- they confirmed Firefox 60.9.0esr is still the main supported firefox ESR version at the moment, but they indicated that ESR channel users will get an automatic update to 68.2.0esr in late October.  We tested this same functionality (pre-fix) in Firefox 68 and it worked fine...so if this is a browser-version-specific issue it should "take care of itself" within a month...except of course for users who refuse the automatic firefox updates or never restart their browsers.

**Comment by cal-smith** [comment]
Sounds good ... Thanks again for the super detailed issue and followups! We'll still look at updating our guidance around the icon tooltip (since nested buttons _is_ a bit hacky) but otherwise it sounds like it should be smooth sailing going forwards.

I'll close this for now, but feel free to re-open if anything else comes up on this topic.
