### ISSUE TITLE
SLider Initial value gets ignored - fix need in 2.x

### ISSUE THREAD

**Issue by sparikh1594** [IBM/carbon-components-angular#797]
## Detailed description

> Describe in detail the issue you're having.
Setting value="30" as an initial value gets ignored and shows the slider thumb at 0 instead.

This issue is related to #545 which is fixed in carbon angular 3.x. Could this be delivered in 2.x?

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
slider

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by cal-smith** [comment]
#800 should have fixed this ... let me know if you're still seeing this @sparikh1594 👍
