### ISSUE TITLE
(table): Property ‘onSelectAllCheckboxChange’ does not exist on type ‘Table’.

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#804]
(table) Property ‘onSelectAllCheckboxChange’ does not exist on type ‘Table’: This method was before on type Table, but after the refactor I can't find that method.

**Comment by zvonimirfras** [comment]
@Pablodotnet there are `selectAll` and `deselectAll` events, can you use those instead?
