### ISSUE TITLE
Got some security issues after scaned by AppScan on Cloud

### ISSUE THREAD

**Issue by Bin-Xiong** [IBM/carbon-components-angular#814]
## Detailed description

> Describe in detail the issue you're having.
We used ASoC to scan open source libs we are packaging in our product, some security issues reported by ASoC.
- main issues reported:
- Insecure Use of setAttribute
![图片](https://user-images.githubusercontent.com/40814512/66465503-8a30a480-eab3-11e9-9164-ddbc8679cf61.png)

- Insecure HTTP Communication
![图片](https://user-images.githubusercontent.com/40814512/66465432-6cfbd600-eab3-11e9-82ca-939132b06e1e.png)

- Query Insecure Manipulation of Child Node
![图片](https://user-images.githubusercontent.com/40814512/66465455-75eca780-eab3-11e9-87c0-a9e06c2bc392.png)

- Insecure random number
![图片](https://user-images.githubusercontent.com/40814512/66465474-7d13b580-eab3-11e9-9a6c-25122aea46d9.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?
Yes.
> Is this issue related to a specific component?
No.
> What did you expect to happen? What happened instead? What would you like to see changed?
No security issues reported by AppScan.
> What browser are you working in?
NA.
> What version of the Carbon Design System are you using?
9.x/10.x
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Service Management Unite
## Steps to reproduce the issue
Login ASoC
Upload source code
Scan
Download report

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by cal-smith** [comment]
I think you have the wrong project.

1. It's not clear to me how this is insecure?
2. We don't do any requests insecure or otherwise
3. That's part of a plugin for flatpickr ... it's not clear to me it's preforming an insecure operation?
4. We don't use `Math.random` ... anywhere.

Based on the filename (`carbon-components.min.js`) perhaps you meant to open this in the carbon-design-system/carbon repo?

**Comment by Bin-Xiong** [comment]
Thank you for the feedback! sorry for the confusion.
