### ISSUE TITLE
Table Expand Issue

### ISSUE THREAD

**Issue by vishals9711** [IBM/carbon-components-angular#817]
This selector doesn't seem to work when I'm trying to use it.
I have imported TableModule, what else do I need to import for it to work?

![Untitled](https://user-images.githubusercontent.com/26935949/66465590-c4437b80-ea9e-11e9-93de-7b5d20bde761.jpg)

The error I get--->
 Uncaught Error: Template parse errors:
Can't bind to 'size' since it isn't a known property of 'app-expansion-table'.
1. If 'app-expansion-table' is an Angular component and it has 'size' input, then verify that it is part of this module.
2. If 'app-expansion-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        </ibm-table-header>
        <app-expansion-table
            [ERROR ->][size]="size"
            [showSelectionColumn]="showSelectionColumn"
            [striped]="stripe"): ng:///AppModule/TableComponent.html@47:12
Can't bind to 'showSelectionColumn' since it isn't a known property of 'app-expansion-table'.
1. If 'app-expansion-table' is an Angular component and it has 'showSelectionColumn' input, then verify that it is part of this module.
2. If 'app-expansion-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        <app-expansion-table
            [size]="size"
            [ERROR ->][showSelectionColumn]="showSelectionColumn"
            [striped]="striped"
            [isDataGrid"): ng:///AppModule/TableComponent.html@48:12
Can't bind to 'striped' since it isn't a known property of 'app-expansion-table'.
1. If 'app-expansion-table' is an Angular component and it has 'striped' input, then verify that it is part of this module.
2. If 'app-expansion-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            [size]="size"
            [showSelectionColumn]="showSelectionColumn"
            [ERROR ->][striped]="striped"
            [isDataGrid]="isDataGrid">
        </app-expansion-table>
"): ng:///AppModule/TableComponent.html@49:12
Can't bind to 'isDataGrid' since it isn't a known property of 'app-expansion-table'.
1. If 'app-expansion-table' is an Angular component and it has 'isDataGrid' input, then verify that it is part of this module.
2. If 'app-expansion-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("          [showSelectionColumn]="showSelectionColumn"
            [striped]="striped"
            [ERROR ->][isDataGrid]="isDataGrid">
        </app-expansion-table>
    </ibm-table-container>"): ng:///AppModule/TableComponent.html@50:12
'app-expansion-table' is not a known element:
1. If 'app-expansion-table' is an Angular component, then verify that it is part of this module.
2. If 'app-expansion-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
            <p ibmTableHeaderDescription>{{description}}</p>
        </ibm-table-header>

**Comment by cal-smith** [comment]
See here for how the expansion table story is implemented: https://github.com/IBM/carbon-components-angular/blob/master/src/table/stories/app-expansion-table.component.ts
