### ISSUE TITLE
Angular dropdown multi-select component not working as expected

### ISSUE THREAD

**Issue by thesupernvk** [IBM/carbon-components-angular#823]
## Detailed description

> Describe in detail the issue you're having.

Using following version of carbon components:
`"carbon-components": "^10.6.2",
 "carbon-components-angular": "^3.16.3"`

Angular dropdown multi-select component does not fire an event when the last value is unchecked from a list of selections.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Angular dropdown multi-select component

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected that on unselecting the last selection in a multi-select component, it fires an event.
Instead, no event was fired and hence the model always contain the last selection.

> What browser are you working in?

Bug is observed on all major browsers like Chrome, Firefox and Edge

> What version of the Carbon Design System are you using?

`"carbon-components": "^10.6.2",
 "carbon-components-angular": "^3.16.3"`

## Steps to reproduce the issue

As can be seen, I have selected two roles, and have printed the selection at top for convenience

![image](https://user-images.githubusercontent.com/38689367/66553942-abec6300-eb69-11e9-8655-ec81fc528ff8.png)

Now, I remove role "REGULAR" by unselecting it and it works fine

![image](https://user-images.githubusercontent.com/38689367/66554067-e48c3c80-eb69-11e9-9d5b-da23a2637825.png)

I proceed to remove the remaining role "ADMINISTRATOR" but it is not removed! It is just unchecked from UI but the model is not changed (as no event is fired on unchecking the last remaining item)

![image](https://user-images.githubusercontent.com/38689367/66554155-16050800-eb6a-11e9-9f6b-e5c6a6af6875.png)

**Comment by Donisius** [comment]
I can not seem to reproduce this error, #809 may have also fixed this.

**Comment by thesupernvk** [comment]
> I can not seem to reproduce this error, #809 may have also fixed this.

The bug is still reproducible. I tested with "carbon-components-angular": "^3.20.1" version.

**Comment by Donisius** [comment]
I will look into this further.
