### ISSUE TITLE
Slowdown in table component after 3.17.0

### ISSUE THREAD

**Issue by art-bazhin** [IBM/carbon-components-angular#838]
## Description

Significant performance slowdown has appeared after table component refactoring in 3.17.0. 

## Steps to reproduce the issue

1. Create table with any data. 
2. Choose 4x CPU throttling in Chrome dev tools.
3. Click on the select row checkbox many times quickly.

You should see freezes and problems with interface responsiveness. On my 2012 MacBook Pro it can cause total page freeze. Moreover, if you just place table on your page and interact with other components presented on the page, you should see same problems.

There is no such problem in 3.16.3.

Thank you.

**Comment by Pablodotnet** [comment]
Having this issues too! :(
