### ISSUE TITLE
Side Nav Opens and closes only for certain window sizes

### ISSUE THREAD

**Issue by Donisius** [IBM/carbon-components-angular#847]
## Detailed description

> Describe in detail the issue you're having.

The Side Nav opens and closes only for certain window sizes as shown below: 

![Screen Recording 2019-10-16 at 12 26 19 PM](https://user-images.githubusercontent.com/45505172/66939572-4ab50b80-f011-11e9-9c4e-384f9457cc7d.gif)

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is a bug.

> What did you expect to happen? What happened instead? What would you like to see changed?

Toggling the hamburger menu should open and close the side navigator. 

> What browser are you working in?

Chrome, Firefox

> What version of the Carbon Design System are you using?

"carbon-components": "^10.6.2",
"carbon-components-angular": "^3.17.3"

**Comment by cal-smith** [comment]
This is by design, check the carbon website - the sidenav should be fixed in place and the hamburger hidden untill the screen is small enough for the sidenav to be hidden and toggled via the hamburger

**Comment by Donisius** [comment]
Okay awesome 👍  I wasn't sure if this was intended.
