### ISSUE TITLE
 File upload component - let user upload theduplicate files with the same name 

### ISSUE THREAD

**Issue by amirkhan064** [IBM/carbon-components-angular#849]
if a user has uploaded a file and now he is uploading one more file with the same name but the content is different this time. I think file uploader considering it as a duplicate file and it's not emitting the files change event at this time.

**Comment by Donisius** [comment]
I am able to upload multiple files with the same name given that the content is different in both files as shown below: 

<img width="300" alt="Screen Shot 2019-10-23 at 12 04 29 PM" src="https://user-images.githubusercontent.com/45505172/67412691-bbb66f00-f58d-11e9-8c3a-bd12cef7e1a0.png">

<img width="304" alt="Screen Shot 2019-10-23 at 12 05 38 PM" src="https://user-images.githubusercontent.com/45505172/67412694-bf49f600-f58d-11e9-9953-da1dd66e63d0.png">

The filesChange event does not get emitted only if the two files are the same.

**Comment by cal-smith** [comment]
> I am able to upload multiple files with the same name given that the content is different in both files as shown below:

Okay awesome

> The filesChange event does not get emitted only if the two files have the same content and name.

I think that may still be an issue ... the native file select still emits an event in this case, and I think it makes sense that we should too

**Comment by Donisius** [comment]
> I think that may still be an issue ... the native file select still emits an event in this case, and I think it makes sense that we should too

So I copied the two exact files and it still emitted an event when I did so. 

<img width="304" alt="Screen Shot 2019-10-23 at 12 05 38 PM" src="https://user-images.githubusercontent.com/45505172/67497067-680a5b00-f64b-11e9-9b36-138fd818d0c7.png">

![Screen Shot 2019-10-24 at 10 43 51 AM](https://user-images.githubusercontent.com/45505172/67497098-76587700-f64b-11e9-916e-cd391a6cf849.png)

**Comment by cal-smith** [comment]
See here for the native file input behaviour: https://stackblitz.com/edit/typescript-f8lky7?file=index.ts

If you select a file, and then re-select the same file it emits the change event, I don't believe we do that currently

**Comment by Donisius** [comment]
It seems to only be emitting the events on firefox selecting and reselecting the same file does not emit the change in chrome.

**Comment by Donisius** [comment]
Also on firefox it emits the change on out component when selecting and unselecting the same file and also lets you upload it.
