### ISSUE TITLE
Pagination component on IE11 has alignment issue

### ISSUE THREAD

**Issue by thesupernvk** [IBM/carbon-components-angular#856]
## Detailed description

> Describe in detail the issue you're having.

ibm-pagination component has alignment issues on IE11 where the page number overlaps and is unreadable

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is bug specific to IE11

> Is this issue related to a specific component?

ibm-pagination

> What did you expect to happen? What happened instead? What would you like to see changed?

The pagination component should not display page numbers in incorrect alignment when viewed on IE11.

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

"carbon-components": "^10.6.2",
"carbon-components-angular": "^3.16.3"

* Screenshots or code

![image](https://user-images.githubusercontent.com/38689367/67280642-38dcd800-f4eb-11e9-91d0-e8397eeae698.png)

* Notes

Issue is reproducible even on Story book if opened in IE11: https://angular.carbondesignsystem.com/?path=/story/pagination--basic

**Comment by cal-smith** [comment]
Just want to confirm if this issue is visible on the carbon design system site as well @thesupernvk ?

**Comment by thesupernvk** [comment]
> Just want to confirm if this issue is visible on the carbon design system site as well @thesupernvk ?

Not actually. I opened this URL [https://www.carbondesignsystem.com/components/pagination/code/](url) on IE11 and the issue is not present.

Seems like the issue is with Angular implementation only as can be seen here [https://angular.carbondesignsystem.com/?path=/story/welcome--to-carbon-angular](url)

**Comment by cal-smith** [comment]
Very strange 🤔 Thanks for taking the time to double check that!
