### ISSUE TITLE
Table Overflow menu should stay active while hovering the opened menu

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#86]
## Detailed description

> Describe in detail the issue you're having.

The overflow menu icon disappears in the [Table storybook](https://angular.carbondesignsystem.com/?knob-size=md&knob-striped=true&knob-showSelectionColumn=true&selectedKind=Table&selectedStory=with%20overflow%20menu&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) as soon as the mouse moves to select an option.

For comparison, (Carbon's Data Table)[http://www.carbondesignsystem.com/components/data-table/code] keeps the overflow icon visible while browsing the menu.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Table

**Comment by stanislavgeorgiev** [comment]
```
ibm-overflow-menu {
    position: relative;
}
```

Seems to fix the issue but I don't know if it's the correct solution from the library's perspective. I don't see you using any custom styles on top of Carbon's and I wouldn't know where to add that code anyway.

**Comment by zvonimirfras** [comment]
Vanilla JS does it by adding `bx--overflow-menu--open` to overflow menu when it's open.
That looks like the correct way of accomplishing this.

**Comment by asudoh** [comment]
Weighing in - From what I read the description, this issue is about the trigger button instead of the menu? The guy who keeps the trigger button open is [`:focus`](https://github.com/IBM/carbon-components/blob/v9.26.0/src/components/data-table-v2/_data-table-v2-core.scss#L87-L95).
