### ISSUE TITLE
[IE]click the number icon should clear all selected options for ibm-dropdown

### ISSUE THREAD

**Issue by dhmengsh** [IBM/carbon-components-angular#878]
Use carbon-components-angular version 2.48.8. could not clear the selected options when click the number icon[IE11].

![image](https://user-images.githubusercontent.com/57174321/67845155-f4c88380-fb39-11e9-96b9-56ef2993736c.png)

**Comment by dhmengsh** [comment]
@cal-smith Any update for this issue?

**Comment by cal-smith** [comment]
Nothing yet ...

**Comment by dhmengsh** [comment]
Thanks, the issue has been fixed.
