### ISSUE TITLE
Issue with ibm-dropdown component in the latest version

### ISSUE THREAD

**Issue by thesupernvk** [IBM/carbon-components-angular#881]
## Detailed description

> Describe in detail the issue you're having.

ibm-dropdown component was working fine till version "^3.16.3". Since upgrading to version "^3.22.0", suddenly the dropdown is not working as expected.

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is a bug

> Is this issue related to a specific component?

**ibm-dropdown-list** component
**ibm-dropdown** component

> What did you expect to happen? What happened instead? What would you like to see changed?

We have set the variable `imlQuery.operator` to `{ "content": "And" }`. 
The dropdown-list is set to: `imlOperationList: any = [{ content: 'And' }, { content: 'Or' }];`

`<div class="inlineBlock operator-div">
          <ibm-dropdown [theme]="theme" placeholder="And" [(ngModel)]="imlQuery.operator">
                     <ibm-dropdown-list [items]="imlOperationList"></ibm-dropdown-list>
          </ibm-dropdown></div>`

While this code worked perfectly till we upgraded carbon-components-angular to latest version. For some reason, it sets the ngModel value to null!

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

```
"carbon-components": "^10.7.3",
"carbon-components-angular": "^3.22.0"
```

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

We were trying to update carbon components angular to latest version as it fixes certain issues. But after upgrading to latest version, we have this reported issue and hence are rolling back.

## Steps to reproduce the issue

**PLEASE NOTE** : In the sandbox, I have commented line `<!--<ibm-dropdown-list [items]="imlOperationList"></ibm-dropdown-list>-->`. It works fine and value is printed. If you uncomment this line, it sets the model to null. It seems it is an issue with ibm-dropdown-list component.

https://codesandbox.io/s/carbon-components-angular-vcgf0?fontsize=14

**Comment by thesupernvk** [comment]
Updated with codesandbox link.

**Comment by ksdme** [comment]
I get a
```
Uncaught Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'ibm-dropdown'.
1. If 'ibm-dropdown' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'ibm-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("g no-margin">
      <ibm-dropdown type="multi" label="Node Type" placeholder="Select" value="value" [ERROR ->][(ngModel)]="nodeTypeSelection">
        <ibm-dropdown-list [items]="nodeTypes"></ibm-dropdown-list>
"): ng:///AppModule/NodeFilterComponent.html@7:86
```

**Comment by thesupernvk** [comment]
> I get a
> 
> ```
> Uncaught Error: Template parse errors:
> Can't bind to 'ngModel' since it isn't a known property of 'ibm-dropdown'.
> 1. If 'ibm-dropdown' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
> 2. If 'ibm-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("g no-margin">
>       <ibm-dropdown type="multi" label="Node Type" placeholder="Select" value="value" [ERROR ->][(ngModel)]="nodeTypeSelection">
>         <ibm-dropdown-list [items]="nodeTypes"></ibm-dropdown-list>
> "): ng:///AppModule/NodeFilterComponent.html@7:86
> ```

You need to import dropdownModule and FormsModule.

`@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, ButtonModule, FormsModule, DropdownModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}`

**Comment by ksdme** [comment]
Ah, I missed `FormsModule`, thanks.
