### ISSUE TITLE
icons-angular-10.5.0.tgz: Request failed \"404 Not Found\

### ISSUE THREAD

**Issue by maxxyouu** [IBM/carbon-components-angular#882]
## Detailed description

> Describe in detail the issue you're having.
running
`npm i --save carbon-components-angular carbon-components @carbon/icons-angular`

gives 
<img width="1050" alt="Screenshot 2019-10-31 at 1 04 22 PM" src="https://user-images.githubusercontent.com/28711466/67969147-0a43b900-fbdf-11e9-9108-42f1af7cc7eb.png">

running `npm i --save carbon-components-angular carbon-components @carbon/icons-angular@10.5.0-alpha.5518` works, but once node_modules folder is deleted, yarn install or npm install will prompt the same 404 error again.
> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by cal-smith** [comment]
This seems like an issue with your artifactory server, it shouldn't be trying to resolve `10.5.0`. 10.4.0` is the last supported release of `icons-angular`, I would just lock your `package.json` to `10.4.0`
