### ISSUE TITLE
Table with overflow is showing bigger rows and vertically misaligned row content 

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#886]
## Detailed description

> Describe in detail the issue you're having.

The basic table is showing row content aligned perfectly:

![image](https://user-images.githubusercontent.com/1253469/68219257-af7dd900-ffb3-11e9-8ec1-5bad36867145.png)

but the one with overflow menu has extra space below the row content:

![image](https://user-images.githubusercontent.com/1253469/68219356-d9cf9680-ffb3-11e9-8448-2c0258a32cf0.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

A bug

> Is this issue related to a specific component?

Table

> What did you expect to happen? What happened instead? What would you like to see changed?

Vertical alignment and spacing should be same between both tables

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

3.22

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

## Steps to reproduce the issue

1. Step one: https://angular.carbondesignsystem.com/?path=/story/table--basic
2. Step two: https://angular.carbondesignsystem.com/?path=/story/table--with-overflow-menu

**Comment by Donisius** [comment]
This seems to be an issue with the carbon design system styling as the problem appears to be present within the other frameworks.

**Comment by stanislavgeorgiev** [comment]
Not sure where the screenshots are coming from but they have it showing ok on the design system website: https://www.carbondesignsystem.com/components/data-table/usage

**Comment by Donisius** [comment]
The screenshots are from https://www.carbondesignsystem.com/components/data-table/code

If you make the screen smaller and allow the content to take up more than one line it acts the same way as shown below:

![Screen Shot 2019-11-05 at 12 55 58 PM](https://user-images.githubusercontent.com/45505172/68232708-ad277900-ffcb-11e9-9e48-e5430627265b.png)

**Comment by stanislavgeorgiev** [comment]
That one, I can tolerate, I think it makes sense but the overflow causing bigger bottom padding is wrong

**Comment by cal-smith** [comment]
Seems like react has the same issue: http://react.carbondesignsystem.com/?path=/story/datatable--with-overflow-menu 

Looks like the `2rem` height on the overflow menu is interfering with the row height

**Comment by stanislavgeorgiev** [comment]
```
margin-top: -0.5rem;
margin-bottom: -0.5rem;
```
fixes it perfectly but just for the standard row size

**Comment by cal-smith** [comment]
I think we're going to have to escalate this to https://github.com/carbon-design-system/carbon ... it's definitely a bug in the styles

**Comment by stanislavgeorgiev** [comment]
sure, when it's the same in all frameworks

**Comment by cal-smith** [comment]
This seems to have been fixed by carbon with carbon-design-system/carbon#5292

**Comment by stanislavgeorgiev** [comment]
Awesome!

**Comment by messaoudi-mounir** [comment]
I suggest add "size" paramter (as react version https://react.carbondesignsystem.com/?path=/docs/components-overflowmenu--default) 
size | Specify the size of the OverflowMenu. supports either sm, 'md' (default) or 'lgas an option.
