### ISSUE TITLE
Angular 9.0 and Carbon Angular v4

### ISSUE THREAD

**Issue by ninja511** [IBM/carbon-components-angular#896]
Plan:

- [x] `@carbon/icons-angular` supports Angular 9
- [x] `carbon-components-angular` compiles with Angular 9 (but can't run due to `icons-angular`)
- [ ] ~all outstanding PRs are merged and only critical new PRs are created~ We just kept things up to date
- [x] `v4-dev` branch created from master
- [x] all icons swapped to their Angular 9 compatible form and `peerDependencies` updated
- [x] testing
  - [x] v4 works with Angular 6 - 9 with updated `icons-angular`
  - [x] v3 works with Angular 6 - 8 with updated `icons-angular`
  - [x] v3 works with Angular 6 - 8 without updated `icons-angular`
- [x] remove legacy gulp + webpack + ngc build steps - we're APF only via the CLI going forward
- [x] code freeze on `master`
- [x] prep for `v4-dev` merge to master
  - [x] semantic release updated to release v3 from the v3 branch
  - [x] `deploy.sh` updated to publish latest v3 storybook to `/v3`
  - [x] `v3` branch created
  - [x]  travis passes on v3
- [x] local breaking change commit dry run with `semantic-release`
- point of no return
- [x] merge `v4-dev` into master
  - [x] ensure BREAKING CHANGE commit correctly added
  - [x] delete once travis passes

Expected breaking changes:
- consumers must upgrade to `@carbon/icons-angular@11`
- consumers should ensure deep modules imports are removed for both `carbon-components-angular` and `@carbon/icons-angular`
  - this will require changes in how icons are used for an app to be compatible with Angular 9

**Comment by stanislavgeorgiev** [comment]
@cal-smith May be not the best place to ask but what about @carbon/charts-angular support for v4? We're using Carbon-ng@3 and would certainly want to upgrade to v4 even if only for the Ng9. At the moment we do depend on the @carbon/charts-angular which is not compatible even with Ng8.

**Comment by theiliad** [comment]
I'm not aware of the changes we'd need to make for that to happen. Can investigate a bit

**Comment by cal-smith** [comment]
Super sorry about that ... Eliad should be catching up on Charts issues next week 👍

**Comment by theiliad** [comment]
Yeah we've been having some internal architecture discussions that have kept me occupied

**Comment by stanislavgeorgiev** [comment]
Sure, no worries Eliad.

**Comment by martijnmelchers** [comment]
When is this expected to be done? We'd love to use your library but disabling Ivy really makes it so much worse to work with...

**Comment by cal-smith** [comment]
@martijnmelchers soon! We hope to have a prerelease out this week 🤞

**Comment by stanislavgeorgiev** [comment]
I can volunteer to out a migration from Angular 7 to 9, Carbon v3 to v4 (I assume?)

**Comment by cal-smith** [comment]
@stanislavgeorgiev that would be excellent :+1: ... v4 and `icons-angular` v11 are both available now on the `@next` dist tag (`npm i carbon-components-angular@next @carbon/icons-angular@next`)

@martijnmelchers see above as well ^^

Definitly let us know if anything breaks!

**Comment by martijnmelchers** [comment]
Thanks! Another issue i've pointed out is #1158 maybe it is automatically fixed in angular 9?

**Comment by cal-smith** [comment]
It's possible! Definitly test it out with v4 and let us know if it's resolved

**Comment by Sieabah** [comment]
So the prerelease is out, do you have a timeline on when a full release would be ready?

**Comment by cal-smith** [comment]
We're still working through some related issues (builds take forever due to icons-angular), so whenever those (and any components-angular) issues are resolved we'll look at flipping it to `@latest`

**Comment by tarablack01** [comment]
@cal-smith Is there any remaining work that we can take to help finish out this PR?

**Comment by cal-smith** [comment]
It's already done! But thanks for the offer @tarablack01 😁

**Comment by Lc0rE** [comment]
It's nice that you are putting effort into migrating to Angular 9, and I thank you for all the work.
I had to do a lot of googling without success before I landed on this issue, and then figured out that the current problem is on `@carbon/icons-angular`

Wouldn't it be nice to put a warning on the main project page?  Just a warning that the work is still in progress and angular-icons are not ready for Angular 9 yet. I can PR if you want.

Thanks again for your work!

**Comment by cal-smith** [comment]
`icons-angular` _was_ done, so we didn't see the need for a warning banner 🙂 As far as I understand `icons-angular` does work with Angular 9 overall, with a handful of exceptions (we pulled `v11.1.0`, which _was_ causing issues) ... I'm hoping to have something more functional next week, with an interim solution published on `@next` sooner ... If you're finding specific issues with `icons-angular` _please_ open an issue over on https://github.com/carbon-design-system/carbon-icons-angular (I see that you have already, thanks for that!)

Sorry for the delayed response!
