### ISSUE TITLE
Add ability to handle scroll event of dropdown list

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#898]
## Detailed description

I have the need to integrate paginated search on my app, I have already managed to accomplish some logic to integrate it well in the table with pagination, change page and make api call, but now, I require to do this on a combo box or dropdown, I have integrated the search with api there but there's no way I can tell to the list that when it reaches bottom when scrolling to request the next page of results, so this is why I'm adding this feature to the ibm-dropdown-list.

**Comment by cal-smith** [comment]
This was closed a while ago by #899
