### ISSUE TITLE
Updates on model for checkbox is not detected

### ISSUE THREAD

**Issue by hvlawren** [IBM/carbon-components-angular#90]
## Detailed description

> Describe in detail the issue you're having.

When a checkbox is bound to a variable via ngModel and the value of the model is set through something other than the checkbox, the update is not updated until the next CDR. Normally this would be automatically triggered, but this component is onPush and so the CDR doesn't seem to be detected.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Checkbox

> What did you expect to happen? What happened instead? What would you like to see changed?

An ngmodel being updated should change the rendered checkbox.

The rendering is not updated until something triggers a change detection cycle

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

> Additional Info

My initial inclination is that writeChanges should mark for change detection.

**Comment by hvlawren** [comment]
This bug appears to occur on toggles as well

**Comment by cal-smith** [comment]
Hey 👋 sorry it took so long to get to this. I'm having trouble creating a repro environment for this ... Would you have some sample I could take a look at? Or has this issue resolved itself through some other changes?

**Comment by cal-smith** [comment]
I'm going to close this since I can't repro ... Feel free to comment if this is still an issue 👍
