### ISSUE TITLE
Breadcrumb: Add [routerLink] support

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#902]
## Detailed description

> Describe in detail the issue you're having.

We started using the `breadcrumb` component for our page headers and noticed it supports only `href` attributes which causes a full page reload.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

`ibm-breadcrumb`

> What did you expect to happen? What happened instead? What would you like to see changed?

Should have the same support for router links as the `UI Shell` component.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

3.23.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

**Comment by itworksafisher** [comment]
any way this could actually use routerLink? The implementation is actually just using the router and passing commands + options. This creates some inconvenience if you want to navigate relative.

`
<ibm-breadcrumb-item routerLink="../">
`
and for routeExtras, now my component needs to depend on activatedRoute so it can provide it to relativeTo.
`
<ibm-breadcrumb-item [route]="['../']" [routeExtras]="{ relativeTo: route }">
`
