### ISSUE TITLE
Date Picker: Doesn't show calendar on icon click

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#903]
## Detailed description

> Describe in detail the issue you're having.

Clicking on the input field would result in showing the calendar but clicking on the icon won't

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Date Picker

> What did you expect to happen? What happened instead? What would you like to see changed?

Clicking on the icon should show calendar

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

3.23.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI 

## Steps to reproduce the issue

1. Go to https://angular.carbondesignsystem.com/?path=/story/date-picker--single
2. Click on the input's icon

**Comment by cal-smith** [comment]
We should be able to reuse https://github.com/IBM/carbon-components-angular/pull/840 for v2 👍

**Comment by stanislavgeorgiev** [comment]
Sorry Cal, that’s in the latest, not v2

**Comment by cal-smith** [comment]
Yep! Just mentioning that we can reuse the code changes from v3 for v2

**Comment by stanislavgeorgiev** [comment]
Is this issue a duplicate of #837?

**Comment by Donisius** [comment]
Yep, #840 should close this

**Comment by stanislavgeorgiev** [comment]
OK, then close this one as a duplicate I guess :)
I didn't see the original one when I was creating this one
