### ISSUE TITLE
Dropdown list position when openning for the first time

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#906]
## Dropdown list position when openning for the first time

The dropdown list container displays with a margin top when openning it for the first time.

## Detailed description

I'm using dropdowns on a modal, when I open a dropdown for the first the list opens with a little margin at the top, if I close it and open it again it displays as expected.

## Screenshots

<img width="442" alt="Screen Shot 2019-11-06 at 3 31 01 PM" src="https://user-images.githubusercontent.com/10190000/68630091-cdfc3c80-04ab-11ea-9975-1b092c41e567.png">

**Comment by zvonimirfras** [comment]
No longer an issue (talked on slack).
