### ISSUE TITLE
Data Table - Alignment issue in expansion row arrow when table size is short

### ISSUE THREAD

**Issue by abhisheksinghrana** [IBM/carbon-components-angular#911]
Having alignment issue in expansion row arrow when table size is short.
<img width="775" alt="image" src="https://user-images.githubusercontent.com/29912424/68881821-e088a700-0733-11ea-8234-99f4985ca931.png">

@cal-smith @zvonimirfras

**Comment by Donisius** [comment]
This seems to be an issue with the carbon design system styling as the problem appears to be present in the other frameworks.

**Comment by cal-smith** [comment]
@abhisheksinghrana could you open this issue in the [Carbon repo](https://github.com/carbon-design-system/carbon)?

**Comment by abhisheksinghrana** [comment]
@cal-smith https://github.com/carbon-design-system/carbon/issues/4833

**Comment by ninja511** [comment]
This is tracked under https://github.com/carbon-design-system/carbon/issues/4796. Closing this one
