### ISSUE TITLE
Slider: Create a range slider

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#916]
## Detailed description

> Describe in detail the issue you're having.

We need a range slider to specify ranges for filters and/or thresholds. We've already implemented it and we're asking if we could contribute it back to the community:

![image](https://user-images.githubusercontent.com/1253469/68965182-2a5fa480-07a9-11ea-8db9-90460d91ef7e.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

Slider

> What version of the Carbon Design System are you using?

3.26.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

**Comment by cal-smith** [comment]
Does this require any style changes @stanislavgeorgiev? If not I don't see a reason why it couldn't be contributed back

**Comment by stanislavgeorgiev** [comment]
No style changes @cal-smith. It's reusing the thumb style and then it just modifies how long the track is to make it look like a range.
If you're ok with it then I will prepare a PR for review next week. In the meantime you could assign this one to me.

**Comment by cal-smith** [comment]
Done! Sounds good!

**Comment by stanislavgeorgiev** [comment]
Great!

**Comment by stanislavgeorgiev** [comment]
@cal-smith What do you think about calling the second value for the range `value2`? In our implementation we have it `lowValue` and `highValue` but obviously I don't want to break anybody else's code and rename `value` to `lowValue` :)

I was initially thinking about creating a `range-slider.component` which will extend the `slider.component`. That didn't go well because I didn't want to clone the template code so I settled to do append some code to the `slider` itself.

**Comment by zvonimirfras** [comment]
Looks like this might have been resolved in #1626. Feel free to reopen if that's not the case :)
