### ISSUE TITLE
UI Shell: Add an active state property

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#920]
## Detailed description

> Describe in detail the issue you're having.

We'd like to have a property that would highlight (put as active) one of the UI Shell header items depending on the app's navigation. The UI Shell already has the style when an header item is hovered so hopefully it would be as simple as having an `[active]="true"` similar to the Tabs component.

![image](https://user-images.githubusercontent.com/1253469/69090972-5a13e400-0a17-11ea-839f-c3e5c39f57d8.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

UI Shell

> What version of the Carbon Design System are you using?

3.26

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM ADDI

**Comment by stanislavgeorgiev** [comment]
It looks like Carbon show they have an active state but only on screenshot, the style is missing. I filed an issue with them for that: https://github.com/carbon-design-system/carbon/issues/4723

**Comment by stanislavgeorgiev** [comment]
@cal-smith Can you assign this one to me? I made the change and submit a PR but I will wait until the Carbon folks add the class first.

**Comment by zvonimirfras** [comment]
@stanislavgeorgiev you had a PR ready for this and it looks like the issue in carbon that you were waiting for was resolved. Any updates on this one too? :)

**Comment by stanislavgeorgiev** [comment]
Looking at that commit and comparing it with the current codebase, I see that you've already have the solution implemented:
```
   [ngClass]="{'bx--header__menu-item--current' : isCurrentPage}"
```

which is only slightly different than my implementation:

```
   [ngClass]="{ 'bx--header__menu-item--selected': active }"
```

I just double checked whether the class should be `--current` or `--selected` and it really looks like you already have it in.

Closing this issue now.

**Comment by boeckMt** [comment]
How is this supposed to work, should there be a subscription on `router.events` and then set the `isCurrentPage` attribute if the route matches?
Normaly I only used `[routerLinkActiveOptions]="routerLinkActiveOptions" routerLinkActive="active"` to get an active class.
