### ISSUE TITLE
Table - Severe performance issue

### ISSUE THREAD

**Issue by r4d** [IBM/carbon-components-angular#922]
## Detailed description

Following addition in the table component is causing multiple callbacks on redraw.

```
	@Input()
	set expandButtonAriaLabel(value: string | Observable<string>) {
		this._expandButtonAriaLabel.override(value);
	}

	get expandButtonAriaLabel() {
		return this._expandButtonAriaLabel.value;
	}

	@Input()
	set checkboxLabel(value: string | Observable<string>) {
		this._checkboxLabel.override(value);
	}

	get checkboxLabel() {
		return this._checkboxLabel.value;
	}
```

When the browser is paused when the screen is locking, it will stop on the following:

```
export const replace = (subject, variables) => subject.pipe(
	map<string, void>(str => {
		const keys = Object.keys(variables);
		for (const key of keys) {
			const value = variables[key];
			str = str.replace(new RegExp(`{{\\s*${key}\\s*}}`, "g"), value);
		}
		return str;
	})
);

```
## Steps to reproduce the issue

1. Add a couple d3 charts to your page with the table component from this library
2. Add carbon-components-angular table (see details below for table markup)
2. Add/remove legend  items from the d3 charts
3. Hit pause when the page starts to slow
4. See details above on how the code will pause on the RegExp in the carbon-components-angular library

## Additional information

* Repeating the steps above when the carbon-components-angular table removed will NOT experience the same slowdown and the d3 charts will respond as expected.  Adding the chart back in will slow the page again.
* No additional logic has been added to the table... this is out-of-the-box boilerplate code for the table
* Table markup added as follows:
```
<div class="data-table">
  <ibm-table-container>
      <ibm-table-header>
          <h4 ibmTableHeaderTitle>{{title}}</h4>
          <p ibmTableHeaderDescription>{{description}}</p>
      </ibm-table-header>
      <ibm-table-toolbar [model]="model">
          <ibm-table-toolbar-actions>
              <button ibmButton="primary">
                  Delete
                  <ibm-icon-delete16 class="bx--btn__icon"></ibm-icon-delete16>
              </button>
              <button ibmButton="primary">
                  Save
                  <ibm-icon-save16 class="bx--btn__icon"></ibm-icon-save16>
              </button>
              <button ibmButton="primary">
                  Download
                  <ibm-icon-download16 class="bx--btn__icon"></ibm-icon-download16>
              </button>
          </ibm-table-toolbar-actions>
          <ibm-table-toolbar-content>
              <ibm-table-toolbar-search [expandable]="true"></ibm-table-toolbar-search>
              <button ibmButton="toolbar-action">
                  <ibm-icon-settings16 class="bx--toolbar-action__icon"></ibm-icon-settings16>
              </button>
              <button ibmButton="primary" size="sm">
                  Primary Button
                  <ibm-icon-add20 class="bx--btn__icon"></ibm-icon-add20>
              </button>
          </ibm-table-toolbar-content>
      </ibm-table-toolbar>

      <ibm-table [model]="model">
      </ibm-table>
  </ibm-table-container>
</div>
```
![image](https://user-images.githubusercontent.com/4708520/69154944-832f8580-0aa6-11ea-99b0-c04b061ea730.png)

**Comment by cal-smith** [comment]
Which version of `carbon-components-angular` are you seeing this with @r4d? I know we had one unexpected performance regression we fixed a few versions back.

**Comment by r4d** [comment]
@cal-smith Man i apologize, i was using 3.17.3 and it appears the issue has indeed been repaired with the latest 3.26.0.  Please close this defect as already addressed.

**Comment by cal-smith** [comment]
No worries! Thanks for reaching out 👍
