### ISSUE TITLE
UI Shell Sidenav: Can't use svg with ibm icon directive on ibm-sidenav-item

### ISSUE THREAD

**Issue by Pablodotnet** [IBM/carbon-components-angular#925]
## Detailed description

On the ui shell sidenav, using the rail sidebar, when setting the ibm-sidenav-item with the icon on its svg format it works well, when on rail sidebar the icon displays correctly and when expanding it is everything great, but when using the icon component (for example: `<ibm-icon-menu20></ibm-icon-menu20>`) or the icon directive (for example: `<svg ibmIconHome20></svg>`) it does not work as expected.

## Screenshots
As you can see on the screenshot's code I'm using the three approaches for setting an icon, the first one (pure svg) is the one that works.

![Screen Shot 2019-11-19 at 2 41 49 PM](https://user-images.githubusercontent.com/10190000/69184596-c86daa80-0ada-11ea-8c1d-585609520a0a.png)

<img width="99" alt="Screen Shot 2019-11-19 at 2 41 36 PM" src="https://user-images.githubusercontent.com/10190000/69184643-dcb1a780-0ada-11ea-93d2-a5f2ef50e126.png">

<img width="265" alt="Screen Shot 2019-11-19 at 2 41 43 PM" src="https://user-images.githubusercontent.com/10190000/69184649-de7b6b00-0ada-11ea-8b8e-ea06accc8cb6.png">

**Comment by Donisius** [comment]
The side nav item applies the `bx--side-nav__icon` class to children with the `icon` attribute. So doing `<svg icon ibmIconHome20></svg>` should work 👍

**Comment by cal-smith** [comment]
Well that's just super weird

**Comment by Pablodotnet** [comment]
I didnt set the icon attribute when used svg directive approach, Ill set them like that, but it should possible to use the icon components
