### ISSUE TITLE
event not emitted from overflow menu

### ISSUE THREAD

**Issue by JehanX** [IBM/carbon-components-angular#926]
https://github.com/IBM/carbon-components-angular/blob/36afe09801cfcb2df85c2811e38eea40352d3230/src/dialog/overflow-menu/overflow-menu-option.component.ts#L94

**Comment by Donisius** [comment]
How are you catching the event? It seems to be emitting for me.

**Comment by zvonimirfras** [comment]
Can't reproduce. Feel free to reopen with additional info.
