### ISSUE TITLE
Notification component support for buttons/links similar to React version

### ISSUE THREAD

**Issue by awackygamer** [IBM/carbon-components-angular#928]
Notification component in Angular is missing a much needed ability to launch actions from it. Either by rendering buttons or links. Support for using any component in the notification.

>
## Detailed description

> UX team has designed several scenarios that have buttons or email links in the notification/toast component.  The component does not appear to support additional non text elements as part of its construction.  See image below of what our design is expecting.  

> Version of the Carbon Angular 3.21.2 . carbon 10.6.0

> IBM Study Advance - Mid January is next release.

## Additional information

![image](https://user-images.githubusercontent.com/23657808/69431910-452c9e80-0cfe-11ea-86be-5dcc9e2bc3bd.png)

![image](https://user-images.githubusercontent.com/23657808/69432967-570f4100-0d00-11ea-92c4-5bda8ed3e908.png)

**Comment by awackygamer** [comment]
@Donisius 
Thanks for working on this - I am not sure that #930 met the requirement though.  I added the actions to my notification object and they did not appear.  Even if they did appear if I understand what I see in the storybook they would be ghost buttons?  The example only shows the basic non-toast example.  Where should they appear for the toast notification?  See my screenshots above for what is required.  thx

<ibm-toast class="notification" (close)="handleClose()" [notificationObj]="notificationObj"></ibm-toast>
`this.notificationObj = {
        type: 'success',
        title: this.i18n({ value: 'Getting started', id: '@@Getting-started' }),
        actions: [
          {
            text: 'Action',
            click: this.actionSubject,
          },
          {
            text: 'Action2',
            click: this.actionSubject,
          }
        ],
        subtitle: this.i18n({
          value: 'Welcome to your new study! Below are project sections that will be completed by you ' +
            'and your team.  Start by inviting members to contribute.', id: '@@welcome-msg'
        }),
        caption: ``
      }
    }`

**Comment by cal-smith** [comment]
I'm curious where you're seeing actions applied to toast notifications ... looking at the react demos for [notification](http://react.carbondesignsystem.com/?path=/story/notifications--inline) and [toast](http://react.carbondesignsystem.com/?path=/story/notifications--toast), only notification has inline actions. 

We definitely should support passing a template for more complex usage (though we do support simple HTML right now), but that's a separate issue.

**Comment by awackygamer** [comment]
I see how my title is misleading - I was going by what someone told me.  The examples I pasted from design and the detailed description clearly indicate/show the need we have for more complex  notification/toast content.

**Comment by cal-smith** [comment]
No worries, I'll open another issue to cover the template passing usecase

**Comment by cal-smith** [comment]
#985
