### ISSUE TITLE
When table is loading, data is empty, no data template will always show

### ISSUE THREAD

**Issue by eddielca** [IBM/carbon-components-angular#929]
https://github.com/IBM/carbon-components-angular/blob/db485f3e225df345c2e111a827e1597e5d53b8b4/src/table/table.component.ts#L534

There should be a check in place to not show no data template when table is still loading, and the last condition should be wrapped in a bracket otherwise this check is invalid

```
return !this.model.isLoading && 
            ( 
                !this.model.data ||
                this.model.data.length === 0 ||
                (this.model.data.length === 1 && this.model.data[0].length === 0)
            );
```

**Comment by zvonimirfras** [comment]
`data` doesn't have to be empty while table is loading new data. It's possible to add or replace the data once it's loaded.

So, let's pretend table already has some data and you want to load more.

You could set `model.isLoading` to show the loading state to user.
Start loading new data from the backend.
While the data is being loaded, old data is still shown in the table.
When data is fetched from the server, replace the data (i.e. `model.data = newData`)
Loading is now done, table shows the newly loaded data so
unset `model.isLoading`

(`noData` getter shouldn't consider the loading state. `isLoading` considers loading state and it displays a loading state as a separate line in the table (useful if lazy-loading new lines).)

If you want to show the `noDataTemplate` while you're loading, empty the `model.data` or set it to a falsy value at the same time you set the `model.isLoading`.


Feel free to reopen in case I misunderstood the problem or ping me on slack for additional info.

**Comment by eddielca** [comment]
two cases:

1. `no data` template is displayed while initializing table, it shouldn't display `no data` on initialization
2. `no data` template should be hidden if table is loading because it's loading data, you should know if the table is empty or no data after the table finishes loading

above may not be a bug...but the last condition check may be?
```
return !this.model.data ||
			this.model.data.length === 0 **||
			this.model.data.length === 1 && this.model.data[0].length === 0**;
```

you may need to put ```this.model.data.length === 1 && this.model.data[0].length === 0``` in a bracket.
