### ISSUE TITLE
Add search event to combobox

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-angular#941]
To allow users to dynamically update the results in the list

**Comment by thesupernvk** [comment]
I was about to raise a similar request for multi-select combo and I stumbled upon this. We have a multi-select country drop-down which needs a search bar as well:

![image](https://user-images.githubusercontent.com/38689367/70414769-0417e680-1a81-11ea-8b8d-5424d0f03b66.png)

We need to allow the user to enter country name in the bar and only the matching ones should be shown in the drop-down. Currently there is no provision to enter text.

**Comment by Donisius** [comment]
> We need to allow the user to enter country name in the bar and only the matching ones should be shown in the drop-down. Currently there is no provision to enter text.

I may be misunderstanding but I believe the combo box already achieves what you are asking: https://angular.carbondesignsystem.com/?path=/story/components-combobox--multi-select,

entering text filters out the options that do not match the entered text.

**Comment by thesupernvk** [comment]
> > We need to allow the user to enter country name in the bar and only the matching ones should be shown in the drop-down. Currently there is no provision to enter text.
> 
> I may be misunderstanding but I believe the combo box already achieves what you are asking: https://angular.carbondesignsystem.com/?path=/story/components-combobox--multi-select,
> 
> entering text filters out the options that do not match the entered text.

Thanks a lot @Donisius . That is exactly what we need. Don't know how we overlooked it although it was always there!

We still need a small modification in this. Once something is selected, the count is too left aligned. The style needs to be corrected in this case.

![image](https://user-images.githubusercontent.com/38689367/70551328-56e6c080-1b9d-11ea-88bc-517f0593325e.png)

**Comment by Donisius** [comment]
> We still need a small modification in this. Once something is selected, the count is too left aligned. The style needs to be corrected in this case.

Thanks for pointing that out! I'll take a look at that.
