### ISSUE TITLE
Need to bubble up rowClick event on the click of table row

### ISSUE THREAD

**Issue by tulasigudibanda** [IBM/carbon-components-angular#944]
For  https://angular.carbondesignsystem.com/?path=/story/table--with-toolbar ,  
   need to bubble up separate `rowClick` event on the table row click without changing any configuration to toggle between checkbox select and row select 

## Detailed description

> Is this a feature request (new component, new icon), a bug, or a general issue?
feature request

> Is this issue related to a specific component?
https://angular.carbondesignsystem.com/?path=/story/table--with-toolbar
https://github.com/IBM/carbon-components-angular/blob/master/src/table/table.component.ts

> What did you expect to happen? What happened instead? What would you like to see changed?
Expected : Table  should be like gmail inbox where clicking on the row opens up the email and clicking on the checkbox selects it.  Should be able to do both simultaneously
Happened :  `singleSelect` enabled and `showSelectionColumn` disabled ,   `selectRow` is emitted when the row is clicked.  checkbox select and row select should not be mutually exclusive.
Requirement : Need to be able to select checkboxes as well as rows with the same config.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
carbon-components-angular@3.28.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
ECAM.

**Comment by tulasigudibanda** [comment]
Could you please let me know if there is any update on this issue

**Comment by cal-smith** [comment]
Nothing just yet ... I've added it to our Q1 plan though 👍

**Comment by tulasigudibanda** [comment]
Thank you for the update
