### ISSUE TITLE
ibm-table is sortable by default

### ISSUE THREAD

**Issue by thesupernvk** [IBM/carbon-components-angular#947]
## Detailed description

> Describe in detail the issue you're having.

After upgrading carbon-components-angular from version **3.16.3** to version **3.28.0**, we found that the table headers are by default sortable and there is no way to remove sorting arrows.

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is a bug

> Is this issue related to a specific component?

<ibm-table> component

> What did you expect to happen? What happened instead? What would you like to see changed?

The table should not be sortable by default. Instead, there should be a provision to let the developer decide weather the table should be sortable or not.

> What browser are you working in?

Issue is reproducible on all browsers

> What version of the Carbon Design System are you using?

"carbon-components": "^10.6.2"
"carbon-components-angular": "^3.28.0"

## Steps to reproduce the issue

The issue can be seen here: https://angular.carbondesignsystem.com/?path=/story/components-table--basic

## Additional information

* Screenshots or code

![image](https://user-images.githubusercontent.com/38689367/70532207-918c3100-1b7c-11ea-89b0-c531a2f0b008.png)

* Notes

On further checking the documentation, the sortable is hardcoded to 'true'. It should be of type input, so that developer can enable or disable sortable 

`<table
	ibmTable
	sortable="true"
	[size]="size"
	[striped]="striped"
	[skeleton]="skeleton">`

https://angular.carbondesignsystem.com/?path=/story/components-table--documentation

**Comment by cal-smith** [comment]
Sortable isn't hardcoded to true, you can disable sorting by setting the relevant header's `sortable` property to `false` 👍
