### ISSUE TITLE
Add a default modal implementation

### ISSUE THREAD

**Issue by stanislavgeorgiev** [IBM/carbon-components-angular#95]
## Detailed description

> Describe in detail the issue you're having.

I'd like to use the modalService to show a default modal with minimal user effort, for ex.:
```
modalService.show({title: "Some title", text: "Some basic text", buttons: [{}]});
```

> Is this a feature request (new component, new icon), a bug, or a general issue?

Yes

> Is this issue related to a specific component?

Modal

**Comment by stanislavgeorgiev** [comment]
@cal-smith @zvonimirfras Are you OK if I update also the modal styling to make it use and match Carbon?

![image](https://user-images.githubusercontent.com/1253469/45821741-f594b200-bcb7-11e8-907e-4d7cc77c5360.png)


![image](https://user-images.githubusercontent.com/1253469/45821716-e6adff80-bcb7-11e8-9f84-85aaf5b67e21.png)

**Comment by zvonimirfras** [comment]
Yeah, that makes sense :)
