### ISSUE TITLE
Label Component id is on the wrong element

### ISSUE THREAD

**Issue by hvlawren** [IBM/carbon-components-angular#96]
> Describe in detail the issue you're having.

The label HTML element of the ibm-label component's for should correspond to the id on the input/textarea/div that is the input. The selector that chooses the element to put the id on instead binds to the div that has the bx--form-item class, as it is the parent of these others.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Label

> What did you expect to happen? What happened instead? What would you like to see changed?

ID should be on the input. Instead it is on the parent div

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

> Additional Information

Changing

```
this.elementRef.nativeElement.querySelector("input,textarea,div").setAttribute("id", this.labelInputID);
```

to

```
this.elementRef.nativeElement.querySelector("input,textarea,div:not(.bx--form-item)").setAttribute("id", this.labelInputID);
```

should resolve

**Comment by zvonimirfras** [comment]
Potentially better solution would be to take out the div completely and put the `bx--form-item` class as on the `ibm-label` with `HostBinding` to that specific class.
