### ISSUE TITLE
File uploader does not build in production

### ISSUE THREAD

**Issue by acorbellini** [IBM/carbon-components-angular#960]
## Detailed description

> Describe in detail the issue you're having.

`ERROR in node_modules/carbon-components-angular/file-uploader/file-uploader.component.d.ts.FileUploader.html(9,7): : Property 'dragOver' is protected and only accessible within class 'FileUploader' and its subclasses.`

> Version

"carbon-components-angular": "^3.30.0"

**Comment by cal-smith** [comment]
Thanks for opening this @acorbellini ... Can you create a PR to fix this (looks like it's pretty straight forward)? Otherwise we'll take a look

**Comment by acorbellini** [comment]
sure! I'll fix it asap.

**Comment by zvonimirfras** [comment]
It's been so long without action that I'll assume it's no longer a problem. Feel free to reopen if needed.
