### ISSUE TITLE
Support the grid from Carbon Design System

### ISSUE THREAD

**Issue by imandyie** [IBM/carbon-components-angular#97]
## Detailed description

> Add support for grid from Carbon Design System to be able to create a responsive design. The grid, row and column can be angular directives.

> Is this a feature request (new component, new icon), a bug, or a general issue?
**Yes**

> Is this issue related to a specific component?
**No**

> What browser are you working in?
**All supported browsers**

> What version of the Carbon Design System are you using?
**Latest**

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
**IBM Assess**

**Comment by cal-smith** [comment]
related to #47
