### ISSUE TITLE
Paginations component causing build error in 3.30.2

### ISSUE THREAD

**Issue by silviabaptista** [IBM/carbon-components-angular#973]
## Detailed description

> Describe in detail the issue you're having.
I'm upgrading carbon-component-angular in my app from 3.0.1 to 3.30.2 and getting this error when I run `ng build --prod --aot`
`
ERROR in : Can't bind to 'ariaLabel' since it isn't a known property of ':svg:svg'. ("
                                                class="bx--select__arrow"
                                                aria-hidden="true"
                                                [ERROR ->][ariaLabel]="optionsListText.subject | async">
                                        </svg>
                                </div>
")
: Can't bind to 'ariaLabel' since it isn't a known property of ':svg:svg'. ("
                                                style="display: inherit;"
                                                class="bx--select__arrow"
                                                [ERROR ->][ariaLabel]="optionsListText.subject | async">
                                        </svg>
                                </div>
")
`

It builds fine if I go to 3.21.0, and breaks if I go to 3.21.1
Our app isn't even using the pagination component.  I'm able to load the app locally just fine, it's only during build that it breaks.

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug
> Is this issue related to a specific component?
Pagination
> What did you expect to happen? What happened instead? What would you like to see changed?
I'm expecting `ng build --prod` to succeed
> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
10.1.0
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Select for IBM
## Steps to reproduce the issue

1. create angular app with ng new using angular ~7.0.0, "@angular-devkit/build-angular": "~0.10.0", 
"carbon-components": "10.1.0", "carbon-components-angular": "3.30.2",
2. In app.module.ts import anything from carbon-component-angular, ex: `import { ModalModule } from 'carbon-components-angular';`
3. On terminal run `ng build --prod`
.

## Additional information

* Screenshots or code
![Screen Shot 2019-12-19 at 5 32 33 PM](https://user-images.githubusercontent.com/14005574/71215392-97bd9400-2285-11ea-9af5-5bb2fe4ab6e5.png)

sample package.json
{
  "name": "sandbox",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "carbon-components": "10.1.0",
    "carbon-components-angular": "3.30.2",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.1",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@carbon/icons-angular": "10.1.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}

**Comment by ChenCheress** [comment]
we ecounter the same issue when I run `ng build --prod --aot` for I'm upgrading carbon-component-angular in my app from 3.21.0 to 3.49.7. And I suggest to use [attr.aria-expanded]="....." when use this aria-XXX attribute.
![image](https://user-images.githubusercontent.com/26919565/81769957-7057b400-9511-11ea-9b6c-54c40de91882.png)
Could u please help to fix this asap. tyty~~

**Comment by cal-smith** [comment]
Seems like we have this sorted now? Definitly reopen and let us know if you're still running into issues!
