### ISSUE TITLE
UI Shell: skipTo param in <ibm-header>

### ISSUE THREAD

**Issue by dsuwirya** [IBM/carbon-components-angular#980]
Shouldn't it be *ngIf="skipTo" instead of *ngIf="!skipTo" ?

![image](https://user-images.githubusercontent.com/5710527/71594897-4a4feb00-2aff-11ea-8e98-782a917d5192.png)

**Comment by cal-smith** [comment]
Oops, it definitely should be ... should be an easy enough fix if you wanted to contribute it?
