### ISSUE TITLE
Update modal to support new designs

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-angular#994]
Specs: https://www.carbondesignsystem.com/components/modal/usage/

We'll likely need a bunch of new helper components/directives/etc to keep usage simple.

More default modals types to go along with `AlertModal`.

And likely some pattern samples for implementation reference.

**Comment by cal-smith** [comment]
We should be sure to break this down to separate issues/PRs ... no need to have one mega-PR that adds everything

**Comment by HYACCCINT** [comment]
@cal-smith For this, is it necessary to await styling updates (buttons styling in acknowledgement modals for example) or would it be better to write them ourselves?

**Comment by HYACCCINT** [comment]
Otherwise, if not, it would be better if we don't base the new modals on alert modal

**Comment by cal-smith** [comment]
We can start prototyping the styles, and once we have a draft PR that's happy, we can contribute the styles to Carbon (assuming they don't already have work to add the necessary styles)

**Comment by zvonimirfras** [comment]
@cal-smith Upon quick inspection, modals in angular seem to match the ones in react. Is this resolved then (perhaps automagically with styles) or should I dig deeper?

**Comment by cal-smith** [comment]
I don't think the styles exist in carbon for some of this ... We can probably close this since I don't think it's a contribution we're going to make ... It may be worth it to create some storybook examples of how to accomplish those patterns however

**Comment by zvonimirfras** [comment]
Ok, let's icebox it then.
