### ISSUE TITLE
<ibm-number>: control's default is null

### ISSUE THREAD

**Issue by alik-p** [IBM/carbon-components-angular#995]
## Detailed description

> Describe in detail the issue you're having.

I'm using an `<ibm-number>` component with Angular reactive form.
The `<ibm-number>` displays `0` for the form control with `null` value when one is set programmatically (the same for empty value `''`). 

Actually the issue is a reverse case of the #974.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug.

> Is this issue related to a specific component?

Yes, `NumberComponent` (`<ibm-number>`).

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect that if the form control value is `null` / `''` the `<ibm-number>` should be empty instead of `0`.

> What browser are you working in?

Chrome, Firefox. I guess the browser doesn't matter.

> What version of the Carbon Design System are you using?
```
"carbon-components": "10.9.0"
"carbon-components-angular": "3.32.1"
```

## Steps to reproduce the issue

https://codesandbox.io/s/carbon-components-angular-m7n0x

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/43789093/72154967-08f2f180-33c3-11ea-8dcf-2c73bf2e54fe.png)

**Comment by cal-smith** [comment]
🤦‍♂ oops, should be a fairly straightforward fix though
